import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Button, LoadingState, Screen, ScreenState, SectionHeading } from "@/components/ui";
import { PropertyCard } from "@/components/property-card";
import { AppIcon } from "@/components/app-icon";
import { friendlyError } from "@/lib/api-error";
import { propertiesApi, propertyQuery } from "@/lib/properties-api";
import { emptyPropertyFilters, type PublicProperty } from "@/lib/property-types";
import { useAuth } from "@/providers/auth-provider";
import { usePropertyState } from "@/providers/property-state-provider";
import { colors, radius, spacing, typography } from "@/theme/tokens";

export default function HomeScreen(){
  const params=useLocalSearchParams<{ref?:string}>();const referralCode=typeof params.ref==="string"?params.ref:undefined;
  const {status}=useAuth();const {savedCodes,refreshSaved,setSaved}=usePropertyState();const [search,setSearch]=useState("");const [items,setItems]=useState<PublicProperty[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [retry,setRetry]=useState(0);const [saving,setSaving]=useState("");
  useEffect(()=>{let active=true;void propertiesApi.list(propertyQuery("",emptyPropertyFilters,1,6)).then(result=>{if(active)setItems(result.items);}).catch(failure=>{if(active)setError(friendlyError(failure));}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[retry]);
  useEffect(()=>{if(status==="signedIn"&&items.length)queueMicrotask(()=>void refreshSaved(items.map(item=>item.code)).catch(()=>{}))},[status,items,refreshSaved]);
  function submit(){const value=search.trim();void propertiesApi.recordSearch().catch(()=>{});router.push({pathname:"/properties",params:{...(value?{q:value}:{}),...(referralCode?{ref:referralCode}:{})}})}
  async function toggleSaved(property:PublicProperty){if(status!=="signedIn"){router.push({pathname:"/(auth)/login",params:{next:`/properties/${encodeURIComponent(property.code)}`}});return}if(saving)return;setSaving(property.code);try{if(savedCodes.has(property.code)){await propertiesApi.unsave(property.code);setSaved(property.code,false)}else{await propertiesApi.save(property.code);setSaved(property.code,true)}}catch(failure){setError(friendlyError(failure))}finally{setSaving("")}}
  return <Screen><View style={styles.hero}><Text accessibilityRole="header" style={styles.display}>Find your next property with confidence.</Text><Text style={styles.heroCopy}>Browse currently listed Beryl Shelter properties. Property transactions are completed offline with our team.</Text><View style={styles.search}><AppIcon name="search" size={20} color={colors.textMuted}/><TextInput accessibilityLabel="Search properties from Home" value={search} onChangeText={setSearch} onSubmitEditing={submit} returnKeyType="search" placeholder="Title, code, state or city" placeholderTextColor={colors.textMuted} style={styles.input}/><Pressable accessibilityRole="button" accessibilityLabel="Search listed properties" onPress={submit} style={styles.searchAction}><AppIcon name="arrow-forward" size={22} color={colors.actionText}/></Pressable></View><Button label="Browse all properties" onPress={()=>router.push(referralCode?{pathname:"/properties",params:{ref:referralCode}}:"/properties")}/></View><SectionHeading title="Latest listings" description="The newest properties currently available to the public."/>{loading?<LoadingState label="Loading latest properties"/>:error?<ScreenState title="Latest listings unavailable" message={error} action={<Button label="Try again" onPress={()=>{setLoading(true);setError("");setRetry(value=>value+1)}}/>}/>:items.length?<FlatList horizontal data={items} keyExtractor={item=>item.code} renderItem={({item})=><View style={styles.card}><PropertyCard property={item} referralCode={referralCode} saved={savedCodes.has(item.code)} saving={saving===item.code} onToggleSaved={()=>void toggleSaved(item)}/></View>} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.horizontal}/>:<ScreenState title="No listed properties yet" message="New public listings will appear here when they become available."/>}<View style={styles.info}><AppIcon name="information-circle-outline" size={24} color={colors.brandDark}/><View style={styles.infoCopy}><Text style={styles.infoTitle}>Purchases happen in person</Text><Text style={styles.infoText}>Browse and plan here, then work directly with Beryl Shelter for viewings and offline property transactions.</Text></View></View></Screen>
}
const styles=StyleSheet.create({hero:{backgroundColor:colors.surfaceMuted,borderRadius:radius.lg,padding:spacing.xl,gap:spacing.lg},display:{...typography.display,color:colors.text},heroCopy:{...typography.body,color:colors.textMuted},search:{minHeight:52,flexDirection:"row",alignItems:"center",gap:spacing.sm,paddingLeft:spacing.md,borderRadius:radius.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,overflow:"hidden"},input:{...typography.body,color:colors.text,flex:1,minWidth:0},searchAction:{width:50,alignSelf:"stretch",alignItems:"center",justifyContent:"center",backgroundColor:colors.action},horizontal:{gap:spacing.md,paddingRight:spacing.lg},card:{width:300},info:{flexDirection:"row",gap:spacing.md,padding:spacing.lg,borderRadius:radius.lg,backgroundColor:"#FBF1E5"},infoCopy:{flex:1,gap:spacing.xs},infoTitle:{...typography.label,color:colors.text},infoText:{...typography.caption,color:colors.textMuted}});
