import assert from "node:assert/strict";
import { randomBytes,randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { test,type TestContext } from "node:test";
import { PGlite } from "@electric-sql/pglite";
import { createApp } from "../src/app.js";
import { adminConfigSchema } from "../src/admin/config.js";
import type { AdminInvitationEmail } from "../src/admin/email.js";
import { SupabaseAdminIdentity,type AdminIdentity } from "../src/admin/identity.js";
import type { InviteAdminInput } from "../src/admin/model.js";
import type { AdminProfile,AdminRepository,InvitationClaim,InvitationPreview,InvitationRecord,StoredAdminSession } from "../src/admin/repository.js";
import { authConfigSchema } from "../src/auth/config.js";
import { AuthError,expired,unavailable } from "../src/auth/errors.js";
import type { ProviderTokens } from "../src/auth/gateway.js";

const auth=authConfigSchema.parse({webOrigin:"http://localhost:3000",apiOrigin:"http://localhost:4000",supabaseUrl:"https://example.supabase.co",anonKey:"anon",serviceKey:"service",encryptionKey:randomBytes(32).toString("base64"),cookieSecure:false,production:false,rateLimit:100});
const admin=adminConfigSchema.parse({appOrigin:"http://localhost:3001",resendApiKey:"test",inviteFrom:"Beryl <admin@example.com>",inviteSeconds:172800,production:false});
const superId="11111111-1111-4111-8111-111111111111",adminId="22222222-2222-4222-8222-222222222222";
const profiles:AdminProfile[]=[{userId:superId,fullName:"Super Admin",email:"super@example.com",phone:"+2348031234567",department:"MANAGEMENT",role:"SUPER_ADMIN",active:true},{userId:adminId,fullName:"Regular Admin",email:"admin@example.com",phone:"+2348031234568",department:"TECH",role:"ADMIN",active:true}];
type StoredInvite=InvitationRecord&{hash:string;accepted:boolean;claim:string|null};
class Repo implements AdminRepository{
  profiles=new Map(profiles.map(value=>[value.userId,{...value}]));sessions=new Map<string,StoredAdminSession>();invites=new Map<string,StoredInvite>();provisioningIds:string[]=[];
  async profile(id:string){return this.profiles.get(id)??null;}
  async reserve(inviter:string,input:InviteAdminInput,hash:string,seconds:number){if(this.profiles.get(inviter)?.role!=="SUPER_ADMIN")throw new AuthError(403,"ADMIN_INVITE_FORBIDDEN","Only a Super Admin may invite administrators.");const old=this.invites.get(input.email);if(old?.accepted)throw new AuthError(409,"ADMIN_IDENTITY_EXISTS","An account already exists.");const value:StoredInvite={id:old?.id??randomUUID(),fullName:input.fullName,email:input.email,phone:input.phone,department:input.department,role:input.role,authUserId:old?.authUserId??null,expiresAt:new Date(Date.now()+seconds*1000).toISOString(),hash,accepted:false,claim:null};this.invites.set(input.email,value);return value;}
  async provisionIdentity(){const id=randomUUID();this.provisioningIds.push(id);return id;}
  async attach(id:string,userId:string){const value=[...this.invites.values()].find(item=>item.id===id);if(!value)throw unavailable();value.authUserId=userId;}
  byHash(hash:string){return [...this.invites.values()].find(item=>item.hash===hash);}
  async preview(hash:string):Promise<InvitationPreview>{const value=this.byHash(hash);if(!value||value.accepted||Date.parse(value.expiresAt)<=Date.now()||!value.authUserId)throw new AuthError(400,"INVALID_OR_EXPIRED_INVITATION","This invitation is invalid, expired, or already used.");return value;}
  async claim(hash:string,claim:string):Promise<InvitationClaim>{const value=this.byHash(hash);await this.preview(hash);if(!value||value.claim)throw new AuthError(400,"INVALID_OR_EXPIRED_INVITATION","This invitation is invalid, expired, or already used.");value.claim=claim;return{authUserId:value.authUserId!,fullName:value.fullName,email:value.email,department:value.department,role:value.role};}
  async release(hash:string,claim:string){const value=this.byHash(hash);if(value?.claim===claim)value.claim=null;}
  async accept(hash:string,claim:string,userId:string){const value=this.byHash(hash);if(!value||value.claim!==claim||value.authUserId!==userId||value.accepted)throw new AuthError(400,"INVALID_OR_EXPIRED_INVITATION","This invitation is invalid, expired, or already used.");value.accepted=true;value.claim=null;const profile:AdminProfile={userId,fullName:value.fullName,email:value.email,phone:value.phone,department:value.department,role:value.role,active:true};this.profiles.set(userId,profile);return profile;}
  async createSession(hash:string,userId:string,tokens:string,seconds:number){this.sessions.set(hash,{token_hash:hash,user_id:userId,encrypted_tokens:tokens,expires_at:new Date(Date.now()+seconds*1000).toISOString(),refresh_lock:null});}
  async readSession(hash:string){return this.sessions.get(hash)??null;}async claimRefresh(hash:string,lock:string){const value=this.sessions.get(hash);if(!value||value.refresh_lock)return null;value.refresh_lock=lock;return value;}async finishRefresh(hash:string,lock:string,tokens:string){const value=this.sessions.get(hash);if(!value||value.refresh_lock!==lock)return false;value.encrypted_tokens=tokens;value.refresh_lock=null;return true;}async deleteSession(hash:string){this.sessions.delete(hash);}async deleteUserSessions(userId:string){for(const [hash,value] of this.sessions)if(value.user_id===userId)this.sessions.delete(hash);}
}
class Identity implements AdminIdentity{loginUser=superId;created=0;provisioningIds:string[]=[];activated:{userId:string;password:string}[]=[];async createPending(_email:string,_fullName:string,provisioningId:string){this.created++;this.provisioningIds.push(provisioningId);return randomUUID();}async deletePending(){}async activate(userId:string,password:string){this.activated.push({userId,password});}async login(){return this.tokens(this.loginUser);}async validate(tokens:ProviderTokens){if(!this.loginUser&&tokens.userId)throw expired();}async refresh(tokens:ProviderTokens){return tokens;}async signOut(){}tokens(userId:string):ProviderTokens{return{userId,accessToken:"secret-access",refreshToken:"secret-refresh",expiresAt:Date.now()/1000+3600};}}
class Email implements AdminInvitationEmail{sent:{fullName:string;email:string;token:string;expiresAt:string}[]=[];fail=false;async send(value:{fullName:string;email:string;token:string;expiresAt:string}){if(this.fail)throw unavailable();this.sent.push(value);}}
async function fixture(t:TestContext){const repository=new Repo(),identity=new Identity(),email=new Email(),server=createApp({webAppUrl:auth.webOrigin,auth,admin,adminRepository:repository,adminIdentity:identity,adminEmail:email}).listen(0,"127.0.0.1");await new Promise<void>(resolve=>server.once("listening",resolve));t.after(()=>new Promise<void>(resolve=>{server.close(()=>resolve());server.closeAllConnections();}));const address=server.address();assert(address&&typeof address!=="string");const jar=new Map<string,string>();async function request(path:string,body?:unknown,headers:Record<string,string>={}){const response=await fetch(`http://127.0.0.1:${address.port}/api/v1/admin${path}`,{method:body===undefined?"GET":"POST",headers:{Origin:admin.appOrigin,"Content-Type":"application/json",Cookie:[...jar].map(([key,value])=>`${key}=${value}`).join("; "),...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});for(const cookie of response.headers.getSetCookie()){const [pair]=cookie.split(";"),index=pair!.indexOf("="),key=pair!.slice(0,index),value=pair!.slice(index+1);if(value)jar.set(key,value);else jar.delete(key);}const text=await response.text();let parsed:unknown={};try{parsed=JSON.parse(text);}catch{parsed={};}return{response,body:parsed as {success:boolean;data?:Record<string,unknown>;error?:{code:string;message:string}}};}async function login(user=superId){identity.loginUser=user;const result=await request("/auth/login",{email:"admin@example.com",password:"Abcdefg!"});assert.equal(result.response.status,200);}return{repository,identity,email,request,login,jar};}
const valid={fullName:"Ada Okafor",email:" ADA.ADMIN@EXAMPLE.COM ",phoneNumber:"0803 123 4567",department:"TECH",role:"ADMIN"};

test("unauthenticated and regular ADMIN callers cannot invite or escalate",async t=>{const f=await fixture(t);assert.equal((await f.request("/invitations",valid)).response.status,401);await f.login(adminId);for(const body of [valid,{...valid,role:"SUPER_ADMIN"},{...valid,admin_role:"SUPER_ADMIN"}]){const result=await f.request("/invitations",body);assert.equal(result.response.status,403);}assert.equal(f.email.sent.length,0);});
test("SUPER_ADMIN sends real ADMIN invitation with normalized identity and hash-only persistence",async t=>{const f=await fixture(t);await f.login();const result=await f.request("/invitations",valid);assert.equal(result.response.status,201);assert.equal(f.email.sent.length,1);const sent=f.email.sent[0]!,stored=f.repository.invites.get("ada.admin@example.com")!;assert.equal(stored.phone,"+2348031234567");assert.equal(stored.role,"ADMIN");assert.equal(stored.hash.length,64);assert.notEqual(stored.hash,sent.token);assert.equal(JSON.stringify(stored).includes(sent.token),false);assert.equal(Math.round((Date.parse(stored.expiresAt)-Date.now())/1000/3600),48);assert.deepEqual(result.body.data?.invitation,{fullName:"Ada Okafor",email:"ada.admin@example.com",expiresAt:stored.expiresAt});});
test("SUPER_ADMIN may invite SUPER_ADMIN and resend replaces the only active token",async t=>{const f=await fixture(t);await f.login();const body={...valid,email:"second@example.com",role:"SUPER_ADMIN"};assert.equal((await f.request("/invitations",body)).response.status,201);const first=f.repository.invites.get(body.email)!.hash,identityCount=f.identity.created;assert.equal((await f.request("/invitations",body)).response.status,201);assert.notEqual(f.repository.invites.get(body.email)!.hash,first);assert.equal(f.repository.invites.size,1);assert.equal(f.identity.created,identityCount);assert.equal(f.email.sent.length,2);});
test("strict validation rejects missing/invalid fields, email, phone, department, role and payload attacks",async t=>{const f=await fixture(t);await f.login();const cases=[{}, {...valid,email:"bad"},{...valid,phoneNumber:"123"},{...valid,department:"FINANCE"},{...valid,role:"ROOT"},{...valid,role:"ADMIN",department:"TECH",permissions:["SUPER_ADMIN"]}];for(const body of cases){const result=await f.request("/invitations",body);assert.equal(result.response.status,400);assert.equal(result.body.error?.code,"VALIDATION_ERROR");}assert.equal(f.repository.invites.size,0);assert.equal((await f.request("/invitations")).response.status,404);});
test("email failure returns no false success and retry safely replaces the token",async t=>{const f=await fixture(t);await f.login();f.email.fail=true;const failed=await f.request("/invitations",valid);assert.equal(failed.response.status,503);assert.equal(failed.body.success,false);const old=f.repository.invites.get("ada.admin@example.com")!.hash;f.email.fail=false;assert.equal((await f.request("/invitations",valid)).response.status,201);assert.notEqual(f.repository.invites.get("ada.admin@example.com")!.hash,old);});
test("validation rejects invalid/expired tokens and never exposes a listing endpoint",async t=>{const f=await fixture(t);assert.equal((await f.request("/invitations/validate",{token:"x"})).response.status,400);await f.login();await f.request("/invitations",valid);const sent=f.email.sent[0]!;f.repository.invites.get("ada.admin@example.com")!.expiresAt=new Date(Date.now()-1).toISOString();assert.equal((await f.request("/invitations/validate",{token:sent.token})).response.status,400);assert.equal((await f.request("/invitations")).response.status,404);});
test("acceptance uses server-persisted role/department, activates once, and stores no password",async t=>{const f=await fixture(t);await f.login();await f.request("/invitations",{...valid,role:"SUPER_ADMIN",department:"MANAGEMENT"});const token=f.email.sent[0]!.token;const preview=await f.request("/invitations/validate",{token});assert.equal((preview.body.data?.invitation as InvitationPreview).role,"SUPER_ADMIN");const password="StrongPass!",accepted=await f.request("/invitations/accept",{token,password,confirmPassword:password});assert.equal(accepted.response.status,200);const profile=[...f.repository.profiles.values()].find(value=>value.email==="ada.admin@example.com")!;assert.equal(profile.role,"SUPER_ADMIN");assert.equal(profile.department,"MANAGEMENT");assert.equal(JSON.stringify([...f.repository.invites.values()]).includes(password),false);assert.equal(f.identity.activated[0]?.password,password);assert.equal((await f.request("/invitations/accept",{token,password,confirmPassword:password,role:"ADMIN"})).response.status,400);assert.equal((await f.request("/invitations/accept",{token,password,confirmPassword:password})).response.status,400);});
test("origin and JSON checks protect all mutations with safe errors",async t=>{const f=await fixture(t);const wrong=await f.request("/auth/login",{email:"admin@example.com",password:"x"},{Origin:"https://evil.example"});assert.equal(wrong.response.status,403);assert.equal(wrong.body.error?.code,"UNTRUSTED_ORIGIN");const text=await f.request("/auth/login",{email:"admin@example.com",password:"x"},{"Content-Type":"text/plain"});assert.equal(text.response.status,403);});
test("Supabase Admin identity creation carries a one-time INSERT marker and reasserts authoritative app_metadata",async()=>{const userId=randomUUID(),calls:{method:string;path:string;body:Record<string,unknown>}[]=[];const transport:typeof fetch=async(input,init)=>{const url=new URL(typeof input==="string"?input:input instanceof URL?input.href:input.url),body=JSON.parse(String(init?.body??"{}")) as Record<string,unknown>;calls.push({method:init?.method??"GET",path:url.pathname,body});const appMetadata=init?.method==="PUT"?(body.app_metadata as Record<string,unknown>):{};return new Response(JSON.stringify({id:userId,email:"pending@example.com",email_confirmed_at:new Date().toISOString(),app_metadata:appMetadata,user_metadata:body.user_metadata??{},aud:"authenticated",role:"authenticated",created_at:new Date().toISOString(),updated_at:new Date().toISOString()}),{status:200,headers:{"Content-Type":"application/json"}});};const identity=new SupabaseAdminIdentity(auth,transport),provisioningId=randomUUID();assert.equal(await identity.createPending("pending@example.com","Pending Admin",provisioningId),userId);assert.equal((calls[0]?.body.user_metadata as Record<string,unknown>).admin_provisioning_id,provisioningId);assert.deepEqual(calls[1]?.body.app_metadata,{account_domain:"ADMIN_INVITED"});assert.equal((calls[1]?.body.user_metadata as Record<string,unknown>).admin_provisioning_id,null);});

test("forward migration preserves customer flows and securely isolates Admin INSERT provisioning",async t=>{
  const db=new PGlite();t.after(()=>db.close());
  await db.exec("create schema auth; create function auth.uid() returns uuid language sql stable as 'select null::uuid'; create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_app_meta_data jsonb default '{}',raw_user_meta_data jsonb default '{}'); create role anon; create role authenticated; create role service_role bypassrls;");
  for(const migration of ["202609060001_customer_auth_foundation.sql","202609270003_admin_invitations.sql","202609270004_admin_identity_provisioning.sql"])await db.exec(await readFile(new URL(`../supabase/migrations/${migration}`,import.meta.url),"utf8"));

  const manualId=randomUUID();
  await db.query("insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values($1,$2,now(),$3)",[manualId,"customer@example.com",{first_name:"Ada",last_name:"Okafor",country_code:"+234",phone_number:"8031234567",phone_number_normalized:"+2348031234567",account_type:"INVESTOR",profile_type:"PERSONAL"}]);
  assert.equal((await db.query("select * from customer_profiles where id=$1",[manualId])).rows.length,1);

  await assert.rejects(db.query("insert into auth.users(id,email,raw_user_meta_data) values($1,$2,$3)",[randomUUID(),"incomplete@example.com",{first_name:"Incomplete"}]),/Manual registration profile is incomplete/);

  const googleId=randomUUID();
  await db.query("insert into auth.users(id,email,raw_app_meta_data,raw_user_meta_data) values($1,$2,$3,$4)",[googleId,"google@example.com",{provider:"google"},{given_name:"Grace",family_name:"Adebayo"}]);
  assert.equal((await db.query("select * from customer_profiles where id=$1",[googleId])).rows.length,1);

  const provisioningId=randomUUID(),adminUserId=randomUUID();
  await db.query("insert into admin_identity_provisioning(id,email,account_domain,expires_at) values($1,$2,'ADMIN',now()+interval '10 minutes')",[provisioningId,"bootstrap@example.com"]);
  await db.query("insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values($1,$2,now(),$3)",[adminUserId,"bootstrap@example.com",{admin_provisioning_id:provisioningId}]);
  assert.equal((await db.query("select * from customer_profiles where id=$1",[adminUserId])).rows.length,0);
  assert.equal((await db.query<{auth_user_id:string;account_domain:string}>("select auth_user_id,account_domain from admin_identity_provisioning where id=$1",[provisioningId])).rows[0]?.auth_user_id,adminUserId);

  await assert.rejects(db.query("insert into auth.users(id,email,raw_user_meta_data) values($1,$2,$3)",[randomUUID(),"attacker@example.com",{admin_provisioning_id:randomUUID()}]),/Manual registration profile is incomplete/);
  await db.query("update auth.users set raw_app_meta_data=$2 where id=$1",[adminUserId,{account_domain:"ADMIN"}]);
  await db.query("insert into admin_profiles(user_id,full_name,email,phone_normalized,department,admin_role,active,accepted_at) values($1,'Bootstrap Admin','bootstrap@example.com','+2348031234599','MANAGEMENT','SUPER_ADMIN',true,now())",[adminUserId]);
  const bootstrap=(await db.query<{admin_role:string;active:boolean}>("select admin_role,active from admin_profiles where user_id=$1",[adminUserId])).rows[0];
  assert.deepEqual(bootstrap,{admin_role:"SUPER_ADMIN",active:true});

  for(const role of ["anon","authenticated"]){await db.exec(`set role ${role}`);await assert.rejects(db.query("select * from public.admin_identity_provisioning"));await assert.rejects(db.query("select public.reserve_admin_identity_provisioning(gen_random_uuid())"));await db.exec("reset role");}
});
