import assert from "node:assert/strict";
import { test } from "node:test";
import { kycFixture,kycForm,jpeg,pdf,png } from "./kyc.fixture.js";

test("KYC requires an ACCOUNT session and ignores owner/status spoofing",async t=>{const f=await kycFixture(t);for(const cookie of ["","beryl_account=forged","beryl_recovery=kyc-session"])assert.equal((await f.request("","GET",undefined,cookie)).response.status,401);for(const data of [{...f.valid,userId:f.other},{...f.valid,status:"APPROVED"},{...f.valid,bvn:"123"},{...f.valid,nin:"123"}])assert.equal((await f.request("","POST",kycForm(data as never,png))).response.status,400);});
test("KYC starts NOT_SUBMITTED and creates server-owned PENDING_REVIEW with declaration time",async t=>{const f=await kycFixture(t);assert.equal((await f.request()).payload.data.status,"NOT_SUBMITTED");const result=await f.request("","POST",kycForm(f.valid,pdf));assert.equal(result.response.status,201,JSON.stringify(result.payload));assert.equal(result.payload.data.status,"PENDING_REVIEW");const row=(await f.db.query<{status:string;declaration_accepted_at:string}>("select status,declaration_accepted_at from public.customer_kyc_submissions where user_id=$1",[f.owner])).rows[0]!;assert.equal(row.status,"PENDING_REVIEW");assert(row.declaration_accepted_at);assert(!JSON.stringify(result.payload).includes("public_id"));});
test("document type side rules enforce passport front-only and two-sided cards",async t=>{for(const [type,back,status] of [["PASSPORT",undefined,201],["PASSPORT",png,400],["DRIVERS_LICENSE",undefined,400],["DRIVERS_LICENSE",png,201],["NATIONAL_ID",undefined,400],["NATIONAL_ID",jpeg,201]] as const)await t.test(`${type}-${back?"two":"one"}`,async child=>{const f=await kycFixture(child),result=await f.request("","POST",kycForm({...f.valid,documentType:type},png,back));assert.equal(result.response.status,status,JSON.stringify(result.payload));});});
test("KYC accepts PNG JPEG PDF and rejects WEBP SVG mismatch empty and oversize",async t=>{for(const file of [png,jpeg,pdf,{type:"image/webp",bytes:Buffer.from("RIFF0000WEBP0")},{type:"image/svg+xml",bytes:Buffer.from("<svg/>")},{type:"image/png",bytes:Buffer.from("fake")},{type:"application/pdf",bytes:Buffer.alloc(0)},{type:"image/png",bytes:Buffer.alloc(10*1024*1024+1)}])await t.test(`${file.type}-${file.bytes.length}`,async child=>{const f=await kycFixture(child),result=await f.request("","POST",kycForm(f.valid,file));assert.equal(result.response.status,[png,jpeg,pdf].includes(file as never)?201:400,JSON.stringify(result.payload));});});
test("declaration and explicit document taxonomy are enforced",async t=>{for(const input of [{...({country:"Nigeria",documentType:"PASSPORT",declarationAccepted:false})},{country:"Nigeria",documentType:"BVN",declarationAccepted:true},{country:"Nigeria",documentType:"NIN",declarationAccepted:true}]){const f=await kycFixture(t);assert.equal((await f.request("","POST",kycForm(input as never,png))).response.status,400);}});
test("pending and approved submissions cannot be replaced; rejected can resubmit with history",async t=>{const f=await kycFixture(t);assert.equal((await f.request("","POST",kycForm(f.valid,png))).response.status,201);assert.equal((await f.request("","POST",kycForm(f.valid,png))).response.status,400);await f.db.query("update public.customer_kyc_submissions set status='APPROVED',reviewed_at=clock_timestamp() where user_id=$1",[f.owner]);assert.equal((await f.request("","POST",kycForm(f.valid,png))).response.status,400);await f.db.query("update public.customer_kyc_submissions set status='REJECTED',rejection_reason='Please resubmit',reviewed_at=clock_timestamp() where user_id=$1",[f.owner]);assert.equal((await f.request("","POST",kycForm(f.valid,png))).response.status,201);assert.equal((await f.db.query<{count:number}>("select count(*)::int count from public.customer_kyc_submissions where user_id=$1",[f.owner])).rows[0]!.count,2);});
test("private document retrieval is owner scoped and hardened",async t=>{const f=await kycFixture(t);const submitted=await f.request("","POST",kycForm(f.valid,pdf));const id=submitted.payload.data.documents[0].id,own=await f.request(`/documents/${id}`);assert.equal(own.response.status,200);assert.equal(own.response.headers.get("cache-control"),"no-store");assert.equal(own.response.headers.get("x-content-type-options"),"nosniff");assert.match(own.response.headers.get("content-disposition")??"",/^attachment;/);assert.equal((await f.request(`/documents/${id}`,"GET",undefined,"beryl_account=forged")).response.status,401);const foreign=await f.repository.read(f.other);assert.equal(foreign.status,"NOT_SUBMITTED");await assert.rejects(f.repository.document(f.other,id));});
test("orphan upload cleanup remains retryable after provider deletion failure",async t=>{const f=await kycFixture(t),id=`beryl-v2/kyc/${f.owner}/${crypto.randomUUID()}.pdf`;await f.repository.journal(f.owner,id);await f.db.query("update public.customer_kyc_uploads set created_at=clock_timestamp()-interval '2 hours' where public_id=$1",[id]);f.setFailRemove(true);const first=await f.repository.claimCleanup(f.owner);assert.deepEqual(first,[id]);await f.repository.releaseCleanup(f.owner,id,false);assert.deepEqual(await f.repository.claimCleanup(f.owner),[id]);});
test("KYC tables and RPCs deny browser roles and store no BVN NIN or binary columns",async t=>{const f=await kycFixture(t);for(const table of ["customer_kyc_submissions","customer_kyc_documents","customer_kyc_uploads"]){await assert.rejects(f.db.query(`set role authenticated; select * from public.${table}`));await f.db.exec("reset role");}await assert.rejects(f.db.query("set role authenticated; select public.read_customer_kyc($1)",[f.owner]));await f.db.exec("reset role");const columns=(await f.db.query<{column_name:string;data_type:string}>("select column_name,data_type from information_schema.columns where table_schema='public' and table_name like 'customer_kyc_%'")).rows;assert(!columns.some(row=>/bvn|nin|binary|bytea/i.test(`${row.column_name} ${row.data_type}`)));});
test("KYC submission attempts are limited to five per hour",async t=>{const f=await kycFixture(t);for(let i=0;i<5;i++)assert.notEqual((await f.request("","POST",kycForm({...f.valid,declarationAccepted:false},png))).response.status,429);assert.equal((await f.request("","POST",kycForm({...f.valid,declarationAccepted:false},png))).response.status,429);});
