import { PGlite } from "@electric-sql/pglite";
import { randomBytes,randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import type { TestContext } from "node:test";
import { createApp } from "../src/app.js";
import { authConfigSchema } from "../src/auth/config.js";
import { AuthCipher,hashToken } from "../src/auth/crypto.js";
import { AuthError } from "../src/auth/errors.js";
import type { AuthGateway,Customer,StoredSession } from "../src/auth/gateway.js";
import type { KycAsset,KycSubmissionInput,KycView } from "../src/kyc/model.js";
import type { KycRepository } from "../src/kyc/repository.js";
import type { MediaStorage } from "../src/listings/media.js";

export async function kycFixture(t:TestContext){
  const db=new PGlite();t.after(()=>db.close());
  await db.exec("create schema auth; create function auth.uid() returns uuid language sql stable as 'select null::uuid'; create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_app_meta_data jsonb default '{}',raw_user_meta_data jsonb default '{}'); create role anon; create role authenticated; create role service_role;");
  await db.exec(await readFile(new URL("../supabase/migrations/202609060001_customer_auth_foundation.sql",import.meta.url),"utf8"));
  await db.exec(await readFile(new URL("../supabase/migrations/202609140003_customer_kyc.sql",import.meta.url),"utf8"));
  const owner=randomUUID(),other=randomUUID(),metadata=(isOther:boolean)=>JSON.stringify({first_name:isOther?"Other":"Ada",last_name:isOther?"Customer":"Okafor",country_code:"+234",phone_number:isOther?"8098765432":"8012345678",phone_number_normalized:isOther?"+2348098765432":"+2348012345678",account_type:"INVESTOR",profile_type:"PERSONAL"});
  for(const [id,email,isOther] of [[owner,"ada@example.test",false],[other,"other@example.test",true]] as const)await db.query("insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values($1,$2,clock_timestamp(),$3)",[id,email,metadata(isOther)]);
  async function rpc<T>(name:string,args:unknown[]){try{return(await db.query<{value:T}>(`select public.${name}(${args.map((_,i)=>`$${i+1}`).join(",")}) value`,args)).rows[0]!.value;}catch(error){const value=error as {code?:string;message?:string};if(value.code==="P0002")throw new AuthError(404,"KYC_DOCUMENT_NOT_FOUND","KYC document not found.");if(["23514","23502","22P02"].includes(value.code??""))throw new AuthError(400,"INVALID_KYC_SUBMISSION",value.message?.includes("cannot be replaced")?"This KYC submission cannot be replaced.":"Check the KYC details and documents.");throw error;}}
  const repository:KycRepository={read:o=>rpc<KycView>("read_customer_kyc",[o]),journal:async(o,id)=>{await rpc("journal_customer_kyc_upload",[o,id]);},reserve:async(o,a)=>{await rpc("reserve_customer_kyc_upload",[o,JSON.stringify(a)]);},submit:(o,input,docs)=>rpc<KycView>("submit_customer_kyc",[o,input.country,input.documentType,input.declarationAccepted,JSON.stringify(docs)]),document:(o,id)=>rpc<KycAsset>("get_customer_kyc_document",[o,id]),claimCleanup:async o=>(await db.query<{value:string}>("select public.claim_customer_kyc_upload_cleanup($1) value",[o])).rows.map(row=>row.value),releaseCleanup:async(o,id,remove)=>{await rpc("release_customer_kyc_upload_cleanup",[o,id,remove]);}};
  const config=authConfigSchema.parse({webOrigin:"http://localhost:3000",apiOrigin:"http://localhost:4000",supabaseUrl:"https://example.supabase.co",anonKey:"test",serviceKey:"test",encryptionKey:randomBytes(32).toString("base64"),cookieSecure:false,production:false}),raw="kyc-session",row:StoredSession={token_hash:hashToken(raw),user_id:owner,purpose:"ACCOUNT",refresh_lock:null,expires_at:new Date(Date.now()+3600000).toISOString(),encrypted_tokens:new AuthCipher(config.encryptionKey).seal({userId:owner,accessToken:"test",refreshToken:"test",expiresAt:Date.now()/1000+3600},"provider-tokens")},profile:Customer={id:owner,first_name:"Ada",last_name:"Okafor",email:"ada@example.test",country_code:"+234",phone_number:"8012345678",phone_number_normalized:"+2348012345678",account_type:"INVESTOR",profile_type:"PERSONAL",email_verified_at:new Date().toISOString()};
  const gateway={readSession:async(hash:string,purpose:string)=>hash===row.token_hash&&purpose===row.purpose?row:null,validate:async()=>{},findCustomer:async(_field:string,value:string)=>value===owner?profile:null} as unknown as AuthGateway,stored=new Map<string,Uint8Array>(),removed:string[]=[];let failRemove=false;
  const storage:MediaStorage={async upload(file,asset){stored.set(asset.public_id,file.bytes);return{...asset,url:"",mime_type:file.mime,size_bytes:file.bytes.length};},async remove(asset){if(failRemove)throw new Error("provider");removed.push(asset.public_id);stored.delete(asset.public_id);},async download(asset){const value=stored.get(asset.public_id);if(!value)throw new Error("missing");return value;}};
  const server=createApp({webAppUrl:config.webOrigin,auth:config,gateway,kycRepository:repository,mediaStorage:storage}).listen(0,"127.0.0.1");await new Promise<void>(resolve=>server.once("listening",resolve));t.after(()=>new Promise<void>(resolve=>{server.close(()=>resolve());server.closeAllConnections();}));const address=server.address();if(!address||typeof address==="string")throw new Error("server");
  async function request(path="",method="GET",body?:FormData,cookie=`beryl_account=${raw}`,origin=config.webOrigin){const response=await fetch(`http://127.0.0.1:${address.port}/api/v1/dashboard/kyc${path}`,{method,headers:{Cookie:cookie,Origin:origin},...(body?{body}:{})});const contentType=response.headers.get("content-type")??"";return{response,payload:contentType.includes("json")?await response.json():await response.arrayBuffer()};}
  const valid:KycSubmissionInput={country:"Nigeria",documentType:"PASSPORT",declarationAccepted:true};return{db,owner,other,repository,request,valid,stored,removed,setFailRemove:(value:boolean)=>{failRemove=value;}};
}
export function kycForm(input:KycSubmissionInput,front:{type:string;bytes:Buffer;name?:string},back?:{type:string;bytes:Buffer;name?:string}){const form=new FormData();form.set("data",JSON.stringify(input));form.set("frontDocument",new Blob([front.bytes],{type:front.type}),front.name??"front");if(back)form.set("backDocument",new Blob([back.bytes],{type:back.type}),back.name??"back");return form;}
export const png={type:"image/png",bytes:Buffer.from([137,80,78,71,13,10,26,10,0])},jpeg={type:"image/jpeg",bytes:Buffer.from([255,216,255,0])},pdf={type:"application/pdf",bytes:Buffer.from("%PDF-1.4\n")};
