import assert from "node:assert/strict";
import {test} from "node:test";
import {randomUUID} from "node:crypto";
import {completeness,minorUnits,parseContent} from "../src/listings/model.js";
import {ListingsService} from "../src/listings/service.js";
import {validateFile} from "../src/listings/uploads.js";
import {imageBytes,listingFixture,listingForm,validContent} from "./listings.fixture.js";

test("Listings API and actual local migration transactions",async t=>{
  const f=await listingFixture(t);let id="",version=1;
  await t.test("requires account session and trusted mutation origin",async()=>{assert.equal((await f.request("","GET",undefined,{Cookie:""})).response.status,401);assert.equal((await f.request("","POST",listingForm(),{Origin:"https://evil.example"})).response.status,403);assert.equal(f.uploaded.length,0);});
  await t.test("valid create generates immutable code, exact kobo and ordered images",async()=>{const {response,payload}=await f.request("","POST",listingForm(validContent,[{bytes:imageBytes,mime:"image/png"},{bytes:imageBytes,mime:"image/png"}]));assert.equal(response.status,201,JSON.stringify(payload));id=payload.data.id;version=payload.data.version;assert.match(payload.data.listing_code,/^RES-[A-HJ-NP-Z2-9]{6}$/);assert.equal(payload.data.property_cost_minor,5000000001);assert.equal(payload.data.listing_status,"UNLISTED");assert.deepEqual(payload.data.images.map((i:{sort_order:number})=>i.sort_order),[0,1]);assert.equal(payload.data.toilet_count,null);assert.equal(payload.data.leads,0);assert.equal(payload.data.views,0);assert(!("user_id" in payload.data));assert(!JSON.stringify(payload).includes("public_id"));});
  await t.test("required fields, amounts, coordinates, owner and moderation spoofing are rejected before storage",async()=>{const count=f.uploaded.length;for(const change of [{title:""},{property_cost:"0"},{minimum_down_payment:"60000000"},{minimum_down_payment:"-1"},{property_cost:"1e9"},{longitude:181},{latitude:-91},{user_id:f.other},{listing_status:"LISTED"},{listing_status:"REJECTED"},{listing_code:"FORGED"},{completeness:100},{year_built:3000}])assert.equal((await f.request("","POST",listingForm({...validContent,...change}))).response.status,400);assert.equal(f.uploaded.length,count);});
  await t.test("foreign ownership is hidden for read, edit, delete, approval and uploads",async()=>{const asset={...f.uploaded[0]!,public_id:`foreign-${randomUUID()}`,id:randomUUID(),sort_order:0};await f.repository.journal(f.other,asset);const foreign=await f.repository.mutate(f.other,{action:"CREATE",id:null,version:null,content:parseContent(validContent),images:[asset]});for(const [path,method,body] of [[`/${foreign}`,"GET",undefined],[`/${foreign}`,"PATCH",listingForm(validContent,[],{version:1})],[`/${foreign}`,"DELETE",{version:1}],[`/${foreign}/request-approval`,"POST",{version:1}],[`/${foreign}/documents`,"POST",listingForm()]] as const)assert.equal((await f.request(path,method,body)).response.status,404);const list=await f.request();assert.deepEqual(list.payload.data.items.map((v:{id:string})=>v.id),[id]);assert.equal((await f.request("?user_id="+f.other)).response.status,400);});
  await t.test("editing retains omitted existing images; explicit removal keeps deterministic order",async()=>{const before=await f.repository.get(f.owner,id);const edited=await f.request(`/${id}`,"PATCH",listingForm({...validContent,title:"Updated property"},[],{version}));assert.equal(edited.response.status,200);version=edited.payload.data.version;assert.deepEqual(edited.payload.data.images.map((i:{id:string})=>i.id),before!.images.map(i=>i.id));assert.equal(edited.payload.data.listing_code,before!.listing_code);const keep=edited.payload.data.images[1].id;const removed=await f.request(`/${id}`,"PATCH",listingForm(validContent,[],{version,retained_images:[keep]}));assert.equal(removed.response.status,200);version=removed.payload.data.version;assert.equal(removed.payload.data.images.length,1);assert.equal(removed.payload.data.images[0].sort_order,0);assert(f.removed.includes(before!.images[0]!.public_id));});
  await t.test("approval, stale version, pending edit protection and unlist transitions",async()=>{const approved=await f.request(`/${id}/request-approval`,"POST",{version});assert.equal(approved.response.status,200);assert.equal(approved.payload.data.listing_status,"PENDING");assert(approved.payload.data.requested_at);assert.equal((await f.request(`/${id}/unlist`,"POST",{version})).response.status,409);version=approved.payload.data.version;assert.equal((await f.request(`/${id}`,"PATCH",listingForm(validContent,[],{version}))).response.status,409);assert.equal((await f.request(`/${id}/request-approval`,"POST",{version})).response.status,409);const unlisted=await f.request(`/${id}/unlist`,"POST",{version});assert.equal(unlisted.payload.data.listing_status,"UNLISTED");version=unlisted.payload.data.version;});
  await t.test("private single-document upload and owner download",async()=>{const body=new FormData();body.set("data",JSON.stringify({title:"Ownership papers",document_type:"Ownership",description:"First document",version}));body.set("document",new Blob(["%PDF-1.4 test"],{type:"application/pdf"}),"../../unsafe.pdf");const result=await f.request(`/${id}/documents`,"POST",body);assert.equal(result.response.status,201,JSON.stringify(result.payload));version=result.payload.data.version;const docs=result.payload.data.documents;assert.equal(docs.length,1);assert.equal(docs[0].description,"First document");assert.equal(docs[0].sort_order,0);assert(!JSON.stringify(docs).includes("public_id"));assert(!JSON.stringify(docs).includes("url"));assert(f.uploaded.filter(v=>v.resource_type==="raw").every(v=>v.delivery_type==="authenticated"));const download=await f.request(`/${id}/documents/${docs[0].id}`);assert.equal(download.response.status,200);assert.match(download.response.headers.get("content-disposition")??"",/^attachment;/);});
  await t.test("search, status, pagination and Dashboard recent listings are owner scoped",async()=>{const listed=await f.request("?q=Duplex&page_size=1");assert.equal(listed.payload.data.total,1);assert.equal(listed.payload.data.page_size,1);assert.equal((await f.request("?status=PENDING")).payload.data.total,0);const code=(await f.repository.get(f.owner,id))!.listing_code;assert.equal((await f.request(`?q=${code}`)).payload.data.total,1);assert.equal((await f.request("?page=2&page_size=1")).payload.data.items.length,0);const dashboard=await f.request("/api/v1/dashboard/overview");assert.deepEqual(dashboard.payload.data.recent_property_listings.map((v:{id:string})=>v.id),[id]);assert.equal(dashboard.payload.data.summary.total_investments,0);});
  await t.test("hard deletion cascades rows; provider failure leaves durable cleanup without failing deletion",async()=>{f.failures.remove=true;const result=await f.request(`/${id}`,"DELETE",{version});assert.equal(result.response.status,200);assert.equal((await f.request(`/${id}`)).response.status,404);assert.equal((await f.db.query("select id from public.customer_listing_documents where listing_id=$1",[id])).rows.length,0);const queued=await f.db.query("select * from public.customer_listing_media_cleanup where user_id=$1",[f.owner]);assert.equal(queued.rows.length,2);await f.db.query("update public.customer_listing_media_cleanup set created_at=clock_timestamp()-interval '2 hours' where user_id=$1",[f.owner]);f.failures.remove=false;await new ListingsService(f.repository,f.storage).cleanup(f.owner);assert.equal((await f.db.query("select * from public.customer_listing_media_cleanup where user_id=$1",[f.owner])).rows.length,0);});
  await t.test("SQL rollback, immutable identity, constraints, RLS and service-only function permissions",async()=>{const content=parseContent(validContent);await assert.rejects(()=>f.repository.mutate(f.owner,{action:"CREATE",id:null,version:null,content,images:[]}));assert.equal((await f.repository.list(f.owner,{q:"",page:1,page_size:10})).total,0);const {rows}=await f.db.query<{enabled:boolean;table_name:string}>("select relname as table_name,relrowsecurity as enabled from pg_class where relname in ('customer_listings','customer_listing_images','customer_listing_documents','customer_listing_media_cleanup')");assert.equal(rows.length,4);assert(rows.every(r=>r.enabled));for(const role of ["anon","authenticated"]){const privilege=await f.db.query<{allowed:boolean}>("select has_table_privilege($1,'public.customer_listings','select') as allowed",[role]);assert.equal(privilege.rows[0]!.allowed,false);const execute=await f.db.query<{allowed:boolean}>("select has_function_privilege($1,'public.mutate_customer_listing(uuid,uuid,text,integer,jsonb,jsonb,jsonb)','execute') as allowed",[role]);assert.equal(execute.rows[0]!.allowed,false);}const foreign=(await f.repository.list(f.other,{q:"",page:1,page_size:10})).items[0]!;await assert.rejects(()=>f.db.query("update public.customer_listings set listing_code='FORGED' where id=$1",[foreign.id]));await assert.rejects(()=>f.db.query("update public.customer_listings set minimum_down_payment_minor=property_cost_minor+1 where id=$1",[foreign.id]));});
});

test("listing completeness and exact money are deterministic, bounded and not browser-authoritative",()=>{assert.equal(minorUnits("9999999999999.99"),999999999999999);assert.equal(minorUnits("0.01"),1);assert.throws(()=>minorUnits("1.001"));const listing={...parseContent(validContent),images:[{}],facilities:[]} as Parameters<typeof completeness>[0];assert.equal(completeness(listing),80);assert.equal(completeness({...listing,units:2,land_area:100,year_built:2020,longitude:0,latitude:0,facilities:["CCTV"]}),100);});
test("image/document MIME magic, file-size and executable restrictions",()=>{validateFile({field:"images",mime:"image/png",bytes:imageBytes},false);for(const [mime,bytes,document] of [["image/png",Buffer.from("MZ executable"),false],["application/pdf",Buffer.from("%PDF-1.4"),false],["image/webp",imageBytes,true],["image/png",Buffer.alloc(5242881),false],["application/pdf",Buffer.alloc(10485761),true]] as const)assert.throws(()=>validateFile({field:"x",mime,bytes},document));});
