import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import { readFile } from "node:fs/promises";
import { test } from "node:test";
import { PGlite } from "@electric-sql/pglite";
import { createApp } from "../src/app.js";
import { authConfigSchema } from "../src/auth/config.js";
import type { PublicInquiriesRepository, RealEstateInquiry } from "../src/public-inquiries/repository.js";

const config=authConfigSchema.parse({webOrigin:"http://localhost:3000",apiOrigin:"http://localhost:4000",supabaseUrl:"https://example.supabase.co",anonKey:"test",serviceKey:"test",encryptionKey:randomBytes(32).toString("base64"),cookieSecure:false,production:false});

test("public inquiries validate, normalize and return only a safe acknowledgement",async t=>{const saved:RealEstateInquiry[]=[];let fail=false;const repository:PublicInquiriesRepository={async submit(value){if(fail)throw new Error("private database detail");saved.push(value)}};
  const server=createApp({webAppUrl:config.webOrigin,auth:config,publicInquiriesRepository:repository}).listen(0,"127.0.0.1");await new Promise<void>(resolve=>server.once("listening",resolve));t.after(()=>new Promise<void>(resolve=>{server.close(()=>resolve());server.closeAllConnections()}));const address=server.address();assert(address&&typeof address!=="string");const base=`http://127.0.0.1:${address.port}/api/v1/public/inquiries`;
  const valid={inquiryType:"Buying a Property",name:"  Ada Buyer  ",phone:" +234 801 234 5678 ",email:" ADA@EXAMPLE.COM ",message:" I need help finding a home. ",sourcePage:"buy"};
  const send=(body:unknown,origin=config.webOrigin,type="application/json")=>fetch(base,{method:"POST",headers:{Origin:origin,"Content-Type":type},body:JSON.stringify(body)});
  const response=await send(valid);assert.equal(response.status,201);assert.deepEqual(await response.json(),{success:true,data:{recorded:true}});assert.deepEqual(saved,[{inquiryType:"Buying a Property",name:"Ada Buyer",phone:"+234 801 234 5678",email:"ada@example.com",message:"I need help finding a home.",sourcePage:"buy"}]);
  for(const key of ["inquiryType","name","phone","email","message","sourcePage"]){const body={...valid} as Record<string,unknown>;delete body[key];assert.equal((await send(body)).status,400,key)}
  for(const invalid of [{...valid,inquiryType:"Mortgage"},{...valid,email:"not-email"},{...valid,phone:"letters"},{...valid,name:"x"},{...valid,message:"x".repeat(3001)},{...valid,sourcePage:"/buy?token=secret"},{...valid,customerId:"private"}])assert.equal((await send(invalid)).status,400);
  assert.equal((await fetch(base)).status,404);assert.equal((await send(valid,"https://attacker.example")).status,403);assert.equal((await send(valid,config.webOrigin,"text/plain")).status,415);assert.equal((await fetch(`${base}?read=true`,{method:"POST",headers:{Origin:config.webOrigin,"Content-Type":"application/json"},body:JSON.stringify(valid)})).status,400);
  fail=true;const unavailable=await send(valid);assert.equal(unavailable.status,503);assert(!JSON.stringify(await unavailable.json()).includes("private database detail"));fail=false;let limited=false;for(let index=0;index<25;index++){if((await send(valid)).status===429){limited=true;break}}assert(limited);
});

test("inquiry migration creates a service-role insert-only table with strict fields",async t=>{const db=new PGlite();t.after(()=>db.close());await db.exec("create role anon; create role authenticated; create role service_role bypassrls;");await db.exec(await readFile(new URL("../supabase/migrations/202609260001_public_real_estate_inquiries.sql",import.meta.url),"utf8"));
  const grants=await db.query<{rls:boolean;anon_read:boolean;anon_insert:boolean;auth_read:boolean;service_insert:boolean;service_read:boolean;service_update:boolean;service_delete:boolean}>("select relrowsecurity rls,has_table_privilege('anon','public.public_real_estate_inquiries','SELECT') anon_read,has_table_privilege('anon','public.public_real_estate_inquiries','INSERT') anon_insert,has_table_privilege('authenticated','public.public_real_estate_inquiries','SELECT') auth_read,has_table_privilege('service_role','public.public_real_estate_inquiries','INSERT') service_insert,has_table_privilege('service_role','public.public_real_estate_inquiries','SELECT') service_read,has_table_privilege('service_role','public.public_real_estate_inquiries','UPDATE') service_update,has_table_privilege('service_role','public.public_real_estate_inquiries','DELETE') service_delete from pg_class where oid='public.public_real_estate_inquiries'::regclass");assert.deepEqual(grants.rows[0],{rls:true,anon_read:false,anon_insert:false,auth_read:false,service_insert:true,service_read:false,service_update:false,service_delete:false});
  await db.exec("set role service_role; insert into public.public_real_estate_inquiries(inquiry_type,full_name,phone,email,message,source_page) values('General Inquiry','Ada Person','0704 205 5678','ada@example.com','Please contact me.','home'); reset role;");const rows=await db.query<{status:string}>("select status from public.public_real_estate_inquiries");assert.deepEqual(rows.rows,[{status:"NEW"}]);await assert.rejects(()=>db.exec("insert into public.public_real_estate_inquiries(inquiry_type,full_name,phone,email,message,source_page) values('Invalid','Ada Person','0704','ada@example.com','Help','home')"));
});
