import assert from "node:assert/strict";
import { test } from "node:test";
import { referralsFixture } from "./referrals.fixture.js";

test("referrals require a current verified account session",async t=>{const f=await referralsFixture(t);for(const cookie of ["","beryl_account=forged",`beryl_recovery=${f.raw}`])assert.equal((await f.request("","GET",undefined,cookie)).response.status,401);f.row.expires_at=new Date(0).toISOString();assert.equal((await f.request()).response.status,401);});
test("referrals return an honest empty model and the server-owned two percent rule",async t=>{const {response,payload}=await (await referralsFixture(t)).request();assert.equal(response.status,200);assert.equal(response.headers.get("cache-control"),"no-store");assert.deepEqual(payload.data,{program:{commissionRateBasisPoints:200},summary:{availableBalance:0,totalEarnings:0,referrals:0,propertiesSold:0},items:[],page:1,pageSize:10,total:0,totalPages:0});});
test("property referral links are owner-safe, opaque and idempotent without becoming referrals",async t=>{const f=await referralsFixture(t);const first=await f.request("","POST",{type:"PROPERTY",listingId:f.listing});assert.equal(first.response.status,201);assert.match(first.payload.data.id,/^REF-[A-HJ-NP-Z2-9]{6}$/);assert.match(first.payload.data.referralUrl,new RegExp(`/buy\\?code=[A-Z]{3}-[A-HJ-NP-Z2-9]{6}&ref=${first.payload.data.id}$`));assert.deepEqual(Object.keys(first.payload.data).sort(),["id","propertyCode","referralType","referralUrl"]);assert(!JSON.stringify(first.payload).includes(f.owner));assert(!JSON.stringify(first.payload).includes(f.listing));const again=await f.request("","POST",{type:"PROPERTY",listingId:f.listing});assert.equal(again.payload.data.id,first.payload.data.id);assert.equal((await f.db.query<{count:number}>("select count(*)::integer as count from public.customer_referral_links")).rows[0]!.count,1);const dashboard=(await f.request()).payload.data;assert.deepEqual(dashboard.summary,{availableBalance:0,totalEarnings:0,referrals:0,propertiesSold:0});assert.deepEqual(dashboard.items,[]);});
test("seller referral links are reusable, unique from property links and never dashboard rows",async t=>{const f=await referralsFixture(t);const property=await f.request("","POST",{type:"PROPERTY",listingId:f.listing});const first=await f.request("","POST",{type:"SELLER"});const again=await f.request("","POST",{type:"SELLER"});assert.equal(first.response.status,201);assert.equal(first.payload.data.id,again.payload.data.id);assert.notEqual(first.payload.data.id,property.payload.data.id);assert.equal(first.payload.data.propertyCode,null);assert.equal(first.payload.data.referralUrl,`http://localhost:3000/register?ref=${first.payload.data.id}`);assert.equal((await f.db.query<{count:number}>("select count(*)::integer as count from public.customer_referral_links")).rows[0]!.count,2);assert.deepEqual((await f.request()).payload.data.items,[]);});
test("foreign properties and browser-owned reward fields are rejected",async t=>{const f=await referralsFixture(t);assert.equal((await f.request("","POST",{type:"PROPERTY",listingId:f.foreignListing})).response.status,404);for(const body of [{type:"SELLER",earnings:100},{type:"SELLER",status:"SUCCESSFUL"},{type:"PROPERTY",listingId:f.listing,userId:f.other},{type:"SELLER",listingId:f.listing},{type:"PROPERTY"}])assert.equal((await f.request("","POST",body)).response.status,400);assert.equal((await f.request()).payload.data.summary.referrals,0);});
test("owners cannot create links for one another and direct browser table access is denied",async t=>{const f=await referralsFixture(t);await f.repository.create(f.owner,"PROPERTY",f.listing);await f.repository.create(f.other,"PROPERTY",f.foreignListing);const rows=(await f.db.query<{user_id:string}>("select user_id from public.customer_referral_links order by user_id")).rows;assert.deepEqual(new Set(rows.map(row=>row.user_id)),new Set([f.owner,f.other]));await assert.rejects(f.db.query("set role authenticated; select * from public.customer_referral_links"));await f.db.exec("reset role");});
test("referral queries and origins are strict without mutating state",async t=>{const f=await referralsFixture(t);for(const path of ["?page=0","?page=1.5","?page=1&page=2","?user_id=other"])assert.equal((await f.request(path)).response.status,400);assert.equal((await f.request("","POST",{type:"SELLER"},undefined,{Origin:"https://evil.example"})).response.status,403);assert.equal((await f.request()).payload.data.summary.referrals,0);});
test("public-property links require an account and a currently LISTED property",async t=>{
  const f=await referralsFixture(t);const path="/public-property";
  const code=(await f.db.query<{listing_code:string}>("select listing_code from public.customer_listings where id=$1",[f.foreignListing])).rows[0]!.listing_code;
  assert.equal((await f.request(path,"POST",{propertyCode:code},"")).response.status,401);
  for(const status of ["UNLISTED","PENDING","REJECTED"]){await f.db.query("update public.customer_listings set listing_status=$1 where id=$2",[status,f.foreignListing]);assert.equal((await f.request(path,"POST",{propertyCode:code})).response.status,404);}
  assert.equal((await f.request(path,"POST",{propertyCode:"BRL-NONEXISTENT"})).response.status,404);
  await f.db.query("update public.customer_listings set listing_status='LISTED' where id=$1",[f.foreignListing]);
  const first=await f.request(path,"POST",{propertyCode:code});assert.equal(first.response.status,201);
  assert.equal(first.payload.data.referralUrl,`http://localhost:3000/buy?code=${code}&ref=${first.payload.data.id}`);
  assert(!JSON.stringify(first.payload).includes(f.owner));assert(!JSON.stringify(first.payload).includes(f.other));assert(!JSON.stringify(first.payload).includes(f.foreignListing));
  const repeat=await f.request(path,"POST",{propertyCode:code});assert.equal(repeat.payload.data.id,first.payload.data.id);
  const second=await f.repository.createPublicProperty(f.other,code);assert.notEqual(second.id,first.payload.data.id);
  const ownerCode=(await f.db.query<{listing_code:string}>("select listing_code from public.customer_listings where id=$1",[f.listing])).rows[0]!.listing_code;
  const ownerLink=await f.repository.create(f.owner,"PROPERTY",f.listing);
  await f.db.query("update public.customer_listings set listing_status='LISTED' where id=$1",[f.listing]);
  assert.equal((await f.repository.createPublicProperty(f.owner,ownerCode)).id,ownerLink.id);
  assert.equal((await f.db.query<{count:number}>("select count(*)::integer as count from public.customer_referral_links")).rows[0]!.count,3);
  assert.equal((await f.request()).payload.data.summary.totalEarnings,0);
  assert.equal((await f.db.query<{listing_status:string}>("select listing_status from public.customer_listings where id=$1",[f.foreignListing])).rows[0]!.listing_status,"LISTED");
  assert.equal((await f.request(path,"POST",{propertyCode:code,userId:f.owner})).response.status,400);
  await assert.rejects(f.db.query("set role authenticated; select public.create_listed_property_referral_link($1,$2)",[f.owner,code]));
  await f.db.exec("reset role");
});
