import assert from "node:assert/strict";
import { test } from "node:test";
import type { ProfileImage } from "../src/settings/model.js";
import { settingsFixture } from "./settings-profile.fixture.js";

test("business settings require the authenticated ACCOUNT owner",async t=>{const f=await settingsFixture(t);for(const cookie of ["","beryl_account=forged","beryl_recovery=settings-session"])assert.equal((await f.businessRequest("GET",undefined,cookie)).response.status,401);const body={...f.validBusiness,userId:f.other,ownerId:f.other,companyId:"BUS-AAAAAA"};assert.equal((await f.businessRequest("PATCH",body)).response.status,400);});
test("business profile is owner isolated with a stable non-UUID display code",async t=>{const f=await settingsFixture(t);const first=await f.repository.readBusiness(f.owner),again=await f.repository.readBusiness(f.owner),other=await f.repository.readBusiness(f.other);assert.match(first.companyId,/^BUS-[A-HJ-NP-Z2-9]{6}$/);assert.equal(again.companyId,first.companyId);assert.notEqual(other.companyId,first.companyId);await f.repository.updateBusiness(f.other,{...f.validBusiness,companyName:"Other Company"},null);const {payload}=await f.businessRequest();assert(!JSON.stringify(payload).includes("Other Company"));});
test("business update preserves auth email and personal address",async t=>{const f=await settingsFixture(t);await f.repository.update(f.owner,{...f.valid,phoneNormalized:"+2348012345678"},null);const before=await f.repository.readBusiness(f.owner),{response,payload}=await f.businessRequest("PATCH",f.validBusiness);assert.equal(response.status,200);assert.equal(payload.data.companyId,before.companyId);assert.equal(payload.data.companyEmail,"business@example.test");const auth=(await f.db.query<{email:string}>("select email from auth.users where id=$1",[f.owner])).rows[0]!,personal=(await f.db.query<{street_address:string}>("select street_address from public.customer_profiles where id=$1",[f.owner])).rows[0]!;assert.equal(auth.email,"ada@example.test");assert.equal(personal.street_address,"1 Beryl Road");});
test("business contact and address fields are validated server side",async t=>{const f=await settingsFixture(t);for(const body of [{...f.validBusiness,companyEmail:"invalid"},{...f.validBusiness,companyPhoneNumber:"abc"},{...f.validBusiness,aboutCompany:"x".repeat(1001)},{...f.validBusiness,streetAddress:""}])assert.equal((await f.businessRequest("PATCH",body)).response.status,400);});
test("company logo accepts PNG JPEG and WEBP but rejects unsafe files",async t=>{for(const file of [{type:"image/png",bytes:Buffer.from([137,80,78,71,13,10,26,10,0]),status:200},{type:"image/jpeg",bytes:Buffer.from([255,216,255,0]),status:200},{type:"image/webp",bytes:Buffer.from("RIFF0000WEBP0"),status:200},{type:"image/svg+xml",bytes:Buffer.from("<svg/>"),status:400},{type:"image/webp",bytes:Buffer.from("not webp"),status:400},{type:"image/png",bytes:Buffer.alloc(2*1024*1024+1),status:400}])await t.test(`${file.type}-${file.status}-${file.bytes.length}`,async child=>{const f=await settingsFixture(child),form=new FormData();form.set("data",JSON.stringify(f.validBusiness));form.set("companyLogo",new Blob([file.bytes],{type:file.type}),"logo");const result=await f.businessRequest("PATCH",form);assert.equal(result.response.status,file.status,JSON.stringify(result.payload));if(file.status===200)assert.match(result.payload.data.companyLogoUrl,/^https:\/\//);});});
test("logo reservation binds authoritative metadata and rejects foreign reservations",async t=>{const f=await settingsFixture(t),logo:ProfileImage={public_id:`beryl-v2/business-logos/${f.owner}/${crypto.randomUUID()}`,url:"https://images.example.test/authoritative",mime_type:"image/webp",size_bytes:12};await f.repository.journalBusinessLogo(f.owner,logo.public_id);await f.repository.reserveBusinessLogo(f.owner,logo);await f.repository.updateBusiness(f.owner,f.validBusiness,logo.public_id);const row=(await f.db.query<{logo_url:string;logo_mime_type:string;logo_size_bytes:number}>("select logo_url,logo_mime_type,logo_size_bytes from public.customer_business_profiles where user_id=$1",[f.owner])).rows[0]!;assert.deepEqual(row,{logo_url:logo.url,logo_mime_type:logo.mime_type,logo_size_bytes:logo.size_bytes});const foreign={...logo,public_id:`beryl-v2/business-logos/${f.other}/${crypto.randomUUID()}`};await f.repository.journalBusinessLogo(f.other,foreign.public_id);await f.repository.reserveBusinessLogo(f.other,foreign);await assert.rejects(f.repository.updateBusiness(f.owner,f.validBusiness,foreign.public_id));});
test("logo replacement queues old provider asset only after persistence",async t=>{const f=await settingsFixture(t),make=(mime:string):ProfileImage=>({public_id:`beryl-v2/business-logos/${f.owner}/${crypto.randomUUID()}`,url:"https://images.example.test/logo",mime_type:mime,size_bytes:12}),save=async(image:ProfileImage)=>{await f.repository.journalBusinessLogo(f.owner,image.public_id);await f.repository.reserveBusinessLogo(f.owner,image);await f.repository.updateBusiness(f.owner,f.validBusiness,image.public_id);};const first=make("image/png"),second=make("image/webp");await save(first);await save(second);assert.deepEqual(await f.repository.claimBusinessLogoCleanup(f.owner),[first.public_id]);});
test("browser roles cannot read business data or execute owner RPCs",async t=>{const f=await settingsFixture(t);await f.repository.readBusiness(f.owner);await assert.rejects(f.db.query("set role authenticated; select company_name from public.customer_business_profiles"));await f.db.exec("reset role");await assert.rejects(f.db.query("set role authenticated; select public.read_customer_settings_business($1)",[f.owner]));await f.db.exec("reset role");});
