"use client";
/* eslint-disable @next/next/no-img-element */
import {useState} from "react";
import {formatMoney,listingDate,statusLabel,type Listing} from "../../lib/listings-api";
import {BrandLoader} from "../auth/brand-loader";
import {useListingError,useListingRequest} from "./use-listing-request";
function Field({label,value,warning=false}:{label:string;value:React.ReactNode;warning?:boolean}){return <div className={warning?"listing-detail-field agent-empty":"listing-detail-field"}><span>{label}</span><div>{value||"-"}</div></div>;}
export function ListingDetail({id}:{id:string}) {
  const {data:listing,loading,reload}=useListingRequest<Listing>(`/${id}`);const [selected,setSelected]=useState(0);const error=useListingError();
  async function download(document:Listing["documents"][number]){try{const response=await fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL?.replace(/\/$/,"")}/api/v1/listings/${id}/documents/${document.id}`,{credentials:"include",cache:"no-store"});if(!response.ok)throw new Error("Document could not be downloaded. Please try again.");const url=URL.createObjectURL(await response.blob());const link=window.document.createElement("a");link.href=url;link.download=`document-${document.id}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}catch(failure){error(failure);}}
  if(loading)return <BrandLoader/>;if(!listing)return <button onClick={reload}>Try again</button>;
  return <div className="listing-detail"><div className="listings-title"><h1>Viewing {listing.title}</h1></div><div className="listing-detail-columns"><section className="listing-gallery" aria-label="Property images">{listing.images[selected]&&<img className="listing-main-image" src={listing.images[selected].url} alt={listing.title}/>}<div>{listing.images.map((image,index)=><button key={image.id} aria-label={`View image ${index+1}`} aria-pressed={selected===index} onClick={()=>setSelected(index)}><img src={image.url} alt=""/></button>)}</div></section><section className="listing-detail-information"><h2>{listing.title}</h2><h3>Description</h3><p>{listing.description}</p><p>This property {listing.has_lien?"has":"does not have"} a lien on it</p><p>Occupancy Type: {listing.occupancy_type.toLowerCase()}</p><p>Ownership Type: {listing.ownership_type.toLowerCase()}</p><p>The property has the following features:<br/>{listing.facilities.join(", ")||"-"}</p><h3>Documents</h3>{listing.documents.length?<ul>{listing.documents.map(document=><li key={document.id}><button className="listing-document-link" onClick={()=>void download(document)}>{document.title} — {document.description}</button></li>)}</ul>:<span>-</span>}<div className="listing-detail-metrics">{[["Bedroom",listing.bedrooms],["Bathroom",listing.bathrooms],["Parking Space",listing.parking_spaces],["Unit",listing.units??"-"]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="listing-two-fields"><Field label="Minimum Payment" value={formatMoney(listing.minimum_down_payment_minor)}/><Field label="Property Cost" value={formatMoney(listing.property_cost_minor)}/><Field label="Locality" value="-"/><Field label="Agent Assigned" value="-" warning/></div><Field label="Location" value={listing.location}/><div className="listing-two-fields"><Field label="City" value={listing.city}/><Field label="State" value={listing.state}/><Field label="Listing Status" value={statusLabel(listing.listing_status)}/><Field label="Property Status" value="Available"/><Field label="Property Type" value={listing.property_type}/><Field label="Property Subtype" value={listing.property_subtype}/></div><p>Agent Details</p><div className="listing-three-fields"><Field label="Name" value="-"/><Field label="Phone" value="-"/><Field label="Email" value="-"/></div><p>Owner Details</p><div className="listing-three-fields"><Field label="Name" value={listing.owner?.full_name}/><Field label="Phone" value={listing.owner?.phone}/><Field label="Email" value={listing.owner?.email}/></div><div className="listing-two-fields"><Field label="Date Listed" value={listingDate(listing.listed_at)}/><Field label="Last Updated" value={listingDate(listing.updated_at)}/></div></section></div></div>;
}
