"use client";
/* Property photographs are provider URLs, rendered directly without a public image proxy. */
/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {toast} from "react-toastify";
import {createReferral} from "../../lib/referrals-api";
import {formatMoney,listingDate,statusLabel,type Listing,type ListingsPage,type ListingStatus} from "../../lib/listings-api";
import {BrandLoader} from "../auth/brand-loader";
import {useDashboard} from "../dashboard/dashboard-provider";
import {DeleteListing,DocumentDrawer,RejectionReview,UnlistListing} from "./listing-overlays";
import {useListingError,useListingRequest} from "./use-listing-request";

const filters:{label:string;value:""|ListingStatus}[]=[{label:"All",value:""},{label:"Approved",value:"LISTED"},{label:"Pending",value:"PENDING"},{label:"Rejected",value:"REJECTED"},{label:"Unlisted",value:"UNLISTED"}];
function Metric({value,label}:{value:React.ReactNode;label:string}){return <div><strong>{value}</strong><small>{label}</small></div>;}
function SearchIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></svg>;}

function ListingCard({listing,reload}:{listing:Listing;reload:()=>void}) {
  const [overlay,setOverlay]=useState<"delete"|"documents"|"review"|"unlist"|null>(null);const [pending,setPending]=useState(false);const [copied,setCopied]=useState(false);const error=useListingError();const menu=useRef<HTMLDetailsElement>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
  useEffect(()=>{const close=(event:PointerEvent)=>{if(menu.current&&!menu.current.contains(event.target as Node))menu.current.open=false;};const escape=(event:KeyboardEvent)=>{if(event.key==="Escape"&&menu.current?.open){menu.current.open=false;menu.current.querySelector("summary")?.focus();}};document.addEventListener("pointerdown",close);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("pointerdown",close);document.removeEventListener("keydown",escape);if(timer.current)clearTimeout(timer.current);};},[]);
  const closeMenu=()=>{if(menu.current)menu.current.open=false;};
  async function refer(){if(pending)return;setPending(true);try{const referral=await createReferral({type:"PROPERTY",listingId:listing.id});await navigator.clipboard.writeText(referral.referralUrl);setCopied(true);toast.success("Referral link copied to clipboard");timer.current=setTimeout(()=>setCopied(false),3000);}catch{error(new Error("Could not copy the referral link. Please try again."));}finally{setPending(false);}}
  const editable=listing.listing_status==="UNLISTED"||listing.listing_status==="REJECTED";
  const place=[listing.city,listing.state].filter(Boolean).join(", ")||listing.location;
  return <article className="customer-listing-card">
    <Link className="listing-photo" href={`/dashboard/listings/${listing.id}`}>{listing.images[0]?<img src={listing.images[0].url} alt={listing.title}/>:<span>No image</span>}</Link>
    <div className="listing-card-information"><h2>{listing.title}</h2><p>{place}</p><strong className="listing-code">{listing.listing_code}</strong><div className="listing-facts"><Metric value={listing.bedrooms} label="Bed"/><Metric value={listing.bathrooms} label="Bath"/>{listing.toilet_count!==null&&<Metric value={listing.toilet_count} label="Toilet"/>}<Metric value={listing.parking_spaces} label="Parking"/>{listing.land_area!==null&&<Metric value={listing.land_area.toLocaleString()} label="Land area"/>}</div></div>
    <div className="listing-card-financial"><Metric value={<span className="listing-green">{formatMoney(listing.property_cost_minor,false)}</span>} label="Price"/><Metric value={listing.time_on_market===null?"Not listed":`${listing.time_on_market} days`} label="Time on Market"/><Metric value={listing.property_status==="AVAILABLE"?"Available":listing.property_status} label="Property Status"/><Metric value={listingDate(listing.listed_at)} label="Date Listed"/></div>
    <div className="listing-performance"><h3>PERFORMANCE</h3><p>View more Performance Analytics Data <Link href="/dashboard/analytics">View</Link></p><div className="listing-performance-metrics"><div className="listing-completeness"><strong>Completeness</strong><progress value={listing.completeness} max={100} aria-label={`Completeness ${listing.completeness}%`}/><small>{listing.completeness}% complete</small></div><Metric value={`${listing.leads} Leads`} label="No trend data"/><Metric value={`${listing.views} Views`} label="No trend data"/></div></div>
    <div className="listing-card-status"><strong className={`listing-status-pill status-${listing.listing_status.toLowerCase()}`}>{statusLabel(listing.listing_status)}</strong><small>Listing Status</small><details className="listing-action-menu" ref={menu}><summary aria-label={`Actions for ${listing.title}`} aria-haspopup="menu">⋮</summary><div role="menu"><Link role="menuitem" href={`/dashboard/listings/${listing.id}`} onClick={closeMenu}>View</Link>{editable&&<Link role="menuitem" href={`/dashboard/listings/${listing.id}/edit`} onClick={closeMenu}>{listing.listing_status==="REJECTED"?"Make changes":"Edit"}</Link>}<button role="menuitem" disabled={pending} onClick={()=>{closeMenu();setOverlay("delete");}}>Delete</button>{editable&&<button role="menuitem" disabled={pending} onClick={()=>{closeMenu();setOverlay("documents");}}>Upload Document</button>}{listing.listing_status==="REJECTED"&&<button role="menuitem" onClick={()=>{closeMenu();setOverlay("review");}}>See reason</button>}{listing.listing_status==="LISTED"&&<><button role="menuitem" disabled={pending} onClick={()=>{closeMenu();void refer();}}>{copied?"Link Copied":"Refer Property"}</button><button role="menuitem" onClick={()=>{closeMenu();setOverlay("unlist");}}>Unlist</button></>}</div></details><div className="listing-card-action">{listing.listing_status==="LISTED"&&<button className="listing-primary" onClick={()=>setOverlay("unlist")}>Unlist</button>}{listing.listing_status==="REJECTED"&&<button className="listing-primary" onClick={()=>setOverlay("review")}>See reason</button>}{listing.listing_status==="UNLISTED"&&<Link className="listing-primary" href={`/dashboard/listings/${listing.id}/edit`}>Complete Listing</Link>}</div></div>
    {overlay==="delete"&&<DeleteListing listing={listing} close={()=>setOverlay(null)} done={()=>{setOverlay(null);reload();}}/>}{overlay==="unlist"&&<UnlistListing listing={listing} close={()=>setOverlay(null)} done={()=>{setOverlay(null);reload();}}/>}{overlay==="review"&&<RejectionReview listing={listing} close={()=>setOverlay(null)}/>} {overlay==="documents"&&<DocumentDrawer listing={listing} close={()=>setOverlay(null)} done={()=>{setOverlay(null);reload();}}/>}
  </article>;
}

export function ListingsScreen(){
  const {refreshOverview}=useDashboard();const [search,setSearch]=useState("");const [q,setQ]=useState("");const [status,setStatus]=useState<""|ListingStatus>("");const [page,setPage]=useState(1);
  useEffect(()=>{if(search===q)return;const timer=setTimeout(()=>{setQ(search.trim());setPage(1);},300);return()=>clearTimeout(timer);},[search,q]);
  const query=new URLSearchParams({q,page:String(page)});if(status)query.set("status",status);
  const {data,loading,reload:refetch}=useListingRequest<ListingsPage>(`?${query}`);const reload=()=>{refreshOverview();refetch();};
  const counts=data?.counts??{all:0,UNLISTED:0,PENDING:0,LISTED:0,REJECTED:0};const totalPages=Math.max(1,data?.total_pages??1);
  return <section className="listings-page"><div className="listings-title"><h1><span className="desktop-listings-title">Listings</span><span className="mobile-listings-title">My Listings</span></h1><Link className="listing-primary create-listing-link" href="/dashboard/listings/new">＋ Create Listing</Link></div>{loading?<BrandLoader/>:!data?<button onClick={reload}>Try again</button>:counts.all===0&&!q?<div className="listings-empty"><span className="listings-empty-art" aria-hidden="true">▧</span><h2>No listings yet</h2><p>Created listings will appear here</p><Link href="/dashboard/listings/new">＋ Create a listing</Link></div>:<><div className="listings-panel"><div className="listings-toolbar"><label className="listings-search"><SearchIcon/><input aria-label="Search" placeholder="Search by title, code or location" value={search} maxLength={100} onChange={event=>setSearch(event.target.value)}/></label><div className="listing-status-filters" role="group" aria-label="Filter listings by status">{filters.map(filter=><button key={filter.label} type="button" className={status===filter.value?"active":""} aria-pressed={status===filter.value} onClick={()=>{setStatus(filter.value);setPage(1);}}>{filter.label} <span>{filter.value?counts[filter.value]:counts.all}</span></button>)}</div></div>{data.items.length?<div className="listing-results">{data.items.map(listing=><ListingCard key={`${listing.id}-${listing.version}`} listing={listing} reload={reload}/>)}</div>:<div className="listings-no-results"><h2>No matching listings</h2><p>Try another search or status filter.</p><button onClick={()=>{setSearch("");setQ("");setStatus("");setPage(1);}}>Clear filters</button></div>}<nav className="listings-pagination" aria-label="Listings pages"><span aria-current="page">Page {Math.min(page,totalPages)} of {totalPages}</span><div><button aria-label="Previous page" disabled={loading||page===1} onClick={()=>setPage(value=>value-1)}>←</button><button aria-label="Next page" disabled={loading||page>=totalPages} onClick={()=>setPage(value=>value+1)}>→</button></div></nav></div></>}</section>;
}
