"use client";
/* Property photographs are provider URLs, rendered directly without a public image proxy. */
/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {toast} from "react-toastify";
import {formatMoney,listingDate,listingsRequest,statusLabel,type Listing,type ListingsPage} from "../../lib/listings-api";
import {BrandLoader} from "../auth/brand-loader";
import {useDashboard} from "../dashboard/dashboard-provider";
import {DeleteListing,DocumentDrawer} from "./listing-overlays";
import {useListingError,useListingRequest} from "./use-listing-request";
function Metric({value,label}:{value:React.ReactNode;label:string}){return <div><strong>{value}</strong><small>{label}</small></div>;}
function ListingCard({listing,reload}:{listing:Listing;reload:()=>void}) {
  const [overlay,setOverlay]=useState<"delete"|"documents"|null>(null);const [pending,setPending]=useState(false);const [copied,setCopied]=useState(false);const error=useListingError();const menu=useRef<HTMLDetailsElement>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
  useEffect(()=>{const close=(event:MouseEvent)=>{if(menu.current&&!menu.current.contains(event.target as Node))menu.current.open=false;};const escape=(event:KeyboardEvent)=>{if(event.key==="Escape"&&menu.current)menu.current.open=false;};document.addEventListener("click",close);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("click",close);document.removeEventListener("keydown",escape);if(timer.current)clearTimeout(timer.current);};},[]);
  async function action(path:string){if(pending)return;setPending(true);try{await listingsRequest(`/${listing.id}/${path}`,{method:"POST",body:{version:listing.version}});toast.success(path==="request-approval"?"Application submitted":"Listing unlisted");reload();}catch(failure){error(failure);}finally{setPending(false);}}
  async function refer(){try{await navigator.clipboard.writeText(listing.referral_url);setCopied(true);toast.success("Referral link copied to clipboard");timer.current=setTimeout(()=>setCopied(false),3000);}catch{error(new Error("Could not copy the referral link. Please try again."));}}
  const editable=["UNLISTED","REJECTED"].includes(listing.listing_status);
  return <article className="customer-listing-card"><div className="listing-card-top"><Link className="listing-photo" href={`/dashboard/listings/${listing.id}`}>{listing.images[0]?<img src={listing.images[0].url} alt={listing.title}/>:<span>-</span>}</Link><div className="listing-card-information"><h2>{listing.title}</h2><p>{listing.location}, {listing.city}</p><strong className="listing-code">{listing.listing_code}</strong><div className="listing-facts"><Metric value={listing.bedrooms} label="Bed"/><Metric value={listing.bathrooms} label="Bath"/><Metric value={listing.toilet_count??0} label="Toilet"/><Metric value={listing.parking_spaces} label="Parking Space"/></div></div><div className="listing-card-financial"><div className="listing-financial-top"><Metric value={<span className="listing-green">{formatMoney(listing.property_cost_minor,false)}</span>} label="Price"/><Metric value={`${listing.time_on_market??"-"} days`} label="Time on Market"/></div><div className="listing-facts"><Metric value={listing.land_area??"-"} label="sqft"/><Metric value="Available" label="Property Status"/><Metric value={listingDate(listing.listed_at)} label="Date Listed"/></div></div></div><div className="listing-card-bottom"><div className="listing-performance"><h3>PERFORMANCE</h3><p>View more Performance Analytics Data <Link href="/dashboard/analytics">View</Link></p><div className="listing-performance-metrics"><div className="listing-completeness"><strong>Completeness</strong><progress value={listing.completeness} max={100} aria-label={`Completeness ${listing.completeness}%`}/></div><Metric value={`${listing.leads} Leads`} label="% — VS last month"/><Metric value={`${listing.views} Views`} label="% — VS last month"/></div></div><div className="listing-card-status"><strong>{statusLabel(listing.listing_status)}</strong><small>Listing Status</small><details className="listing-action-menu" ref={menu}><summary aria-label={`Actions for ${listing.title}`}>⋮</summary><div><Link href={`/dashboard/listings/${listing.id}`}>◉ View</Link>{editable&&<Link href={`/dashboard/listings/${listing.id}/edit`}>✎ Edit</Link>}<button disabled={pending} onClick={()=>setOverlay("delete")}>♧ Delete</button>{editable&&<button disabled={pending} onClick={()=>setOverlay("documents")}>▣ Upload Document</button>}<button disabled={pending} onClick={()=>void refer()}>↪ {copied?"Link Copied":"Refer Property"}</button>{listing.listing_status==="UNLISTED"&&<button disabled={pending} onClick={()=>void action("request-approval")}>◎ Request Approval</button>}</div></details>{listing.listing_status==="PENDING"&&<button className="listing-primary unlist-button" disabled={pending} onClick={()=>void action("unlist")}>Unlist</button>}</div></div>{overlay==="delete"&&<DeleteListing listing={listing} close={()=>setOverlay(null)} done={()=>{setOverlay(null);reload();}}/>}{overlay==="documents"&&<DocumentDrawer listing={listing} close={()=>setOverlay(null)} done={()=>{setOverlay(null);reload();}}/>}</article>;
}
export function ListingsScreen(){
  const {refreshOverview}=useDashboard();
  const [search,setSearch]=useState("");const [q,setQ]=useState("");const [status,setStatus]=useState("");const [page,setPage]=useState(1);
  useEffect(()=>{if(search===q)return;const timer=setTimeout(()=>{setQ(search);setPage(1);},300);return()=>clearTimeout(timer);},[search,q]);
  const query=new URLSearchParams({q,page:String(page)});if(status)query.set("status",status);
  const {data,loading,reload:refetch}=useListingRequest<ListingsPage>(`?${query}`);
  const reload=()=>{refreshOverview();refetch();};
  return <div className="listings-page"><div className="listings-title"><h1>My Listings</h1><Link className="listing-primary" href="/dashboard/listings/new">+ Create Listing</Link></div><div className="listings-toolbar"><input aria-label="Search" placeholder="⌕  Search" value={search} maxLength={100} onChange={event=>setSearch(event.target.value)}/><select aria-label="Status" value={status} onChange={event=>{setStatus(event.target.value);setPage(1);}}><option value="">Status</option>{["All","Unlisted","Pending","Listed","Rejected"].map(label=><option key={label} value={label==="All"?"":label.toUpperCase()}>{label}</option>)}</select><span>Page {data?.total?(page-1)*data.page_size+1:1}-{data?Math.min(page*data.page_size,data.total):0} of {data?.total??0}</span></div>{loading?<BrandLoader/>:!data?<button onClick={reload}>Try again</button>:data.items.length?<div className="listing-results">{data.items.map(listing=><ListingCard key={`${listing.id}-${listing.version}`} listing={listing} reload={reload}/>)}</div>:<p className="listings-empty">No listings.</p>}<nav className="listings-pagination" aria-label="Listings pages"><button aria-label="Previous page" disabled={loading||page===1} onClick={()=>setPage(value=>value-1)}>‹</button><span aria-current="page">{page}</span><button aria-label="Next page" disabled={loading||page>=(data?.total_pages??0)} onClick={()=>setPage(value=>value+1)}>›</button></nav></div>;
}
