import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

const src = (file: string) => readFileSync(path.resolve(__dirname, file), "utf8");
const app = (file: string) => readFileSync(path.resolve(__dirname, "..", file), "utf8");
const landing = src("components/referrals/referral-landing-screen.tsx");
const form = src("components/referrals/direct-referral-screen.tsx");
const tracking = src("components/referrals/referral-tracking-screen.tsx");
const dashboard = src("components/referrals/referral-dashboard-screen.tsx");
const bank = src("components/referrals/referral-bank-details-screen.tsx");
const api = src("api/referrals.ts");
const flow = src("store/referral-flow.tsx");
const auth = src("store/auth-flow.tsx");
const ui = src("components/referrals/referral-ui.tsx");

describe("approved Mobile Referral architecture", () => {
  it("creates the referral landing route", () => expect(app("app/refer.tsx")).toContain("ReferralLandingScreen"));
  it("creates the referral dashboard route", () => expect(app("app/referrals/index.tsx")).toContain("ReferralDashboardScreen"));
  it("creates the direct-referral route", () => expect(app("app/referrals/new.tsx")).toContain("DirectReferralScreen"));
  it("creates the tracking route", () => expect(app("app/referrals/track.tsx")).toContain("ReferralTrackingScreen"));
  it("creates the bank-details route", () => expect(app("app/referrals/bank-details.tsx")).toContain("ReferralBankDetailsScreen"));
  it("renders the approved marketing heading and limits", () => { expect(landing).toContain("Refer someone and"); expect(landing).toContain("₦2,500,000"); expect(landing).toContain("up to 25%"); });
  it("uses approved native mobile artwork rather than a design screenshot", () => { expect(landing).toContain("referral-hero.png"); expect(existsSync(path.resolve(__dirname, "../assets/referrals/referral-hero.png"))).toBe(true); });
  it("uses only the canonical API referral context for a personal link", () => { expect(landing).toContain("/referrals/context"); expect(landing).toContain("referrer.referralLink"); expect(landing).not.toMatch(/EMK7Q2|BSR-ADA/); });
  it("provides native Copy and copied feedback", () => { expect(ui).toContain("Clipboard.setStringAsync(value)"); expect(ui).toContain('"Copied!"'); });
  it("provides the approved direct referral CTA", () => { expect(landing).toContain("Refer them directly"); expect(landing).toContain("Fill in their details"); });
  it("supports Buying and Selling", () => { expect(form).toContain('[["BUYING", "Buying"], ["SELLING", "Selling"]]'); });
  it("validates before direct referral submission", () => { expect(form).toContain("guestReferrerSchema.safeParse"); expect(form).toContain("referredPersonSchema.safeParse"); });
  it("submits through the canonical referral endpoint", () => expect(api).toContain('"/referrals", "POST"'));
  it("supports anonymous referrers without customer onboarding", () => { expect(form).toContain("!session.isAuthenticated"); expect(form).toContain("referrer: guest.data"); expect(form).not.toContain("/buyer"); expect(form).not.toContain("/seller"); });
  it("uses customer authorization for logged-in referrals", () => expect(form).toContain("session.accessToken"));
  it("does not send customer or referrer ids from the client", () => { expect(form).not.toMatch(/customerId|referrerId|customer_user_id/); expect(api).not.toMatch(/customerId|referrerId/); });
  it("branches authenticated success to the dashboard", () => { expect(form).toContain('"OPEN_REFERRAL_DASHBOARD"'); expect(form).toContain("Go to dashboard"); });
  it("branches guest success to real tracking delivery", () => { expect(form).toContain("requestReferralTracking"); expect(form).toContain("Send code on WhatsApp"); });
  it("shows provider-unavailable state truthfully", () => { expect(src("referrals/helpers.ts")).toContain("REFERRAL_TRACKING_UNAVAILABLE"); expect(form).toContain("referralErrorMessage"); });
  it("describes the configured WhatsApp-only delivery path without client Termii credentials", () => { expect(tracking).toContain("send a code on WhatsApp"); expect(tracking).not.toMatch(/TERMII_|api\/sms\/send|developers\.termii/i); });
  it("supports tracking identity and phone validation", () => expect(tracking).toContain("referralTrackingIdentitySchema.safeParse"));
  it("renders six accessible OTP inputs", () => { expect(tracking).toContain("Digit ${index + 1}"); expect(tracking).toContain("digits.map"); });
  it("automatically verifies a complete six-digit OTP", () => expect(tracking).toContain("if (next.every(Boolean)) submitOtp"));
  it("maps invalid, expired and rate-limited OTP errors", () => ["REFERRAL_OTP_INVALID", "REFERRAL_OTP_EXPIRED", "REFERRAL_OTP_RATE_LIMITED"].forEach((code) => expect(src("referrals/helpers.ts")).toContain(code)));
  it("stores only the narrow opaque tracking token in a separate SecureStore key", () => { expect(flow).toContain("beryl_referral_tracking_token"); expect(flow).not.toContain("beryl_customer_access_token"); expect(tracking).toContain("referralTrackingSession.save(token)"); });
  it("isolates the referral token to referral dashboard and payout requests", () => { expect(api).toContain('"X-Referral-Tracking-Token"'); expect(api).not.toMatch(/marketplace|personas|onboarding|seller\/listings/); expect(auth).not.toContain("X-Referral-Tracking-Token"); });
  it("loads only the canonical referrer's dashboard records", () => expect(api).toContain("/referrals/dashboard?page="));
  it("maps status through shared Mobile display helpers", () => expect(dashboard).toContain("referralStatus(item.status)"));
  it("displays only backend-supplied reward amounts", () => { expect(dashboard).toContain("item.rewardAmount !== null"); expect(dashboard).not.toMatch(/\.25|25\s*\/\s*100|askingPrice/); });
  it("displays backend payment state", () => expect(dashboard).toContain("paymentLabel(item.paymentStatus)"));
  it("provides an intentional empty state", () => expect(dashboard).toContain("No referrals yet"));
  it("supports dashboard pagination and guarded load more", () => { expect(dashboard).toContain("useInfiniteQuery"); expect(dashboard).toContain("dashboard.hasNextPage"); expect(dashboard).toContain("dashboard.isFetchingNextPage"); });
  it("provides safe dashboard retry and referral-session recovery", () => { expect(dashboard).toContain("dashboard.refetch()"); expect(dashboard).toContain("REFERRAL_SESSION_REQUIRED"); });
  it("loads the bank directory from the server", () => expect(api).toContain('"/referrals/banks", "GET"'));
  it("does not embed a separate mobile bank directory", () => { expect(bank).not.toMatch(/Guaranty Trust Bank|OPay|PalmPay|Moniepoint/); expect(bank).toContain("directory.find"); });
  it("supports OPay, PalmPay and Moniepoint through unfiltered server results", () => { expect(bank).toContain("banks.data?.data?.banks"); expect(bank).toContain("banks.filter"); });
  it("validates a ten-digit account number and strips non-digits", () => { expect(src("referrals/schemas.ts")).toContain("/^\\d{10}$/"); expect(bank).toContain('value.replace(/\\D/g, "").slice(0, 10)'); });
  it("uses manual account-name entry without fake verification", () => { expect(bank).toContain("Account Name"); expect(bank).toContain("entered manually"); expect(bank).not.toMatch(/verified account|resolveAccount/i); });
  it("saves payout details through the canonical PUT endpoint", () => expect(api).toContain('"/referrals/payout-details", "PUT"'));
  it("renders only the backend-masked account number after saving", () => { expect(dashboard).toContain("details.maskedAccountNumber"); expect(dashboard).not.toContain("accountNumber.slice"); });
  it("never persists or logs bank account data locally", () => { expect(flow).not.toMatch(/accountNumber|bankCode|accountName/); expect(bank).not.toMatch(/console\.|AsyncStorage|SecureStore/); });
  it("uses safe areas and keyboard-aware scrolling", () => { expect(ui).toContain("SafeAreaView"); expect(ui).toContain("KeyboardAwareScrollView"); expect(bank).toContain('keyboardType="number-pad"'); });
  it("uses flex and shrink-safe controls without screenshot widths", () => { expect(ui).toContain("minWidth: 0"); expect(bank).toContain("flexShrink: 1"); expect(landing).not.toMatch(/width:\s*390|width:\s*430|width:\s*360/); });
  it("provides intentional loading, empty and error states", () => { expect(dashboard).toContain("Loading your referrals"); expect(dashboard).toContain("No referrals yet"); expect(dashboard).toContain("We could not load your referrals"); });
  it("disables automatic mutation retries so forms remain retryable", () => { expect(form).toContain("retry: false"); expect(tracking).toContain("retry: false"); expect(bank).toContain("retry: false"); });
  it("centralizes referral query keys and invalidates after writes", () => { expect(form).toContain("referralQueryKeys.all"); expect(bank).toContain("invalidateQueries"); });
  it("adds no speculative referral analytics", () => { const files = landing + form + tracking + dashboard + bank; expect(files).not.toMatch(/trackCustomerEvent|mixpanel|analytics/i); });
  it("preserves Buyer Marketplace, Seller Marketplace, persona switching and customer auth routes", () => ["app/marketplace/index.tsx", "app/marketplace/[propertyId].tsx", "app/seller/listings/index.tsx", "src/components/persona-switcher.tsx", "src/store/auth-flow.tsx"].forEach((file) => expect(existsSync(path.resolve(__dirname, "..", file))).toBe(true)));
  it("makes referrals reachable from the existing account sheet", () => expect(src("components/marketplace/marketplace-ui.tsx")).toContain("Refer & earn"));
});
