"use client";

import { ArrowLeft, Check, Download, Landmark, UserRound, X } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import type { AdminReferralPaymentPreparation, AdminReferrerDetail, ApiEnvelope } from "@/lib/contracts";

const money = (value: number | null) => value === null ? "—" : new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(value);
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-NG", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)) : "—";
const lifecycle = { NEW: "New", CONTACTED: "Contacted", IN_PROGRESS: "In Progress", COMPLETED: "Completed", LOST: "Lost" } as const;

function PaymentDialog({ referrerId, referralId, onClose, onPaid }: { referrerId: string; referralId: string; onClose: () => void; onPaid: () => void }) {
  const [payment, setPayment] = useState<AdminReferralPaymentPreparation | null>(null); const [file, setFile] = useState<File | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [pending, setPending] = useState(false); const closeRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { closeRef.current?.focus(); const close = (event: KeyboardEvent) => event.key === "Escape" && !pending && onClose(); window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [onClose, pending]);
  useEffect(() => { let active = true; void (async () => { try { const response = await fetch(`/api/admin/referrers/${referrerId}/referrals/${referralId}/payment-preparation`, { cache: "no-store" }); const payload = await response.json() as ApiEnvelope<{ payment: AdminReferralPaymentPreparation }>; if (!response.ok || !payload.data?.payment) throw new Error(payload.message || "Payment details could not be prepared."); if (active) setPayment(payload.data.payment); } catch (reason) { if (active) setError(reason instanceof Error ? reason.message : "Payment details could not be prepared."); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, [referrerId, referralId]);
  const selectFile = (selected: File | null) => { setError(""); if (!selected) return setFile(null); if (!["application/pdf", "image/png", "image/jpeg"].includes(selected.type) || selected.size > 10 * 1024 * 1024) { setFile(null); setError("Upload one PDF, PNG, or JPG receipt up to 10MB."); return; } setFile(selected); };
  const confirm = async () => { if (!payment || !file || pending) return; setPending(true); setError(""); try { const form = new FormData(); form.set("receipt", file); const response = await fetch(`/api/admin/referrers/${referrerId}/referrals/${referralId}/mark-paid`, { method: "POST", body: form }); const payload = await response.json() as ApiEnvelope<Record<string, unknown>>; if (!response.ok) throw new Error(payload.message || "Payment could not be recorded."); onPaid(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Payment could not be recorded."); setPending(false); } };
  return <div className="referrer-dialog-backdrop" onMouseDown={(event) => event.target === event.currentTarget && !pending && onClose()}><div className="referrer-payment-dialog" role="dialog" aria-modal="true" aria-labelledby="payment-title"><button ref={closeRef} type="button" className="dialog-close" disabled={pending} onClick={onClose} aria-label="Close payment dialog"><X /></button><h2 id="payment-title">Record this payment</h2><p>Confirm the recipient and upload proof of payment. The amount is set by the referral record.</p>{loading ? <div className="payment-loading">Preparing secure payout details…</div> : null}{payment ? <><dl className="payment-recipient"><div><dt>Referrer</dt><dd>{payment.referrer.fullName}</dd></div><div><dt>Referral</dt><dd>{payment.referral.referenceId}</dd></div><div><dt>Amount</dt><dd>{money(payment.amount)}</dd></div></dl><div className="pay-to"><Landmark aria-hidden /><div><small>Pay to</small><strong>{payment.payout.accountName}</strong><span>{payment.payout.bankName} · {payment.payout.accountNumber}</span></div></div><label className="receipt-upload"><strong>Upload Payment Receipt or bank confirmation <span>*</span></strong><small>Upload PDF, PNG, or JPG. Maximum 10MB.</small><input type="file" accept="application/pdf,image/png,image/jpeg,.pdf,.png,.jpg,.jpeg" onChange={(event) => selectFile(event.target.files?.[0] ?? null)} /><span>{file ? file.name : "Choose receipt"}</span></label></> : null}{error ? <div className="alert alert-error" role="alert">{error}</div> : null}<footer><button type="button" disabled={pending} onClick={onClose}>Cancel</button><button type="button" disabled={!payment || !file || pending} onClick={() => void confirm()}>{pending ? "Recording…" : "Confirm Payment"}</button></footer></div></div>;
}

function SuccessDialog({ onClose }: { onClose: () => void }) { useEffect(() => { const close = (event: KeyboardEvent) => event.key === "Escape" && onClose(); window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [onClose]); return <div className="referrer-dialog-backdrop"><div className="payment-success" role="dialog" aria-modal="true" aria-labelledby="payment-success-title"><span><Check /></span><h2 id="payment-success-title">Payment Recorded</h2><p>Payment has been recorded successfully and the receipt is available to authorized Admin staff.</p><button type="button" autoFocus onClick={onClose}>Done</button></div></div>; }

export function AdminReferrerDetailScreen({ referrerId }: { referrerId: string }) {
  const [detail, setDetail] = useState<AdminReferrerDetail | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [paying, setPaying] = useState<string | null>(null); const [success, setSuccess] = useState(false); const [receipt, setReceipt] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch(`/api/admin/referrers/${encodeURIComponent(referrerId)}`, { cache: "no-store" }); const payload = await response.json() as ApiEnvelope<{ referrer: AdminReferrerDetail }>; if (!response.ok || !payload.data?.referrer) throw new Error(payload.message || "Referrer could not be loaded."); setDetail(payload.data.referrer); } catch (reason) { setError(reason instanceof Error ? reason.message : "Referrer could not be loaded."); } finally { setLoading(false); } }, [referrerId]);
  useEffect(() => { const task = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(task); }, [load]);
  const openReceipt = async (referralId: string) => { if (receipt) return; setReceipt(referralId); setError(""); try { const response = await fetch(`/api/admin/referrers/${referrerId}/referrals/${referralId}/payment/receipt/access`, { cache: "no-store" }); const payload = await response.json() as ApiEnvelope<{ access: { url: string } }>; if (!response.ok || !payload.data?.access?.url) throw new Error(payload.message || "Receipt could not be opened."); window.open(payload.data.access.url, "_blank", "noopener,noreferrer"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Receipt could not be opened."); } finally { setReceipt(null); } };
  if (loading && !detail) return <div className="referrer-detail-state">Loading referrer…</div>;
  if (!detail) return <div className="referrer-detail-state alert alert-error" role="alert"><span>{error || "Referrer could not be loaded."}</span><button type="button" onClick={() => void load()}>Try again</button></div>;
  const { identity, summary, payout, referrals } = detail;
  return <article className="admin-referrer-detail"><Link className="back-referrers" href={"/dashboard/referrers" as never}><ArrowLeft size={16} />Back to referrers</Link>{error ? <div className="alert alert-error" role="alert">{error}</div> : null}<header className="referrer-detail-header"><div className="identity-avatar"><UserRound /></div><div><span>{identity.identityType === "CUSTOMER_LINKED" ? "Customer-linked referrer" : "Referral-only referrer"}</span><h1>{identity.fullName}</h1><p>{identity.phone || identity.email || "No contact displayed"} · {identity.referralCode}</p><small>Joined {date(identity.joinedAt)}</small>{detail.linkedCustomer ? <Link href={`/dashboard/users/${detail.linkedCustomer.id}` as never}>View Customer</Link> : null}</div></header><div className="referrer-detail-summary">{[["Referrals", summary.referrals.toLocaleString("en-NG")], ["Completed", summary.completed.toLocaleString("en-NG")], ["Earned", money(summary.earnedAmount)], ["Outstanding", money(summary.outstandingAmount)]].map(([label, value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>
    <div className="referrer-detail-layout"><section className="referral-history"><h2>Referral history</h2><p>Canonical referral progress and eligible rewards.</p><div className="referral-history-scroll"><table><thead><tr><th>Reference</th><th>Referred Person</th><th>Purpose</th><th>Date</th><th>Status</th><th>Reward</th><th>Payment</th></tr></thead><tbody>{referrals.map((item) => <tr key={item.id}><td><strong>{item.referenceId}</strong></td><td>{item.referredFullName}</td><td>{item.purpose === "BUYING" ? "Buying" : "Selling"}</td><td>{date(item.createdAt)}</td><td><span className="referral-lifecycle" data-state={item.lifecycleStatus.toLowerCase()}>{lifecycle[item.lifecycleStatus]}</span></td><td>{money(item.rewardAmount)}</td><td>{item.paymentStatus === "OUTSTANDING" ? <button className="mark-paid" type="button" disabled={payout.status !== "ON_FILE"} title={payout.status !== "ON_FILE" ? "Payout details are required" : undefined} onClick={() => setPaying(item.id)}>Mark as paid</button> : item.paymentStatus === "PAID" ? <span className="paid-actions"><b>Paid</b><button type="button" disabled={receipt === item.id} onClick={() => void openReceipt(item.id)}><Download size={13} />View Receipt</button></span> : <span className="not-eligible">Not eligible</span>}</td></tr>)}</tbody></table></div>{referrals.length === 0 ? <div className="referrals-empty"><strong>No referrals yet</strong><p>Referral history will appear here.</p></div> : null}</section><aside className="referrer-payout-card"><header><h2>Payment details</h2><span data-state={payout.status.toLowerCase()}>{payout.status === "ON_FILE" ? "On File" : payout.status === "MISSING" ? "Missing" : "Not Needed"}</span></header>{payout.status === "ON_FILE" ? <dl><div><dt>Account name</dt><dd>{payout.accountName}</dd></div><div><dt>Bank</dt><dd>{payout.bankName}</dd></div><div><dt>Account number</dt><dd>{payout.maskedAccountNumber}</dd></div></dl> : <p>{payout.status === "MISSING" ? "The referrer must add payout details before an eligible reward can be paid." : "No payout details are needed while there is no outstanding reward."}</p>}<small>Set by the referrer. Admin can view but not edit.</small></aside></div>
    {paying ? <PaymentDialog referrerId={referrerId} referralId={paying} onClose={() => setPaying(null)} onPaid={() => { setPaying(null); void load().then(() => setSuccess(true)); }} /> : null}{success ? <SuccessDialog onClose={() => setSuccess(false)} /> : null}
  </article>;
}
