"use client";
import Link from "next/link";import { useRouter,useSearchParams } from "next/navigation";import { useEffect,useState,type FormEvent } from "react";
import { listAdminReferrers,type ReferrerDirectoryPage,type ReferrerFilter,type ReferrerSort } from "../lib/admin-referrers-api";import { AdminAppShell } from "./admin-app-shell";
const filters:ReferrerFilter[]=["ALL","OWED","PAID"],sorts:ReferrerSort[]=["NEWEST","OLDEST","NAME_ASC","NAME_DESC","OUTSTANDING_DESC"];
const money=(value:number)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:2}).format(value/100).replace("NGN","₦");
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join("").toUpperCase()||"—";
const bankLabel={ON_FILE:"On File",MISSING:"Missing",NOT_NEEDED:"Not Needed"} as const;
function Content(){const router=useRouter(),params=useSearchParams(),search=params.get("search")?.slice(0,100)??"",rawFilter=params.get("filter")?.toUpperCase() as ReferrerFilter|null,rawSort=params.get("sort")?.toUpperCase() as ReferrerSort|null,filter=rawFilter&&filters.includes(rawFilter)?rawFilter:"ALL",sort=rawSort&&sorts.includes(rawSort)?rawSort:"NEWEST",rawPage=Number(params.get("page")??1),page=Number.isInteger(rawPage)&&rawPage>0?rawPage:1;const[data,setData]=useState<ReferrerDirectoryPage|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
useEffect(()=>{const controller=new AbortController();queueMicrotask(()=>{if(!controller.signal.aborted){setLoading(true);setError("");}});listAdminReferrers({search,filter,sort,page},controller.signal).then(setData).catch(reason=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:"Referrers could not be loaded.");}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[filter,page,search,sort]);
function update(values:Record<string,string|number>){const next=new URLSearchParams(params.toString());for(const[key,value]of Object.entries(values)){if(value===""||(key==="page"&&value===1)||(key==="filter"&&value==="ALL")||(key==="sort"&&value==="NEWEST"))next.delete(key);else next.set(key,String(value));}router.replace(next.size?`/dashboard/referrers?${next}`:"/dashboard/referrers");}
function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();update({search:String(new FormData(event.currentTarget).get("search")??"").trim(),page:1});}
const first=data?.total?(data.page-1)*data.pageSize+1:0,last=data?Math.min(data.page*data.pageSize,data.total):0;
return <main className="admin-referrers-page"><header className="admin-page-heading"><h1>Referrers</h1><p>Everyone who has sent Beryl a referral, and what they&apos;re owed.</p></header>
{data&&data.summary.referrers>0&&<><section className="referrer-summary" aria-label="Referrer summary">{[["Referrers",data.summary.referrers,"people"],["Referrals",data.summary.referrals,"links"],["Completed",data.summary.completed,"done"],["Outstanding",money(data.summary.outstandingMinor),"money"]].map(([label,value,kind])=><article className={kind==="money"?"is-outstanding":""} key={label}><span aria-hidden="true">{kind==="money"?"₦":kind==="done"?"✓":"♙"}</span><small>{label}</small><strong>{value}</strong></article>)}</section><section className="referrer-controls"><div className="referrer-search-sort"><form onSubmit={submit} role="search"><span aria-hidden="true">⌕</span><input aria-label="Search referrers" defaultValue={search} key={search} name="search" placeholder="Search by name or phone"/><button>Search</button></form><label><span>Sort by</span><select aria-label="Sort referrers" onChange={event=>update({sort:event.target.value,page:1})} value={sort}><option value="NEWEST">Newest</option><option value="OLDEST">Oldest</option><option value="NAME_ASC">Name A–Z</option><option value="NAME_DESC">Name Z–A</option><option value="OUTSTANDING_DESC">Highest outstanding</option></select></label></div><nav aria-label="Referrer filters">{[["ALL","All",data.counts.all],["OWED","Owed Money",data.counts.owed],["PAID","Fully Paid",data.counts.paid]].map(([value,label,count])=><button aria-current={filter===value?"page":undefined} key={value} onClick={()=>update({filter:String(value),page:1})}>{label}<span>{count}</span></button>)}</nav></section></>}
{error&&<p className="admin-data-error" role="alert">{error}</p>}{loading&&!data?<div className="admin-directory-loading">Loading referrers…</div>:data?.summary.referrers===0?<section className="referrer-empty"><span aria-hidden="true">♙</span><h2>No referrers yet</h2><p>Registered referrers will appear here.</p></section>:data?.items.length===0?<section className="referrer-empty"><span aria-hidden="true">⌕</span><h2>No matching referrers</h2><p>Try another search or payment filter.</p></section>:data&&<section className="referrer-table-card" aria-busy={loading}><div className="referrer-table-scroll"><table><thead><tr>{["Referrer","Referrals","Completed","Earned","Outstanding","Bank Details","Actions"].map(value=><th key={value}>{value}</th>)}</tr></thead><tbody>{data.items.map(item=><tr key={item.id}><td><div className="referrer-person"><span>{initials(item.fullName)}</span><div><strong>{item.fullName}</strong><small>{item.phone??"—"}</small></div></div></td><td>{item.referrals}</td><td>{item.completed}</td><td>{money(item.earnedMinor)}</td><td><strong>{money(item.outstandingMinor)}</strong></td><td><span className={`referrer-bank referrer-bank--${item.bankStatus.toLowerCase()}`}>{bankLabel[item.bankStatus]}</span></td><td><Link aria-label={`View ${item.fullName}`} href={`/dashboard/referrers/${item.id}`}>⋮</Link></td></tr>)}</tbody></table></div><footer><span>Showing {first}–{last} of {data.total}</span><nav aria-label="Referrer pages"><button disabled={data.page<=1} onClick={()=>update({page:data.page-1})}>‹ Previous</button><span>Page {data.page} of {Math.max(1,data.totalPages)}</span><button disabled={data.page>=data.totalPages} onClick={()=>update({page:data.page+1})}>Next ›</button></nav></footer></section>}</main>;}
export function AdminReferrersDirectory(){return <AdminAppShell><Content/></AdminAppShell>;}