"use client";

import { ArrowLeft, BadgeCheck, Building2, ChevronLeft, ChevronRight, Download, FileText, ImageIcon, UserRound, X } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import type { AdminPropertyReviewDetail, ApiEnvelope } from "@/lib/contracts";
import { formatInitialDeposit, formatPropertyDate, formatPropertyFileSize, formatPropertyMoney, humanizePropertyValue, propertyStatus, rejectionReasonPresets } from "@/lib/admin-property-display";

function Fact({ label, value }: { label: string; value: React.ReactNode }) { return <div><dt>{label}</dt><dd>{value ?? "Not available"}</dd></div>; }

function SectionNavigation() {
  const sections = [["property-top", "All Info"], ["basic-info", "Basic Info"], ["pricing", "Pricing"], ["amenities", "Amenities"], ["photos", "Photos"], ["documents", "Documents"], ["sales-mandate", "Sales Mandate"]] as const;
  return <nav className="property-section-nav" aria-label="Property information sections">{sections.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav>;
}

function Gallery({ review, onClose }: { review: AdminPropertyReviewDetail; onClose: () => void }) {
  const [index, setIndex] = useState(0);
  const images = review.property.images;
  useEffect(() => { const close = (event: KeyboardEvent) => event.key === "Escape" && onClose(); window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [onClose]);
  return <div className="property-dialog-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div role="dialog" aria-modal="true" aria-label={`Gallery for ${review.property.title}`} className="property-gallery-dialog"><button type="button" className="dialog-close" onClick={onClose} aria-label="Close gallery"><X /></button><div className="gallery-stage" style={{ backgroundImage: `url(${images[index]?.url})` }} /><footer><button type="button" disabled={index === 0} onClick={() => setIndex((value) => value - 1)}><ChevronLeft />Previous</button><span>{index + 1} of {images.length}{images[index]?.isCover ? " · Cover" : ""}</span><button type="button" disabled={index >= images.length - 1} onClick={() => setIndex((value) => value + 1)}>Next<ChevronRight /></button></footer></div></div>;
}

function PropertySummary({ review }: { review: AdminPropertyReviewDetail }) {
  const cover = review.property.images.find((image) => image.isCover) ?? review.property.images[0];
  return <div className="review-property-summary"><span style={cover ? { backgroundImage: `url(${cover.url})` } : undefined}><Building2 /></span><div><strong>{review.property.title}</strong><small>{review.summary.referenceId} · {review.seller?.companyName || review.seller?.fullName || "Seller unavailable"}</small><b>{formatPropertyMoney(review.property.askingPrice)}</b></div></div>;
}

function ReviewDialog({ mode, review, pending, error, onClose, onConfirm }: { mode: "approve" | "reject"; review: AdminPropertyReviewDetail; pending: boolean; error: string; onClose: () => void; onConfirm: (reason?: string) => void }) {
  const [preset, setPreset] = useState("");
  const [explanation, setExplanation] = useState("");
  useEffect(() => { const close = (event: KeyboardEvent) => event.key === "Escape" && !pending && onClose(); window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [onClose, pending]);
  const confirm = () => { if (mode === "approve") return onConfirm(); const detail = explanation.trim(); if (detail.length < 3) return; onConfirm(preset && preset !== "Other" ? `${preset}. ${detail}` : detail); };
  return <div className="property-dialog-backdrop" onMouseDown={(event) => event.target === event.currentTarget && !pending && onClose()}><div role="dialog" aria-modal="true" aria-labelledby="review-dialog-title" className={`property-review-dialog ${mode}`}>
    <button type="button" className="dialog-close" disabled={pending} onClick={onClose} aria-label="Close review dialog"><X /></button><span className="decision-icon" aria-hidden>{mode === "approve" ? "✓" : "!"}</span>
    <h2 id="review-dialog-title">{mode === "approve" ? "Approve this property?" : "Give reason for rejection"}</h2><p>{mode === "approve" ? "It goes live on the Marketplace after server confirmation and buyers can start registering interest." : "Your feedback is sent to the Seller so they can correct the listing and resubmit for review."}</p><PropertySummary review={review} />
    {mode === "reject" ? <><fieldset className="rejection-presets"><legend>Reason for rejection</legend><small>You can select a helper reason and add specific feedback.</small><div>{rejectionReasonPresets.map((reason) => <button type="button" aria-pressed={preset === reason} key={reason} onClick={() => setPreset(reason)}>+ {reason}</button>)}</div></fieldset><label className="rejection-explanation">Explain clearly what the seller needs to change<span aria-hidden>*</span><textarea value={explanation} maxLength={1000} onChange={(event) => setExplanation(event.target.value)} placeholder="The seller sees this message word for word. Be specific and constructive." /></label><label className="resubmit-policy"><input type="checkbox" checked disabled readOnly /><span>Allow seller resubmit for review<small>Seller correction and resubmission is currently supported and cannot be disabled.</small></span></label></> : null}
    {error ? <div className="alert alert-error" role="alert">{error}</div> : null}<footer><button type="button" disabled={pending} onClick={onClose}>Cancel</button><button type="button" className={mode === "approve" ? "confirm-approve" : "confirm-reject"} disabled={pending || (mode === "reject" && explanation.trim().length < 3)} onClick={confirm}>{pending ? (mode === "approve" ? "Approving…" : "Rejecting…") : (mode === "approve" ? "Confirm Approval" : "Confirm Rejection")}</button></footer>
  </div></div>;
}

export function AdminPropertyDetailScreen({ propertyId, backHref }: { propertyId: string; backHref: string }) {
  const router = useRouter();
  const [review, setReview] = useState<AdminPropertyReviewDetail | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [openingDocument, setOpeningDocument] = useState<string | null>(null);
  const [galleryOpen, setGalleryOpen] = useState(false);
  const [decision, setDecision] = useState<"approve" | "reject" | null>(null);
  const [decisionError, setDecisionError] = useState("");
  const [decisionPending, setDecisionPending] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch(`/api/admin/marketplace/properties/${encodeURIComponent(propertyId)}`, { cache: "no-store" }); const payload = await response.json() as ApiEnvelope<{ review: AdminPropertyReviewDetail }>; if (!response.ok || !payload.data?.review) throw new Error(payload.message || "Property could not be loaded."); setReview(payload.data.review); } catch (reason) { setError(reason instanceof Error ? reason.message : "Property could not be loaded."); } finally { setLoading(false); } }, [propertyId]);
  useEffect(() => { const task = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(task); }, [load]);
  const accessDocument = async (documentId: string, displayName: string, mode: "view" | "download") => { if (openingDocument) return; setOpeningDocument(`${documentId}:${mode}`); setError(""); try { const response = await fetch(`/api/admin/marketplace/properties/${encodeURIComponent(propertyId)}/documents/${encodeURIComponent(documentId)}/access`, { cache: "no-store" }); const payload = await response.json() as ApiEnvelope<{ access: { url: string } }>; if (!response.ok || !payload.data?.access?.url) throw new Error(payload.message || "Document access could not be created."); if (mode === "view") window.open(payload.data.access.url, "_blank", "noopener,noreferrer"); else { const link = document.createElement("a"); link.href = payload.data.access.url; link.download = displayName; link.target = "_blank"; link.rel = "noopener noreferrer"; link.click(); } } catch (reason) { setError(reason instanceof Error ? reason.message : "Document access could not be created."); } finally { setOpeningDocument(null); } };
  const submitDecision = async (reason?: string) => { if (!decision || decisionPending) return; setDecisionPending(true); setDecisionError(""); try { const response = await fetch(`/api/admin/marketplace/properties/${encodeURIComponent(propertyId)}/${decision === "approve" ? "approve" : "reject"}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(decision === "approve" ? {} : { reason }) }); const payload = await response.json() as ApiEnvelope<Record<string, unknown>>; if (!response.ok) throw new Error(payload.message || `Property could not be ${decision === "approve" ? "approved" : "rejected"}.`); setDecision(null); await load(); router.refresh(); } catch (reasonValue) { setDecisionError(reasonValue instanceof Error ? reasonValue.message : "The review decision could not be saved."); } finally { setDecisionPending(false); } };

  const backLabel = backHref.startsWith("/dashboard/leads/") ? "Back to lead" : "Back to properties";
  if (loading) return <section className="admin-property-detail"><div className="detail-heading skeleton" /><div className="property-detail-layout"><div className="property-detail-main"><div className="detail-panel skeleton-card" /><div className="detail-panel skeleton-card" /><div className="detail-panel skeleton-card" /></div><div className="property-detail-side"><div className="detail-panel skeleton-card" /><div className="detail-panel skeleton-card" /></div></div></section>;
  if (error && !review) return <section className="admin-property-detail"><Link href={backHref as never} className="back-link"><ArrowLeft size={16} />{backLabel}</Link><div className="lead-state alert alert-error" role="alert"><span>{error}</span><button type="button" onClick={() => void load()}>Try again</button></div></section>;
  if (!review) return null;
  const { property, summary, seller, mandate } = review; const mappedStatus = propertyStatus[summary.status];
  const commission = mandate && (mandate.commissionPercentage != null || mandate.commissionAmount != null) ? [mandate.commissionPercentage != null ? `${mandate.commissionPercentage}%` : null, mandate.commissionAmount != null ? formatPropertyMoney(mandate.commissionAmount) : null].filter(Boolean).join(" · ") : null;
  const residentialFacts = [["Bedrooms", property.bedrooms], ["Bathrooms", property.bathrooms], ["Toilets", property.toilets], ["Parking", property.parkingSpaces]] as const; const commercialFacts = [["Floors", property.numberOfFloors], ["Parking capacity", property.parkingCapacity]] as const;
  const decisions = review.history.filter((item) => item.action === "APPROVED" || item.action === "REJECTED");
  const latestDecision = decisions[0] ?? null;
  const rejectionAttempts = decisions.filter((item) => item.action === "REJECTED");
  const publicWebUrl = process.env.NEXT_PUBLIC_PUBLIC_WEB_URL?.replace(/\/$/, "");
  return <article className="admin-property-detail" id="property-top"><Link href={backHref as never} className="back-link"><ArrowLeft size={16} />{backLabel}</Link>
    <header className="property-detail-header"><div><div className="property-title-line"><h1>{property.title}</h1><span className={`property-status status-${mappedStatus.tone}`}>{mappedStatus.label}</span>{summary.status === "REJECTED" && rejectionAttempts.length > 1 ? <span className="property-attempt-badge">{rejectionAttempts.length} attempts</span> : null}</div><p><span>ID {summary.referenceId}</span><span>{seller?.companyName || seller?.fullName || "Seller unavailable"}</span><span>{summary.status === "LIVE" ? `Published ${formatPropertyDate(summary.publishedAt)}` : summary.status === "REJECTED" ? `Reviewed ${formatPropertyDate(summary.rejectedAt)}` : `Submitted ${formatPropertyDate(summary.submittedAt)}`}</span></p></div></header><SectionNavigation />{error ? <div className="alert alert-error" role="alert">{error}</div> : null}
    <div className="property-detail-layout"><div className="property-detail-main">
      <section className="detail-panel" id="basic-info"><h2>Basic Information</h2><dl className="basic-info-grid"><Fact label="Category" value={humanizePropertyValue(property.propertyCategory)} /><Fact label="Type" value={humanizePropertyValue(property.propertyType)} /><Fact label="Ownership" value={humanizePropertyValue(property.ownershipType)} /><Fact label="Condition" value={`${humanizePropertyValue(property.condition)}${property.furnishing ? ` · ${humanizePropertyValue(property.furnishing)}` : ""}`} /></dl></section>
      <section className="detail-panel" id="photos"><div className="panel-heading"><h2>Photos <small>{summary.photoCount}</small></h2>{property.images.length ? <button type="button" onClick={() => setGalleryOpen(true)}>Open Gallery</button> : null}</div>{property.images.length ? <div className="property-thumbnails approved-gallery">{property.images.map((image) => <button type="button" key={image.id} onClick={() => setGalleryOpen(true)} aria-label={`Open photo ${image.order + 1}`} style={{ backgroundImage: `url(${image.url})` }}>{image.isCover ? <span>Cover</span> : null}</button>)}</div> : <div className="property-cover property-cover-empty"><ImageIcon /><span>No property images</span></div>}</section>
      <section className="detail-panel" id="documents"><div className="panel-heading"><h2>Documents <small>{review.documents.length}</small></h2></div>{review.documents.length ? <div className="property-documents">{review.documents.map((item) => <div key={item.id}><FileText /><div><strong>{item.displayName}</strong><span>{formatPropertyFileSize(item.sizeBytes)}</span></div><div className="document-actions"><button type="button" disabled={Boolean(openingDocument)} onClick={() => void accessDocument(item.id, item.displayName, "view")}>{openingDocument === `${item.id}:view` ? "Opening…" : "View"}</button><button type="button" disabled={Boolean(openingDocument)} onClick={() => void accessDocument(item.id, item.displayName, "download")}>{openingDocument === `${item.id}:download` ? "Preparing…" : "Download"}<Download size={13} /></button></div></div>)}</div> : <p className="detail-empty">No supporting documents were uploaded.</p>}</section>
      <section className="detail-panel" id="pricing"><h2>Pricing</h2><dl className="basic-info-grid"><Fact label="Asking Price" value={formatPropertyMoney(property.askingPrice)} /><Fact label="Initial deposit" value={formatInitialDeposit(property.initialDepositType, property.initialDepositValue)} /><Fact label="Negotiable?" value={property.negotiable ? "Yes" : "No"} /></dl></section>
      <section className="detail-panel"><h2>Property Details</h2><dl className="property-detail-chips">{(property.propertyCategory?.toUpperCase() === "COMMERCIAL" ? commercialFacts : residentialFacts).filter(([, value]) => value != null && value > 0).map(([label, value]) => <Fact key={label} label={label} value={value} />)}</dl></section>
      <section className="detail-panel"><h2>Description</h2><p className="property-description">{property.description || "No description supplied."}</p></section>
      <section className="detail-panel"><h2>Location</h2><dl className="location-facts"><Fact label="Public Location" value={property.publicLocation} /><Fact label="Full Address" value={property.fullAddress} /></dl></section>
      <section className="detail-panel" id="amenities"><h2>Utilities &amp; Amenities <small>{property.amenities.length}</small></h2>{property.amenities.length ? <div className="property-amenities"><div>{property.amenities.map((amenity) => <span key={amenity}>✓ {amenity}</span>)}</div></div> : <p className="detail-empty">No amenities supplied.</p>}</section>
      <section className="detail-panel" id="sales-mandate"><h2>Sales Mandate</h2>{mandate ? <dl className="basic-info-grid"><Fact label="Mandate" value={humanizePropertyValue(mandate.mandateType)} />{commission ? <Fact label="Commission" value={commission} /> : null}<Fact label="Seller" value={mandate.sellerFullName} /><Fact label="Ownership" value={mandate.ownershipConfirmed ? "Confirmed" : "Not confirmed"} /><Fact label="Accepted" value={mandate.mandateAccepted ? formatPropertyDate(mandate.acceptedAt) : "Not accepted"} />{mandate.agreementVersion ? <Fact label="Agreement version" value={mandate.agreementVersion} /> : null}</dl> : <p className="detail-empty">No Marketplace mandate is available.</p>}</section>
      {review.history.length ? <section className="detail-panel property-history"><h2>Review history</h2>{review.history.map((item) => <div key={item.id}><strong>{humanizePropertyValue(item.action)}</strong><span>{humanizePropertyValue(item.previousStatus)} → {humanizePropertyValue(item.newStatus)}</span><time dateTime={item.createdAt}>{formatPropertyDate(item.createdAt)}</time>{item.reason ? <p>{item.reason}</p> : null}</div>)}</section> : null}
    </div><aside className="property-detail-side">{summary.status === "IN_REVIEW" ? <><section className="detail-panel approval-panel"><h2>Approve or Reject this property listing</h2><p>Approving this property makes it visible on the Marketplace for buyers immediately.</p><button type="button" className="approve-property" onClick={() => { setDecisionError(""); setDecision("approve"); }}>Approve Property ✓</button><button type="button" className="reject-property" onClick={() => { setDecisionError(""); setDecision("reject"); }}>Reject with reason</button></section><section className="detail-panel seller-card"><h2>Seller</h2>{seller ? <><div className="seller-card-heading"><span><UserRound /></span><div><strong>{seller.companyName || seller.fullName || "Name unavailable"}</strong>{seller.companyName && seller.fullName ? <small>{seller.fullName}</small> : null}{seller.emailVerified ? <small><BadgeCheck size={13} />Verified email</small> : null}</div></div><p>{seller.email || "Email unavailable"}</p><p>{seller.phone || "Phone unavailable"}</p><Link href={`/dashboard/users/${seller.id}` as never}>View Customer</Link></> : <p className="detail-empty">Seller information is unavailable.</p>}</section></> : null}
      {summary.status === "LIVE" ? <section className="detail-panel marketplace-live-panel"><h2>Live on the marketplace</h2><p>Approved by <strong>{latestDecision?.reviewedByAdminName || "Beryl Shelter Admin"}</strong></p><time dateTime={summary.publishedAt || summary.reviewedAt || undefined}>{formatPropertyDate(summary.publishedAt || summary.reviewedAt)}</time>{publicWebUrl ? <a href={`${publicWebUrl}/marketplace/${encodeURIComponent(property.id)}`} target="_blank" rel="noreferrer">View on the marketplace</a> : null}</section> : null}
      {summary.status === "REJECTED" ? <><section className="detail-panel awaiting-seller-panel"><h2>Awaiting Seller</h2><p>The seller can fix and resubmit. It returns to Pending Review automatically.</p></section><section className="detail-panel rejected-state-panel"><h2>Rejected by {latestDecision?.reviewedByAdminName || "Beryl Shelter Admin"}</h2><p>{review.rejectionFeedback || latestDecision?.reason || "The Seller must correct this listing before resubmitting."}</p><time dateTime={summary.rejectedAt || summary.reviewedAt || undefined}>{formatPropertyDate(summary.rejectedAt || summary.reviewedAt)}</time></section>{rejectionAttempts.length > 1 ? <section className="detail-panel earlier-attempts"><h2>Earlier Attempts</h2>{rejectionAttempts.slice(1).map((item, index) => <div key={item.id}><strong>Attempt {rejectionAttempts.length - index - 1}</strong><span>{item.reviewedByAdminName || "Beryl Shelter Admin"}</span><time dateTime={item.createdAt}>{formatPropertyDate(item.createdAt)}</time>{item.reason ? <p>{item.reason}</p> : null}</div>)}</section> : null}</> : null}
    </aside></div>{galleryOpen ? <Gallery review={review} onClose={() => setGalleryOpen(false)} /> : null}{decision ? <ReviewDialog mode={decision} review={review} pending={decisionPending} error={decisionError} onClose={() => { if (!decisionPending) setDecision(null); }} onConfirm={(reason) => void submitDecision(reason)} /> : null}
  </article>;
}
