"use client";

import Link from "next/link";
import Image from "next/image";
import { useEffect,useRef,useState,type ReactNode } from "react";

import { adminMandateSignatureUrl,adminPropertyDocumentUrl,approveAdminProperty,getAdminProperty,rejectAdminProperty,type PropertyDetail,type PropertyStatus } from "../lib/admin-properties-api";
import { AdminAppShell } from "./admin-app-shell";

const labels:Record<PropertyStatus,string>={UNLISTED:"Unlisted",PENDING:"Pending Review",LISTED:"Approved",REJECTED:"Rejected"};
const webOrigin=(process.env.NEXT_PUBLIC_WEB_APP_URL??"http://localhost:3000").replace(/\/$/,"");
function date(value:string|null,time=false){if(!value)return "—";return new Intl.DateTimeFormat("en-GB",time?{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}:{day:"2-digit",month:"short",year:"numeric"}).format(new Date(value));}
function money(value:number){return new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(value/100);}
function size(value:number){return value>=1048576?`${(value/1048576).toFixed(1)} MB`:`${Math.max(1,Math.round(value/1024))} KB`;}
function Field({label,value}:{label:string;value:ReactNode}){return <div><dt>{label}</dt><dd>{value??"—"}</dd></div>;}
async function privateFile(url:string,filename:string,view=false){const popup=view?window.open("about:blank","_blank"):null;if(popup)popup.opener=null;try{const response=await fetch(url,{credentials:"include"});if(!response.ok)throw new Error("Private file unavailable");const objectUrl=URL.createObjectURL(await response.blob());if(view&&popup)popup.location.href=objectUrl;else{const link=document.createElement("a");link.href=objectUrl;link.download=filename;link.click();}window.setTimeout(()=>URL.revokeObjectURL(objectUrl),60000);}catch{popup?.close();}}

function Modal({title,children,close}:{title:string;children:ReactNode;close:()=>void}){const dialog=useRef<HTMLDivElement>(null),closeButton=useRef<HTMLButtonElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow="hidden";closeButton.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape")close();if(event.key==="Tab"&&dialog.current){const controls=[...dialog.current.querySelectorAll<HTMLElement>('button:not(:disabled),textarea:not(:disabled),a[href]')];if(!controls.length)return;const first=controls[0]!,last=controls.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);document.body.style.overflow=overflow;previous?.focus();};},[close]);return <div className="property-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)close();}} role="presentation"><div aria-labelledby="property-modal-title" aria-modal="true" className="property-modal" ref={dialog} role="dialog"><button aria-label="Close dialog" className="property-modal-close" onClick={close} ref={closeButton}>×</button><h2 id="property-modal-title">{title}</h2>{children}</div></div>;}

function ReviewPanel({property,onChange}:{property:PropertyDetail;onChange:(value:PropertyDetail)=>void}){const [dialog,setDialog]=useState<"approve"|"reject"|null>(null),[reason,setReason]=useState(""),[pending,setPending]=useState(false),[error,setError]=useState("");const latestApproval=property.reviews.find(review=>review.action==="APPROVED"),latestRejection=property.reviews.find(review=>review.action==="REJECTED");async function approve(){setPending(true);setError("");try{onChange(await approveAdminProperty(property.code,property.version));setDialog(null);}catch(value){setError(value instanceof Error?value.message:"Approval failed.");}finally{setPending(false);}}async function reject(){if(!reason.trim())return;setPending(true);setError("");try{onChange(await rejectAdminProperty(property.code,property.version,reason.trim()));setDialog(null);setReason("");}catch(value){setError(value instanceof Error?value.message:"Rejection failed.");}finally{setPending(false);}}
  if(property.status==="PENDING")return <><aside className="property-review-panel"><h2>Approve or Reject this property listing</h2><p>Approving this property makes it visible on the marketplace immediately.</p><button className="property-approve" onClick={()=>setDialog("approve")}>Approve Property ✓</button><button className="property-reject" onClick={()=>setDialog("reject")}>Reject with reason</button>{error&&<p className="admin-data-error" role="alert">{error}</p>}</aside>{dialog==="approve"&&<Modal close={()=>setDialog(null)} title="Approve this property?"><div className="property-modal-symbol approve">✓</div><p>It goes live on the marketplace straight away and buyers can register interest.</p><div className="property-modal-actions"><button onClick={()=>setDialog(null)}>Cancel</button><button className="property-approve" disabled={pending} onClick={()=>void approve()}>{pending?"Approving…":"Confirm Approval ✓"}</button></div></Modal>}{dialog==="reject"&&<Modal close={()=>setDialog(null)} title="Give reason for rejection"><div className="property-modal-symbol reject">!</div><p>It will be sent to the seller so they can fix the listing and resubmit for review.</p><label className="property-reason-field">Explain clearly what the seller needs to change*<textarea autoFocus maxLength={2000} onChange={event=>setReason(event.target.value)} placeholder="The seller sees this message word for word. Be specific and constructive" rows={6} value={reason}/></label><p className="property-resubmit-note"><strong>Seller resubmission is enabled</strong><span>V2 allows every rejected listing to be corrected and returned to Pending Review.</span></p><div className="property-modal-actions"><button onClick={()=>setDialog(null)}>Cancel</button><button className="property-reject-solid" disabled={pending||!reason.trim()} onClick={()=>void reject()}>{pending?"Rejecting…":"Confirm Rejection ✓"}</button></div></Modal>}</>;
  if(property.status==="LISTED")return <aside className="property-live-panel"><h2>◉ Live on the marketplace</h2>{latestApproval?<p>Approved by <strong>{latestApproval.reviewer.name}</strong><small>{date(latestApproval.reviewedAt,true)}</small></p>:<p>Approval attribution is unavailable for this legacy listing.</p>}<a href={`${webOrigin}/buy/${encodeURIComponent(property.code)}`} rel="noreferrer" target="_blank">View on the marketplace</a></aside>;
  if(property.status==="REJECTED")return <div className="property-rejected-panels"><aside><h2>⌛ Awaiting Seller</h2><p>The seller can fix and resubmit. It returns to Pending Review automatically.</p></aside><aside><h2>● Rejected{latestRejection?<> by {latestRejection.reviewer.name}</>:null}</h2><p>{property.rejectionReason??latestRejection?.reason??"No rejection reason is available for this legacy listing."}</p><small>{date(property.rejectedAt??latestRejection?.reviewedAt??null,true)}</small></aside>{property.reviews.filter(review=>review.action==="REJECTED").length>0&&<aside><h2>Rejection History</h2>{property.reviews.filter(review=>review.action==="REJECTED").map((review,index)=><div className="property-attempt" key={review.id}><strong>Attempt {property.reviews.filter(value=>value.action==="REJECTED").length-index} · {date(review.reviewedAt)} · {review.reviewer.name}</strong><span>{review.reason}</span></div>)}</aside>}</div>;
  return <aside className="property-review-panel"><h2>Unlisted</h2><p>This owner-controlled listing is not in the moderation queue or public marketplace.</p></aside>;
}

function PropertyContent({code}:{code:string}){const [property,setProperty]=useState<PropertyDetail|null>(null),[error,setError]=useState(""),[gallery,setGallery]=useState(false);useEffect(()=>{const controller=new AbortController();getAdminProperty(code,controller.signal).then(setProperty).catch(reason=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:"Property could not be loaded.");});return()=>controller.abort();},[code]);if(error)return <main className="admin-property-detail"><Link className="admin-back-link" href="/dashboard/properties">‹ Back to properties</Link><p className="admin-data-error" role="alert">{error}</p></main>;if(!property)return <main className="admin-directory-loading" role="status">Loading property…</main>;const minimumPercent=property.priceMinor?Math.round(property.minimumDownPaymentMinor/property.priceMinor*100):0;return <main className="admin-property-detail">
  <Link className="admin-back-link" href="/dashboard/properties">‹ Back to properties</Link>
  <header className="property-detail-heading"><div><h1>{property.title}</h1><span className={`property-status property-status--${property.status.toLowerCase()}`}>{labels[property.status]}</span>{property.status==="REJECTED"&&property.reviews.filter(review=>review.action==="REJECTED").length>0&&<span className="property-attempt-count">{property.reviews.filter(review=>review.action==="REJECTED").length} attempts</span>}</div><p><span>ID {property.code}</span><span>{property.seller.name}</span><span>Submitted {date(property.submittedAt,true)}</span></p></header>
  <div className="property-detail-layout"><div className="property-detail-main"><nav className="property-section-nav" aria-label="Property sections">{[["all-info","All Info"],["basic-info","Basic Info"],["pricing","Pricing"],["amenities","Amenities"],["photos","Photos"],["documents","Documents"],["sales-mandate","Sales Mandate"]].map(([id,label])=><a href={`#${id}`} key={id}>{label}</a>)}</nav>
  <section className="property-detail-card" id="basic-info"><h2>Basic Information</h2><dl className="property-field-grid"><Field label="Category" value={property.propertyType}/><Field label="Type" value={property.propertySubtype}/><Field label="Ownership" value={property.ownershipType}/><Field label="Occupancy" value={property.occupancyType}/><Field label="Lien" value={property.hasLien?"Lien recorded":"No lien recorded"}/><Field label="Year Built" value={property.yearBuilt??"—"}/></dl></section>
  <section className="property-detail-card" id="photos"><header><h2>Photos <small>{property.images.length}</small></h2>{property.images.length>0&&<button onClick={()=>setGallery(true)}>Open Gallery</button>}</header>{property.images.length?<div className="property-photo-strip">{property.images.slice(0,5).map((image,index)=><figure key={image.id}><Image alt={`${property.title}, image ${index+1}`} height={640} src={image.url} unoptimized width={800}/>{index===0&&<figcaption>Cover</figcaption>}</figure>)}</div>:<p className="property-detail-empty">No property photos uploaded.</p>}</section>
  <section className="property-detail-card" id="documents"><h2>Documents <small>{property.documents.length}</small></h2>{property.documents.length?<ul className="property-documents">{property.documents.map(document=><li key={document.id}><span aria-hidden="true">PDF</span><span><strong>{document.title}</strong><small>{document.documentType} · {size(document.sizeBytes)}</small></span><button onClick={()=>void privateFile(adminPropertyDocumentUrl(property.code,document.id),document.title,true)}>View</button><button onClick={()=>void privateFile(adminPropertyDocumentUrl(property.code,document.id),document.title)}>Download ↓</button></li>)}</ul>:<p className="property-detail-empty">No property documents uploaded.</p>}</section>
  <section className="property-detail-card" id="pricing"><h2>Pricing</h2><dl className="property-field-grid three"><Field label="Asking Price" value={money(property.priceMinor)}/><Field label="Minimum Down Payment" value={`${money(property.minimumDownPaymentMinor)} · ${minimumPercent}%`}/><Field label="Online Purchase" value="Not available — transactions are completed offline"/></dl></section>
  <section className="property-detail-card"><h2>Property Details</h2><div className="property-fact-list"><span>{property.bedrooms} Bedrooms</span><span>{property.bathrooms} Bathrooms</span>{property.toilets!==null&&<span>{property.toilets} Toilets</span>}<span>{property.parkingSpaces} Parking</span>{property.units!==null&&<span>{property.units} Units</span>}{property.landArea!==null&&<span>{property.landArea.toLocaleString()} Land Area</span>}</div></section>
  <section className="property-detail-card"><h2>Description</h2><p>{property.description}</p>{property.additionalInformation&&<><h3>Additional Information</h3><p>{property.additionalInformation}</p></>}</section>
  <section className="property-detail-card"><h2>Location</h2><dl className="property-location"><Field label="Public Location" value={[property.city,property.state].join(", ")}/><Field label="Full Address" value={property.location}/></dl></section>
  <section className="property-detail-card" id="amenities"><h2>Utilities & Amenities <small>{property.facilities.length}</small></h2>{property.facilities.length?<div className="property-fact-list">{property.facilities.map(value=><span key={value}>{value}</span>)}</div>:<p className="property-detail-empty">No amenities recorded.</p>}</section>
  <section className="property-detail-card" id="sales-mandate"><h2>Sales Mandate</h2>{property.mandate?<><dl className="property-field-grid three"><Field label="Mandate" value={property.mandate.type}/><Field label="Commission" value={`${property.mandate.commissionPercent}% · ${money(Math.round(property.priceMinor*property.mandate.commissionPercent/100))}`}/><Field label="Signed" value={`${property.mandate.signerName} · ${date(property.mandate.signedAt,true)}`}/></dl><div className="property-mandate-links">{property.mandate.hasSignature&&<button onClick={()=>void privateFile(adminMandateSignatureUrl(property.code),"mandate-signature.png")}>Download signature</button>}{property.mandate.documents.map(document=><button key={document.id} onClick={()=>void privateFile(adminPropertyDocumentUrl(property.code,document.id,true),document.title,true)}>{document.title}</button>)}</div></>:<p className="property-detail-empty">No sales mandate recorded.</p>}</section>
  </div><div className="property-detail-aside"><ReviewPanel onChange={setProperty} property={property}/><aside className="property-seller-card"><h2>Seller</h2><strong>{property.seller.name}</strong><span>{property.seller.email}</span><span>{property.seller.phone??"—"}</span><Link href={`/dashboard/users/${property.seller.id}`}>View Customer</Link></aside></div></div>
  {gallery&&<Modal close={()=>setGallery(false)} title={`${property.title} photos`}><div className="property-gallery-grid">{property.images.map((image,index)=><Image alt={`${property.title}, image ${index+1}`} height={640} key={image.id} src={image.url} unoptimized width={800}/>)}</div></Modal>}
  </main>;}
export function AdminPropertyDetail({code}:{code:string}){return <AdminAppShell><PropertyContent code={code}/></AdminAppShell>;}
