"use client";
/* eslint-disable react-hooks/incompatible-library */
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { errorMessage, postApi } from "@/lib/client-api";
import { AuthLayout } from "./auth-layout";
import { PasswordField } from "./form-controls";
import { PasswordStrength, passwordChecks } from "./password-strength";
const password = z.string().min(8, "Use at least 8 characters").refine((value) => passwordChecks(value).every(([, pass]) => pass), "Use every password requirement"); const schema = z.object({ currentPassword: z.string().min(1, "Enter your current password"), newPassword: password, confirmPassword: z.string() }).refine((value) => value.newPassword === value.confirmPassword, { path: ["confirmPassword"], message: "Passwords do not match" }); type Values = z.infer<typeof schema>;
export function ChangeInitialPasswordScreen() { const router = useRouter(); const [apiError, setApiError] = useState(""); const [success, setSuccess] = useState(false); const { register, handleSubmit, watch, formState: { errors, isSubmitting } } = useForm<Values>({ resolver: zodResolver(schema), mode: "onChange" }); const newPassword = watch("newPassword", ""); const submit = async (values: Values) => { setApiError(""); try { await postApi("/api/admin/complete-first-password-change", values); setSuccess(true); window.setTimeout(() => router.replace("/login" as never), 1100); } catch (error) { setApiError(errorMessage(error, "Unable to change your password.")); } }; return <AuthLayout title="Set a new password"><h1 className="page-title">Set a new password</h1><p className="page-copy">Choose a new password for your account. Make it one you&apos;ll remember.</p><form className="form-stack" onSubmit={handleSubmit(submit)} noValidate><PasswordField label="Temporary password" autoComplete="current-password" error={errors.currentPassword?.message} {...register("currentPassword")} /><PasswordField label="New password" autoComplete="new-password" error={errors.newPassword?.message} {...register("newPassword")} /><PasswordStrength password={newPassword} /><PasswordField label="Confirm new password" autoComplete="new-password" error={errors.confirmPassword?.message} {...register("confirmPassword")} />{apiError ? <p className="alert alert-error" role="alert" aria-live="polite">{apiError}</p> : null}{success ? <p className="alert alert-success" aria-live="polite">Password changed successfully. Please log in again.</p> : null}<button className="button button-primary" type="submit" disabled={isSubmitting || success}>{isSubmitting ? "Saving…" : "Save new password"}</button></form></AuthLayout>; }
