"use client";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useRef, useState } from "react";
import { errorMessage, postApi } from "@/lib/client-api";
import type { LoginChallenge } from "@/lib/contracts";
import { AuthLayout } from "./auth-layout";
import { OtpInput } from "./otp-input";
import { trackAdminEvent } from "@/lib/analytics/admin";
type ChallengeState = Pick<LoginChallenge, "challengeId" | "maskedEmail" | "resendAvailableIn">;
const readChallenge = (): ChallengeState | null => { try { return JSON.parse(sessionStorage.getItem("beryl_admin_login_challenge") ?? "") as ChallengeState; } catch { return null; } };
export function VerifyOtpScreen() {
  const router = useRouter();
  const [challenge] = useState<ChallengeState | null>(() => typeof window === "undefined" ? null : readChallenge());
  const [remaining, setRemaining] = useState(() => typeof window === "undefined" ? 0 : readChallenge()?.resendAvailableIn ?? 0);
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [resetKey, setResetKey] = useState(0); const [resendCount, setResendCount] = useState(0); const attempts = useRef(0); const viewed = useRef(false);
  useEffect(() => { if (!challenge) router.replace("/login" as never); else if (!viewed.current) { viewed.current = true; void trackAdminEvent("Verification Screen Viewed", { otp_context: "login" }); } }, [challenge, router]);
  useEffect(() => { if (!remaining) return; const timer = window.setTimeout(() => setRemaining((value) => Math.max(0, value - 1)), 1000); return () => window.clearTimeout(timer); }, [remaining]);
  const formatted = useMemo(() => `${Math.floor(remaining / 60)}:${String(remaining % 60).padStart(2, "0")}`, [remaining]);
  const verify = async (otp: string) => { if (!challenge || busy) return; setBusy(true); setMessage(""); try { const response = await postApi<{ nextAction: string }>("/api/admin/verify-login-otp", { challengeId: challenge.challengeId, otp }); sessionStorage.removeItem("beryl_admin_login_challenge"); router.replace((response.data?.nextAction === "CHANGE_INITIAL_ADMIN_PASSWORD" ? "/change-initial-password" : "/dashboard") as never); } catch (error) { const code = (error as { code?: string }).code; attempts.current += 1; if (code === "INVALID_OTP" || code === "OTP_EXPIRED") void trackAdminEvent("OTP Verification Failed", { otp_context: "login", attempt_number: attempts.current, failure_reason: code === "OTP_EXPIRED" ? "expired" : "invalid" }); const copy: Record<string, string> = { INVALID_OTP: "That code is not correct. Please try again.", OTP_EXPIRED: "This code has expired. Request a new one.", OTP_ATTEMPTS_EXCEEDED: "Too many attempts. Request a new code.", OTP_NO_LONGER_VALID: "This code is no longer valid. Request a new code.", ADMIN_LOGIN_CHALLENGE_INVALID: "Your login challenge is no longer valid. Sign in again." }; setMessage(copy[code ?? ""] ?? errorMessage(error, "Unable to verify this code.")); setResetKey((value) => value + 1); } finally { setBusy(false); } };
  const resend = async () => { if (!challenge || remaining || busy) return; setBusy(true); setMessage(""); try { const response = await postApi<{ resendAvailableIn: number }>("/api/admin/resend-login-otp", { challengeId: challenge.challengeId }); const next = response.data?.resendAvailableIn ?? 60; const nextCount = resendCount + 1; void trackAdminEvent("OTP Resend Requested", { otp_context: "login", resend_count: nextCount }); setResendCount(nextCount); setRemaining(next); sessionStorage.setItem("beryl_admin_login_challenge", JSON.stringify({ ...challenge, resendAvailableIn: next })); setMessage("A new verification code has been sent."); setResetKey((value) => value + 1); } catch (error) { setMessage(errorMessage(error, "Unable to resend a code.")); } finally { setBusy(false); } };
  return <AuthLayout title="Admin verification"><h1 className="page-title">Check your email for OTP</h1><p className="page-copy">We sent a 6-digit code to <strong>{challenge?.maskedEmail ?? "your email"}</strong>. Enter it below to confirm it&apos;s you.</p><label className="field-label">Enter OTP here</label><OtpInput key={resetKey} onComplete={verify} disabled={busy} /><div aria-live="polite" style={{ minHeight: 44, marginTop: 16 }}>{message ? <p className={message.startsWith("A new") ? "alert alert-success" : "alert alert-error"} role="alert">{message}</p> : null}</div><button className="button button-primary" style={{ width: "100%", marginTop: 12 }} type="button" disabled={busy || remaining > 0} onClick={resend}>{remaining ? `Resend code in ${formatted}` : "Resend code"}</button><button className="icon-btn otp-change-account" type="button" onClick={() => { sessionStorage.removeItem("beryl_admin_login_challenge"); router.push("/login" as never); }}>Wrong email? <strong>Change it</strong></button></AuthLayout>;
}
