import { Request,Response,NextFunction } from "express"; import { getAuthUserId } from "../../utils/getAuthUserId"; import * as service from "./marketplace.service"; import { draftListSchema } from "./marketplace.validators";
export const createDraft=async(req:Request,res:Response,next:NextFunction)=>{try{res.status(201).json({success:true,message:"Property draft created successfully",data:{property:await service.createDraft(getAuthUserId(req),req.body)}})}catch(e){next(e)}};
export const updateDraft=async(req:Request,res:Response,next:NextFunction)=>{try{res.json({success:true,message:"Property draft saved successfully",data:{property:await service.updateDraft(req.params.propertyId,getAuthUserId(req),req.body)}})}catch(e){next(e)}};
export const getDraft=async(req:Request,res:Response,next:NextFunction)=>{try{res.json({success:true,message:"Property draft fetched successfully",data:{property:await service.getDraft(req.params.propertyId,getAuthUserId(req))}})}catch(e){next(e)}};
export const listDrafts=async(req:Request,res:Response,next:NextFunction)=>{try{const query=draftListSchema.parse(req.query);res.json({success:true,message:"Property drafts fetched successfully",data:await service.listDrafts(getAuthUserId(req),query)})}catch(e){next(e)}};
export const uploadImages=async(req:Request,res:Response,next:NextFunction)=>{try{res.status(201).json({success:true,message:"Property images uploaded successfully",data:{images:await service.uploadDraftImages(req.params.propertyId,getAuthUserId(req),req.files as Express.Multer.File[])}})}catch(e){next(e)}};
export const deleteImage=async(req:Request,res:Response,next:NextFunction)=>{try{await service.deleteDraftImage(req.params.propertyId,req.params.imageId,getAuthUserId(req));res.json({success:true,message:"Property image deleted successfully"})}catch(e){next(e)}};
export const reorderImages=async(req:Request,res:Response,next:NextFunction)=>{try{res.json({success:true,message:"Property images reordered successfully",data:{images:await service.reorderDraftImages(req.params.propertyId,req.body.imageIds,getAuthUserId(req))}})}catch(e){next(e)}};
export const setCover=async(req:Request,res:Response,next:NextFunction)=>{try{res.json({success:true,message:"Property cover image updated successfully",data:{images:await service.setDraftCover(req.params.propertyId,req.params.imageId,getAuthUserId(req))}})}catch(e){next(e)}};
