import { supabaseAdmin } from "../../config/supabase"; import { AppError } from "../../utils/AppError"; import { uploadImageWithPublicId,deleteImageFromCloudinary,uploadPropertyDocument,deletePropertyDocument } from "../../utils/cloudinary"; import { PublicMarketplaceSearchInput } from "./marketplace.validators";
const map=(x:Record<string,unknown>)=>({title:x.title,description:x.description,category:x.propertyCategory,property_type:x.propertyType,ownership_type:x.ownershipType,public_location:x.publicLocation,full_address:x.fullAddress,price:x.askingPrice,negotiable:x.negotiable,initial_deposit_type:x.initialDepositType,initial_deposit_value:x.initialDepositValue,property_condition:x.condition,furnishing:x.furnishing,bedrooms:x.bedrooms,bathrooms:x.bathrooms,toilets:x.toilets,parking_spaces:x.parkingSpaces,number_of_floors:x.numberOfFloors,parking_capacity:x.parkingCapacity,amenities:x.amenities,marketplace_current_step:x.currentStep});
const dto=(p:any)=>({id:p.id,referenceId:p.property_code,status:p.marketplace_status,currentStep:p.marketplace_current_step,title:p.title,description:p.description,propertyCategory:p.category,propertyType:p.property_type,ownershipType:p.ownership_type,publicLocation:p.public_location,fullAddress:p.full_address,askingPrice:p.price,negotiable:p.negotiable,initialDepositType:p.initial_deposit_type,initialDepositValue:p.initial_deposit_value,condition:p.property_condition,furnishing:p.furnishing,bedrooms:p.bedrooms,bathrooms:p.bathrooms,toilets:p.toilets,parkingSpaces:p.parking_spaces,numberOfFloors:p.number_of_floors,parkingCapacity:p.parking_capacity,amenities:p.amenities,createdAt:p.created_at,updatedAt:p.updated_at});
export const assertSeller=async(userId:string)=>{const {data,error}=await supabaseAdmin.from("user_personas").select("persona_type,onboarding_status").eq("user_id",userId).eq("persona_type","SELLER_DEVELOPER").maybeSingle();if(error||!data||data.onboarding_status!=="COMPLETED")throw new AppError("Seller persona is required",403,"SELLER_PERSONA_REQUIRED");};
export const createDraft=async(userId:string,payload:Record<string,unknown>)=>{await assertSeller(userId);const {data,error}=await supabaseAdmin.from("properties").insert({...map(payload),owner_id:userId,marketplace_status:"DRAFT",marketplace_current_step:"PROPERTY_INFORMATION",status:"pending",is_published:false,property_code:`BRL-${Date.now()}-${Math.floor(Math.random()*9000+1000)}`}).select("*").single();if(error)throw new AppError("Marketplace is temporarily unavailable",503,"MARKETPLACE_UNAVAILABLE");return dto(data);};
const own=async(id:string,userId:string)=>{const {data,error}=await supabaseAdmin.from("properties").select("*").eq("id",id).eq("owner_id",userId).eq("marketplace_status","DRAFT").maybeSingle();if(error||!data)throw new AppError("Property draft not found",404,"PROPERTY_NOT_FOUND");return data;};
const ownedProperty=async(id:string,userId:string)=>{const {data,error}=await supabaseAdmin.from("properties").select("*").eq("id",id).eq("owner_id",userId).maybeSingle();if(error||!data)throw new AppError("Property draft not found",404,"PROPERTY_NOT_FOUND");return data;};
export const getDraft=async(id:string,userId:string)=>{await assertSeller(userId);const property=await own(id,userId);return {...dto(property),images:(await images(id)).map(imageDto),documents:await listDocumentMetadata(id,userId)};}; export const updateDraft=async(id:string,userId:string,p:Record<string,unknown>)=>{await assertSeller(userId);await own(id,userId);const {data,error}=await supabaseAdmin.from("properties").update(map(p)).eq("id",id).eq("owner_id",userId).select("*").single();if(error)throw new AppError("Marketplace is temporarily unavailable",503,"MARKETPLACE_UNAVAILABLE");return dto(data);};
export const marketplaceStatuses=["DRAFT","IN_REVIEW","LIVE","REJECTED"] as const; export type MarketplaceStatus=typeof marketplaceStatuses[number]; export type MarketplaceStatusFilter=MarketplaceStatus|"ALL";
export const sellerNextAction=(status:MarketplaceStatus,currentStep:string|null|undefined,rejectedAt?:string|null)=>{if(status==="IN_REVIEW")return "VIEW_REVIEW_STATUS" as const;if(status==="LIVE")return "VIEW_LIVE_LISTING" as const;if(status==="REJECTED")return "VIEW_REJECTION" as const;if(status==="DRAFT"&&rejectedAt)return "EDIT_REJECTED_LISTING" as const;const steps:Record<string,string>={PROPERTY_INFORMATION:"CONTINUE_PROPERTY_INFORMATION",PHOTOS_DOCUMENTS:"CONTINUE_PHOTOS_DOCUMENTS",SALES_MANDATE:"CONTINUE_SALES_MANDATE",REVIEW:"CONTINUE_REVIEW"};return steps[currentStep??""]??"CONTINUE_PROPERTY_INFORMATION"};
const sellerSummary=(p:any)=>{const propertyImages=[...(p.property_images??[])].sort((a:any,b:any)=>a.sort_order-b.sort_order);const status=p.marketplace_status as MarketplaceStatus;const cover=propertyImages.find((image:any)=>image.is_cover);const rejectionReason=status==="LIVE"?null:(p.rejection_reason??null);return {id:p.id,referenceId:p.property_code,title:p.title,askingPrice:p.price,status,currentStep:p.marketplace_current_step??null,coverImage:cover?imageDto(cover):null,photoCount:propertyImages.length,updatedAt:p.updated_at,submittedAt:p.marketplace_submitted_at??null,reviewedAt:p.marketplace_reviewed_at??null,publishedAt:p.marketplace_published_at??null,rejectedAt:p.marketplace_rejected_at??null,rejectionReason,rejectionFeedback:rejectionReason,reviewProgress:status==="IN_REVIEW"?{submitted:true,reviewing:true,live:false}:null,nextAction:sellerNextAction(status,p.marketplace_current_step,p.marketplace_rejected_at??null)}};
const sellerStatusCount=async(userId:string,status?:MarketplaceStatus)=>{let query=supabaseAdmin.from("properties").select("id",{count:"exact",head:true}).eq("owner_id",userId);query=status?query.eq("marketplace_status",status):query.in("marketplace_status",marketplaceStatuses);const {count,error}=await query;if(error)throw new AppError("Property management is temporarily unavailable",503,"PROPERTY_MANAGEMENT_UNAVAILABLE");return count??0};
export const listDrafts=async(userId:string,q:{page:number;limit:number;status:MarketplaceStatusFilter})=>{await assertSeller(userId);const from=(q.page-1)*q.limit;let request=supabaseAdmin.from("properties").select("*,property_images(id,image_url,sort_order,is_cover)",{count:"exact"}).eq("owner_id",userId);request=q.status==="ALL"?request.in("marketplace_status",marketplaceStatuses):request.eq("marketplace_status",q.status);const [{data,error,count},all,draft,inReview,live,rejected]=await Promise.all([request.order("updated_at",{ascending:false}).order("id",{ascending:false}).range(from,from+q.limit-1),sellerStatusCount(userId),sellerStatusCount(userId,"DRAFT"),sellerStatusCount(userId,"IN_REVIEW"),sellerStatusCount(userId,"LIVE"),sellerStatusCount(userId,"REJECTED")]);if(error)throw new AppError("Property management is temporarily unavailable",503,"PROPERTY_MANAGEMENT_UNAVAILABLE");return {counts:{all,draft,inReview,live,rejected},items:(data??[]).map(sellerSummary),pagination:{page:q.page,limit:q.limit,total:count??0,total_pages:Math.ceil((count??0)/q.limit)}};};
const images=async(id:string)=>{const {data,error}=await supabaseAdmin.from("property_images").select("*").eq("property_id",id).order("sort_order",{ascending:true});if(error)throw new AppError("Marketplace is temporarily unavailable",503,"MARKETPLACE_UNAVAILABLE");return data??[]}; const imageDto=(x:any)=>({id:x.id,url:x.image_url,order:x.sort_order,isCover:x.is_cover});
export type SellerPropertyDocumentDto={id:string;documentType:"OWNERSHIP_PAPERS"|"SURVEY_PLAN"|"DEED"|"CERTIFICATE_OF_OCCUPANCY"|"OTHER";displayName:string;mimeType:string;sizeBytes:number;uploadedAt:string}; type DocumentType=SellerPropertyDocumentDto["documentType"]; const documentDto=(x:any):SellerPropertyDocumentDto=>({id:x.id,documentType:x.document_type,displayName:x.display_name,mimeType:x.mime_type,sizeBytes:x.size_bytes,uploadedAt:x.created_at}); export const listDocumentMetadata=async(propertyId:string,userId:string)=>{await assertSeller(userId);await own(propertyId,userId);const {data,error}=await supabaseAdmin.from("property_documents").select("*").eq("property_id",propertyId).order("created_at",{ascending:true});if(error)throw new AppError("Marketplace is temporarily unavailable",503,"MARKETPLACE_UNAVAILABLE");return (data??[]).map(documentDto)}; export const findDocumentMetadata=async(propertyId:string,documentId:string,userId:string)=>{await assertSeller(userId);await own(propertyId,userId);const {data,error}=await supabaseAdmin.from("property_documents").select("*").eq("property_id",propertyId).eq("id",documentId).maybeSingle();if(error)throw new AppError("Marketplace is temporarily unavailable",503,"MARKETPLACE_UNAVAILABLE");if(!data)throw new AppError("Property document not found",404,"PROPERTY_DOCUMENT_NOT_FOUND");return data}; export const createDocumentMetadata=async(propertyId:string,userId:string,row:{document_type:string;display_name:string;cloudinary_public_id:string;cloudinary_resource_type:string;mime_type:string;size_bytes:number})=>{await assertSeller(userId);await own(propertyId,userId);const {data,error}=await supabaseAdmin.from("property_documents").insert({property_id:propertyId,...row}).select("*").single();if(error)throw new AppError("Marketplace is temporarily unavailable",503,"MARKETPLACE_UNAVAILABLE");return documentDto(data)}; export const deleteDocumentMetadata=async(propertyId:string,documentId:string,userId:string)=>{await assertSeller(userId);await own(propertyId,userId);const {error}=await supabaseAdmin.from("property_documents").delete().eq("id",documentId).eq("property_id",propertyId);if(error)throw new AppError("Marketplace is temporarily unavailable",503,"MARKETPLACE_UNAVAILABLE")};
const safeDisplayName=(value:string|undefined,fallback:string)=>{const name=(value?.trim()||fallback).split(/[\\/]/).pop()??"document.pdf";return name.replace(/[\u0000-\u001f\u007f<>:"|?*]/g,"_").trim().slice(0,180)||"document.pdf"};
export const uploadDraftDocument=async(propertyId:string,userId:string,file:Express.Multer.File|undefined,metadata:{documentType:DocumentType;displayName?:string})=>{if(!file||file.mimetype!=="application/pdf"||file.buffer.subarray(0,5).toString("ascii")!=="%PDF-")throw new AppError("Only valid PDF documents are allowed",400,"INVALID_DOCUMENT_TYPE");if(file.size>10*1024*1024)throw new AppError("Document must not exceed 10MB",400,"DOCUMENT_TOO_LARGE");await assertSeller(userId);await own(propertyId,userId);let uploaded:{public_id:string;resource_type:"raw"}|undefined;try{uploaded=await uploadPropertyDocument(file.buffer,"beryl-prestige/properties/documents");return await createDocumentMetadata(propertyId,userId,{document_type:metadata.documentType,display_name:safeDisplayName(metadata.displayName,file.originalname),cloudinary_public_id:uploaded.public_id,cloudinary_resource_type:uploaded.resource_type,mime_type:file.mimetype,size_bytes:file.size})}catch{if(uploaded)try{await deletePropertyDocument(uploaded.public_id)}catch{}throw new AppError("Document upload failed",503,"DOCUMENT_UPLOAD_FAILED")}};
export const deleteDraftDocument=async(propertyId:string,documentId:string,userId:string)=>{const document=await findDocumentMetadata(propertyId,documentId,userId);try{await deletePropertyDocument(document.cloudinary_public_id);await deleteDocumentMetadata(propertyId,documentId,userId)}catch{throw new AppError("Document delete failed",503,"DOCUMENT_DELETE_FAILED")}};
export type SellerSalesMandateDto={mandateType:"EXCLUSIVE"|"OPEN";sellerFullName:string;ownershipConfirmed:boolean;mandateAccepted:boolean;acceptedAt:string|null;agreementVersion:string|null;commissionPercentage:number|null;commissionAmount:number|null};
const configuredMandateTerms:{agreementVersion:string|null;commissionPercentage:number|null;commissionAmount:number|null}={agreementVersion:null,commissionPercentage:null,commissionAmount:null};
const mandateDto=(row:any):SellerSalesMandateDto=>({mandateType:row.marketplace_mandate_type,sellerFullName:row.full_name,ownershipConfirmed:Boolean(row.ownership_confirmed),mandateAccepted:Boolean(row.mandate_accepted),acceptedAt:row.accepted_at??null,agreementVersion:row.agreement_version??null,commissionPercentage:row.commission_percentage==null?null:Number(row.commission_percentage),commissionAmount:row.commission_amount==null?null:Number(row.commission_amount)});
const findSalesMandateRow=async(propertyId:string)=>{const {data,error}=await supabaseAdmin.from("mandates").select("*").eq("property_id",propertyId).not("marketplace_mandate_type","is",null).maybeSingle();if(error)throw new AppError("Sales mandate is temporarily unavailable",503,"MANDATE_UNAVAILABLE");return data};
export const saveSalesMandate=async(propertyId:string,userId:string,input:{mandateType:"EXCLUSIVE"|"OPEN";sellerFullName:string;ownershipConfirmed:boolean;mandateAccepted:boolean})=>{await assertSeller(userId);const property=await own(propertyId,userId);const {data:profile,error:profileError}=await supabaseAdmin.from("profiles").select("email,phone_number").eq("id",userId).maybeSingle();if(profileError||!profile)throw new AppError("Sales mandate is temporarily unavailable",503,"MANDATE_UNAVAILABLE");const existing=await findSalesMandateRow(propertyId);const ownershipConfirmed=Boolean(existing?.ownership_confirmed)||input.ownershipConfirmed;const mandateAccepted=Boolean(existing?.mandate_accepted)||input.mandateAccepted;if(mandateAccepted&&!ownershipConfirmed)throw new AppError("Ownership confirmation is required before accepting the mandate",400,"MANDATE_OWNERSHIP_CONFIRMATION_REQUIRED");const acceptedAt=existing?.accepted_at??(mandateAccepted?new Date().toISOString():null);const configuredTerms={...(configuredMandateTerms.agreementVersion!==null?{agreement_version:configuredMandateTerms.agreementVersion}:{}),...(configuredMandateTerms.commissionPercentage!==null?{commission_percentage:configuredMandateTerms.commissionPercentage}:{}),...(configuredMandateTerms.commissionAmount!==null?{commission_amount:configuredMandateTerms.commissionAmount}:{})};const values={marketplace_mandate_type:input.mandateType,full_name:input.sellerFullName,ownership_confirmed:ownershipConfirmed,mandate_accepted:mandateAccepted,accepted_at:acceptedAt,terms_accepted:mandateAccepted,...configuredTerms};let result;if(existing){result=await supabaseAdmin.from("mandates").update(values).eq("id",existing.id).eq("property_id",propertyId).select("*").single()}else{result=await supabaseAdmin.from("mandates").insert({user_id:userId,property_id:propertyId,mandate_type:"seller",status:"pending",email:profile.email,phone_number:profile.phone_number,address:property.full_address??property.public_location??null,submitted_at:new Date().toISOString(),agreement_version:configuredMandateTerms.agreementVersion,commission_percentage:configuredMandateTerms.commissionPercentage,commission_amount:configuredMandateTerms.commissionAmount,...values}).select("*").single()}if(result.error||!result.data)throw new AppError("Sales mandate is temporarily unavailable",503,"MANDATE_UNAVAILABLE");return mandateDto(result.data)};
export const getSalesMandate=async(propertyId:string,userId:string)=>{await assertSeller(userId);await own(propertyId,userId);const mandate=await findSalesMandateRow(propertyId);if(!mandate)throw new AppError("Sales mandate not found",404,"MANDATE_NOT_FOUND");return mandateDto(mandate)};
export type ListingSubmissionValidation={missingSections:string[];missingFields:string[]};
const missingText=(value:unknown)=>typeof value!=="string"||value.trim().length===0;
export const validateListingSubmission=(property:any,propertyImages:any[],mandate:any):ListingSubmissionValidation=>{const missingSections:string[]=[];const missingFields:string[]=[];const add=(section:string,field:string)=>{if(!missingSections.includes(section))missingSections.push(section);if(!missingFields.includes(field))missingFields.push(field)};for(const [field,value] of [["title",property.title],["description",property.description],["propertyCategory",property.category],["propertyType",property.property_type],["ownershipType",property.ownership_type],["publicLocation",property.public_location],["fullAddress",property.full_address],["condition",property.property_condition]] as const)if(missingText(value))add("PROPERTY_INFORMATION",field);if(property.price===null||property.price===undefined||!Number.isFinite(Number(property.price)))add("PROPERTY_INFORMATION","askingPrice");if(propertyImages.length<1)add("PHOTOS","images");if(propertyImages.length>10)add("PHOTOS","images");if(propertyImages.filter((image)=>Boolean(image.is_cover)).length!==1)add("PHOTOS","coverImage");const orders=propertyImages.map((image)=>Number(image.sort_order)).sort((a,b)=>a-b);if(orders.some((order,index)=>!Number.isInteger(order)||order!==index))add("PHOTOS","imageOrder");if(!mandate){add("SALES_MANDATE","mandate")}else{if(!["EXCLUSIVE","OPEN"].includes(mandate.marketplace_mandate_type))add("SALES_MANDATE","mandateType");if(missingText(mandate.full_name))add("SALES_MANDATE","sellerFullName");if(mandate.ownership_confirmed!==true)add("SALES_MANDATE","ownershipConfirmed");if(mandate.mandate_accepted!==true)add("SALES_MANDATE","mandateAccepted");if(!mandate.accepted_at)add("SALES_MANDATE","acceptedAt")}return {missingSections,missingFields}};
export const getPropertyReview=async(propertyId:string,userId:string)=>{await assertSeller(userId);const property=await own(propertyId,userId);const propertyImages=await images(propertyId);const mandate=await findSalesMandateRow(propertyId);const orderedImages=propertyImages.map(imageDto);return {buyerPreview:{id:property.id,referenceId:property.property_code,title:property.title,description:property.description,propertyType:property.property_type,propertyCategory:property.category,publicLocation:property.public_location,askingPrice:property.price,negotiable:Boolean(property.negotiable),initialDeposit:property.initial_deposit_type||property.initial_deposit_value!=null?{type:property.initial_deposit_type,value:property.initial_deposit_value}:null,condition:property.property_condition,furnishing:property.furnishing,bedrooms:property.bedrooms,bathrooms:property.bathrooms,toilets:property.toilets,parkingSpaces:property.parking_spaces,numberOfFloors:property.number_of_floors,parkingCapacity:property.parking_capacity,amenities:property.amenities??[],images:orderedImages,coverImage:orderedImages.find((image)=>image.isCover)??null,photoCount:orderedImages.length},sellerPrivate:{fullAddress:property.full_address},mandate:mandate?mandateDto(mandate):null,currentStep:property.marketplace_current_step,status:property.marketplace_status,validation:validateListingSubmission(property,propertyImages,mandate)}};
export const getSellerPropertyManagement=async(propertyId:string,userId:string)=>{
  await assertSeller(userId);
  const {data:property,error}=await supabaseAdmin.from("properties").select("*,property_images(id,image_url,sort_order,is_cover)").eq("id",propertyId).eq("owner_id",userId).maybeSingle();
  if(error)throw new AppError("Property management is temporarily unavailable",503,"PROPERTY_MANAGEMENT_UNAVAILABLE");
  if(!property||!marketplaceStatuses.includes(property.marketplace_status))throw new AppError("Property not found",404,"PROPERTY_NOT_FOUND");
  let documentsResult:any,mandate:any,historyResult:any;
  try{[documentsResult,mandate,historyResult]=await Promise.all([
    supabaseAdmin.from("property_documents").select("id,document_type,display_name,mime_type,size_bytes,created_at").eq("property_id",propertyId).order("created_at",{ascending:true}),
    findSalesMandateRow(propertyId),
    supabaseAdmin.from("marketplace_property_review_history").select("id,previous_status,new_status,action,reason,created_at").eq("property_id",propertyId).order("created_at",{ascending:false})
  ])}catch{throw new AppError("Property management is temporarily unavailable",503,"PROPERTY_MANAGEMENT_UNAVAILABLE")}
  const {data:documents,error:documentsError}=documentsResult;
  const {data:history,error:historyError}=historyResult;
  if(documentsError||historyError)throw new AppError("Property management is temporarily unavailable",503,"PROPERTY_MANAGEMENT_UNAVAILABLE");
  const propertyImages=[...(property.property_images??[])].sort((a:any,b:any)=>a.sort_order-b.sort_order);
  const rejectionReason=property.marketplace_status==="LIVE"?null:(property.rejection_reason??null);
  return {summary:sellerSummary(property),property:{...dto(property),submittedAt:property.marketplace_submitted_at??null,reviewedAt:property.marketplace_reviewed_at??null,publishedAt:property.marketplace_published_at??null,rejectedAt:property.marketplace_rejected_at??null,rejectionReason,rejectionFeedback:rejectionReason,images:propertyImages.map(imageDto)},documents:(documents??[]).map(documentDto),mandate:mandate?mandateDto(mandate):null,reviewHistory:(history??[]).map((row:any)=>({id:row.id,previousStatus:row.previous_status,newStatus:row.new_status,action:row.action,reason:row.reason,createdAt:row.created_at}))};
};
export const submitPropertyForReview=async(propertyId:string,userId:string)=>{await assertSeller(userId);const property=await ownedProperty(propertyId,userId);if(property.marketplace_status==="IN_REVIEW")throw new AppError("Property listing has already been submitted",409,"LISTING_ALREADY_SUBMITTED");if(property.marketplace_status!=="DRAFT")throw new AppError("Property is not editable",409,"PROPERTY_NOT_EDITABLE");const propertyImages=await images(propertyId);const mandate=await findSalesMandateRow(propertyId);const validation=validateListingSubmission(property,propertyImages,mandate);if(validation.missingSections.length)throw new AppError("Property listing is incomplete",400,"LISTING_SUBMISSION_INCOMPLETE",validation);const {data,error}=await supabaseAdmin.rpc("submit_marketplace_property_for_review",{p_property_id:propertyId,p_owner_id:userId});if(error)throw new AppError("Property submission is temporarily unavailable",503,"LISTING_SUBMISSION_FAILED");const result=Array.isArray(data)?data[0]:data;if(!result)throw new AppError("Property submission is temporarily unavailable",503,"LISTING_SUBMISSION_FAILED");if(result.outcome==="INCOMPLETE")throw new AppError("Property listing is incomplete",400,"LISTING_SUBMISSION_INCOMPLETE",{missingSections:result.missing_sections??[],missingFields:result.missing_fields??[]});if(result.outcome==="ALREADY_SUBMITTED")throw new AppError("Property listing has already been submitted",409,"LISTING_ALREADY_SUBMITTED");if(result.outcome==="NOT_EDITABLE")throw new AppError("Property is not editable",409,"PROPERTY_NOT_EDITABLE");if(result.outcome==="NOT_FOUND")throw new AppError("Property draft not found",404,"PROPERTY_NOT_FOUND");if(result.outcome!=="SUBMITTED")throw new AppError("Property submission is temporarily unavailable",503,"LISTING_SUBMISSION_FAILED");return {propertyId:result.property_id,referenceId:result.reference_id,status:result.marketplace_status,submittedAt:result.submitted_at,nextAction:"OPEN_MY_LISTINGS" as const}};
export const uploadDraftImages=async(id:string,user:string,files:Express.Multer.File[])=>{await assertSeller(user);const p=await own(id,user);const existing=await images(id);if(!files?.length)throw new AppError("At least one image is required",400,"INVALID_IMAGE_TYPE");if(existing.length+files.length>10)throw new AppError("A property can have at most 10 images",400,"IMAGE_LIMIT_EXCEEDED");const rows=[];for(let i=0;i<files.length;i++){const up=await uploadImageWithPublicId(files[i].buffer,"beryl-prestige/properties");rows.push({property_id:id,image_url:up.secure_url,cloudinary_public_id:up.public_id,alt_text:p.title,is_cover:existing.length===0&&i===0,sort_order:existing.length+i})}const {data,error}=await supabaseAdmin.from("property_images").insert(rows).select("*");if(error)throw new AppError("Media upload failed",503,"MEDIA_UPLOAD_FAILED");return (data??[]).map(imageDto)};
export const deleteDraftImage=async(pid:string,iid:string,user:string)=>{await assertSeller(user);await own(pid,user);const all=await images(pid);const image=all.find(x=>x.id===iid);if(!image)throw new AppError("Property image not found",404,"PROPERTY_IMAGE_NOT_FOUND");try{if(image.cloudinary_public_id)await deleteImageFromCloudinary(image.cloudinary_public_id);const {error}=await supabaseAdmin.from("property_images").delete().eq("id",iid).eq("property_id",pid);if(error)throw error;const rest=all.filter(x=>x.id!==iid);if(image.is_cover&&rest[0])await supabaseAdmin.from("property_images").update({is_cover:true}).eq("id",rest[0].id);return true}catch{throw new AppError("Media delete failed",503,"MEDIA_DELETE_FAILED")}};
export const reorderDraftImages=async(pid:string,ids:string[],user:string)=>{await assertSeller(user);await own(pid,user);const all=await images(pid);if(ids.length!==all.length||new Set(ids).size!==ids.length||ids.some(id=>!all.some(x=>x.id===id)))throw new AppError("Invalid image order",400,"INVALID_IMAGE_ORDER");await Promise.all(ids.map((id,sort_order)=>supabaseAdmin.from("property_images").update({sort_order}).eq("id",id).eq("property_id",pid)));return (await images(pid)).map(imageDto)};
export const setDraftCover=async(pid:string,iid:string,user:string)=>{await assertSeller(user);await own(pid,user);const all=await images(pid);if(!all.some(x=>x.id===iid))throw new AppError("Property image not found",404,"PROPERTY_IMAGE_NOT_FOUND");await supabaseAdmin.from("property_images").update({is_cover:false}).eq("property_id",pid);await supabaseAdmin.from("property_images").update({is_cover:true}).eq("id",iid).eq("property_id",pid);return (await images(pid)).map(imageDto)};

export const reopenRejectedProperty=async(propertyId:string,userId:string)=>{
  await assertSeller(userId);
  const {data,error}=await supabaseAdmin.rpc("reopen_rejected_marketplace_property",{p_property_id:propertyId,p_owner_id:userId});
  if(error)throw new AppError("Listing reopen failed",503,"LISTING_REOPEN_FAILED");
  const result=Array.isArray(data)?data[0]:data;
  if(!result||result.outcome==="NOT_FOUND")throw new AppError("Property not found",404,"PROPERTY_NOT_FOUND");
  if(result.outcome==="ALREADY_REOPENED")throw new AppError("Listing has already been reopened",409,"LISTING_ALREADY_REOPENED");
  if(result.outcome==="NOT_REJECTED")throw new AppError("Only rejected listings can be reopened",409,"LISTING_NOT_REJECTED");
  if(result.outcome!=="REOPENED")throw new AppError("Listing reopen failed",503,"LISTING_REOPEN_FAILED");
  return {propertyId:result.property_id,referenceId:result.reference_id,status:result.marketplace_status,currentStep:result.current_step,rejectionReason:result.rejection_reason,rejectedAt:result.rejected_at,reviewedAt:result.reviewed_at,nextAction:"EDIT_REJECTED_LISTING" as const};
};

const publicCardDto=(property:any)=>{
  const propertyImages=[...(property.property_images??[])].sort((a:any,b:any)=>a.sort_order-b.sort_order);
  const cover=propertyImages.find((image:any)=>image.is_cover)??null;
  return {id:property.id,referenceId:property.property_code,title:property.title,askingPrice:property.price,negotiable:Boolean(property.negotiable),propertyType:property.property_type,propertyCategory:property.category,publicLocation:property.public_location,bedrooms:property.bedrooms??null,bathrooms:property.bathrooms??null,toilets:property.toilets??null,parkingSpaces:property.parking_spaces??null,coverImage:cover?{id:cover.id,url:cover.image_url}:null,photoCount:propertyImages.length,verified:property.marketplace_status==="LIVE",publishedAt:property.marketplace_published_at??null};
};

export const searchPublicMarketplace=async(query:PublicMarketplaceSearchInput)=>{
  const from=(query.page-1)*query.limit;
  let request=supabaseAdmin.from("properties").select("id,property_code,title,description,category,property_type,public_location,price,negotiable,bedrooms,bathrooms,toilets,parking_spaces,marketplace_status,marketplace_published_at,updated_at,property_images(id,image_url,sort_order,is_cover)",{count:"exact"}).eq("marketplace_status","LIVE");
  if(query.q){const term=`%${query.q}%`;request=request.or(`title.ilike.${term},description.ilike.${term},public_location.ilike.${term},property_type.ilike.${term}`)}
  if(query.location)request=request.ilike("public_location",`%${query.location}%`);
  if(query.minPrice!==undefined)request=request.gte("price",query.minPrice);
  if(query.maxPrice!==undefined)request=request.lte("price",query.maxPrice);
  if(query.propertyType?.length)request=request.in("property_type",query.propertyType);
  if(query.category)request=request.eq("category",query.category);
  if(query.bedrooms!==undefined)request=request.eq("bedrooms",query.bedrooms);
  if(query.sort==="PRICE_HIGH_TO_LOW")request=request.order("price",{ascending:false});
  else if(query.sort==="PRICE_LOW_TO_HIGH")request=request.order("price",{ascending:true});
  else if(query.sort==="BEDS")request=request.order("bedrooms",{ascending:false,nullsFirst:false});
  else request=request.order("marketplace_published_at",{ascending:false,nullsFirst:false}).order("updated_at",{ascending:false});
  const {data,error,count}=await request.order("id",{ascending:false}).range(from,from+query.limit-1);
  if(error)throw new AppError("Marketplace is temporarily unavailable",503,"MARKETPLACE_UNAVAILABLE");
  return {properties:(data??[]).map(publicCardDto),pagination:{page:query.page,limit:query.limit,total:count??0,total_pages:Math.ceil((count??0)/query.limit)}};
};
