import assert from "node:assert/strict";
import { runIfMain } from "./run-ui-suite.mjs";
import { resetSavedPropertiesState, savedPropertiesState } from "./saved-properties-ui.checks.mjs";

runIfMain(import.meta.url,"compare-properties");

export async function checkCompareProperties({page,origin,calls,failures,screenshot,passed}){
  failures.set("/me",{status:401,code:"SESSION_EXPIRED",message:"Your session has expired. Please log in again."});
  await page.goto(origin+"/compare-properties");await page.waitForURL("**/login?next=%2Fcompare-properties");failures.delete("/me");
  resetSavedPropertiesState();await page.goto(origin+"/compare-properties");await page.getByRole("heading",{name:"Compare Saved Properties"}).waitFor();await page.locator(".compare-property-card").first().waitFor();
  assert.equal(await page.getByText("0 of 3 Properties Selected").count(),1);assert.equal(await page.getByRole("button",{name:"Compare Properties"}).isDisabled(),true);
  const compareButtons=page.getByRole("button",{name:"Compare",exact:true});await compareButtons.nth(0).click();assert.equal(await page.getByText("1 of 3 Property Selected").count(),1);assert.equal(await page.getByRole("button",{name:"Compare Properties"}).isDisabled(),true);
  await compareButtons.nth(0).click();assert.equal(await page.getByText("2 of 3 Properties Selected").count(),1);assert.equal(await page.getByRole("button",{name:"Compare Properties"}).isEnabled(),true);
  await page.getByPlaceholder("Search your saved properties").fill("Rivers");await page.getByPlaceholder("Search your saved properties").press("Enter");assert.equal(await page.getByText("2 of 3 Properties Selected").count(),1);await page.getByPlaceholder("Search your saved properties").fill("");await page.getByPlaceholder("Search your saved properties").press("Enter");await page.locator(".compare-property-card").first().waitFor();
  await page.getByRole("button",{name:"Compare",exact:true}).first().click();assert.equal(await page.getByText("3 of 3 Properties Selected").count(),1);assert.equal(await page.getByRole("button",{name:"Compare",exact:true}).first().isDisabled(),true);
  const savesBefore=savedPropertiesState.items.length;await page.getByRole("button",{name:/Remove .* from comparison/}).first().click();assert.equal(savedPropertiesState.items.length,savesBefore);assert.equal(await page.getByText("2 of 3 Properties Selected").count(),1);
  await page.getByRole("button",{name:"Clear All"}).click();assert.equal(savedPropertiesState.items.length,savesBefore);assert.equal(await page.getByText("0 of 3 Properties Selected").count(),1);
  await page.getByRole("button",{name:"Compare",exact:true}).nth(0).click();await page.getByRole("button",{name:"Compare",exact:true}).nth(0).click();
  await page.context().grantPermissions(["clipboard-read","clipboard-write"],{origin});await page.evaluate(()=>Object.defineProperty(navigator,"share",{value:undefined,configurable:true}));await page.getByLabel("Share 4 Bedroom Semi Detached Duplex").click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),`${origin}/buy?code=RES-SAVE01`);
  const selectedTitle=await page.locator(".compare-property-card h2").first().innerText();await page.getByLabel(`Remove ${selectedTitle} from saved properties`).click();assert.equal(savedPropertiesState.items.some(item=>item.title===selectedTitle),false);assert.equal(await page.getByLabel(`Remove ${selectedTitle} from comparison`).count(),0);
  resetSavedPropertiesState();await page.reload();await page.locator(".compare-property-card").first().waitFor();await page.getByRole("button",{name:"Compare",exact:true}).nth(0).click();await page.getByRole("button",{name:"Compare",exact:true}).nth(0).click();await page.getByRole("button",{name:"Compare Properties"}).click();await page.waitForURL(/\/compare-properties\/compare\?codes=RES-SAVE01%2CRES-SAVE02/);await page.getByText("Property Ref No.").waitFor();assert.equal(await page.getByText("—").count()>0,true);assert.equal(await page.locator(".comparison-property-header").count(),2);
  savedPropertiesState.items=savedPropertiesState.items.filter(item=>item.code==="RES-SAVE01");await page.reload();await page.getByText("Enough properties are no longer available to compare.").waitFor();
  resetSavedPropertiesState();for(let index=5;index<=13;index++)savedPropertiesState.items.push({...savedPropertiesState.items[0],code:`RES-SAVE${String(index).padStart(2,"0")}`,title:`Later page property ${index}`});
  let compareResponse=page.waitForResponse(response=>response.url().includes("/api/v1/saved-properties/compare?"));await page.goto(origin+"/compare-properties?codes=RES-SAVE01,RES-SAVE13");await compareResponse;await page.getByText("2 of 3 Properties Selected").waitFor();assert.equal(await page.getByRole("heading",{name:"Later page property 13"}).count(),0);assert.equal(await page.getByLabel("Remove Later page property 13 from comparison").count(),1);
  await page.reload();await page.getByText("2 of 3 Properties Selected").waitFor();await page.getByRole("button",{name:"Compare Properties"}).click();await page.getByText("Property Ref No.").waitFor();await page.getByRole("link",{name:"Back to Compare Saved Properties"}).click();await page.getByText("2 of 3 Properties Selected").waitFor();assert.equal(await page.getByLabel("Remove Later page property 13 from comparison").count(),1);
  compareResponse=page.waitForResponse(response=>response.url().includes("/api/v1/saved-properties/compare?"));await page.goto(origin+"/compare-properties?codes=RES-SAVE01,RES-UNSAVED");await compareResponse;await page.getByText("1 of 3 Property Selected").waitFor();assert.equal(await page.getByRole("button",{name:"Compare Properties"}).isDisabled(),true);
  resetSavedPropertiesState();savedPropertiesState.nonListedCodes.add("RES-SAVE04");compareResponse=page.waitForResponse(response=>response.url().includes("/api/v1/saved-properties/compare?"));await page.goto(origin+"/compare-properties?codes=RES-SAVE01,RES-SAVE04");await compareResponse;await page.getByText("1 of 3 Property Selected").waitFor();assert.equal(await page.getByLabel("Remove Abuja Courtyard Bungalow from comparison").count(),0);
  resetSavedPropertiesState();compareResponse=page.waitForResponse(response=>response.url().includes("/api/v1/saved-properties/compare?"));await page.goto(origin+"/compare-properties?codes=RES-SAVE03,RES-SAVE01,RES-SAVE02");await compareResponse;await page.getByText("3 of 3 Properties Selected").waitFor();const restoredLabels=await page.locator(".compare-selection-thumb button").evaluateAll(buttons=>buttons.map(button=>button.getAttribute("aria-label")));assert.deepEqual(restoredLabels,["Remove Central Lagos Apartment from comparison","Remove 4 Bedroom Semi Detached Duplex from comparison","Remove Garden Family Home from comparison"]);
  resetSavedPropertiesState();for(const width of [1440,1280,1024,768,430,390,360,320]){await page.setViewportSize({width,height:900});await page.goto(origin+"/compare-properties?codes=RES-SAVE01,RES-SAVE02,RES-SAVE03");await page.locator(".compare-property-card").first().waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`selection overflow ${width}`);await page.goto(origin+"/compare-properties/compare?codes=RES-SAVE01,RES-SAVE02,RES-SAVE03");await page.locator(".comparison-property-header").first().waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`results overflow ${width}`);if(width<=430){const region=page.locator(".comparison-scroll");assert.equal(await region.evaluate(element=>element.scrollWidth>element.clientWidth),true,`comparison region scroll ${width}`)}if(width===390)await screenshot("compare-properties-results-390")}
  assert.equal(calls.some(call=>/referral|checkout|payment|purchase|inquiry|commission|payout/i.test(call.endpoint)),false);passed.push("Compare Saved Properties enforces 0–3 selection, separates compare removal from unsave, preserves selection across search, shares public URLs, and safely reconstructs authorized results");passed.push("URL hydration restores ordered 2/3-property selections outside the current page through the compare endpoint while rejecting unsaved and non-LISTED codes");passed.push("Selection/results layouts avoid global overflow at eight widths and use intentional local overflow for three mobile columns");
}
