import assert from "node:assert/strict";
import { runIfMain } from "./run-ui-suite.mjs";

runIfMain(import.meta.url,"inquiry");
export async function checkInquiry({page,origin,calls,failures,screenshot,passed,pauseRequest,resume}){
  await page.goto(origin+"/");const help=page.getByRole("button",{name:"Open help"});await help.waitFor();await help.click();assert.equal(await page.getByRole("button",{name:"Close help"}).count(),1);await page.getByRole("heading",{name:"Home"}).waitFor();
  await page.getByRole("button",{name:"Close help"}).click();assert.equal(await page.getByRole("dialog",{name:"Home help"}).count(),0);await page.getByRole("button",{name:"Open help"}).click();await page.getByRole("button",{name:"Dismiss"}).click();assert.equal(await page.getByRole("dialog",{name:"Home help"}).count(),0);
  await page.getByRole("button",{name:"Open help"}).click();await page.getByRole("button",{name:"Need More Help"}).click();const dialog=page.getByRole("dialog",{name:"Real Estate Inquiry Form"});await dialog.waitFor();assert.deepEqual(await dialog.getByLabel(/Inquiry Type/).locator("option").allTextContents(),["Select Inquiry Type","Property Inquiry","Buying a Property","Selling/Listing a Property","Property Viewing","General Inquiry","Other"]);assert.equal(await dialog.getByLabel(/Your Name/).inputValue(),"Ada Okafor");assert.equal(await dialog.getByLabel(/Contact Email/).inputValue(),"ada@example.test");assert.equal(await dialog.getByRole("button",{name:/Chat us on WhatsApp/}).isDisabled(),true);assert.equal(await dialog.getByRole("link",{name:"0704 205 5678"}).getAttribute("href"),"tel:+2347042055678");
  await dialog.getByRole("button",{name:"Submit Inquiry"}).click();assert.equal(await dialog.getByRole("alert").count()>=3,true);await dialog.getByLabel(/Inquiry Type/).selectOption("Buying a Property");await dialog.getByLabel(/Contact Number/).fill("+234 801 234 5678");await dialog.getByLabel(/What do you need help with/).fill("Please help me find a home.");
  const paused=pauseRequest("/public/inquiries");await dialog.getByRole("button",{name:"Submit Inquiry"}).click();await paused;assert.equal(await dialog.getByRole("button",{name:"Submitting…"}).isDisabled(),true);resume();await dialog.getByText("Inquiry received").waitFor();const inquiryCalls=calls.filter(call=>call.endpoint==="/public/inquiries");assert.equal(inquiryCalls.length,1);assert.deepEqual(inquiryCalls[0].body,{inquiryType:"Buying a Property",name:"Ada Okafor",phone:"+234 801 234 5678",email:"ada@example.test",message:"Please help me find a home.",sourcePage:"home"});await dialog.getByRole("button",{name:"Close",exact:true}).click();assert.equal(await page.getByRole("button",{name:"Open help"}).evaluate(element=>element===document.activeElement),true);
  await page.getByRole("button",{name:"Open help"}).click();await page.getByRole("button",{name:"Need More Help"}).click();await page.keyboard.press("Escape");assert.equal(await page.getByRole("dialog",{name:"Real Estate Inquiry Form"}).count(),0);await page.getByRole("button",{name:"Open help"}).click();await page.keyboard.press("Escape");assert.equal(await page.getByRole("dialog",{name:"Home help"}).count(),0);
  failures.set("/public/inquiries",{status:503,code:"INQUIRY_UNAVAILABLE",message:"Your inquiry could not be submitted. Please try again."});await page.getByRole("button",{name:"Open help"}).click();await page.getByRole("button",{name:"Need More Help"}).click();await dialog.getByLabel(/Inquiry Type/).selectOption("General Inquiry");await dialog.getByLabel(/Contact Number/).fill("07042055678");await dialog.getByLabel(/What do you need help with/).fill("Keep this message on failure.");await dialog.getByRole("button",{name:"Submit Inquiry"}).click();await dialog.getByText("Your inquiry could not be submitted").waitFor();assert.equal(await dialog.getByLabel(/What do you need help with/).inputValue(),"Keep this message on failure.");failures.delete("/public/inquiries");await dialog.getByRole("button",{name:"Close inquiry form"}).click();
  for(const width of [1440,1280,1024,768,430,390,360,320]){await page.setViewportSize({width,height:900});await page.goto(origin+"/buy");await page.getByRole("button",{name:"Open help"}).click();const card=page.getByRole("dialog",{name:"Buy help"});await card.waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`help overflow ${width}`);await card.getByRole("button",{name:"Need More Help"}).click();await dialog.waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`modal overflow ${width}`);if(width<=800){const formBox=await dialog.locator(".inquiry-form-panel h1").boundingBox(),imageBox=await dialog.locator(".inquiry-expert").boundingBox();assert.equal(formBox.y<imageBox.y,true,`mobile expert order ${width}`)}else{const formBox=await dialog.locator(".inquiry-form-panel").boundingBox(),imageBox=await dialog.locator(".inquiry-expert").boundingBox();assert.equal(imageBox.x<formBox.x,true,`desktop expert order ${width}`)}if(width===1440||width===390)await screenshot(`inquiry-${width}`);await dialog.getByRole("button",{name:"Close inquiry form"}).click()}
  await page.goto(origin+"/dashboard");await page.getByRole("heading",{name:/Ada Okafor/}).waitFor();assert.equal(await page.getByRole("button",{name:"Open help"}).count(),0);
  assert.equal(calls.some(call=>/purchase|payment|checkout|referral|saved-properties|mortgage/i.test(call.endpoint)&&call.method!=="GET"),false);passed.push("Floating contextual help opens and closes by button, Dismiss and Escape; inquiry modal validates, traps state, submits once, confirms success and retains failed input");passed.push("Inquiry UI matches desktop/mobile ordering at eight widths, has no global overflow, uses safe phone/disabled WhatsApp actions, and remains absent from Dashboard");
}
