import assert from "node:assert/strict";
import { runIfMain } from "./run-ui-suite.mjs";

runIfMain(import.meta.url,"landing");

export async function checkLanding({page,origin,calls,screenshot,passed}){
  const open=async width=>{await page.setViewportSize({width,height:1000});await page.goto(origin+"/");await page.getByRole("heading",{name:/Earn Rich when you refer/}).waitFor();await page.evaluate(()=>document.fonts.ready);};
  for(const width of [1440,1280,768,430,390,360]){await open(width);await page.waitForFunction(()=>[...document.images].filter(image=>image.loading==="eager").every(image=>image.complete&&image.naturalWidth>0));const layout=await page.evaluate(()=>{const hero=document.querySelector(".landing-hero-picture").getBoundingClientRect(),tabs=document.querySelector(".search-tabs").getBoundingClientRect(),accountElement=document.querySelector(".hero-account-link"),account=accountElement.getBoundingClientRect(),searchButton=document.querySelector(".search-query button").getBoundingClientRect(),searchIcon=document.querySelector(".search-query button svg").getBoundingClientRect();return {overflow:document.documentElement.scrollWidth>innerWidth,heroLeft:hero.left,heroRight:hero.right,viewport:innerWidth,accountAligned:Math.abs(account.top-tabs.top)<1,accountBackground:getComputedStyle(accountElement).backgroundColor,searchIconCentered:Math.abs(searchButton.x+searchButton.width/2-(searchIcon.x+searchIcon.width/2))<1&&Math.abs(searchButton.y+searchButton.height/2-(searchIcon.y+searchIcon.height/2))<1,searchIconSize:searchIcon.width,background:getComputedStyle(document.querySelector(".landing-page")).backgroundColor,appBackground:getComputedStyle(document.querySelector(".app-section")).backgroundColor,footerBrandBackground:getComputedStyle(document.querySelector(".site-footer-about .brand-name")).backgroundColor,sharedHeader:!!document.querySelector(".public-header")};});assert.equal(layout.overflow,false);assert.equal(layout.heroLeft,0);assert.equal(layout.heroRight,layout.viewport);assert.equal(layout.accountAligned,true);assert.equal(layout.accountBackground,"rgb(255, 255, 255)");assert.equal(layout.searchIconCentered,true);assert.equal(layout.searchIconSize,18);assert.equal(layout.background,"rgb(247, 247, 250)");assert.equal(layout.appBackground,"rgb(247, 247, 250)");assert.equal(layout.footerBrandBackground,"rgba(0, 0, 0, 0)");assert.equal(layout.sharedHeader,true);assert.equal(await page.getByText("Earn your 2% commission",{exact:true}).count(),1);assert.equal(await page.getByText(/Earn your (5|10)% commission/).count(),0);assert.equal(await page.getByText("No listed properties are available right now.",{exact:true}).count(),1);await screenshot(`landing-${width}`);}
  passed.push("Landing uses the shared auth header, full-width hero, aligned white account tab, centered 18px search icon, visible light app panel, unboxed footer brand and no overflow at six widths");
  await open(1440);const beforeSearch=calls.filter(call=>call.endpoint==="/public/property-searches").length;assert.equal(beforeSearch,0);await page.getByRole("tab",{name:"buy"}).click();await page.getByLabel("Search property listings").fill("duplex");await page.getByLabel("Location").selectOption("Lagos");await Promise.all([page.waitForURL(url=>url.pathname==="/buy"),page.getByRole("button",{name:"Search properties"}).click()]);const url=new URL(page.url());assert.equal(url.searchParams.get("mode"),"buy");assert.equal(url.searchParams.get("q"),"duplex");assert.equal(url.searchParams.get("location"),"Lagos");assert.equal(calls.filter(call=>call.endpoint==="/public/property-searches").length,0);
  await open(1440);assert.equal(await page.getByRole("link",{name:"Create An Account"}).getAttribute("href"),"/register");assert.match(await page.getByRole("link",{name:/refer someone to buy/i}).getAttribute("href"),/^\/login\?next=/);assert.equal(await page.getByRole("link",{name:/View Properties/}).first().getAttribute("href"),"/buy");
  assert.equal(await page.getByAltText("Download on the App Store").first().isVisible(),true);assert.equal(await page.getByAltText("Get it on Google Play").first().isVisible(),true);
  const footerBadges=page.locator(".store-badges img");assert.deepEqual(await footerBadges.evaluateAll(images=>images.map(image=>image.getAttribute("src"))),["/landing/footer-app-store.png","/landing/footer-google-play.png"]);assert.equal(await page.locator(".store-badges").evaluate(element=>getComputedStyle(element).flexDirection),"row");
  for(const asset of ["landingpagehero_desktop.png","landingpagehero_mobile.png","step-1.png","step-2.png","step-3.png","startreferring.png","refertobuy.png","refertosell.png","propertysearchmadeeasy.png","getourapp.png","black-app-store.png","black-google-play.png","footer-app-store.png","footer-google-play.png"]){const response=await page.request.get(`${origin}/landing/${asset}`);assert.equal(response.ok(),true,asset);}
  passed.push("Search preserves supported future Buy parameters; auth/referral/property CTAs map safely; all fourteen landing assets resolve and footer badges remain in one row");
}
