import assert from "node:assert/strict";
import { runIfMain } from "./run-ui-suite.mjs";

runIfMain(import.meta.url,"public-pages");

export async function checkPublicPages({page,origin,calls,failures,screenshot,passed,pauseRequest,resume}){
  const widths=[1440,1280,768,430,390,360];
  const loadPage=async(path,heading)=>{await page.goto(origin+path);await page.getByRole("heading",{name:heading}).waitFor();const failed=await page.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=700){scrollTo(0,y);await new Promise(resolve=>setTimeout(resolve,20));}scrollTo(0,0);await document.fonts.ready;const results=await Promise.all([...document.images].map(async image=>{const source=image.currentSrc||image.src;try{return (await fetch(source,{cache:"force-cache"})).ok?null:source;}catch{return source;}}));return results.filter(Boolean);});assert.deepEqual(failed,[]);await page.waitForFunction(()=>[...document.images].filter(image=>image.loading==="eager").every(image=>image.complete&&image.naturalWidth>0));};
  const checkAbout=async width=>{
    assert.equal(await page.locator(".about-hero .about-eyebrow").innerText(),"WHO ARE WE?");
    assert.equal(await page.getByRole("heading",{level:1,name:"About Us"}).count(),1);
    const headingSizes=await page.locator(".about-hero").evaluate(section=>[parseFloat(getComputedStyle(section.querySelector(".about-eyebrow")).fontSize),parseFloat(getComputedStyle(section.querySelector("h1")).fontSize)]);
    assert.equal(headingSizes[1]>headingSizes[0]*2,true);
    assert.deepEqual(await page.locator(".purpose-cards article:first-child li").allTextContents(),["To build real estate apartments that will always excite and delight all."]);
    assert.equal((await page.locator(".purpose-cards article:nth-child(2) li").allTextContents()).join(" "),"To be a preeminent real estate developer in Nigeria To be known for the finest and largest portfolio of classic residential properties in Nigeria.");
    assert.equal(await page.locator(".leadership article small").count(),4);
    for(const email of await page.locator(".leadership article small").allTextContents())assert.equal(email.includes("afolayan@berylshelter.com"),true);
    assert.equal(await page.locator(".leadership article small").evaluateAll(items=>items.every(item=>item.scrollWidth<=item.clientWidth+1)),true);
    const address=page.locator(".office address");
    for(const value of ["Plot 2, Cornerstone Estate Drive, Ikate-Elegshi, Lekki, Lagos.","07042055678","info@berylshelter.com","Monday - Friday","8:00 AM - 6:00 PM"])assert.equal((await address.innerText()).includes(value),true);
    const map=page.locator(".office iframe");
    assert.equal(await map.getAttribute("title"),"Map of Beryl Shelter office in Lekki, Lagos");
    assert.equal(new URL(await map.getAttribute("src")).searchParams.get("q"),"Plot 2, Cornerstone Estate Drive, Ikate-Elegshi, Lekki, Lagos.");
    assert.equal(await page.locator('.office img[src*="office-map"]').count(),0);
    assert.equal(await map.evaluate(element=>element.getBoundingClientRect().width<=element.parentElement.getBoundingClientRect().width+1),true);
    assert.equal((await page.locator(".working p").allTextContents()).join(" "),"Come be a part of a truly amazing real estate company. Our people are always working together to build the next big thing, and that really keeps us all on the go. Whether we're planning projects or signing new clients, we all have a great time here. Want to join our team?");
    assert.equal(await page.locator('.working a[href="/careers"]').count(),1);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`About overflow at ${width}`);
  };
  for(const width of widths){await page.setViewportSize({width,height:950});await loadPage("/about",/Since incorporation in 2001/);await checkAbout(width);assert.equal(await page.locator(".public-header").count(),1);assert.equal(await page.locator(".site-footer").isVisible(),width>900);if(width<=700){const menu=page.getByRole("button",{name:"Toggle navigation"});assert.equal(await menu.isVisible(),true);await menu.click();assert.equal(await page.getByRole("navigation",{name:"Public navigation"}).isVisible(),true);await menu.click();}await screenshot(`about-${width}`);await loadPage("/careers","Join the Beryl Shelter Team");assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.getByLabel(/Full Name/).count(),1);assert.equal(await page.getByLabel(/Position Applied For/).isEnabled(),true);assert.deepEqual(await page.getByLabel(/Position Applied For/).locator("option").allTextContents(),["Select a role","Frontend Developer","Backend Developer","Real Estate Agent","Sales Manager","Marketing Specialist"]);assert.equal(await page.getByLabel(/Position Applied For/).evaluate(element=>getComputedStyle(element).borderRadius),"6px");assert.equal(await page.getByLabel(/Full Name/).evaluate(element=>getComputedStyle(element).borderRadius),"6px");assert.equal(await page.locator(".site-footer").isVisible(),width>900);await screenshot(`careers-${width}`);}
  passed.push("About and Careers match shared-header/footer responsive contracts with no overflow at 1440/1280/768/430/390/360px");
  await loadPage("/about",/Since incorporation in 2001/);await page.getByRole("link",{name:"See Open Positions"}).click();await page.waitForURL(origin+"/careers");
  const endpoint="/public/careers/applications";const writesBefore=calls.filter(call=>call.endpoint===endpoint).length;await page.getByRole("button",{name:"Submit Application"}).click();assert.equal(await page.getByLabel(/Full Name/).evaluate(input=>input.validationMessage.length>0),true);await page.getByLabel(/Full Name/).fill("Ada Okafor");await page.getByLabel(/Email Address/).fill("ada@example.test");await page.getByLabel(/Phone Number/).fill("08012345678");await page.getByLabel(/Upload Resume/).setInputFiles({name:"resume.pdf",mimeType:"application/pdf",buffer:Buffer.from("%PDF-1.4\n%%EOF")});await page.getByRole("button",{name:"Submit Application"}).click();assert.equal(await page.getByLabel(/Position Applied For/).evaluate(input=>input.validationMessage.length>0),true);assert.equal(calls.filter(call=>call.endpoint===endpoint).length,writesBefore);await page.getByLabel(/Position Applied For/).selectOption("Frontend Developer");
  const paused=pauseRequest(endpoint);await page.getByRole("button",{name:"Submit Application"}).click();await paused;assert.equal(await page.getByRole("button",{name:"Submitting application…"}).isDisabled(),true);assert.equal(await page.getByRole("status").count(),0);resume();await page.getByRole("status").filter({hasText:"application has been received"}).waitFor();assert.equal(calls.filter(call=>call.endpoint===endpoint).length,writesBefore+1);assert.equal(await page.getByLabel(/Full Name/).inputValue(),"");
  await page.getByLabel(/Full Name/).fill("Ada Okafor");await page.getByLabel(/Email Address/).fill("ada@example.test");await page.getByLabel(/Phone Number/).fill("08012345678");await page.getByLabel(/Position Applied For/).selectOption("Backend Developer");await page.getByLabel(/Upload Resume/).setInputFiles({name:"resume.pdf",mimeType:"application/pdf",buffer:Buffer.from("%PDF-1.4\n%%EOF")});failures.set(endpoint,{status:503,code:"CAREERS_UNAVAILABLE"});await page.getByRole("button",{name:"Submit Application"}).click();await page.getByRole("alert").filter({hasText:"could not be submitted"}).waitFor();assert.equal(await page.getByLabel(/Full Name/).inputValue(),"Ada Okafor");assert.equal(await page.getByLabel(/Position Applied For/).inputValue(),"Backend Developer");failures.delete(endpoint);passed.push("Careers exact roles, required PDF, restrained corners, real pending/success/failure request states and no overflow at six widths");
}
