import assert from "node:assert/strict";
import { runIfMain } from "./run-ui-suite.mjs";

runIfMain(import.meta.url,"public-pages");

export async function checkPublicPages({page,origin,calls,screenshot,passed}){
  const widths=[1440,1280,768,430,390,360];
  const loadPage=async(path,heading)=>{await page.goto(origin+path);await page.getByRole("heading",{name:heading}).waitFor();await page.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=700){scrollTo(0,y);await new Promise(resolve=>setTimeout(resolve,20));}scrollTo(0,0);await document.fonts.ready;});await page.waitForFunction(()=>[...document.images].every(image=>image.complete&&image.naturalWidth>0));};
  for(const width of widths){await page.setViewportSize({width,height:950});await loadPage("/about",/Since incorporation in 2001/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator(".public-header").count(),1);assert.equal(await page.locator(".site-footer").isVisible(),width>900);if(width<=700){const menu=page.getByRole("button",{name:"Toggle navigation"});assert.equal(await menu.isVisible(),true);await menu.click();assert.equal(await page.getByRole("navigation",{name:"Public navigation"}).isVisible(),true);await menu.click();}await screenshot(`about-${width}`);await loadPage("/careers","Join the Beryl Prestige Team");assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.getByLabel(/Full Name/).count(),1);assert.equal(await page.getByLabel(/Position Applied For/).isDisabled(),true);assert.equal(await page.locator(".site-footer").isVisible(),width>900);await screenshot(`careers-${width}`);}
  passed.push("About and Careers match shared-header/footer responsive contracts with no overflow at 1440/1280/768/430/390/360px");
  await loadPage("/about",/Since incorporation in 2001/);await page.getByRole("link",{name:"See Open Positions"}).click();await page.waitForURL(origin+"/careers");
  const writesBefore=calls.filter(call=>call.endpoint!=="/me").length;await page.getByRole("button",{name:"Submit Application"}).click();assert.equal(await page.getByLabel(/Full Name/).evaluate(input=>input.validationMessage.length>0),true);assert.equal(await page.getByRole("status").count(),0);await page.getByLabel(/Full Name/).fill("Ada Okafor");await page.getByLabel(/Email Address/).fill("ada@example.test");await page.getByLabel(/Phone Number/).fill("08012345678");await page.getByLabel(/Upload Resume/).setInputFiles({name:"resume.pdf",mimeType:"application/pdf",buffer:Buffer.from("%PDF-1.4")});await page.getByRole("button",{name:"Submit Application"}).click();assert.equal(await page.getByRole("status").innerText(),"Applications are not available yet. Please check back when open positions are published.");assert.equal(calls.filter(call=>call.endpoint!=="/me").length,writesBefore);passed.push("About CTA opens Careers; native required validation works; unavailable Careers submission performs no network mutation or fake success");
}
