import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { createRequire } from "node:module";
import { resolve } from "node:path";
import { setTimeout as delay } from "node:timers/promises";
import { chromium } from "playwright";
import { dashboardFixture } from "./dashboard-ui.checks.mjs";

const origin="http://127.0.0.1:3027",require=createRequire(import.meta.url),next=require.resolve("next/dist/bin/next"),cwd=resolve(import.meta.dirname,"..");
const server=spawn(process.execPath,[next,"dev","-H","127.0.0.1","-p","3027"],{cwd,env:{...process.env,NEXT_PUBLIC_API_BASE_URL:origin},stdio:["ignore","pipe","pipe"]});
let output="";server.stdout.on("data",chunk=>output+=chunk);server.stderr.on("data",chunk=>output+=chunk);
async function ready(){for(let i=0;i<60;i++){try{if((await fetch(origin)).ok)return;}catch{}await delay(500);}throw new Error(`Web server did not start. ${output}`);}
let available=200000,pending=0,items=[];
const model=()=>({balance:{totalEarnedMinor:200000,totalPaidMinor:0,grossOutstandingMinor:200000,pendingMinor:pending,availableMinor:available,minimumMinor:10000},bank:{complete:true,accountName:"Controlled Referrer",bankName:"Test Bank",maskedAccountNumber:"••••••6789"},items,page:1,pageSize:10,total:items.length,totalPages:items.length?1:0});
try{
  await ready();const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE}),context=await browser.newContext({serviceWorkers:"block"}),calls=[];
  await context.route(`${origin}/api/v1/**`,async route=>{const request=route.request(),url=new URL(request.url()),path=url.pathname.replace("/api/v1","");const reply=(data,status=200)=>route.fulfill({status,contentType:"application/json",body:JSON.stringify({success:true,data})});if(path==="/dashboard/overview")return reply(dashboardFixture);if(path==="/dashboard/referrals/withdrawals"&&request.method()==="GET")return reply(model());if(path==="/dashboard/referrals/withdrawals"&&request.method()==="POST"){const body=request.postDataJSON();calls.push(body);const item={id:"WDR-ABC234",amountMinor:body.amountMinor,status:"PENDING",requestedAt:"2026-09-29T10:00:00Z",processingStartedAt:null,paidAt:null,rejectedAt:null,rejectionReason:null,cancelledAt:null,paymentId:null};items=[item];pending=body.amountMinor;available=200000-pending;return reply({id:item.id},201);}if(path==="/dashboard/referrals/withdrawals/WDR-ABC234/cancel"&&request.method()==="POST"){items=[{...items[0],status:"CANCELLED",cancelledAt:"2026-09-29T11:00:00Z"}];pending=0;available=200000;return reply({id:"WDR-ABC234",status:"CANCELLED"});}return route.abort();});
  const page=await context.newPage(),errors=[];page.on("pageerror",error=>errors.push(error.message));page.setDefaultNavigationTimeout(60000);await page.setViewportSize({width:1440,height:950});await page.goto(`${origin}/dashboard/referrals/withdraw`);await page.getByRole("heading",{name:"Withdraw Earnings"}).waitFor();assert.match(await page.locator(".withdrawal-balance>strong").innerText(),/2,000\.00/);assert.equal(await page.getByText("••••••6789").count(),1);await page.getByLabel("Withdrawal amount").fill("123456");assert.equal(await page.getByLabel("Withdrawal amount").inputValue(),"123,456");for(const[value,expected]of [[25,"500.00"],[50,"1,000.00"],[75,"1,500.00"],[100,"2,000.00"]]){await page.getByRole("button",{name:`${value}%`}).click();assert.equal(await page.getByLabel("Withdrawal amount").inputValue(),expected);}await page.getByRole("button",{name:"25%"}).click();await page.getByRole("button",{name:"Submit Withdrawal Request"}).click();await page.getByText("WDR-ABC234").waitFor();assert.equal(calls.length,1);assert.equal(calls[0].amountMinor,50000);assert.equal("amountMinor" in calls[0],true);assert.equal("referrerId" in calls[0],false);await page.getByRole("button",{name:"Cancel",exact:true}).click();await page.getByText("CANCELLED",{exact:true}).waitFor();
  for(const width of [1440,1280,1024,768,430,390,360]){await page.setViewportSize({width,height:900});await page.goto(`${origin}/dashboard/referrals/withdraw`);await page.getByRole("heading",{name:"Withdraw Earnings"}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`withdrawal overflow at ${width}`);if(width<=800)assert.equal(await page.getByRole("button",{name:/Menu/}).isVisible(),true);}
  assert.deepEqual(errors,[]);await browser.close();console.log("Customer withdrawal UI: amount formatting, quick select, submit/cancel, real history, and 7 responsive widths passed");
}finally{server.kill();}
