import assert from "node:assert/strict";
import { runIfMain } from "./run-ui-suite.mjs";
import { dashboardFixture } from "./dashboard-ui.checks.mjs";
runIfMain(import.meta.url,"settings");
export const settingsState={profile:{firstName:"Ada",lastName:"Okafor",email:"ada@example.test",countryCode:"+234",phoneNumber:"8012345678",accountType:"INVESTOR",briefBio:"Property investor",accountName:"Ada Okafor",bankName:"Beryl Bank",accountNumber:"1234567890",streetAddress:"1 Beryl Road",zipCode:"100001",city:"Ikeja",state:"Lagos",country:"Nigeria",profileImageUrl:null}};
export function settingsRequestBody(request){const raw=request.postData()??"";if(!request.headers()["content-type"]?.startsWith("multipart/form-data"))return request.postDataJSON();const data=raw.match(/name="data"\r\n\r\n([^]*?)\r\n--/),mime=raw.match(/name="profileImage"[^]*?Content-Type: ([^\r\n]+)/i);return {...JSON.parse(data?.[1]??"{}"),_hasImage:raw.includes('name="profileImage"'),_imageMime:mime?.[1]};}
export function settingsResponse(method,body){if(method==="GET")return structuredClone(settingsState.profile);const {_hasImage,_imageMime,...data}=body,extension=_imageMime==="image/png"?"png":_imageMime==="image/jpeg"?"jpg":"webp";Object.assign(settingsState.profile,data,_hasImage?{profileImageUrl:`https://images.example.test/profile.${extension}`}:{ });dashboardFixture.customer.profile_image_url=settingsState.profile.profileImageUrl;return structuredClone(settingsState.profile);}
export async function checkSettings({page,origin,calls,failures,screenshot,passed,pauseRequest,resume,toast}){
  const endpoint="/dashboard/settings/profile",ready=()=>page.getByRole("heading",{name:"Personal Information",exact:true}).waitFor(),open=async()=>{await page.goto(origin+"/dashboard/settings");await ready();await page.evaluate(()=>document.fonts.ready);};
  for(const width of [1440,1280,1024,768,390,320]){await page.setViewportSize({width,height:1000});await open();assert.equal(await page.getByRole("heading",{name:"Account Settings",level:1}).count(),1);assert.deepEqual(await page.getByRole("tab").allTextContents(),["Profile","Password","Business"]);assert.equal(await page.getByRole("tab",{name:"Profile"}).getAttribute("aria-selected"),"true");assert.equal(await page.getByRole("tab",{name:"Password"}).isDisabled(),true);assert.equal(await page.getByRole("tab",{name:"Business"}).isDisabled(),true);assert.equal(await page.getByRole("link",{name:"Verify Account"}).count(),1);for(const heading of ["Personal Information","Profile Picture *","Account Information","Address"])assert.equal(await page.getByRole("heading",{name:heading,exact:true}).count(),1);assert.equal(await page.locator(".settings-identity .settings-avatar").count(),1);assert.equal(await page.locator(".settings-identity strong").textContent(),"Investor");assert.equal(await page.getByLabel("Email Address").isEditable(),false);assert.equal(await page.getByLabel("First Name *").inputValue(),"Ada");assert.equal(await page.getByLabel("Account Number").inputValue(),"1234567890");assert.equal(await page.getByLabel("Street Address *").inputValue(),"1 Beryl Road");assert.equal(await page.locator('input[type="file"]').getAttribute("accept"),".png,.jpg,.jpeg,.webp,image/png,image/jpeg,image/webp");assert.equal(await page.getByText("PNG, JPG, WebP (max 2 MiB)",{exact:true}).count(),1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`Settings overflow at ${width}`);await screenshot(`settings-profile-${width}`);}
  passed.push("Profile reference layout, populated identity/private/address fields, active Profile tab, inert Password/Business labels and responsive stacking at six widths");
  assert.equal(await page.locator(".settings-avatar img").count(),0);assert.deepEqual(await page.locator(".settings-avatar").allTextContents(),["AO","AO"]);assert.notEqual(await page.locator(".settings-avatar").first().evaluate(element=>getComputedStyle(element).backgroundColor),"rgba(0, 0, 0, 0)");
  await page.setViewportSize({width:1440,height:1000});await open();const writes=()=>calls.filter(call=>call.endpoint===endpoint&&call.method==="PATCH"),before=writes().length;await page.getByLabel("First Name *").fill("Unsaved");await page.getByRole("button",{name:"Cancel",exact:true}).click();assert.equal(await page.getByLabel("First Name *").inputValue(),"Ada");assert.equal(writes().length,before);await page.getByLabel("First Name *").fill("Amara");await page.getByRole("button",{name:"Save Changes",exact:true}).click();await toast("Profile updated successfully");assert.equal(settingsState.profile.firstName,"Amara");
  for(const image of [{name:"profile.png",mimeType:"image/png",buffer:Buffer.from("89504e470d0a1a0a","hex"),extension:"png"},{name:"profile.jpg",mimeType:"image/jpeg",buffer:Buffer.from("ffd8ffdb","hex"),extension:"jpg"},{name:"profile.webp",mimeType:"image/webp",buffer:Buffer.from("RIFF0000WEBP0"),extension:"webp"}]){await page.locator('input[type="file"]').setInputFiles(image);await page.getByRole("button",{name:"Save Changes",exact:true}).click();await toast("Profile updated successfully");assert.equal(writes().at(-1).body._imageMime,image.mimeType);assert.match(settingsState.profile.profileImageUrl,new RegExp(`profile\\.${image.extension}$`));}
  failures.set(endpoint,{status:400,code:"INVALID_PROFILE_IMAGE",message:"Profile image must be PNG, JPEG, or WebP."});await page.locator('input[type="file"]').setInputFiles({name:"profile.svg",mimeType:"image/svg+xml",buffer:Buffer.from("<svg/>")});await page.getByLabel("Last Name *").fill("Preserved");await page.getByRole("button",{name:"Save Changes",exact:true}).click();await toast("Profile image must be PNG, JPEG, or WebP.");assert.equal(await page.getByText("profile.svg",{exact:true}).count(),1);assert.equal(await page.getByLabel("Last Name *").inputValue(),"Preserved");const errorToast=page.locator("#settings-profile-error");await errorToast.locator(".Toastify__close-button").click();await errorToast.waitFor({state:"detached"});await page.getByRole("button",{name:"Cancel",exact:true}).click();failures.delete(endpoint);passed.push("Cancel avoids mutation; text and PNG/JPEG/WebP saves succeed; unsupported-image errors preserve drafts");
  assert.equal(await page.locator(".settings-avatar img").count(),2);assert.equal(await page.locator(".settings-avatar").first().evaluate(element=>getComputedStyle(element).backgroundColor),"rgba(0, 0, 0, 0)");assert.equal(await page.locator(".settings-avatar img").first().evaluate(element=>getComputedStyle(element).objectFit),"cover");await page.locator(".dashboard-avatar img").waitFor();assert.match(await page.locator(".dashboard-avatar img").getAttribute("src"),/profile\.webp$/);passed.push("Transparent profile images replace initials without a fallback background and refresh the shared sidebar avatar");
  const observed=pauseRequest(endpoint),navigation=page.goto(origin+"/dashboard/settings");await observed;assert.equal(await page.getByRole("status",{name:"Loading"}).count(),1);resume();await navigation;await ready();passed.push("Initial profile loading state remains visible until the profile request resolves");
  failures.set(endpoint,{status:503,code:"SETTINGS_UNAVAILABLE",message:"Settings are temporarily unavailable. Please try again."});await page.goto(origin+"/dashboard/settings");await page.getByRole("button",{name:"Try again"}).waitFor();await toast("Settings are temporarily unavailable. Please try again.");failures.delete(endpoint);await page.getByRole("button",{name:"Try again"}).click();await ready();passed.push("Profile load failure exposes a working retry state");
  failures.set(endpoint,{status:401,code:"AUTH_REQUIRED",message:"Please sign in again."});await page.goto(origin+"/dashboard/settings");await page.waitForURL(origin+"/login");failures.delete(endpoint);passed.push("Expired profile session returns the customer to login");
}
