import { AuthApiError } from "./auth-api";
export type SettingsProfile={firstName:string;lastName:string;email:string;countryCode:string|null;phoneNumber:string;accountType:string|null;briefBio:string;accountName:string;bankName:string;accountNumber:string;streetAddress:string;zipCode:string;city:string;state:string;country:string;profileImageUrl:string|null};
export type SettingsBusiness={companyId:string;companyName:string;companyEmail:string;companyPhoneNumber:string;aboutCompany:string;companyLogoUrl:string|null;streetAddress:string;zipCode:string;city:string;state:string;country:string};
const base=()=>{const value=process.env.NEXT_PUBLIC_API_BASE_URL;if(!value)throw new AuthApiError("CONFIGURATION_UNAVAILABLE","Settings services are not configured.");return value.replace(/\/$/,"");};
async function parse<T>(response:Response){let payload:{success:boolean;data:T;error?:{code:string;message:string}};try{payload=await response.json();}catch{throw new AuthApiError("INVALID_RESPONSE","Settings are temporarily unavailable. Please try again.");}if(!response.ok||!payload.success)throw new AuthApiError(payload.error?.code??"SETTINGS_UNAVAILABLE",payload.error?.message??"Settings are temporarily unavailable. Please try again.",response.status);return payload.data;}
export async function fetchSettingsProfile(signal:AbortSignal){return parse<SettingsProfile>(await fetch(`${base()}/api/v1/dashboard/settings/profile`,{credentials:"include",cache:"no-store",signal}));}
export async function saveSettingsProfile(value:SettingsProfile,file?:File){const body={firstName:value.firstName,lastName:value.lastName,phoneNumber:value.phoneNumber,briefBio:value.briefBio,accountName:value.accountName,bankName:value.bankName,accountNumber:value.accountNumber,streetAddress:value.streetAddress,zipCode:value.zipCode,city:value.city,state:value.state,country:value.country};let requestBody:BodyInit,headers:HeadersInit|undefined;if(file){const form=new FormData();form.set("data",JSON.stringify(body));form.set("profileImage",file);requestBody=form;}else{requestBody=JSON.stringify(body);headers={"Content-Type":"application/json"};}return parse<SettingsProfile>(await fetch(`${base()}/api/v1/dashboard/settings/profile`,{method:"PATCH",credentials:"include",body:requestBody,...(headers?{headers}:{})}));}
export async function changeSettingsPassword(oldPassword:string,newPassword:string,confirmNewPassword:string){const response=await fetch(`${base()}/api/v1/dashboard/settings/password`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({oldPassword,newPassword,confirmNewPassword})});let payload:{success:boolean;data?:{reauthenticate:boolean};error?:{code:string;message:string}};try{payload=await response.json();}catch{throw new AuthApiError("INVALID_RESPONSE","Settings are temporarily unavailable. Please try again.");}if(!response.ok||!payload.success)throw new AuthApiError(payload.error?.code??"SETTINGS_UNAVAILABLE",payload.error?.message??"Settings are temporarily unavailable. Please try again.",response.status);return payload.data;}
export async function fetchSettingsBusiness(signal:AbortSignal){return parse<SettingsBusiness>(await fetch(`${base()}/api/v1/dashboard/settings/business`,{credentials:"include",cache:"no-store",signal}));}
export async function saveSettingsBusiness(value:SettingsBusiness,file?:File){const body={companyName:value.companyName,companyEmail:value.companyEmail,companyPhoneNumber:value.companyPhoneNumber,aboutCompany:value.aboutCompany,streetAddress:value.streetAddress,zipCode:value.zipCode,city:value.city,state:value.state,country:value.country};let requestBody:BodyInit,headers:HeadersInit|undefined;if(file){const form=new FormData();form.set("data",JSON.stringify(body));form.set("companyLogo",file);requestBody=form;}else{requestBody=JSON.stringify(body);headers={"Content-Type":"application/json"};}return parse<SettingsBusiness>(await fetch(`${base()}/api/v1/dashboard/settings/business`,{method:"PATCH",credentials:"include",body:requestBody,...(headers?{headers}:{})}));}
