import { Feather } from "@expo/vector-icons";
import { useInfiniteQuery } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { listSellerProperties } from "@/api/seller-marketplace";
import { SellerHeader, SellerPage, SellerState } from "@/components/seller-marketplace/seller-ui";
import { formatNaira } from "@/marketplace/filters";
import { sellerRoute, sellerSteps, sellerTabs, stepSlug } from "@/seller-marketplace/helpers";
import { useCustomerSession } from "@/store/auth-flow";
import { colors, radii, spacing } from "@/theme/tokens";
import type { SellerStatus, SellerSummary } from "@/types/seller-marketplace";
const badgeColor=(status:string)=>status==="LIVE"?colors.success:status==="REJECTED"?colors.danger:status==="IN_REVIEW"?"#c87818":colors.muted;
function ListingRow({item,onOpen}:{item:SellerSummary;onOpen:()=>void}){const step=Math.max(0,sellerSteps.indexOf(item.currentStep??"PROPERTY_INFORMATION"));return <Pressable accessibilityRole="button" accessibilityLabel={`Open ${item.title??"Untitled Listing"}`} onPress={onOpen} style={s.row}>{item.coverImage?.url?<Image source={{uri:item.coverImage.url}} style={s.thumb}/>:<View style={s.thumbFallback}><Feather name="home" size={25} color={colors.brown}/></View>}<View style={s.body}><Text style={[s.badge,{color:badgeColor(item.status),borderColor:badgeColor(item.status)}]}>{item.status.replace("_"," ")}</Text><Text numberOfLines={2} style={s.title}>{item.title??"Untitled Listing"}</Text>{item.askingPrice!==null?<Text style={s.price}>{formatNaira(item.askingPrice)}</Text>:null}{item.status==="IN_REVIEW"&&item.submittedAt?<Text style={s.meta}>Submitted {new Date(item.submittedAt).toLocaleDateString()}</Text>:null}</View><Feather name="more-horizontal" size={21} color={colors.ink}/>{item.status==="DRAFT"?<View style={s.progress}><Text style={s.progressText}>Step {step+1} of 4: {item.currentStep?.replaceAll("_"," ")}</Text><View style={s.progressLine}>{sellerSteps.map((value,index)=><View key={value} style={[s.segment,index<=step&&s.segmentOn]}/>)}</View><Text style={s.continue}>Continue</Text></View>:null}</Pressable>}
export function SellerListingsScreen(){const router=useRouter();const session=useCustomerSession();const[status,setStatus]=useState<SellerStatus>("ALL");const query=useInfiniteQuery({queryKey:["mobile-seller-listings",status],initialPageParam:1,enabled:session.isAuthenticated,queryFn:({pageParam})=>listSellerProperties(session.authenticatedRequest,status,pageParam),getNextPageParam:last=>{const p=last.data?.pagination;return p&&p.page<p.total_pages?p.page+1:undefined}});const data=query.data?.pages[0]?.data;const items=useMemo(()=>{const map=new Map<string,SellerSummary>();query.data?.pages.forEach(page=>page.data?.items.forEach(item=>map.set(item.id,item)));return [...map.values()]},[query.data]);const load=()=>{if(query.hasNextPage&&!query.isFetchingNextPage)void query.fetchNextPage()};const tabs=<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{sellerTabs.map(tab=><Pressable key={tab.status} accessibilityRole="tab" accessibilityLabel={`${tab.label}, ${data?.counts[tab.count]??0}`} accessibilityState={{selected:status===tab.status}} onPress={()=>setStatus(tab.status)} style={[s.tab,status===tab.status&&s.tabOn]}><Text style={[s.tabText,status===tab.status&&s.tabTextOn]}>{tab.label} {data?.counts[tab.count]??0}</Text></Pressable>)}</ScrollView>;return <SellerPage><SellerHeader title="My Listings" action={<Pressable accessibilityRole="button" onPress={()=>router.push("/seller/listings/new")} style={s.add}><Feather name="plus" size={19} color={colors.brown}/><Text style={s.addText}>List property</Text></Pressable>}/>{tabs}<FlatList data={items} keyExtractor={item=>item.id} contentContainerStyle={s.list} renderItem={({item})=><ListingRow item={item} onOpen={()=>router.push(sellerRoute(item.nextAction,item.id))}/>} onEndReached={load} onEndReachedThreshold={.4} ListEmptyComponent={query.isLoading?<SellerState label="Loading your listings"/>:query.isError?<SellerState error="We could not load your listings." onRetry={()=>void query.refetch()}/>:<SellerState error="No listings in this section."/>} ListFooterComponent={query.isFetchingNextPage?<ActivityIndicator color={colors.brown}/>:null}/></SellerPage>}
const s=StyleSheet.create({add:{minHeight:44,borderWidth:1,borderColor:colors.brown,borderRadius:10,paddingHorizontal:10,flexDirection:"row",alignItems:"center",gap:5},addText:{fontSize:12,fontWeight:"800",color:colors.brown},tabs:{paddingHorizontal:spacing.md,paddingVertical:12,gap:8},tab:{minHeight:42,borderWidth:1,borderColor:colors.line,borderRadius:radii.pill,paddingHorizontal:14,alignItems:"center",justifyContent:"center"},tabOn:{borderColor:colors.brown,backgroundColor:colors.cream},tabText:{fontSize:12,fontWeight:"700",color:colors.muted},tabTextOn:{color:colors.brown},list:{padding:spacing.md,paddingBottom:spacing.xxl},row:{marginBottom:18,minHeight:118,borderBottomWidth:1,borderBottomColor:colors.line,paddingBottom:16,flexDirection:"row",alignItems:"flex-start",gap:12,position:"relative"},thumb:{width:112,height:112,borderRadius:12},thumbFallback:{width:112,height:112,borderRadius:12,alignItems:"center",justifyContent:"center",backgroundColor:colors.field},body:{flex:1,minWidth:0},badge:{alignSelf:"flex-start",borderWidth:1,borderRadius:radii.pill,paddingHorizontal:8,paddingVertical:3,fontSize:10,fontWeight:"900"},title:{marginTop:6,fontSize:14,lineHeight:19,fontWeight:"800",color:colors.ink},price:{marginTop:7,fontSize:15,fontWeight:"900",color:colors.ink},meta:{marginTop:5,fontSize:10,color:colors.muted},progress:{position:"absolute",left:0,right:0,top:124,borderWidth:1,borderColor:colors.brown,borderRadius:10,padding:10,backgroundColor:colors.canvas},progressText:{fontSize:10,color:colors.brown},progressLine:{marginTop:8,marginRight:90,flexDirection:"row",gap:4},segment:{height:4,flex:1,backgroundColor:colors.line},segmentOn:{backgroundColor:colors.brown},continue:{position:"absolute",right:12,top:17,fontWeight:"800",color:colors.brown}});
