import { Feather } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useRef, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import { createSellerDraft } from "@/api/seller-marketplace";
import { SellerHeader, SellerPage } from "@/components/seller-marketplace/seller-ui";
import { useCustomerSession } from "@/store/auth-flow";
import { colors, radii, spacing } from "@/theme/tokens";
const steps=[['home','Tell us about the property','Add title, description, location, price and the details buyers generally ask about.'],['image','Add photos & documents','Add up to 10 photos. Good ones get far more interest.'],['file-text','Agree the sales mandate',"Choose how you'd like Beryl to market it, then confirm."],['check-circle','Review and submit','See it exactly as buyers will, then send it to our team to verify.']] as const;
export function SellerIntroScreen(){const router=useRouter();const session=useCustomerSession();const creating=useRef<Promise<string>|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const start=async()=>{if(creating.current)return;setBusy(true);setError("");creating.current=createSellerDraft(session.authenticatedRequest,{}).then(result=>{const id=result.data?.property.id;if(!id)throw new Error("Draft was not returned");return id});try{const id=await creating.current;router.replace(`/seller/listings/${id}/edit?step=property-information`)}catch{setError("We could not start your listing. Please try again.");creating.current=null}finally{setBusy(false)}};return <SellerPage><SellerHeader onBack={()=>router.replace("/seller/listings")}/><View style={s.content}><Text accessibilityRole="header" style={s.title}>Listing your property is straightforward</Text><View style={s.steps}>{steps.map(([icon,title,copy],index)=><View key={title} style={s.row}><View style={s.number}><Text style={s.numberText}>{index+1}</Text></View><View style={s.body}><Text style={s.stepTitle}>{title}</Text><Text style={s.copy}>{copy}</Text></View><Feather name={icon} size={25} color={colors.brown}/></View>)}</View>{error?<Text accessibilityLiveRegion="polite" style={s.error}>{error}</Text>:null}<Pressable accessibilityRole="button" accessibilityState={{disabled:busy}} disabled={busy} onPress={()=>void start()} style={s.button}>{busy?<ActivityIndicator color={colors.white}/>:<Text style={s.buttonText}>Get Started</Text>}</Pressable><Text style={s.note}>Your progress saves as you go. You can come back anytime.</Text></View></SellerPage>}
const s=StyleSheet.create({content:{flex:1,padding:spacing.lg},title:{marginTop:20,fontSize:26,lineHeight:34,fontWeight:"900",color:colors.ink},steps:{marginTop:34,gap:25},row:{flexDirection:"row",alignItems:"flex-start",gap:12},number:{width:34,height:34,borderRadius:17,alignItems:"center",justifyContent:"center",backgroundColor:colors.cream},numberText:{fontWeight:"900",color:colors.brown},body:{flex:1},stepTitle:{fontSize:15,fontWeight:"900",color:colors.ink},copy:{marginTop:4,fontSize:13,lineHeight:19,color:colors.muted},button:{marginTop:"auto",minHeight:56,borderRadius:radii.pill,paddingHorizontal:24,alignItems:"center",justifyContent:"center",backgroundColor:colors.brown},buttonText:{fontSize:16,fontWeight:"800",color:colors.white},note:{marginTop:12,textAlign:"center",fontSize:11,color:colors.muted},error:{marginTop:18,borderRadius:radii.control,padding:12,color:colors.white,backgroundColor:colors.danger}});
