import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { Button, Card, Screen, SectionHeading, TextField } from "@/components/ui";
import { authApi, type Registration } from "@/lib/auth-api";
import { friendlyError } from "@/lib/api-error";
import { colors, radius, spacing, typography } from "@/theme/tokens";

const accountTypes: [Registration["accountType"],string][]=[["INVESTOR","Investor"],["PROPERTY_DEVELOPER","Property Developer"],["LANDLORD","Landlord"],["REGISTERED_AGENT","Registered Agent"],["FREELANCE_AGENT","Freelance Agent"]];
export default function RegisterScreen(){const [form,setForm]=useState<Registration>({firstName:"",lastName:"",email:"",countryCode:"+234",phoneNumber:"",accountType:"INVESTOR",profileType:"PERSONAL",password:"",confirmPassword:""});const [error,setError]=useState("");const [loading,setLoading]=useState(false);const field=<K extends keyof Registration>(key:K,value:Registration[K])=>setForm(current=>({...current,[key]:value}));
  async function submit(){setError("");if(form.password!==form.confirmPassword){setError("Passwords do not match.");return;}setLoading(true);try{await authApi.register(form);router.push("/(auth)/verify-email");}catch(failure){setError(friendlyError(failure));}finally{setLoading(false);}}
  return <Screen keyboard><SectionHeading title="Create your customer account" description="Your account can use Buyer, Seller and Referrer features as your activity grows."/><Card><TextField label="First name" autoComplete="given-name" value={form.firstName} onChangeText={value=>field("firstName",value)}/><TextField label="Last name" autoComplete="family-name" value={form.lastName} onChangeText={value=>field("lastName",value)}/><TextField label="Email" autoCapitalize="none" autoComplete="email" keyboardType="email-address" value={form.email} onChangeText={value=>field("email",value)}/><TextField label="Country code" keyboardType="phone-pad" value={form.countryCode} onChangeText={value=>field("countryCode",value)}/><TextField label="Phone number" keyboardType="phone-pad" value={form.phoneNumber} onChangeText={value=>field("phoneNumber",value)}/><Text style={styles.label}>Account type</Text><View style={styles.choices}>{accountTypes.map(([value,label])=><Choice key={value} label={label} selected={form.accountType===value} onPress={()=>field("accountType",value)}/>)}</View><Text style={styles.label}>Profile type</Text><View style={styles.choices}><Choice label="Personal" selected={form.profileType==="PERSONAL"} onPress={()=>field("profileType","PERSONAL")}/><Choice label="Business" selected={form.profileType==="BUSINESS"} onPress={()=>field("profileType","BUSINESS")}/></View><TextField label="Password" secureTextEntry autoComplete="new-password" value={form.password} onChangeText={value=>field("password",value)}/><TextField label="Confirm password" secureTextEntry autoComplete="new-password" value={form.confirmPassword} onChangeText={value=>field("confirmPassword",value)} error={error||undefined}/><Button label="Create account" loading={loading} onPress={()=>void submit()}/></Card></Screen>;
}
function Choice({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <Pressable accessibilityRole="radio" accessibilityState={{checked:selected}} onPress={onPress} style={[styles.choice,selected&&styles.selected]}><Text style={[styles.choiceText,selected&&styles.selectedText]}>{label}</Text></Pressable>}
const styles=StyleSheet.create({label:{...typography.label,color:colors.text},choices:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm},choice:{minHeight:44,justifyContent:"center",borderRadius:radius.pill,borderWidth:1,borderColor:colors.border,paddingHorizontal:spacing.md,backgroundColor:colors.surface},selected:{backgroundColor:colors.action,borderColor:colors.action},choiceText:{...typography.caption,color:colors.text,fontWeight:"600"},selectedText:{color:colors.actionText}});
