import { Feather, MaterialCommunityIcons } from "@expo/vector-icons";
import { useInfiniteQuery, useQuery } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { ActivityIndicator, Modal, Pressable, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { getReferralDashboard, getReferralPayout } from "@/api/referrals";
import { CopyReferralLink, ReferralAlert, ReferralBack, ReferralButton, ReferralPage, ReferralState } from "@/components/referrals/referral-ui";
import { formatReferralDate, formatReferralMoney, paymentLabel, purposeLabel, referralErrorMessage, referralInitials, referralRoutes, referralStatus } from "@/referrals/helpers";
import { referralQueryKeys } from "@/referrals/query-keys";
import { useCustomerSession } from "@/store/auth-flow";
import { colors, radii, spacing } from "@/theme/tokens";
import type { ReferralDashboardItem, ReferralPayoutDetails } from "@/types/referrals";

export function ReferralDashboardScreen() {
  const router = useRouter(); const session = useCustomerSession(); const [payoutOpen, setPayoutOpen] = useState(false);
  const requester = session.isAuthenticated ? session.authenticatedRequest : undefined;
  const dashboard = useInfiniteQuery({ queryKey: referralQueryKeys.dashboard(session.isAuthenticated), enabled: !session.isHydrating, initialPageParam: 1, retry: false, queryFn: ({ pageParam }) => getReferralDashboard(requester, pageParam), getNextPageParam: (last) => { const pagination = last.data?.pagination; return pagination && pagination.page < pagination.totalPages ? pagination.page + 1 : undefined; } });
  const payout = useQuery({ queryKey: referralQueryKeys.payout(session.isAuthenticated), enabled: !session.isHydrating, retry: false, queryFn: () => getReferralPayout(requester) });
  const first = dashboard.data?.pages[0]?.data; const items = useMemo(() => { const values = new Map<string, ReferralDashboardItem>(); dashboard.data?.pages.forEach((page) => page.data?.referrals.forEach((item) => values.set(item.id, item))); return [...values.values()]; }, [dashboard.data]);
  const errorCode = (dashboard.error as { code?: string } | null)?.code;
  if (session.isHydrating || dashboard.isLoading) return <ReferralPage background="#fff7da"><ReferralState loading title="Loading your referrals" copy="We’re gathering your referral progress and rewards."/></ReferralPage>;
  if (dashboard.isError || !first) return <ReferralPage background={colors.canvas}><ReferralBack/><ReferralState title={errorCode === "REFERRAL_SESSION_REQUIRED" ? "Verify to see your referrals" : "We could not load your referrals"} copy={errorCode === "REFERRAL_SESSION_REQUIRED" ? "Use the phone number you referred with to securely open your referral dashboard." : referralErrorMessage(errorCode)} onRetry={errorCode === "REFERRAL_SESSION_REQUIRED" ? () => router.replace(referralRoutes.tracking) : () => void dashboard.refetch()}/></ReferralPage>;
  const details = payout.data?.data?.payoutDetails ?? null;
  return <ReferralPage background="#fff1be">
    <View style={styles.header}><ReferralBack/><View style={styles.headerCopy}><Text accessibilityRole="header" style={styles.headerTitle}>Your referrals</Text><Text numberOfLines={1} style={styles.headerName}>{first.referrer.fullName}</Text></View><Pressable accessibilityRole="button" onPress={() => router.push(referralRoutes.newReferral)} style={styles.referButton}><Feather name="plus" size={18} color={colors.white}/><Text style={styles.referText}>Refer</Text></Pressable></View>
    <Pressable accessibilityRole="button" onPress={() => details ? setPayoutOpen(true) : router.push(referralRoutes.bankDetails)} style={styles.bankBanner}><MaterialCommunityIcons name="bank-outline" size={26} color={colors.brown}/><View style={styles.bankCopy}><Text style={styles.bankTitle}>{details ? "Check your payment details" : `Add your bank details, ${first.referrer.fullName.split(/\s+/)[0]}`}</Text>{!details ? <Text style={styles.bankDetail}>You&apos;ve earned a reward. We need your account to pay it</Text> : null}</View><Feather name="chevron-right" size={22} color={colors.brown}/></Pressable>
    <View style={styles.summary}><Text style={styles.summaryLabel}>Commission earned</Text><Text style={styles.amount}>{formatReferralMoney(first.summary.earnedAmount)}</Text><Text style={styles.linkLabel}>Copy and share your referral link</Text><CopyReferralLink value={first.referrer.referralLink}/></View>
    <View style={styles.list}>{items.length ? items.map((item) => <ReferralRow key={item.id} item={item}/>) : <View style={styles.empty}><Feather name="users" size={30} color={colors.brown}/><Text style={styles.emptyTitle}>No referrals yet</Text><Text style={styles.emptyCopy}>Share your link or refer someone directly to get started.</Text><ReferralButton label="Refer someone" onPress={() => router.push(referralRoutes.newReferral)}/></View>}
      {dashboard.hasNextPage ? <ReferralButton outline label={dashboard.isFetchingNextPage ? "Loading more…" : "Load more referrals"} disabled={dashboard.isFetchingNextPage} onPress={() => void dashboard.fetchNextPage()}/> : null}{dashboard.isFetchingNextPage ? <ActivityIndicator accessibilityLabel="Loading more referrals" color={colors.brown}/> : null}
      {dashboard.isRefetching && !dashboard.isFetchingNextPage ? <Text accessibilityLiveRegion="polite" style={styles.refreshing}>Refreshing referrals…</Text> : null}
    </View>
    <ReferralAlert message={payout.isError ? referralErrorMessage((payout.error as { code?: string }).code) : undefined} tone="info"/>
    {details ? <PayoutDetailsModal visible={payoutOpen} details={details} onClose={() => setPayoutOpen(false)} onChange={() => { setPayoutOpen(false); router.push(referralRoutes.bankDetails); }}/> : null}
  </ReferralPage>;
}

function ReferralRow({ item }: { item: ReferralDashboardItem }) {
  const state = referralStatus(item.status); const paid = item.paymentStatus === "PAID";
  return <View style={styles.row}><View style={styles.avatar}><Text style={styles.avatarText}>{referralInitials(item.referredName)}</Text></View><View style={styles.rowBody}><View style={styles.rowTop}><Text numberOfLines={2} style={styles.name}>{item.referredName}</Text><View style={[styles.badge, state.tone === "complete" && styles.badgeComplete, state.tone === "progress" && styles.badgeProgress, state.tone === "lost" && styles.badgeLost]}><Text style={[styles.badgeText, state.tone === "complete" && styles.badgeCompleteText, state.tone === "progress" && styles.badgeProgressText, state.tone === "lost" && styles.badgeLostText]}>• {state.label}</Text></View></View><Text style={styles.meta}>{item.referenceId} · {purposeLabel(item.purpose)} · {formatReferralDate(item.submittedAt)}</Text>{state.message ? <Text style={styles.message}>{state.message}</Text> : null}{item.rewardAmount !== null ? <View style={styles.reward}><View><Text style={styles.rewardLabel}>Your Reward</Text><Text style={styles.rewardAmount}>{formatReferralMoney(item.rewardAmount)}</Text></View><View style={[styles.payment, paid && styles.paymentPaid]}><Text style={[styles.paymentText, paid && styles.paymentPaidText]}>• {paymentLabel(item.paymentStatus)}</Text></View></View> : null}</View></View>;
}

function PayoutDetailsModal({ visible, details, onClose, onChange }: { visible: boolean; details: NonNullable<ReferralPayoutDetails["payoutDetails"]>; onClose: () => void; onChange: () => void }) {
  return <Modal transparent visible={visible} animationType="slide" onRequestClose={onClose}><SafeAreaView style={styles.modalSafe}><Pressable accessibilityRole="button" accessibilityLabel="Close payment details" onPress={onClose} style={styles.backdrop}/><View accessibilityViewIsModal style={styles.modal}><View style={styles.modalHeading}><Text accessibilityRole="header" style={styles.modalTitle}>Payment Details</Text><Pressable accessibilityRole="button" accessibilityLabel="Close payment details" onPress={onClose} style={styles.modalClose}><Feather name="x" size={23} color={colors.brown}/></Pressable></View><View style={styles.detailCard}><View style={styles.detailRow}><View><Text style={styles.detailLabel}>Account Name</Text><Text style={styles.detailValue}>{details.accountName}</Text></View><Pressable accessibilityRole="button" onPress={onChange} style={styles.change}><Feather name="edit-2" size={14} color={colors.brown}/><Text style={styles.changeText}>Change</Text></Pressable></View><View style={styles.detailRow}><View><Text style={styles.detailLabel}>Bank</Text><Text style={styles.detailValue}>{details.bankName}</Text></View></View><View style={styles.detailRow}><View><Text style={styles.detailLabel}>Account Number</Text><Text style={styles.detailValue}>{details.maskedAccountNumber}</Text></View></View></View></View></SafeAreaView></Modal>;
}

const styles = StyleSheet.create({
  header: { minHeight: 58, flexDirection: "row", alignItems: "center", gap: 7 }, headerCopy: { flex: 1, minWidth: 0 }, headerTitle: { fontSize: 20, fontWeight: "900", color: colors.ink }, headerName: { marginTop: 1, fontSize: 12, color: colors.ink }, referButton: { minHeight: 40, borderRadius: 8, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 5, backgroundColor: "#a2751d" }, referText: { fontWeight: "800", color: colors.white },
  bankBanner: { marginHorizontal: -8, marginTop: 8, borderRadius: radii.control, padding: 16, minHeight: 76, flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: "#fffaf0" }, bankCopy: { flex: 1, minWidth: 0 }, bankTitle: { fontSize: 13, lineHeight: 18, fontWeight: "800", color: colors.brown }, bankDetail: { marginTop: 3, fontSize: 12, lineHeight: 17, color: colors.ink },
  summary: { marginHorizontal: -8, marginTop: 13, borderRadius: radii.card, padding: 20, backgroundColor: colors.white }, summaryLabel: { fontSize: 13, color: colors.muted }, amount: { marginTop: 3, fontSize: 27, fontWeight: "900", color: colors.brown }, linkLabel: { marginTop: 19, marginBottom: 8, fontSize: 11, color: colors.muted }, list: { marginHorizontal: -spacing.lg, marginTop: 16, paddingHorizontal: spacing.lg, paddingTop: 20, paddingBottom: spacing.xl, gap: 14, backgroundColor: colors.white },
  row: { paddingHorizontal: 4, paddingVertical: 10, flexDirection: "row", alignItems: "flex-start", gap: 12 }, avatar: { width: 44, height: 44, borderRadius: 22, alignItems: "center", justifyContent: "center", backgroundColor: colors.field }, avatarText: { fontSize: 17, color: colors.ink }, rowBody: { flex: 1, minWidth: 0 }, rowTop: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 7 }, name: { flex: 1, minWidth: 0, fontSize: 14, lineHeight: 19, fontWeight: "800", color: colors.ink }, badge: { flexShrink: 0, maxWidth: "46%", borderWidth: 1, borderColor: "#1768cf", borderRadius: radii.pill, paddingHorizontal: 8, paddingVertical: 2 }, badgeText: { flexShrink: 1, fontSize: 10, color: "#1768cf" }, badgeComplete: { borderColor: colors.success }, badgeCompleteText: { color: colors.success }, badgeProgress: { borderColor: "#d66b10" }, badgeProgressText: { color: "#d66b10" }, badgeLost: { borderColor: colors.muted }, badgeLostText: { color: colors.muted }, meta: { marginTop: 3, fontSize: 11, lineHeight: 16, color: colors.ink }, message: { marginTop: 7, fontSize: 11, lineHeight: 16, color: colors.muted }, reward: { marginTop: 12, borderRadius: 10, padding: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8, backgroundColor: "#fff7e7" }, rewardLabel: { fontSize: 10, color: colors.muted }, rewardAmount: { marginTop: 2, fontSize: 16, fontWeight: "900", color: "#a06f12" }, payment: { borderWidth: 1, borderColor: "#d66b10", borderRadius: radii.pill, paddingHorizontal: 8, paddingVertical: 3 }, paymentText: { fontSize: 10, color: "#d66b10" }, paymentPaid: { borderColor: colors.success }, paymentPaidText: { color: colors.success },
  empty: { minHeight: 260, padding: spacing.lg, gap: 8, alignItems: "center", justifyContent: "center" }, emptyTitle: { fontSize: 19, fontWeight: "900", color: colors.ink }, emptyCopy: { marginBottom: 10, textAlign: "center", fontSize: 12, lineHeight: 18, color: colors.muted }, refreshing: { textAlign: "center", fontSize: 11, color: colors.muted },
  modalSafe: { flex: 1, justifyContent: "flex-end" }, backdrop: { ...StyleSheet.absoluteFill, backgroundColor: "rgba(20,19,17,.42)" }, modal: { borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20, paddingBottom: 30, backgroundColor: colors.white }, modalHeading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, modalTitle: { fontSize: 19, fontWeight: "900", color: colors.ink }, modalClose: { width: 44, height: 44, alignItems: "center", justifyContent: "center" }, detailCard: { marginTop: 12, borderWidth: 1, borderColor: colors.line, borderRadius: radii.control, overflow: "hidden" }, detailRow: { minHeight: 72, padding: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: colors.line }, detailLabel: { fontSize: 11, color: colors.muted }, detailValue: { marginTop: 4, fontSize: 13, color: colors.ink }, change: { minHeight: 38, borderWidth: 1, borderColor: colors.brown, borderRadius: 8, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 6 }, changeText: { fontSize: 11, fontWeight: "800", color: colors.brown }
});
