import { Feather } from "@expo/vector-icons";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { getReferralBanks, getReferralPayout, saveReferralPayout } from "@/api/referrals";
import { ReferralAlert, ReferralBack, ReferralButton, ReferralPage, ReferralState } from "@/components/referrals/referral-ui";
import { referralErrorMessage, referralRoutes } from "@/referrals/helpers";
import { referralQueryKeys } from "@/referrals/query-keys";
import { referralPayoutSchema } from "@/referrals/schemas";
import { useCustomerSession } from "@/store/auth-flow";
import { colors, radii, sizes, spacing } from "@/theme/tokens";

export function ReferralBankDetailsScreen() {
  const router = useRouter(); const queryClient = useQueryClient(); const session = useCustomerSession();
  const requester = session.isAuthenticated ? session.authenticatedRequest : undefined;
  const banks = useQuery({ queryKey: referralQueryKeys.banks, queryFn: getReferralBanks });
  const payout = useQuery({ queryKey: referralQueryKeys.payout(session.isAuthenticated), enabled: !session.isHydrating, retry: false, queryFn: () => getReferralPayout(requester) });
  const [selectorOpen, setSelectorOpen] = useState(false); const [bankCode, setBankCode] = useState(""); const [accountNumber, setAccountNumber] = useState(""); const [accountName, setAccountName] = useState(""); const [error, setError] = useState("");
  const directory = banks.data?.data?.banks ?? []; const selected = directory.find((bank) => bank.code === bankCode);
  const save = useMutation({ retry: false, mutationFn: () => saveReferralPayout({ bankCode, accountNumber, accountName: accountName.trim() }, requester), onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: referralQueryKeys.payout(session.isAuthenticated) }), queryClient.invalidateQueries({ queryKey: referralQueryKeys.dashboard(session.isAuthenticated) })]); router.replace(referralRoutes.dashboard); }, onError: (next: { code?: string }) => setError(referralErrorMessage(next.code)) });
  const submit = () => { const parsed = referralPayoutSchema.safeParse({ bankCode, accountNumber, accountName }); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? "Check your account details"); return; } setError(""); save.mutate(); };
  if (banks.isLoading || payout.isLoading || session.isHydrating) return <ReferralPage><ReferralState loading title="Loading payment details" copy="Your secure bank form will be ready shortly."/></ReferralPage>;
  if (banks.isError) return <ReferralPage><ReferralBack/><ReferralState title="We could not load the bank list" copy={referralErrorMessage((banks.error as { code?: string }).code)} onRetry={() => void banks.refetch()}/></ReferralPage>;
  if (payout.isError) { const code = (payout.error as { code?: string }).code; return <ReferralPage><ReferralBack/><ReferralState title={code === "REFERRAL_SESSION_REQUIRED" ? "Verify before adding payment details" : "We could not load payment details"} copy={referralErrorMessage(code)} onRetry={code === "REFERRAL_SESSION_REQUIRED" ? () => router.replace(referralRoutes.tracking) : () => void payout.refetch()}/></ReferralPage>; }
  const existing = payout.data?.data?.payoutDetails;
  return <ReferralPage keyboard><ReferralBack/><Text accessibilityRole="header" style={styles.title}>Where should we pay you?</Text><Text style={styles.copy}>We&apos;ll transfer your rewards to this account. Only used for payouts.</Text>
    {existing ? <View style={styles.existing}><Text style={styles.existingLabel}>Current payment account</Text><Text style={styles.existingValue}>{existing.accountName} · {existing.bankName}</Text><Text style={styles.existingMasked}>{existing.maskedAccountNumber}</Text></View> : null}
    <Pressable accessibilityRole="button" accessibilityLabel="Select bank" onPress={() => setSelectorOpen(true)} style={styles.select}><Text style={selected ? styles.inputText : styles.placeholder}>{selected?.name ?? "Bank"}</Text><Feather name="chevron-down" size={20} color={colors.muted}/></Pressable>
    <TextInput accessibilityLabel="Account Number (10 Digits)" value={accountNumber} onChangeText={(value) => setAccountNumber(value.replace(/\D/g, "").slice(0, 10))} keyboardType="number-pad" maxLength={10} placeholder="Account Number (10 Digits)" placeholderTextColor={colors.inputPlaceholder} selectionColor={colors.selectionColor} cursorColor={colors.selectionColor} style={styles.input}/>
    <TextInput accessibilityLabel="Account Name" value={accountName} onChangeText={setAccountName} autoCapitalize="words" placeholder="Account Name" placeholderTextColor={colors.inputPlaceholder} selectionColor={colors.selectionColor} cursorColor={colors.selectionColor} style={styles.input}/>
    <View style={styles.privacy}><Feather name="shield" size={18} color="#1768cf"/><Text style={styles.privacyText}>Your details are stored securely and never shown to buyers, sellers or other referrers.</Text></View>
    <Text style={styles.manual}>Account name is entered manually. Automatic bank-name verification is not currently available.</Text><ReferralAlert message={error}/><ReferralButton label="Save account details" loading={save.isPending} onPress={submit}/>
    <BankSelector visible={selectorOpen} banks={directory} onClose={() => setSelectorOpen(false)} onSelect={(code) => { setBankCode(code); setSelectorOpen(false); setError(""); }}/>
  </ReferralPage>;
}

function BankSelector({ visible, banks, onClose, onSelect }: { visible: boolean; banks: { code: string; name: string }[]; onClose: () => void; onSelect: (code: string) => void }) {
  const [search, setSearch] = useState(""); const filtered = useMemo(() => banks.filter((bank) => bank.name.toLowerCase().includes(search.trim().toLowerCase())), [banks, search]);
  return <Modal transparent visible={visible} animationType="slide" onRequestClose={onClose}><SafeAreaView style={styles.modalSafe}><Pressable accessibilityRole="button" accessibilityLabel="Close bank selector" style={styles.backdrop} onPress={onClose}/><View accessibilityViewIsModal style={styles.sheet}><View style={styles.sheetHeading}><Text accessibilityRole="header" style={styles.sheetTitle}>Select your bank</Text><Pressable accessibilityRole="button" accessibilityLabel="Close bank selector" onPress={onClose} style={styles.close}><Feather name="x" size={23} color={colors.ink}/></Pressable></View><View style={styles.search}><Feather name="search" size={18} color={colors.muted}/><TextInput accessibilityLabel="Search supported banks" value={search} onChangeText={setSearch} placeholder="Search supported banks" placeholderTextColor={colors.inputPlaceholder} selectionColor={colors.selectionColor} cursorColor={colors.selectionColor} style={styles.searchInput}/></View><Text style={styles.directoryNote}>Choose from the supported bank directory.</Text><FlatList data={filtered} keyExtractor={(item) => item.code} keyboardShouldPersistTaps="handled" renderItem={({ item }) => <Pressable accessibilityRole="button" onPress={() => onSelect(item.code)} style={styles.bankRow}><Text style={styles.bankName}>{item.name}</Text><Feather name="chevron-right" size={19} color={colors.muted}/></Pressable>} ListEmptyComponent={<Text style={styles.noBank}>No matching supported bank.</Text>}/></View></SafeAreaView></Modal>;
}

const styles = StyleSheet.create({
  title: { marginTop: 26, fontSize: 25, lineHeight: 32, fontWeight: "900", color: colors.ink }, copy: { marginTop: 5, marginBottom: 22, fontSize: 15, lineHeight: 23, color: colors.muted }, existing: { marginBottom: 14, borderRadius: radii.control, padding: 13, backgroundColor: "#fff7e8" }, existingLabel: { fontSize: 10, color: colors.muted }, existingValue: { marginTop: 3, fontSize: 13, fontWeight: "800", color: colors.ink }, existingMasked: { marginTop: 3, fontSize: 12, color: colors.muted }, select: { minHeight: 56, borderRadius: radii.control, paddingHorizontal: 15, flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: colors.inputBackground, borderWidth: 1, borderColor: colors.inputBorder }, input: { minHeight: 56, marginTop: 14, borderRadius: radii.control, paddingHorizontal: 15, fontSize: 15, color: colors.inputText, backgroundColor: colors.inputBackground, borderWidth: 1, borderColor: colors.inputBorder }, inputText: { flex: 1, fontSize: 14, color: colors.ink }, placeholder: { flex: 1, fontSize: 14, color: colors.inputPlaceholder }, privacy: { marginTop: 24, borderRadius: 8, padding: 14, flexDirection: "row", alignItems: "flex-start", gap: 9, backgroundColor: "#e8f2ff" }, privacyText: { flex: 1, fontSize: 11, lineHeight: 17, color: "#1768cf" }, manual: { marginTop: 10, fontSize: 10, lineHeight: 15, color: colors.muted },
  modalSafe: { flex: 1, justifyContent: "flex-end" }, backdrop: { ...StyleSheet.absoluteFill, backgroundColor: "rgba(20,19,17,.42)" }, sheet: { maxHeight: "82%", borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: spacing.lg, paddingBottom: spacing.xl, backgroundColor: colors.white }, sheetHeading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, sheetTitle: { fontSize: 20, fontWeight: "900", color: colors.ink }, close: { width: sizes.touch, height: sizes.touch, alignItems: "center", justifyContent: "center" }, search: { minHeight: 52, marginTop: 12, borderRadius: radii.control, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: colors.field }, searchInput: { flex: 1, minWidth: 0, height: 50, fontSize: 14, color: colors.ink }, directoryNote: { marginTop: 9, marginBottom: 5, fontSize: 10, color: colors.muted }, bankRow: { minHeight: 54, borderBottomWidth: 1, borderBottomColor: colors.line, flexDirection: "row", alignItems: "center", gap: 8 }, bankName: { flex: 1, minWidth: 0, flexShrink: 1, fontSize: 13, lineHeight: 18, color: colors.ink }, noBank: { paddingVertical: 28, textAlign: "center", color: colors.muted }
});
