import Image from "next/image";
import Link from "next/link";
import { PublicHeader } from "../auth/public-header";
import { PublicSiteFooter } from "./public-site-footer";

const leaders=["team_afolayan.png","teammember2.png","teammember3.png","teammember4.png"];
const officeAddress="Plot 2, Cornerstone Estate Drive, Ikate-Elegshi, Lekki, Lagos.";
const details=[
  ["⌖","Address",officeAddress],
  ["◔","Call Us","07042055678"],
  ["✉","Have any questions?","info@berylshelter.com"],
  ["▣","Working Hours","Monday - Friday\n8:00 AM - 6:00 PM"],
];

export function AboutPage(){return <div className="public-page about-page"><PublicHeader sessionAware mobileMenu/><main>
  <section className="about-hero"><div><span className="about-eyebrow">WHO ARE WE?</span><h1>About Us</h1><h2>Since incorporation in 2001, Beryl Shelter Nigeria Limited has embarked on a number of strategic initiatives to expand the growth of its real estate market share in Nigeria and ensure strong continuous relevance.</h2><p>Beryl Shelter Nigeria Limited is building classic residential apartments that will excite and delight all. Our lead-off project has been designed as a strong asset for upwardly mobile professionals. All our real estate development construction projects will be constructed with the best materials and by the best building professionals</p></div></section>
  <section className="about-service public-content"><article><b>HERE TO SERVE</b><h2>We at Beryl Shelter<br/> are Here To Serve</h2><p>“Beryl Shelter Nigeria Limited is a real estate marketing and development company. At Beryl, we continuously strive to deliver efficient and value-driven services and products to satisfy high-profile real estate demands covering most aspects of property ownership, maintenance, and development - Sales, Lettings Management, and Development of classic residential and commercial apartments. Since incorporation in 2001, we have humbly served many reputable individuals and organizations. We look forward to serving you too.”</p><p>Best Regards</p><Image src="/about/afolayan_about.png" alt="Abiola Afolayan" width={459} height={309}/><strong>Abiola Afolayan</strong><small>Group Managing Director<br/>Beryl Shelter Nigeria Limited Nigeria</small></article><div className="purpose-cards"><article><div><h2>Our Mission</h2><ul><li>To build real estate apartments that will always excite and delight all.</li></ul></div><Image src="/about/mission_img.png" alt="Modern commercial buildings" width={226} height={218}/></article><article><div><h2>Our Vision</h2><ul><li>To be a preeminent real estate developer in Nigeria</li><li>To be known for the finest and largest portfolio of classic residential properties in Nigeria.</li></ul></div><Image src="/about/vision_img.png" alt="Modern residential development" width={226} height={218}/></article></div></section>
  <section className="leadership public-content"><header><b>OUR LEADERSHIP TEAM</b><h2>Meet our dedicated leadership</h2></header><div>{leaders.map((image,index)=><article key={image}><Image src={`/about/${image}`} alt={`Leadership team member ${index+1}`} width={309} height={361}/><h3>Abiola Omolara Afolayan</h3><p>Chief Executive Officer</p><small>✉&nbsp; afolayan@berylshelter.com</small></article>)}</div></section>
  <section className="office public-content"><div><h2>Our Office<br/>Locations</h2><p>Visit us at any of our office locations to connect with our team. We&apos;re here to assist you with all your real estate needs.</p><address>{details.map(([icon,label,value])=><div key={label}><span>{icon}</span><p><small>{label}</small><strong>{(value??"").split("\n").map(line=><span key={line}>{line}</span>)}</strong></p></div>)}</address></div><iframe title="Map of Beryl Shelter office in Lekki, Lagos" src={`https://www.google.com/maps?q=${encodeURIComponent(officeAddress)}&output=embed`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/></section>
  <section className="working public-content"><Image src="/about/workingwithus.png" alt="Real estate colleagues working together" width={492} height={450}/><div><h2>Working with us</h2><p>Come be a part of a truly amazing real estate company.</p><p>Our people are always working together to build the next big thing, and that really keeps us all on the go. Whether we&apos;re planning projects or signing new clients, we all have a great time here.</p><p>Want to join our team?</p><Link href="/careers">See Open Positions</Link></div></section>
  </main><PublicSiteFooter/></div>}
