import Image from "next/image";
import Link from "next/link";
import { PublicHeader } from "../auth/public-header";
import { PublicSiteFooter } from "./public-site-footer";

const leaders=["team_afolayan.png","teammember2.png","teammember3.png","teammember4.png"];
const details=[
  ["⌖","Address","Plot 2, Cornerstone Estate Drive, Ikate-Elegshi, Lekki, Lagos."],
  ["◔","Call Us","07042055678"],
  ["✉","Have any questions?","info@berylprestigeliving.com"],
  ["▣","Working Hours","Monday - Friday\n8:00 AM - 6:00 PM"],
];

export function AboutPage(){return <div className="public-page about-page"><PublicHeader sessionAware mobileMenu/><main>
  <section className="about-hero"><div><b>ABOUT US</b><span>WHO WE ARE</span><h1>Since incorporation in 2001, Beryl Prestige Living has embarked on a number of strategic initiatives to expand the growth of its real estate market share in Nigeria and ensure strong continuous relevance.</h1><p>Beryl Prestige Living is building classic residential apartments that will excite and delight all. Our lead-off project has been designed as a strong asset for upwardly mobile professionals. All our real estate development construction projects will be constructed with the best materials and by the best building professio</p></div></section>
  <section className="about-service public-content"><article><b>HERE TO SERVE</b><h2>We at Beryl Prestige<br/>Living are Here To Serve</h2><p>“Beryl Prestige Living is a real estate marketing and development company. At Beryl, we continuously strive to deliver efficient and value-driven services and products to satisfy high-profile real estate demands covering most aspects of property ownership, maintenance, and development - Sales, Lettings Management, and Development of classic residential and commercial apartments. Since incorporation in 2001, we have humbly served many reputable individuals and organizations. We look forward to serving you too.”</p><p>Best Regards</p><Image src="/about/afolayan_about.png" alt="Abiola Afolayan" width={459} height={309}/><strong>Abiola Afolayan</strong><small>Group Managing Director<br/>Beryl Prestige Living Nigeria Ltd.</small></article><div className="purpose-cards"><article><div><h2>Our Mission</h2><p>To build real estate apartments that will always excite and delight all.</p></div><Image src="/about/mission_img.png" alt="Modern commercial buildings" width={226} height={218}/></article><article><div><h2>Our Vision</h2><p>To be a preeminent real estate developer in Nigeria and To be known for the finest and largest portfolio of classic residential properties in Nigeria.</p></div><Image src="/about/vision_img.png" alt="Modern residential development" width={226} height={218}/></article></div></section>
  <section className="leadership public-content"><header><b>OUR LEADERSHIP TEAM</b><h2>Meet our dedicated leadership</h2></header><div>{leaders.map((image,index)=><article key={image}><Image src={`/about/${image}`} alt={`Leadership team member ${index+1}`} width={309} height={361}/><h3>Abiola Omolara Afolayan</h3><p>Chief Executive Officer</p><small>✉&nbsp; afolayon@berylprestigeliving.com</small></article>)}</div></section>
  <section className="office public-content"><div><h2>Our Office<br/>Locations</h2><p>Visit us at any of our office locations to connect with our team. We&apos;re here to assist you with all your real estate needs.</p><address>{details.map(([icon,label,value])=><div key={label}><span>{icon}</span><p><small>{label}</small><strong>{(value??"").split("\n").map(line=><span key={line}>{line}</span>)}</strong></p></div>)}</address></div><Image src="/about/office-map.png" alt="Map showing Gerrard Road, Ikoyi, Lagos" width={2880} height={1624}/></section>
  <section className="working public-content"><Image src="/about/workingwithus.png" alt="Real estate colleagues working together" width={492} height={450}/><div><h2>Working with us</h2><p>Come be a part of a truly amazing real estate company. Our people are always working together to build the next big thing, and that really keeps us all on the go. Whether we&apos;re planning projects or signing new clients, we all have a great time here. Want to join our team?</p><Link href="/careers">See Open Positions</Link></div></section>
  </main><PublicSiteFooter/></div>}
