"use client";

import Image from "next/image";
import { FormEvent, useState } from "react";
import { PublicHeader } from "../auth/public-header";
import { PublicSiteFooter } from "./public-site-footer";

export function CareersPage(){const [notice,setNotice]=useState("");function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setNotice("Applications are not available yet. Please check back when open positions are published.");}return <div className="public-page careers-page"><PublicHeader sessionAware mobileMenu/><main>
  <section className="careers-hero"><div className="careers-hero-inner"><div><b>CAREERS</b><h1>Join the Beryl<br/>Prestige Team</h1><p>We are looking for driven, innovative, and passionate individuals to help us redefine luxury real estate. Discover open roles and build your career with us.</p></div><Image src="/careers/careers-hero.png" alt="Beryl Prestige Living team collaborating" width={669} height={608}/></div></section>
  <section className="career-application"><div className="career-application-inner"><header><h2>Apply for an<br/>Open Position</h2><p>Ready to take the next step in your career? Fill out the form with your details, select the role you are interested in, and attach your latest resume. Our hiring team will review your application and get back to you if your profile matches our current needs.</p></header><form onSubmit={submit}><div className="career-fields"><label>Full Name <span>*</span><input required name="fullName" placeholder="Enter your Full Name"/></label><label>Email Address <span>*</span><input required type="email" name="email" placeholder="Enter your email address"/></label><label>Phone Number <span>*</span><input required type="tel" name="phone" placeholder="Enter your phone number"/></label><label>Position Applied For <span>*</span><select aria-describedby="positions-note" disabled name="position" defaultValue=""><option value="">Select a role</option></select><small id="positions-note">Open positions have not been published yet.</small></label></div><label className="resume-field">Upload Resume/CV <span>*</span><span className="resume-control">⌕ <strong>Choose File</strong><input required type="file" name="resume" accept=".pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document"/></span></label><label className="cover-field">Cover Letter / Additional Notes<textarea name="coverLetter" placeholder="Tell us a little about yourself"/></label><button type="submit">Submit Application</button>{notice&&<p className="career-notice" role="status">{notice}</p>}</form></div></section>
  </main><PublicSiteFooter/></div>}
