"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { toast } from "react-toastify";
import type { Customer } from "../../lib/auth-api";
import { formatNaira } from "../../lib/buy-query";
import { nigerianStates } from "../../lib/property-taxonomy";
import { fetchPublicProperties, type PublicProperty } from "../../lib/public-properties-api";
import { fetchSavedPropertyStates, saveProperty } from "../../lib/saved-properties-api";
import { PublicHeader } from "../auth/public-header";
import { showAuthError } from "../auth/toast-provider";
import { PublicSiteFooter } from "./public-site-footer";

const steps=[
  {number:"STEP 1",image:"/landing/step-1.png",title:"Register an account with Beryl Shelter Nigeria Limited",copy:"Create a new account by clicking Register, completing the registration form, and verifying your email address. If you're already a member, click Login to access your existing account."},
  {number:"STEP 2",image:"/landing/step-2.png",title:"Refer the transaction - Buyer or Seller",copy:"After creating and verifying your account, click on refer, fill the form that shows on the page and click on Submit."},
  {number:"STEP 3",image:"/landing/step-3.png",title:"Earn your 2% commission",copy:"For any property bought or rented by your referral, you earn a 2% commission. If 2 or more persons were involved in the referral through our platform, the commission will be shared among all involved. Terms and conditions apply."},
] as const;

export function LandingPage(){const router=useRouter();const [customer,setCustomer]=useState<Customer|null>(null);const [latest,setLatest]=useState<{status:"loading"|"ready"|"error";items:PublicProperty[]}>({status:"loading",items:[]});const [savedCodes,setSavedCodes]=useState<Set<string>>(()=>new Set());const [savingCode,setSavingCode]=useState<string|null>(null);useEffect(()=>{const controller=new AbortController();const query=new URLSearchParams({sort:"latest",pageSize:"3"});void fetchPublicProperties(query,controller.signal).then(result=>{if(!controller.signal.aborted)setLatest({status:"ready",items:result.items});}).catch(()=>{if(!controller.signal.aborted)setLatest({status:"error",items:[]});});return()=>controller.abort();},[]);useEffect(()=>{if(!customer||latest.status!=="ready"||!latest.items.length)return;const controller=new AbortController();void fetchSavedPropertyStates(latest.items.map(property=>property.code),controller.signal).then(codes=>{if(!controller.signal.aborted)setSavedCodes(new Set(codes));}).catch(()=>{});return()=>controller.abort();},[customer,latest]);async function saveLatest(property:PublicProperty){if(!customer){router.push(`/login?next=${encodeURIComponent(`/buy/${property.code}`)}`);return;}if(savingCode||savedCodes.has(property.code))return;setSavingCode(property.code);try{await saveProperty(property.code);setSavedCodes(current=>new Set(current).add(property.code));toast.success("Property saved");}catch(error){showAuthError(error,"landing-save-error");}finally{setSavingCode(null);}}return <div className="landing-page">
  <PublicHeader sessionAware mobileMenu onSessionChange={setCustomer}/>
  <main>
    <section className="landing-hero">
      <picture className="landing-hero-picture"><source media="(max-width: 700px)" srcSet="/landing/landingpagehero_mobile.png"/><img src="/landing/landingpagehero_desktop.png" alt="Customer receiving a Beryl Shelter referral notification"/></picture>
      <div className="landing-hero-copy"><h1><em>Earn Rich</em> when you refer<br/>to us someone who wants to<br/>Buy or Sell a property!</h1><p>Each successful transaction greatly<br/>maximizes your income!</p></div>
      <form className="property-search" action="/buy" method="get"><nav className="search-tabs" aria-label="Property services"><Link className="active" href="/referrals">Refer</Link><Link href="/buy">Buy</Link><Link href="/sell">Sell</Link></nav><Link className="hero-account-link" href={customer?"/dashboard":"/register"}>{customer?"My Dashboard":"Create An Account"}</Link><label className="search-query"><span aria-hidden="true">⌕</span><input name="q" aria-label="Search property listings" placeholder="Enter here to search our property listings"/><button aria-label="Search properties"><svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="10.5" cy="10.5" r="5.5"/><path d="m15 15 4.5 4.5"/></svg></button></label><div className="search-fields"><label>Location<select name="location" defaultValue=""><option value="">Select Location</option>{nigerianStates.map(state=><option key={state}>{state}</option>)}</select></label><label>Property Type<select name="propertyType" defaultValue=""><option value="">Select Property Type</option><option>Residential</option><option>Commercial</option></select></label><label>Budget<select name="budget" defaultValue=""><option value="">Select your budget</option><option value="5000000">Up to ₦5m</option><option value="10000000">Up to ₦10m</option><option value="25000000">Up to ₦25m</option><option value="50000000">Up to ₦50m</option><option value="100000000">Up to ₦100m</option><option value="250000000">Up to ₦250m</option><option value="500000000">Up to ₦500m</option></select></label><label>Bedroom<select name="bedrooms" defaultValue=""><option value="">Select Bedroom No.</option>{[1,2,3,4,5,6].map(value=><option key={value}>{value}</option>)}</select></label></div></form>
    </section>
    <section className="landing-section how-section"><header><h2>Refer and <u>Get Rich!</u></h2><h3>How it works</h3><p>Our referral program is simple, secure, and<br/>rewarding. Here&apos;s how to get started:</p></header><div className="steps-grid">{steps.map(step=><article key={step.number}><Image src={step.image} alt="" width={411} height={350}/><b>{step.number}</b><h3>{step.title}</h3><p>{step.copy}</p></article>)}</div></section>
    <section className="start-section"><div className="start-inner"><Image src="/landing/startreferring.png" alt="Customers sharing property referrals" width={560} height={509}/><div><h2>Start Referring Now</h2><p>Earn a 2% commission for every referral that buys a property using our platform. If there are 2 or more people involved in the referral through our platform, the 2% commission will be shared among all participants. If you have any more questions, don&apos;t fail to reach us through any means below.</p><address><span>⌕</span><p><small>Call Us</small><strong>07042055678</strong></p><span>✉</span><p><small>Email Us</small><strong>info@berylshelter.com</strong></p><span>⌂</span><p><small>Visit Us</small><strong>Plot 2, Cornerstone Estate Drive,<br/>Ikate-Elegshi, Lekki, Lagos.</strong></p></address></div></div><div className="referral-choice-grid"><article><Image src="/landing/refertobuy.png" alt="Couple discussing a property purchase" width={208} height={200}/><h3>Refer someone to buy<br/>a property</h3><p>Are you referring someone to<br/>buy a property(ies)?</p><Link href={customer?"/buy":"/login?next=/buy"}>Click here to refer someone to buy <span>→</span></Link></article><article><Image src="/landing/refertosell.png" alt="Apartment building for sale" width={208} height={200}/><h3>Refer someone to sell<br/>a property</h3><p>Are you referring someone to<br/>sell a property(ies)?</p><Link href={customer?"/dashboard/referrals":"/login?next=/dashboard/referrals"}>Click here to refer someone to sell <span>→</span></Link></article></div></section>
    <section className="landing-section latest-section"><h2>Latest Listings</h2><p>View our newest listings and find your perfect match today.</p>{latest.status==="loading"?<div className="latest-empty" role="status"><strong>Loading latest listings…</strong></div>:latest.status==="error"?<div className="latest-empty" role="alert"><strong>Latest listings are temporarily unavailable.</strong><span>Please try again shortly or browse all properties.</span><Link href="/buy">View Properties</Link></div>:latest.items.length?<><div className="latest-grid">{latest.items.map(property=><article className="latest-card" key={property.code}><Link className="latest-card-image" href={`/buy/${encodeURIComponent(property.code)}`}>{property.images[0]?<Image src={property.images[0]} alt={`Exterior of ${property.title}`} width={520} height={330} unoptimized/>:<span role="img" aria-label={`No photograph available for ${property.title}`}>Photo unavailable</span>}</Link><button type="button" className="latest-save" aria-label={savedCodes.has(property.code)?`${property.title} is saved`:`Save ${property.title}`} aria-pressed={savedCodes.has(property.code)} disabled={savingCode===property.code||savedCodes.has(property.code)} onClick={()=>void saveLatest(property)}>{savedCodes.has(property.code)?"♥":"♡"}</button><div><p>{property.propertySubtype} · {property.propertyType}</p><h3><Link href={`/buy/${encodeURIComponent(property.code)}`}>{property.title}</Link></h3><span>⌖ {property.city}, {property.state}</span><strong>{formatNaira(property.priceMinor)}</strong></div></article>)}</div><Link className="latest-view-all" href="/buy">View All Properties <span>→</span></Link></>:<div className="latest-empty"><strong>No listed properties are available right now.</strong><span>New public listings will appear here when they become available.</span></div>}</section>
    <section className="search-made-easy"><div className="search-video"><Image src="/landing/propertysearchmadeeasy.png" alt="Property search tutorial preview" fill loading="eager" sizes="(max-width: 700px) 100vw, 55vw"/></div><div><h2>Property Search<br/>Made Easy</h2><p>Watch our tutorial on how to effortlessly find and evaluate properties. Learn the best tools and tips to streamline your search and secure your ideal home with ease.</p><Link href="/buy">View Properties <span>→</span></Link></div></section>
    <section className="app-section"><div><h2>Get Our App</h2><p>Download our app from the Play Store for a seamless property search experience. Access exclusive listings, receive real-time notifications, and manage your search on the go. Stay updated and find your perfect home anytime, anywhere.</p><div className="app-downloads" aria-label="Mobile applications coming soon"><Image src="/landing/black-app-store.png" alt="Download on the App Store" width={599} height={175} loading="eager"/><Image src="/landing/black-google-play.png" alt="Get it on Google Play" width={290} height={84} loading="eager"/></div></div><Image src="/landing/getourapp.png" alt="Beryl Shelter mobile app screens" width={577} height={677} loading="eager"/></section>
  </main>
  <PublicSiteFooter/>
</div>}
