"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { PublicHeader } from "../auth/public-header";
import { PublicSiteFooter } from "./public-site-footer";

const steps=[
  {number:"STEP 1",image:"/landing/step-1.png",title:"Register an account with Beryl Prestige Living",copy:"Create a new account by clicking Register, completing the registration form, and verifying your email address. If you're already a member, click Login to access your existing account."},
  {number:"STEP 2",image:"/landing/step-2.png",title:"Refer the transaction - Buyer or Seller",copy:"After creating and verifying your account, click on refer, fill the form that shows on the page and click on Submit."},
  {number:"STEP 3",image:"/landing/step-3.png",title:"Earn your 2% commission",copy:"For any property bought or rented by your referral, you earn a 2% commission. If 2 or more persons were involved in the referral through our platform, the commission will be shared among all involved. Terms and conditions apply."},
] as const;

export function LandingPage(){const [mode,setMode]=useState("refer");return <div className="landing-page">
  <PublicHeader sessionAware mobileMenu/>
  <main>
    <section className="landing-hero">
      <picture className="landing-hero-picture"><source media="(max-width: 700px)" srcSet="/landing/landingpagehero_mobile.png"/><img src="/landing/landingpagehero_desktop.png" alt="Customer receiving a Beryl Shelter referral notification"/></picture>
      <div className="landing-hero-copy"><h1><em>Earn Rich</em> when you refer<br/>to us someone who wants to<br/>Buy or Sell a property!</h1><p>Each successful transaction greatly<br/>maximizes your income!</p></div>
      <form className="property-search" action="/buy" method="get"><div className="search-tabs" role="tablist" aria-label="Property search mode">{["refer","buy","sell"].map(value=><button type="button" role="tab" aria-selected={mode===value} key={value} onClick={()=>setMode(value)}>{value}</button>)}</div><Link className="hero-account-link" href="/register">Create An Account</Link><input type="hidden" name="mode" value={mode}/><label className="search-query"><span aria-hidden="true">⌕</span><input name="q" aria-label="Search property listings" placeholder="Enter here to search our property listings"/><button aria-label="Search properties"><svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="10.5" cy="10.5" r="5.5"/><path d="m15 15 4.5 4.5"/></svg></button></label><div className="search-fields"><label>Location<select name="location" defaultValue=""><option value="">Select Location</option><option>Lagos</option><option>Abuja</option><option>Rivers</option></select></label><label>Property Type<select name="propertyType" defaultValue=""><option value="">Select Property Type</option><option>Residential</option><option>Commercial</option></select></label><label>Budget<select name="budget" defaultValue=""><option value="">Select your budget</option><option value="50000000">Up to ₦50m</option><option value="100000000">Up to ₦100m</option></select></label><label>Bedroom<select name="bedrooms" defaultValue=""><option value="">Select Bedroom No.</option>{[1,2,3,4,5,6].map(value=><option key={value}>{value}</option>)}</select></label></div></form>
    </section>
    <section className="landing-section how-section"><header><h2>Refer and <u>Get Rich!</u></h2><h3>How it works</h3><p>Our referral program is simple, secure, and<br/>rewarding. Here&apos;s how to get started:</p></header><div className="steps-grid">{steps.map(step=><article key={step.number}><Image src={step.image} alt="" width={411} height={350}/><b>{step.number}</b><h3>{step.title}</h3><p>{step.copy}</p></article>)}</div></section>
    <section className="start-section"><div className="start-inner"><Image src="/landing/startreferring.png" alt="Customers sharing property referrals" width={560} height={509}/><div><h2>Start Referring Now</h2><p>Earn a 2% commission for every referral that buys a property using our platform. If there are 2 or more people involved in the referral through our platform, the 2% commission will be shared among all participants. If you have any more questions, don&apos;t fail to reach us through any means below.</p><address><span>⌕</span><p><small>Call Us</small><strong>07042055678</strong></p><span>✉</span><p><small>Email Us</small><strong>info@berylprestigeliving.com</strong></p><span>⌂</span><p><small>Visit Us</small><strong>Plot 2, Cornerstone Estate Drive,<br/>Ikate-Elegshi, Lekki, Lagos.</strong></p></address></div></div><div className="referral-choice-grid"><article><Image src="/landing/refertobuy.png" alt="Couple discussing a property purchase" width={208} height={200}/><h3>Refer someone to buy<br/>a property</h3><p>Are you referring someone to<br/>buy a property(ies)?</p><Link href="/login?next=/dashboard/referrals">Click here to refer someone to buy <span>→</span></Link></article><article><Image src="/landing/refertosell.png" alt="Apartment building for sale" width={208} height={200}/><h3>Refer someone to sell<br/>a property</h3><p>Are you referring someone to<br/>sell a property(ies)?</p><Link href="/login?next=/dashboard/referrals">Click here to refer someone to sell <span>→</span></Link></article></div></section>
    <section className="landing-section latest-section"><h2>Latest Listings</h2><p>View our newest listings and find your perfect match today.</p><div className="latest-empty"><strong>No listed properties are available right now.</strong><span>New public listings will appear here when they become available.</span></div></section>
    <section className="search-made-easy"><div className="search-video"><Image src="/landing/propertysearchmadeeasy.png" alt="Property search tutorial preview" fill loading="eager" sizes="(max-width: 700px) 100vw, 55vw"/></div><div><h2>Property Search<br/>Made Easy</h2><p>Watch our tutorial on how to effortlessly find and evaluate properties. Learn the best tools and tips to streamline your search and secure your ideal home with ease.</p><Link href="/buy">View Properties <span>→</span></Link></div></section>
    <section className="app-section"><div><h2>Get Our App</h2><p>Download our app from the Play Store for a seamless property search experience. Access exclusive listings, receive real-time notifications, and manage your search on the go. Stay updated and find your perfect home anytime, anywhere.</p><div className="app-downloads" aria-label="Mobile applications coming soon"><Image src="/landing/black-app-store.png" alt="Download on the App Store" width={599} height={175} loading="eager"/><Image src="/landing/black-google-play.png" alt="Get it on Google Play" width={290} height={84} loading="eager"/></div></div><Image src="/landing/getourapp.png" alt="Beryl Shelter mobile app screens" width={577} height={677} loading="eager"/></section>
  </main>
  <PublicSiteFooter/>
</div>}
