"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent, type KeyboardEvent } from "react";
import { toast } from "react-toastify";
import type { Customer } from "../../lib/auth-api";
import { formatNairaInput, nairaToKobo } from "../../lib/buy-query";
import { createPublicPropertyReferral } from "../../lib/referrals-api";
import { fetchSavedPropertyStates, removeSavedProperty, saveProperty } from "../../lib/saved-properties-api";
import { fetchPublicPropertyDetail, type PublicProperty, type PublicPropertyDetail } from "../../lib/public-properties-api";
import { submitPropertyViewing } from "../../lib/property-viewings-api";
import { showAuthError } from "../auth/toast-provider";
import { PublicHeader } from "../auth/public-header";
import { calculateMortgage } from "./mortgage-calculator-page";
import { PublicSiteFooter } from "./public-site-footer";

const naira = (minor: number, decimals = 0) => `₦${new Intl.NumberFormat("en-NG", { minimumFractionDigits: decimals, maximumFractionDigits: decimals }).format(minor / 100)}`;
const inputFromMinor = (minor: number) => formatNairaInput(`${Math.floor(minor / 100)}.${String(minor % 100).padStart(2, "0")}`) ?? "";
const initialViewing = { firstName: "", lastName: "", email: "", phone: "", preferredDate: "", preferredTime: "", flexibleDates: false };

function PropertyPhoto({ property, src, className = "" }: { property: PublicProperty; src?: string | undefined; className?: string }) {
  return src ? <Image className={className} src={src} alt={`${property.title} property photograph`} fill sizes="(max-width: 700px) 100vw, 52vw" unoptimized/>
    : <div className={`property-detail-placeholder ${className}`} role="img" aria-label={`No photograph available for ${property.title}`}>Photo unavailable</div>;
}

function EmbeddedMortgage({ priceMinor }: { priceMinor: number }) {
  const [downPayment, setDownPayment] = useState(""); const [loanTerm, setLoanTerm] = useState(""); const [interestRate, setInterestRate] = useState("");
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [result, setResult] = useState({ monthlyPaymentMinor: 0, totalRepaymentMinor: 0, totalInterestMinor: 0 });
  const downMinor = useMemo(() => downPayment ? nairaToKobo(downPayment) : null, [downPayment]);
  const percentage = downMinor === null ? 0 : Number(BigInt(downMinor)) / Number(BigInt(priceMinor)) * 100;
  function calculate(event: FormEvent) {
    event.preventDefault(); const next: Record<string, string> = {}; const down = downMinor === null ? null : Number(downMinor);
    const years = Number(loanTerm); const rate = interestRate === "" ? Number.NaN : Number(interestRate);
    if (down === null || down < 0 || down > priceMinor) next.downPayment = "Enter a valid down payment no greater than the property price.";
    if (![5,10,15,20,25,30].includes(years)) next.loanTerm = "Select a valid loan term.";
    if (!Number.isFinite(rate) || rate < 0 || rate > 100) next.interestRate = "Enter an interest rate from 0 to 100%.";
    setErrors(next); if (Object.keys(next).length || down === null) return;
    setResult(calculateMortgage(priceMinor, down, years, rate));
  }
  function reset() { setDownPayment(""); setLoanTerm(""); setInterestRate(""); setErrors({}); setResult({ monthlyPaymentMinor: 0, totalRepaymentMinor: 0, totalInterestMinor: 0 }); }
  return <section className="property-mortgage" aria-labelledby="property-mortgage-title"><div className="mortgage-card-heading"><h2 id="property-mortgage-title">Mortgage Calculator</h2><button type="button" onClick={reset}>Reset</button></div>
    <form onSubmit={calculate} noValidate>
      <div className="mortgage-field"><label htmlFor="detail-purchase-price">Property Purchase Price <span>*</span></label><div className="mortgage-control"><b>NGN</b><input id="detail-purchase-price" value={inputFromMinor(priceMinor)} readOnly/></div><p>This is the price of the property you are currently viewing.</p></div>
      <div className="mortgage-field"><label htmlFor="detail-down-payment">Down Payment <span>*</span></label><div className="mortgage-control"><b>NGN</b><input id="detail-down-payment" inputMode="decimal" placeholder="Enter amount" value={downPayment} aria-invalid={!!errors.downPayment} onChange={event => { const value = formatNairaInput(event.target.value); if (value !== null) setDownPayment(value); }}/><output className="mortgage-percentage">{Number.isFinite(percentage) ? percentage.toFixed(2) : "0.00"} %</output></div><p>Enter the amount you can pay upfront towards this property&apos;s purchase</p>{errors.downPayment && <p className="mortgage-error" role="alert">{errors.downPayment}</p>}</div>
      <div className="mortgage-field"><label htmlFor="detail-loan-term">Loan Term <span>*</span></label><select id="detail-loan-term" value={loanTerm} aria-invalid={!!errors.loanTerm} onChange={event => setLoanTerm(event.target.value)}><option value="">Select Loan Duration</option>{[5,10,15,20,25,30].map(years => <option key={years} value={years}>{years} years</option>)}</select><p>Specify the length of time over which you&apos;ll pay the loan</p>{errors.loanTerm && <p className="mortgage-error" role="alert">{errors.loanTerm}</p>}</div>
      <div className="mortgage-field"><label htmlFor="detail-interest-rate">Interest Rate <span>*</span></label><div className="mortgage-control"><b>%</b><input id="detail-interest-rate" inputMode="decimal" placeholder="Enter Interest Rate" value={interestRate} aria-invalid={!!errors.interestRate} onChange={event => setInterestRate(event.target.value)}/></div><p>This is the interest rate for your loan, which affects your monthly payments.</p>{errors.interestRate && <p className="mortgage-error" role="alert">{errors.interestRate}</p>}</div>
      <button className="mortgage-calculate" type="submit">Calculate</button>
    </form><dl className="property-mortgage-results" aria-live="polite"><div><dt>Estimated Monthly Payment</dt><dd>{naira(result.monthlyPaymentMinor, 2)}</dd></div><div><dt>Total Repayment Amount</dt><dd>{naira(result.totalRepaymentMinor, 2)}</dd></div><div><dt>Total Interest to Pay</dt><dd>{naira(result.totalInterestMinor, 2)}</dd></div></dl><p className="property-estimate-note">Estimate only. This is not a mortgage offer, approval, purchase, or payment.</p>
  </section>;
}

function SimilarCard({ property, saved, saving, onSave }: { property: PublicProperty; saved: boolean; saving: boolean; onSave: () => void }) {
  return <article className="similar-property-card"><div className="similar-property-image">{property.images[0] ? <Image src={property.images[0]} alt={`${property.title} property photograph`} fill sizes="(max-width: 700px) 76vw, 24vw" unoptimized/> : <span>Photo unavailable</span>}<button type="button" className="similar-save" aria-label={saved ? `${property.title} is saved` : `Save ${property.title}`} aria-pressed={saved} disabled={saving || saved} onClick={onSave}>{saved ? "♥" : "♡"}</button></div><Link className="similar-property-copy" href={`/buy/${encodeURIComponent(property.code)}`}><strong>{property.title}</strong><small>{property.bedrooms} Bedrooms · {property.bathrooms} Bathrooms</small><b>{naira(property.priceMinor)}</b></Link></article>;
}

export function PublicPropertyDetailPage({ propertyCode }: { propertyCode: string }) {
  const router = useRouter(); const params = useSearchParams();
  const [customer, setCustomer] = useState<Customer | null>(null); const [property, setProperty] = useState<PublicPropertyDetail | null>(null);
  const [similar, setSimilar] = useState<PublicProperty[]>([]); const [loading, setLoading] = useState(true); const [notFound, setNotFound] = useState(false);
  const [selected, setSelected] = useState(0); const [expanded, setExpanded] = useState(false); const [saved, setSaved] = useState(false); const [saving, setSaving] = useState(false); const [copying, setCopying] = useState(false);
  const [similarSavedCodes, setSimilarSavedCodes] = useState<Set<string>>(() => new Set()); const [similarSaving, setSimilarSaving] = useState<string | null>(null);
  const [viewing, setViewing] = useState(initialViewing); const [viewingErrors, setViewingErrors] = useState<Record<string, string>>({}); const [viewingPending, setViewingPending] = useState(false); const [viewingFailure, setViewingFailure] = useState(""); const [success, setSuccess] = useState(false);
  const successDialog = useRef<HTMLDivElement>(null); const closeButton = useRef<HTMLButtonElement>(null); const submitButton = useRef<HTMLButtonElement>(null);
  useEffect(() => { const controller = new AbortController(); void fetchPublicPropertyDetail(propertyCode, controller.signal).then(result => { if (!controller.signal.aborted) { setProperty(result.property); setSimilar(result.similar); setSelected(0); } }).catch(error => { if (!controller.signal.aborted) setNotFound(error instanceof Error && error.message === "PROPERTY_NOT_FOUND"); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [propertyCode]);
  useEffect(() => { if (!customer || !property) return; const controller = new AbortController(); void fetchSavedPropertyStates([property.code,...similar.map(item=>item.code)], controller.signal).then(codes => { if (!controller.signal.aborted) { setSaved(codes.includes(property.code)); setSimilarSavedCodes(new Set(codes)); } }).catch(() => {}); return () => controller.abort(); }, [customer, property, similar]);
  const handleSessionChange = useCallback((value: Customer | null) => { setCustomer(value); if (value) setViewing(current => ({ ...current, firstName: current.firstName || value.first_name || "", lastName: current.lastName || value.last_name || "", email: current.email || value.email, phone: current.phone || value.phone_number || "" })); }, []);
  useEffect(() => { if (!success) return; const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; closeButton.current?.focus(); return () => { document.body.style.overflow = previous; }; }, [success]);
  const returnPath = `/buy/${encodeURIComponent(propertyCode)}${params.toString() ? `?${params}` : ""}`;
  async function toggleSaved() { if (!property) return; if (!customer) { router.push(`/login?next=${encodeURIComponent(returnPath)}`); return; } if (saving) return; setSaving(true); try { if (saved) { await removeSavedProperty(property.code); setSaved(false); toast.success("Property removed from saved properties"); } else { await saveProperty(property.code); setSaved(true); toast.success("Property saved"); } } catch (error) { showAuthError(error, "property-detail-save-error"); } finally { setSaving(false); } }
  async function saveSimilarProperty(item: PublicProperty) { if (!customer) { router.push(`/login?next=${encodeURIComponent(`/buy/${item.code}`)}`); return; } if (similarSaving || similarSavedCodes.has(item.code)) return; setSimilarSaving(item.code); try { await saveProperty(item.code); setSimilarSavedCodes(current => new Set(current).add(item.code)); toast.success("Property saved"); } catch (error) { showAuthError(error, "similar-property-save-error"); } finally { setSimilarSaving(null); } }
  async function refer() { if (!property) return; if (!customer) { router.push(`/login?next=${encodeURIComponent(returnPath)}`); return; } if (copying) return; setCopying(true); try { const referral = await createPublicPropertyReferral(property.code); await navigator.clipboard.writeText(referral.referralUrl); toast.success("Referral link copied to clipboard"); } catch (error) { showAuthError(error, "property-detail-referral-error"); } finally { setCopying(false); } }
  function resetViewing() { setViewing({ ...initialViewing, firstName: customer?.first_name ?? "", lastName: customer?.last_name ?? "", email: customer?.email ?? "", phone: customer?.phone_number ?? "" }); setViewingErrors({}); setViewingFailure(""); }
  async function schedule(event: FormEvent) { event.preventDefault(); if (!property) return; const errors: Record<string, string> = {}; if (viewing.firstName.trim().length < 2) errors.firstName = "Enter your first name."; if (viewing.lastName.trim().length < 2) errors.lastName = "Enter your last name."; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(viewing.email.trim())) errors.email = "Enter a valid email address."; if (!/^\+?[0-9()\-\s]{7,25}$/.test(viewing.phone.trim())) errors.phone = "Enter a valid phone number."; if (!viewing.flexibleDates && !viewing.preferredDate) errors.preferredDate = "Choose a preferred date."; if (!viewing.flexibleDates && !viewing.preferredTime) errors.preferredTime = "Choose a preferred time."; if (viewing.preferredDate && viewing.preferredDate < new Date().toISOString().slice(0,10)) errors.preferredDate = "Preferred date cannot be in the past."; setViewingErrors(errors); if (Object.keys(errors).length) return; setViewingPending(true); setViewingFailure(""); try { await submitPropertyViewing({ propertyCode: property.code, firstName: viewing.firstName.trim(), lastName: viewing.lastName.trim(), email: viewing.email.trim().toLowerCase(), phone: viewing.phone.trim(), preferredDate: viewing.preferredDate || null, preferredTime: viewing.preferredTime || null, flexibleDates: viewing.flexibleDates }); setSuccess(true); } catch (error) { setViewingFailure(error instanceof Error ? error.message : "Your viewing could not be scheduled. Please try again."); } finally { setViewingPending(false); } }
  function modalKeys(event: KeyboardEvent<HTMLDivElement>) { if (event.key === "Escape") { event.preventDefault(); closeSuccess(); return; } if (event.key !== "Tab" || !successDialog.current) return; const items = [...successDialog.current.querySelectorAll<HTMLElement>('button:not([disabled]),a[href]')]; const first = items[0]; const last = items.at(-1); if (!first || !last) return; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }
  function closeSuccess() { setSuccess(false); resetViewing(); setTimeout(() => submitButton.current?.focus(), 0); }
  function showPreviousPhoto() { if (property?.images.length) setSelected(current => (current - 1 + property.images.length) % property.images.length); }
  function showNextPhoto() { if (property?.images.length) setSelected(current => (current + 1) % property.images.length); }
  if (loading) return <div className="property-detail-page"><PublicHeader sessionAware mobileMenu onSessionChange={handleSessionChange}/><main className="property-detail-state" role="status">Loading property…</main><PublicSiteFooter/></div>;
  if (!property || notFound) return <div className="property-detail-page"><PublicHeader sessionAware mobileMenu onSessionChange={handleSessionChange}/><main className="property-detail-state"><h1>Property not found</h1><p>This property is unavailable or is no longer publicly listed.</p><Link href="/buy">Back to search results</Link></main><PublicSiteFooter/></div>;
  const description = !expanded && property.description.length > 260 ? `${property.description.slice(0, 257).trimEnd()}…` : property.description;
  const mapUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${property.location}, ${property.city}, ${property.state}, Nigeria`)}`;
  const commission = Math.round(property.priceMinor * .02);
  return <div className="property-detail-page"><PublicHeader sessionAware mobileMenu onSessionChange={handleSessionChange}/><main>
    <div className="property-detail-actions"><Link href="/buy">← Back to search results</Link><button type="button" onClick={() => void refer()} disabled={copying}>♙ {copying ? "Copying referral…" : "Refer a friend for this property"}<small>Potential 2% earning: {naira(commission)}</small></button></div>
    <nav className="property-breadcrumb" aria-label="Breadcrumb"><Link href="/buy">Buy</Link><span>/</span><Link href={`/buy?propertyType=${encodeURIComponent(property.propertyType)}`}>{property.propertyType}</Link><span>/</span><span>{property.title}</span></nav>
    <section className="property-detail-hero"><div className="property-gallery"><div className="property-thumbnails">{property.images.slice(0,5).map((image,index) => <button type="button" key={image} aria-label={`Show property photo ${index+1}`} aria-pressed={selected===index} onClick={() => setSelected(index)}><Image src={image} alt="" fill sizes="100px" unoptimized/>{index===4 && property.images.length>5 && <span>+{property.images.length-5}<small>more photos</small></span>}</button>)}</div><div className="property-primary-image"><PropertyPhoto property={property} src={property.images[selected]}/>{property.images.length>1&&<><button type="button" className="property-gallery-previous" aria-label="Show previous property photo" onClick={showPreviousPhoto}>‹</button><button type="button" className="property-gallery-next" aria-label="Show next property photo" onClick={showNextPhoto}>›</button><span className="property-gallery-count" aria-live="polite">{selected+1} / {property.images.length}</span></>}<button type="button" className="property-detail-save" aria-label={saved ? `Remove ${property.title} from saved properties` : `Save ${property.title}`} aria-pressed={saved} disabled={saving} onClick={() => void toggleSaved()}>{saved ? "♥" : "♡"}</button></div></div>
      <div className="property-detail-copy"><p>{property.bedrooms} Bedroom {property.propertySubtype}</p><h1>{property.title}</h1><div className="property-detail-facts"><span>▱ {property.bedrooms} {property.bedrooms===1?"Bedroom":"Bedrooms"}</span><span>♧ {property.bathrooms} {property.bathrooms===1?"Bathroom":"Bathrooms"}</span><span>▣ {property.parkingSpaces} {property.parkingSpaces===1?"Parking Space":"Parking Spaces"}</span>{property.landArea!==null&&<span>◇ {property.landArea.toLocaleString()} land area</span>}</div><p className="property-detail-location">⌖ {property.city}, {property.state}</p>
        <div className="property-description"><h2>Description</h2><p>{description}</p><dl><div><dt>Property Code</dt><dd>{property.code}</dd></div><div><dt>Lien information</dt><dd>{property.hasLien?"Lien recorded":"No lien recorded"}</dd></div><div><dt>Occupancy Type</dt><dd>{property.occupancyType}</dd></div><div><dt>Ownership Type</dt><dd>{property.ownershipType}</dd></div>{property.yearBuilt!==null&&<div><dt>Year Built</dt><dd>{property.yearBuilt}</dd></div>}</dl>{property.description.length>260&&<button type="button" onClick={() => setExpanded(value=>!value)}>{expanded?"Show less":"Show full description"}</button>}</div>
        {property.facilities.length>0&&<div className="property-facilities"><h2>Facilities and features</h2><ul>{property.facilities.map(item=><li key={item}>✓ {item}</li>)}</ul></div>}
        <section className="property-location-grid" aria-label="Property location details"><div><b>Locality</b><span>⌖ {property.city}</span></div><div className="property-address"><b>Location</b><span>⌖ {property.location}<a href={mapUrl} target="_blank" rel="noreferrer">Open In Map ↗</a></span></div><div><b>City</b><span>{property.city}</span></div><div><b>State</b><span>{property.state}</span></div><div><b>Property Type</b><span>{property.propertyType}</span></div><div><b>Property Subtype</b><span>{property.propertySubtype}</span></div></section>
        <section className="property-payment"><h2>Payment Plan and Duration</h2><dl><div><dt>Property Cost</dt><dd>{naira(property.priceMinor)}</dd></div><div><dt>Minimum Down payment</dt><dd>{naira(property.minimumDownPaymentMinor)}</dd></div></dl><p>Information only. Property purchases are completed offline with Beryl Shelter.</p></section>
        <form className="property-viewing-form" onSubmit={schedule} noValidate><div className="property-section-heading"><h2>Enter your details to schedule a viewing of this property</h2><button type="button" onClick={resetViewing}>Reset</button></div><div className="property-viewing-fields">{([['firstName','First Name','Enter first name','text'],['lastName','Last Name','Enter last name','text'],['email','Email address','Enter email address','email'],['phone','Phone Number','Enter phone number','tel']] as const).map(([key,label,placeholder,type])=><label key={key}>{label} <span>*</span><input type={type} value={viewing[key] as string} maxLength={key==='email'?254:key==='phone'?25:80} placeholder={placeholder} aria-invalid={!!viewingErrors[key]} onChange={event=>setViewing(current=>({...current,[key]:event.target.value}))}/>{viewingErrors[key]&&<small role="alert">{viewingErrors[key]}</small>}</label>)}<label>Preferred Date {!viewing.flexibleDates&&<span>*</span>}<input type="date" min={new Date().toISOString().slice(0,10)} value={viewing.preferredDate} aria-invalid={!!viewingErrors.preferredDate} onChange={event=>setViewing(current=>({...current,preferredDate:event.target.value}))}/>{viewingErrors.preferredDate&&<small role="alert">{viewingErrors.preferredDate}</small>}</label><label>Preferred Time {!viewing.flexibleDates&&<span>*</span>}<input type="time" value={viewing.preferredTime} aria-invalid={!!viewingErrors.preferredTime} onChange={event=>setViewing(current=>({...current,preferredTime:event.target.value}))}/>{viewingErrors.preferredTime&&<small role="alert">{viewingErrors.preferredTime}</small>}</label></div><label className="property-flexible"><input type="checkbox" checked={viewing.flexibleDates} onChange={event=>setViewing(current=>({...current,flexibleDates:event.target.checked}))}/> My dates are flexible</label>{viewingFailure&&<p className="property-viewing-failure" role="alert">{viewingFailure}</p>}<button ref={submitButton} className="property-viewing-submit" type="submit" disabled={viewingPending}>{viewingPending?"Scheduling…":"Submit"}</button></form>
        <EmbeddedMortgage priceMinor={property.priceMinor}/>
      </div></section>
    <section className="similar-properties"><h2>Similar properties</h2><p>Explore other currently listed properties with similar type and location details.</p>{similar.length?<div>{similar.map(item=><SimilarCard property={item} key={item.code} saved={similarSavedCodes.has(item.code)} saving={similarSaving===item.code} onSave={()=>void saveSimilarProperty(item)}/>)}</div>:<p className="similar-empty">No similar listed properties are available right now.</p>}</section>
  </main><PublicSiteFooter/>
  {success&&<div className="viewing-success-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)closeSuccess()}}><div ref={successDialog} className="viewing-success-dialog" role="dialog" aria-modal="true" aria-labelledby="viewing-success-title" onKeyDown={modalKeys}><button ref={closeButton} type="button" className="viewing-success-close" aria-label="Close viewing confirmation" onClick={closeSuccess}>×</button><span className="viewing-success-check" aria-hidden="true">✓</span><h2 id="viewing-success-title">Viewing Scheduled Successfully</h2><p>Your viewing has been scheduled. We will contact you through your email or phone number within 24 hours to confirm the details.</p><div className="viewing-success-property">{property.images[0]?<Image src={property.images[0]} alt="" width={86} height={70} unoptimized/>:<span/>}<div><strong>{property.title}</strong><b>{naira(property.priceMinor)}</b></div></div><button type="button" className="viewing-success-got-it" onClick={closeSuccess}>Got it</button></div></div>}
  </div>;
}
