import { addAmenity, canUploadDocument, canUploadPhoto, counterValue, moveId, normalizeAmenities, removeAmenity, sellerDraftPayload, sellerRoute, stepFromSlug, stepSlug } from "./helpers";
describe("seller marketplace helpers",()=>{
 it("deduplicates amenities case-insensitively",()=>expect(normalizeAmenities(["Pool"," pool ","Gym"])).toEqual(["Pool","Gym"]));
 it("adds a custom amenity",()=>expect(addAmenity(["Pool"],"Gym")).toEqual(["Pool","Gym"]));
 it("does not add duplicate amenities",()=>expect(addAmenity(["Pool"]," pool ")).toEqual(["Pool"]));
 it("removes amenities case-insensitively",()=>expect(removeAmenity(["Pool","Gym"],"POOL")).toEqual(["Gym"]));
 it("increments a counter",()=>expect(counterValue(2,1)).toBe(3));
 it("does not decrement below minimum",()=>expect(counterValue(0,-1)).toBe(0));
 it("normalizes invalid counters",()=>expect(counterValue(undefined,1)).toBe(1));
 it("allows valid photos",()=>expect(canUploadPhoto(0,1024,"image/jpeg")).toBe(true));
 it("rejects the eleventh photo",()=>expect(canUploadPhoto(10,1024,"image/jpeg")).toBe(false));
 it("rejects oversized photos",()=>expect(canUploadPhoto(0,6*1024*1024,"image/png")).toBe(false));
 it("rejects unsupported image mime",()=>expect(canUploadPhoto(0,1024,"image/gif")).toBe(false));
 it("allows valid PDFs",()=>expect(canUploadDocument(1024,"application/pdf")).toBe(true));
 it("rejects oversized PDFs",()=>expect(canUploadDocument(11*1024*1024,"application/pdf")).toBe(false));
 it("rejects non-PDF documents",()=>expect(canUploadDocument(1024,"text/plain")).toBe(false));
 it("moves image order left",()=>expect(moveId(["a","b","c"],"b",-1)).toEqual(["b","a","c"]));
 it("moves image order right",()=>expect(moveId(["a","b","c"],"b",1)).toEqual(["a","c","b"]));
 it("does not move beyond an edge",()=>expect(moveId(["a","b"],"a",-1)).toEqual(["a","b"]));
 it("maps all step slugs",()=>expect(["PROPERTY_INFORMATION","PHOTOS_DOCUMENTS","SALES_MANDATE","REVIEW"].map(v=>stepSlug(v as never))).toEqual(["property-information","photos-documents","sales-mandate","review"]));
 it("reads review step",()=>expect(stepFromSlug("review")).toBe("REVIEW"));
 it("defaults unknown steps safely",()=>expect(stepFromSlug("bad")).toBe("PROPERTY_INFORMATION"));
 it("routes live listings to buyer detail",()=>expect(sellerRoute("VIEW_LIVE_LISTING","p1")).toBe("/marketplace/p1"));
 it("routes review status to management",()=>expect(sellerRoute("VIEW_REVIEW_STATUS","p1")).toBe("/seller/listings/p1"));
 it("routes rejection to management",()=>expect(sellerRoute("VIEW_REJECTION","p1")).toBe("/seller/listings/p1"));
 it("routes draft steps to editor",()=>expect(sellerRoute("CONTINUE_PHOTOS_DOCUMENTS","p1")).toContain("step=photos-documents"));
 it("clears residential counters for commercial drafts",()=>expect(sellerDraftPayload({propertyCategory:"COMMERCIAL",bedrooms:4,numberOfFloors:2})).toMatchObject({bedrooms:null,numberOfFloors:2}));
 it("clears commercial counters for residential drafts",()=>expect(sellerDraftPayload({propertyCategory:"RESIDENTIAL",bedrooms:4,numberOfFloors:2})).toMatchObject({bedrooms:4,numberOfFloors:null}));
 it("normalizes missing deposit",()=>expect(sellerDraftPayload({initialDepositType:null,initialDepositValue:30})).toMatchObject({initialDepositType:null,initialDepositValue:null}));
 it("preserves amount deposit",()=>expect(sellerDraftPayload({initialDepositType:"AMOUNT",initialDepositValue:500000})).toMatchObject({initialDepositType:"AMOUNT",initialDepositValue:500000}));
});
