import Busboy from "busboy";
import type { Request } from "express";
import { basename } from "node:path";
import { AuthError } from "../auth/errors.js";
import { validateFile,type UploadFile } from "../listings/uploads.js";
export type KycUpload=UploadFile&{side:"FRONT"|"BACK";filename:string};
const maximum=10*1024*1024,invalid=()=>new AuthError(400,"INVALID_KYC_DOCUMENT","Choose a PDF, PNG or JPG file no larger than 10 MiB.");
const safeName=(value:string)=>{const clean=basename(value).replace(/[^A-Za-z0-9._ -]/g,"_").slice(0,120);return clean||"document";};
export function readKycUpload(request:Request):Promise<{data:unknown;files:KycUpload[]}>{return new Promise((resolve,reject)=>{let parser:ReturnType<typeof Busboy>;try{parser=Busboy({headers:request.headers,limits:{files:2,fields:1,fieldSize:8192,fileSize:maximum,parts:4}});}catch{reject(invalid());return;}let data:unknown,seen=false,failed=false,total=0;const files:KycUpload[]=[];parser.on("field",(name,value,info)=>{if(name!=="data"||seen||info.valueTruncated){failed=true;return;}seen=true;try{data=JSON.parse(value);}catch{failed=true;}});parser.on("file",(field,stream,info)=>{const side=field==="frontDocument"?"FRONT":field==="backDocument"?"BACK":null,chunks:Buffer[]=[];if(!side||files.some(file=>file.side===side)){failed=true;stream.resume();return;}const file:KycUpload={field,mime:info.mimeType,bytes:Buffer.alloc(0),side,filename:safeName(info.filename)};files.push(file);stream.on("limit",()=>{failed=true;});stream.on("data",(chunk:Buffer)=>{total+=chunk.length;if(total>2*maximum)failed=true;if(!failed)chunks.push(chunk);});stream.on("end",()=>{if(!failed)file.bytes=Buffer.concat(chunks);});});for(const event of ["filesLimit","fieldsLimit","partsLimit"])parser.on(event,()=>{failed=true;});parser.once("error",()=>reject(invalid()));parser.once("close",()=>{try{if(failed||!seen||!files.length)throw invalid();for(const file of files)validateFile(file,true,false);resolve({data,files});}catch{reject(invalid());}});request.pipe(parser);});}
