import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "expo-router";
import { Controller, useForm } from "react-hook-form";
import { useEffect, useRef, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ApiError, post } from "@/api/client";
import { BrandHeader, FormError, Heading, PasswordChecklist, PrimaryButton, Screen, TextField } from "@/components/ui";
import { forgotPasswordSchema, loginSchema, resetPasswordSchema, type ForgotPasswordValues, type LoginValues, type ResetPasswordValues } from "@/schemas/customer-auth";
import { useCustomerSession, useResetFlow } from "@/store/auth-flow";
import { colors, radii } from "@/theme/tokens";
import type { CustomerSession, NextAction } from "@/types/auth";

const errorMessage=(error:unknown, fallback:string)=>{const api=error as ApiError; return ({INVALID_CREDENTIALS:"Incorrect email/phone or password.",LOGIN_RATE_LIMITED:"Too many login attempts. Please try again later.",ACCOUNT_VERIFICATION_REQUIRED:"Please verify your email before signing in.",ACCOUNT_SUSPENDED:"This account is suspended.",ACCOUNT_LOCKED:"This account is locked.",INVALID_OTP:"That code was not right. Check your email and try again.",OTP_EXPIRED:"That code has expired. Request a new one.",OTP_ATTEMPTS_EXCEEDED:"Too many attempts. Request a new code to continue.",OTP_NO_LONGER_VALID:"That code is no longer valid. Request a new one.",INVALID_RESET_TOKEN:"This password reset session is no longer valid. Start again.",RESET_TOKEN_EXPIRED:"This password reset session has expired. Start again.",RESET_TOKEN_USED:"This password reset session has already been used.",NEW_PASSWORD_SAME_AS_CURRENT:"Your new password must differ from your current password.",PASSWORD_RESET_UNAVAILABLE:"Password reset is temporarily unavailable."}[api.code??""]??api.message??fallback);};
const routeFor=(action:NextAction)=>({VERIFY_EMAIL:"/verify-email",COMPLETE_BUYER_ONBOARDING:"/buyer",COMPLETE_SELLER_ONBOARDING:"/seller",OPEN_BUYER_DASHBOARD:"/buyer-dashboard",OPEN_SELLER_DASHBOARD:"/seller-dashboard"}[action]);

export function LoginScreen(){const router=useRouter();const{establishSession}=useCustomerSession();const{control,handleSubmit,formState:{errors,isSubmitting},setError}=useForm<LoginValues>({resolver:zodResolver(loginSchema),defaultValues:{identifier:"",password:""}});const submit=async(values:LoginValues)=>{try{const result=await post<CustomerSession>("/auth/login",values);if(!result.data)throw new Error("Session was not returned");await establishSession(result.data);router.replace(routeFor(result.data.nextAction));}catch(error){setError("root",{message:errorMessage(error,"Unable to sign in.")});}};return <Screen><BrandHeader/><Heading title="Login back to your account" copy="Log in to save homes, message agents and manage your listings."/><Controller control={control} name="identifier" render={({field})=><TextField label="Email address / Phone" keyboardType="email-address" autoComplete="email" value={field.value} onChangeText={field.onChange} error={errors.identifier?.message}/>}/><Controller control={control} name="password" render={({field})=><TextField label="Password" secure autoComplete="password" value={field.value} onChangeText={field.onChange} error={errors.password?.message}/>}/><FormError>{errors.root?.message}</FormError><Pressable accessibilityRole="button" onPress={()=>router.push("/forgot-password")}><Text style={styles.link}>Forgot Password?</Text></Pressable><PrimaryButton title="Log in" loading={isSubmitting} onPress={handleSubmit(submit)}/><Pressable accessibilityRole="button" onPress={()=>router.replace("/signup")}><Text style={styles.bottom}>Don&apos;t have an account? <Text style={styles.strong}>Create account</Text></Text></Pressable></Screen>}

export function ForgotPasswordScreen(){const router=useRouter();const{setResetFlow}=useResetFlow();const{control,handleSubmit,formState:{errors,isSubmitting},setError}=useForm<ForgotPasswordValues>({resolver:zodResolver(forgotPasswordSchema),defaultValues:{email:""}});const submit=async(values:ForgotPasswordValues)=>{try{const result=await post<{resendAvailableIn:number}>("/auth/forgot-password",values);setResetFlow({email:values.email,resendAvailableIn:result.data?.resendAvailableIn??60});router.push("/verify-reset-otp");}catch(error){setError("root",{message:errorMessage(error,"Unable to start password recovery.")});}};return <Screen><BrandHeader/><Heading title="Forgot password?" copy="Enter your email address and we&apos;ll send a password reset code."/><Controller control={control} name="email" render={({field})=><TextField label="Email address" keyboardType="email-address" autoComplete="email" value={field.value} onChangeText={field.onChange} error={errors.email?.message}/>}/><FormError>{errors.root?.message}</FormError><PrimaryButton title="Send reset code" loading={isSubmitting} onPress={handleSubmit(submit)}/><Pressable accessibilityRole="button" onPress={()=>router.replace("/login")}><Text style={styles.bottom}>Back to <Text style={styles.strong}>Log in</Text></Text></Pressable></Screen>}

export function ResetOtpScreen(){const router=useRouter();const{resetFlow,setResetFlow}=useResetFlow();const[digits,setDigits]=useState(["","","","","",""]);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[remaining,setRemaining]=useState(resetFlow?.resendAvailableIn??0);const refs=useRef<Array<TextInput|null>>([]);useEffect(()=>{if(!resetFlow)router.replace("/forgot-password");},[resetFlow,router]);useEffect(()=>{if(!remaining)return;const timer=setTimeout(()=>setRemaining(value=>Math.max(0,value-1)),1000);return()=>clearTimeout(timer);},[remaining]);const submit=async(code=digits.join(""))=>{if(!resetFlow||code.length!==6||busy)return;setBusy(true);setMessage("");try{const result=await post<{resetToken:string}>("/auth/verify-password-reset-otp",{email:resetFlow.email,otp:code});if(!result.data?.resetToken)throw new Error("Reset proof was not returned");setResetFlow({...resetFlow,resetToken:result.data.resetToken});router.replace("/reset-password");}catch(error){setMessage(errorMessage(error,"Unable to verify this code."));setDigits(["","","","","",""]);refs.current[0]?.focus();}finally{setBusy(false);}};const change=(value:string,index:number)=>{const digit=value.replace(/\D/g,"").slice(-1);const next=[...digits];next[index]=digit;setDigits(next);if(digit&&index<5)refs.current[index+1]?.focus();if(next.join("").length===6&&!next.includes(""))void submit(next.join(""));};const resend=async()=>{if(!resetFlow||remaining||busy)return;setBusy(true);try{const result=await post<{resendAvailableIn:number}>("/auth/forgot-password",{email:resetFlow.email});const seconds=result.data?.resendAvailableIn??60;setRemaining(seconds);setResetFlow({...resetFlow,resendAvailableIn:seconds});setMessage("If an account exists, a new code has been sent.");}catch(error){setMessage(errorMessage(error,"Unable to send another code."));}finally{setBusy(false);}};return <Screen><BrandHeader/><Heading title="Check your email for the password reset code" copy="Enter the six-digit code we sent to your email address."/><Text style={styles.otpLabel}>Enter OTP here</Text><View style={styles.otpRow}>{digits.map((digit,index)=><TextInput key={index} ref={node=>{refs.current[index]=node;}} accessibilityLabel={`Reset code digit ${index+1} of 6`} autoFocus={index===0} value={digit} onChangeText={value=>change(value,index)} onKeyPress={({nativeEvent})=>{if(nativeEvent.key==="Backspace"&&!digits[index]&&index>0)refs.current[index-1]?.focus();}} keyboardType="number-pad" maxLength={1} style={styles.box}/>)}</View>{busy?<ActivityIndicator color={colors.brown} style={styles.spinner}/>:null}<FormError>{message&&!message.startsWith("If an account")?message:undefined}</FormError>{message.startsWith("If an account")?<Text accessibilityLiveRegion="polite" style={styles.success}>{message}</Text>:null}<PrimaryButton title={remaining?`Resend code in 0:${String(remaining).padStart(2,"0")}`:"Resend code"} disabled={Boolean(remaining)||busy} onPress={resend}/></Screen>}

export function ResetPasswordScreen(){const router=useRouter();const{resetFlow,setResetFlow}=useResetFlow();const{clearSession}=useCustomerSession();const{control,handleSubmit,watch,formState:{errors,isSubmitting},setError}=useForm<ResetPasswordValues>({resolver:zodResolver(resetPasswordSchema),defaultValues:{newPassword:"",confirmPassword:""},mode:"onChange"});const password=watch("newPassword","");useEffect(()=>{if(!resetFlow?.resetToken)router.replace("/forgot-password");},[resetFlow,router]);const submit=async(values:ResetPasswordValues)=>{if(!resetFlow?.resetToken)return;try{await post("/auth/reset-password",{resetToken:resetFlow.resetToken,newPassword:values.newPassword,confirmPassword:values.confirmPassword});await clearSession();setResetFlow(null);router.replace("/login");}catch(error){setError("root",{message:errorMessage(error,"Unable to reset your password.")});}};return <Screen><BrandHeader/><Heading title="Set a new password" copy="Choose a strong password you will remember."/><Text style={styles.notice}>For your security, you will be logged out on all devices and need to log in again.</Text><Controller control={control} name="newPassword" render={({field})=><TextField label="New password" secure autoComplete="new-password" value={field.value} onChangeText={field.onChange} error={errors.newPassword?.message}/>}/><PasswordChecklist value={password}/><Controller control={control} name="confirmPassword" render={({field})=><TextField label="Confirm new password" secure autoComplete="new-password" value={field.value} onChangeText={field.onChange} error={errors.confirmPassword?.message}/>}/><FormError>{errors.root?.message}</FormError><PrimaryButton title="Save new password" loading={isSubmitting} onPress={handleSubmit(submit)}/></Screen>}

const styles=StyleSheet.create({link:{color:colors.brown,fontWeight:"800",fontSize:13,marginBottom:4},bottom:{textAlign:"center",marginTop:18,color:colors.muted,fontSize:13},strong:{color:colors.brown,fontWeight:"800"},notice:{backgroundColor:colors.cream,color:colors.ink,borderRadius:radii.control,padding:13,fontSize:13,lineHeight:19,marginBottom:16},otpLabel:{fontSize:13,fontWeight:"700",marginBottom:8},otpRow:{flexDirection:"row",gap:8},box:{flex:1,height:52,backgroundColor:colors.inputBackground,borderRadius:radii.control,textAlign:"center",fontSize:21,fontWeight:"800",color:colors.inputText,borderWidth:1,borderColor:colors.inputBorder},spinner:{marginTop:16},success:{color:colors.success,fontWeight:"700",fontSize:13,marginTop:15,textAlign:"center"}});
