import { useEffect, useMemo, useRef, useState } from "react";
import { usePathname, useRouter } from "expo-router";
import { AppState, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ApiError, patchAuthenticated } from "@/api/client";
import { consumeMobileOnboardingAnalytics, customerPersonaForAnalytics, trackCustomerEvent, trackCustomerEventOnce } from "@/analytics/customer";
import { BrandHeader, FormError, Heading, PrimaryButton, Screen, TextField } from "@/components/ui";
import { PersonaSwitcher } from "@/components/persona-switcher";
import { useCustomerSession } from "@/store/auth-flow";
import { colors, radii } from "@/theme/tokens";
import type { NextAction, OnboardingStatus, Persona } from "@/types/auth";

const locations=["Lekki, Lagos","Lekki Phase 1, Lagos","Lekki Peninsula Scheme II, Lagos","Victoria Island, Lagos","Ikoyi, Lagos","Ikeja, Lagos","Ajah, Lagos","Abuja"];
// Text inputs use placeholderTextColor={colors.inputPlaceholder} through the shared input style.
const message=(error:unknown)=>{const api=error as ApiError;return api.message??"Unable to save onboarding.";};
function Header({title,copy}:{title:string;copy:string}){return <><BrandHeader/><Heading title={title} copy={copy}/></>}
function useWizard(){const router=useRouter();const pathname=usePathname();const type:Persona["type"]=pathname.includes("seller")?"SELLER_DEVELOPER":"BUYER";const session=useCustomerSession();const[ready,setReady]=useState(false);const completed=useRef(false);const backgrounded=useRef(false);useEffect(()=>{if(session.isHydrating||!session.accessToken)return;void Promise.all([session.authenticatedRequest<OnboardingStatus>("/onboarding/status","GET"),session.fetchPersonas()]).then(([result,personas])=>{const status=result.data;const persona=personas?.personas.find(item=>item.type===type);if(status)session.updatePersonaState(status);if(!status||persona?.activated!==true){router.replace(status?session.routeFromNextAction(status.nextAction):"/login");return;}setReady(true);void trackCustomerEventOnce(`onboarding-start-${type}`,"Onboarding Wizard Started",{persona_type:customerPersonaForAnalytics(type),trigger_source:consumeMobileOnboardingAnalytics()});}).catch(()=>{void session.clearSession();router.replace("/login");});},[session.isHydrating,session.accessToken,type]);useEffect(()=>{const subscription=AppState.addEventListener("change",state=>{if(!ready||completed.current)return;if((state==="background"||state==="inactive")&&!backgrounded.current){backgrounded.current=true;void trackCustomerEvent("Onboarding Wizard Abandoned",{persona_type:customerPersonaForAnalytics(type)});}if(state==="active")backgrounded.current=false;});return()=>subscription.remove();},[ready,type]);return{...session,router,ready,complete:()=>{completed.current=true;}}}
export function BuyerOnboarding(){const{accessToken,routeFromNextAction,router,ready,clearSession,complete}=useWizard();const[selected,setSelected]=useState<string[]>([]);const[min,setMin]=useState("");const[max,setMax]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);const submit=async(skip=false)=>{if(!accessToken||busy)return;const low=min?Number(min):undefined;const high=max?Number(max):undefined;if(!skip&&low!==undefined&&high!==undefined&&high<low){setError("Maximum budget must be greater than or equal to minimum budget.");return;}if(!skip)void trackCustomerEventOnce("buyer-onboarding-completed","Buyer Onboarding Completed",{preferred_locations:selected,budget_provided:low!==undefined||high!==undefined,skipped_budget:false});setBusy(true);try{const result=await patchAuthenticated<{nextAction:NextAction}>("/onboarding/buyer",skip?{skip:true}:{preferredLocations:selected,budgetMin:low,budgetMax:high,currency:"NGN"},accessToken);complete();router.replace(routeFromNextAction(result.data?.nextAction??"OPEN_BUYER_DASHBOARD"));}catch(caught){if((caught as ApiError).code?.startsWith("ACCOUNT_"))await clearSession();setError(message(caught));}finally{setBusy(false);}};if(!ready)return null;return <Screen><Header title="Tell us what you&apos;re looking for" copy="Select your preferred locations and set a budget to find the right property."/><Text style={styles.label}>Preferred locations</Text><View style={styles.choices}>{locations.slice(0,4).map(location=><Pressable key={location} onPress={()=>setSelected(items=>items.includes(location)?items.filter(item=>item!==location):[...items,location])} style={styles.choice}><Text>{location}</Text></Pressable>)}</View><TextInput accessibilityLabel="Minimum budget" value={min} onChangeText={value=>setMin(value.replace(/\D/g,""))} keyboardType="number-pad" style={styles.input}/><TextInput accessibilityLabel="Maximum budget" value={max} onChangeText={value=>setMax(value.replace(/\D/g,""))} keyboardType="number-pad" style={styles.input}/><FormError>{error}</FormError><PrimaryButton title="Find a property" loading={busy} onPress={()=>void submit(false)}/><Pressable onPress={()=>void submit(true)}><Text style={styles.skip}>Skip for now</Text></Pressable></Screen>}
export function SellerOnboarding(){const{accessToken,routeFromNextAction,router,ready,clearSession,complete}=useWizard();const[type,setType]=useState<"INDIVIDUAL"|"BUSINESS">("INDIVIDUAL");const[companyName,setCompanyName]=useState("");const[companyAddress,setCompanyAddress]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);const submit=async(skip=false)=>{if(!accessToken||busy)return;if(!skip&&type==="BUSINESS"&&(!companyName.trim()||!companyAddress.trim())){setError("Company name and address are required for a business profile.");return;}if(!skip)void trackCustomerEventOnce("seller-onboarding-completed","Seller Onboarding Completed",{profile_type:type==="BUSINESS"?"Business":"Individual",company_name_provided:Boolean(companyName.trim()),company_address_provided:Boolean(companyAddress.trim())});setBusy(true);try{const body=skip?{skip:true}:type==="BUSINESS"?{profileType:type,companyName:companyName.trim(),companyAddress:companyAddress.trim()}:{profileType:type};const result=await patchAuthenticated<{nextAction:NextAction}>("/onboarding/seller",body,accessToken);complete();router.replace(routeFromNextAction(result.data?.nextAction??"OPEN_SELLER_DASHBOARD"));}catch(caught){if((caught as ApiError).code?.startsWith("ACCOUNT_"))await clearSession();setError(message(caught));}finally{setBusy(false);}};if(!ready)return null;return <Screen><Header title="Tell us about you" copy="This helps us tailor your listing experience."/><Pressable onPress={()=>setType("INDIVIDUAL")}><Text>Individual</Text></Pressable><Pressable onPress={()=>setType("BUSINESS")}><Text>Business</Text></Pressable>{type==="BUSINESS"?<><TextField label="Company name" value={companyName} onChangeText={setCompanyName}/><TextField label="Company address" value={companyAddress} onChangeText={setCompanyAddress}/></>:null}<FormError>{error}</FormError><PrimaryButton title="Continue" loading={busy} onPress={()=>void submit(false)}/><Pressable onPress={()=>void submit(true)}><Text style={styles.skip}>Skip for now</Text></Pressable></Screen>}
export function DashboardPlaceholder({seller=false}:{seller?:boolean}){const{activePersona,logout,routeFromNextAction}=useCustomerSession();const router=useRouter();const[switcher,setSwitcher]=useState(false);const leave=async()=>{await logout();router.replace("/login");};return <Screen><Header title={seller?"Seller Dashboard":"Buyer Dashboard"} copy={seller?"Seller dashboard placeholder":"Buyer dashboard placeholder"}/><Text>Current mode: {activePersona}</Text><PrimaryButton title="Switch profile" onPress={()=>setSwitcher(true)}/><PrimaryButton title="Log out" onPress={()=>void leave()}/><PersonaSwitcher visible={switcher} onClose={()=>setSwitcher(false)} onNavigate={action=>router.replace(routeFromNextAction(action))}/></Screen>}
const styles=StyleSheet.create({label:{fontWeight:"800",marginBottom:8},choices:{gap:8,marginBottom:16},choice:{padding:12,borderWidth:1,borderColor:colors.line,borderRadius:radii.control},input:{height:52,borderWidth:1,borderColor:colors.inputBorder,borderRadius:radii.control,marginBottom:12,padding:12,backgroundColor:colors.inputBackground,color:colors.inputText},skip:{textAlign:"center",padding:18,color:colors.brown,fontWeight:"800"}});
