import { Feather } from "@expo/vector-icons";
import { forwardRef, useRef, useState } from "react";
import type { TextInput } from "react-native";
import { Image, Platform, Pressable, StyleSheet, Text, TextInput as Input, View } from "react-native";
import { KeyboardAwareScrollView } from "react-native-keyboard-controller";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors, radii, sizes, spacing } from "@/theme/tokens";

export function Screen({ children }: { children: React.ReactNode }) { return <SafeAreaView style={styles.safe}><KeyboardAwareScrollView style={styles.fill} contentContainerStyle={styles.scroll} mode="insets" bottomOffset={20} extraKeyboardSpace={20} keyboardShouldPersistTaps="handled" keyboardDismissMode={Platform.OS === "ios" ? "interactive" : "on-drag"}>{children}</KeyboardAwareScrollView></SafeAreaView>; }
export function BrandHeader() { return <View style={styles.brand}><Image accessibilityLabel="Beryl Shelter" source={require("../../assets/brand/beryl-shelter-logo.png")} style={styles.logo}/><Text style={styles.brandName}>Beryl Shelter</Text></View>; }
export function Heading({ title, copy }: { title: string; copy: string }) { return <View style={styles.heading}><Text accessibilityRole="header" style={styles.title}>{title}</Text><Text style={styles.copy}>{copy}</Text></View>; }
export const TextField = forwardRef<Input, { label: string; error?: string; secure?: boolean; value?: string; onChangeText?: (value: string) => void; keyboardType?: "default" | "email-address" | "phone-pad" | "number-pad"; autoComplete?: "name" | "email" | "tel" | "password" | "new-password"; returnKeyType?: "next" | "done"; onSubmitEditing?: () => void; placeholder?: string }>(function TextField({ label, error, secure, value, onChangeText, ...props }, ref) { const [hidden, setHidden] = useState(Boolean(secure)); return <View style={styles.field}><Text style={styles.label}>{label}</Text><View><Input ref={ref} value={value} onChangeText={onChangeText} secureTextEntry={hidden} accessibilityLabel={label} style={[styles.input, error ? styles.inputError : null, secure ? styles.inputPassword : null]} {...props} placeholderTextColor={colors.inputPlaceholder} selectionColor={colors.selectionColor} cursorColor={colors.selectionColor} />{secure ? <Pressable accessibilityRole="button" accessibilityLabel={hidden ? `Show ${label}` : `Hide ${label}`} style={styles.eye} onPress={() => setHidden((next) => !next)}><Feather name={hidden ? "eye" : "eye-off"} size={20} color={colors.muted} /></Pressable> : null}</View>{error ? <Text accessibilityLiveRegion="polite" style={styles.error}>{error}</Text> : null}</View>; });
export function PrimaryButton({ title, onPress, loading, disabled }: { title: string; onPress: () => void; loading?: boolean; disabled?: boolean }) { return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled || loading} onPress={onPress} style={({ pressed }) => [styles.button, (disabled || loading) ? styles.disabled : null, pressed ? styles.pressed : null]}><Text style={styles.buttonText}>{loading ? "Please wait…" : title}</Text></Pressable>; }
export function FormError({ children }: { children?: string }) { return children ? <View accessibilityLiveRegion="polite" style={styles.alert}><Feather name="alert-circle" size={17} color="#fff"/><Text style={styles.alertText}>{children}</Text></View> : null; }
export function PasswordChecklist({ value }: { value: string }) { const rules: ReadonlyArray<readonly [label: string, pass: boolean]> = [["At least 8 characters", value.length >= 8], ["At least 1 uppercase letter", /[A-Z]/.test(value)], ["At least 1 lowercase letter", /[a-z]/.test(value)], ["At least 1 number", /\d/.test(value)], ["At least 1 special character", /[^A-Za-z0-9]/.test(value)]]; const valid = rules.filter(([, pass]) => pass).length; const state=value.length===0?null:valid>=5?{label:"Strong",message:"Great job! This password is strong and secure.",color:colors.passwordStrong}:valid>=3?{label:"Moderate",message:"Getting stronger. Add more symbols or numbers for better protection.",color:colors.passwordModerate}:{label:"Weak",message:"Try a longer, more unique password that is harder to guess.",color:colors.passwordWeak}; return <View style={styles.checklist}>{state?<><View style={styles.meterRow}><Text style={[styles.strength,{color:state.color}]}>{state.label}</Text><Text style={styles.strength}>{valid}/5</Text></View><View style={styles.meter}><View style={[styles.meterProgress, { width: `${valid * 20}%`, backgroundColor:state.color }]} /></View><Text style={{fontSize:12,lineHeight:18,marginBottom:8,color:state.color}}>{state.message}</Text></>:<View style={styles.meter}><View style={[styles.meterProgress,{width:"0%",backgroundColor:colors.passwordNeutral}]}/></View>}<Text style={styles.rulesTitle}>Password must contain</Text>{rules.map(([label, pass]) => <Text key={label} style={[styles.rule, pass ? styles.rulePass : null]}>{pass ? "✓" : "○"}  {label}</Text>)}</View>; }
const styles = StyleSheet.create({ safe:{ flex:1, backgroundColor:colors.canvas }, fill:{ flex:1 }, scroll:{ flexGrow:1, padding:spacing.lg, paddingBottom:spacing.xxl }, brand:{ alignItems:"center", marginTop:spacing.sm, marginBottom:spacing.xl }, logo:{width:38,height:38,resizeMode:"contain",marginBottom:9}, brandName:{ color:colors.brown,fontWeight:"800",fontSize:15 }, heading:{ marginBottom:spacing.lg }, title:{ fontSize:32, lineHeight:37, fontWeight:"800", color:colors.ink, letterSpacing:-1.1 }, copy:{ marginTop:8, fontSize:15, lineHeight:23, color:colors.muted }, field:{ gap:6, marginBottom:12 }, label:{ fontWeight:"700",fontSize:13,color:colors.ink }, input:{ height:sizes.input,borderRadius:radii.control,backgroundColor:colors.inputBackground,paddingHorizontal:15,fontSize:16,color:colors.inputText,borderWidth:1,borderColor:colors.inputBorder }, inputPassword:{ paddingRight:50 }, inputError:{ borderColor:colors.danger }, eye:{ position:"absolute",right:12,top:16 }, error:{ color:colors.danger,fontSize:12 }, button:{ height:sizes.button,borderRadius:radii.pill,backgroundColor:colors.brown,justifyContent:"center",alignItems:"center",marginTop:10 }, buttonText:{ color:"white",fontSize:16,fontWeight:"800" }, disabled:{ opacity:.55 }, pressed:{ opacity:.82 }, alert:{ flexDirection:"row",alignItems:"center",gap:8,borderRadius:radii.control,backgroundColor:colors.danger,padding:13,marginBottom:12 }, alertText:{ color:"white",fontSize:13,flex:1 }, checklist:{ marginTop:-2, marginBottom:8 }, meterRow:{ flexDirection:"row",justifyContent:"space-between" }, strength:{ fontSize:12,fontWeight:"700",color:colors.ink }, meter:{ height:5,backgroundColor:colors.line,borderRadius:6,marginVertical:7 }, meterProgress:{ height:5,backgroundColor:colors.brown,borderRadius:6 }, rulesTitle:{ fontSize:12,color:colors.muted,marginBottom:3 }, rule:{ fontSize:12,color:colors.muted,lineHeight:19 }, rulePass:{ color:colors.success } });
