import { Feather } from "@expo/vector-icons";
import { forwardRef, useRef, useState } from "react";
import type { TextInput } from "react-native";
import { Image, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput as Input, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors, radii, sizes, spacing } from "@/theme/tokens";

export function Screen({ children }: { children: React.ReactNode }) { return <SafeAreaView style={styles.safe}><KeyboardAvoidingView style={styles.fill} behavior={Platform.OS === "ios" ? "padding" : undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.scroll}>{children}</ScrollView></KeyboardAvoidingView></SafeAreaView>; }
export function BrandHeader() { return <View style={styles.brand}><Image accessibilityLabel="Beryl Shelter" source={require("../../assets/brand/beryl-shelter-logo.png")} style={styles.logo}/><Text style={styles.brandName}>Beryl Shelter</Text></View>; }
export function Heading({ title, copy }: { title: string; copy: string }) { return <View style={styles.heading}><Text accessibilityRole="header" style={styles.title}>{title}</Text><Text style={styles.copy}>{copy}</Text></View>; }
export const TextField = forwardRef<Input, { label: string; error?: string; secure?: boolean; value?: string; onChangeText?: (value: string) => void; keyboardType?: "default" | "email-address" | "phone-pad" | "number-pad"; autoComplete?: "name" | "email" | "tel" | "password" | "new-password"; returnKeyType?: "next" | "done"; onSubmitEditing?: () => void; placeholder?: string }>(function TextField({ label, error, secure, value, onChangeText, ...props }, ref) { const [hidden, setHidden] = useState(Boolean(secure)); return <View style={styles.field}><Text style={styles.label}>{label}</Text><View><Input ref={ref} value={value} onChangeText={onChangeText} secureTextEntry={hidden} accessibilityLabel={label} style={[styles.input, error ? styles.inputError : null, secure ? styles.inputPassword : null]} {...props} />{secure ? <Pressable accessibilityRole="button" accessibilityLabel={hidden ? `Show ${label}` : `Hide ${label}`} style={styles.eye} onPress={() => setHidden((next) => !next)}><Feather name={hidden ? "eye" : "eye-off"} size={20} color={colors.muted} /></Pressable> : null}</View>{error ? <Text accessibilityLiveRegion="polite" style={styles.error}>{error}</Text> : null}</View>; });
export function PrimaryButton({ title, onPress, loading, disabled }: { title: string; onPress: () => void; loading?: boolean; disabled?: boolean }) { return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled || loading} onPress={onPress} style={({ pressed }) => [styles.button, (disabled || loading) ? styles.disabled : null, pressed ? styles.pressed : null]}><Text style={styles.buttonText}>{loading ? "Please wait…" : title}</Text></Pressable>; }
export function FormError({ children }: { children?: string }) { return children ? <View accessibilityLiveRegion="polite" style={styles.alert}><Feather name="alert-circle" size={17} color="#fff"/><Text style={styles.alertText}>{children}</Text></View> : null; }
export function PasswordChecklist({ value }: { value: string }) { const rules: ReadonlyArray<readonly [label: string, pass: boolean]> = [["At least 8 characters", value.length >= 8], ["1 uppercase letter", /[A-Z]/.test(value)], ["1 lowercase letter", /[a-z]/.test(value)], ["1 number", /\d/.test(value)], ["1 special character", /[^A-Za-z0-9]/.test(value)]]; const valid = rules.filter(([, pass]) => pass).length; return <View style={styles.checklist}><View style={styles.meterRow}><Text style={styles.strength}>{valid >= 5 ? "Strong" : valid >= 3 ? "Fair" : "Weak"}</Text><Text style={styles.strength}>{valid}/5</Text></View><View style={styles.meter}><View style={[styles.meterProgress, { width: `${valid * 20}%` }]} /></View><Text style={styles.rulesTitle}>Password must contain</Text>{rules.map(([label, pass]) => <Text key={label} style={[styles.rule, pass ? styles.rulePass : null]}>{pass ? "✓" : "○"}  {label}</Text>)}</View>; }
const styles = StyleSheet.create({ safe:{ flex:1, backgroundColor:colors.canvas }, fill:{ flex:1 }, scroll:{ flexGrow:1, padding:spacing.lg, paddingBottom:spacing.xxl }, brand:{ alignItems:"center", marginTop:spacing.sm, marginBottom:spacing.xl }, logo:{width:38,height:38,resizeMode:"contain",marginBottom:9}, brandName:{ color:colors.brown,fontWeight:"800",fontSize:15 }, heading:{ marginBottom:spacing.lg }, title:{ fontSize:32, lineHeight:37, fontWeight:"800", color:colors.ink, letterSpacing:-1.1 }, copy:{ marginTop:8, fontSize:15, lineHeight:23, color:colors.muted }, field:{ gap:6, marginBottom:12 }, label:{ fontWeight:"700",fontSize:13,color:colors.ink }, input:{ height:sizes.input,borderRadius:radii.control,backgroundColor:colors.field,paddingHorizontal:15,fontSize:16,color:colors.ink }, inputPassword:{ paddingRight:50 }, inputError:{ borderWidth:1,borderColor:colors.danger }, eye:{ position:"absolute",right:12,top:16 }, error:{ color:colors.danger,fontSize:12 }, button:{ height:sizes.button,borderRadius:radii.pill,backgroundColor:colors.brown,justifyContent:"center",alignItems:"center",marginTop:10 }, buttonText:{ color:"white",fontSize:16,fontWeight:"800" }, disabled:{ opacity:.55 }, pressed:{ opacity:.82 }, alert:{ flexDirection:"row",alignItems:"center",gap:8,borderRadius:radii.control,backgroundColor:colors.danger,padding:13,marginBottom:12 }, alertText:{ color:"white",fontSize:13,flex:1 }, checklist:{ marginTop:-2, marginBottom:8 }, meterRow:{ flexDirection:"row",justifyContent:"space-between" }, strength:{ fontSize:12,fontWeight:"700",color:colors.ink }, meter:{ height:5,backgroundColor:colors.line,borderRadius:6,marginVertical:7 }, meterProgress:{ height:5,backgroundColor:colors.brown,borderRadius:6 }, rulesTitle:{ fontSize:12,color:colors.muted,marginBottom:3 }, rule:{ fontSize:12,color:colors.muted,lineHeight:19 }, rulePass:{ color:colors.success } });
