import type { AuthenticatedRequester } from "@/api/marketplace";
import { normalizeSellerDraft } from "@/seller-marketplace/helpers";
import type { ApiEnvelope } from "@/types/auth";
import type { SellerDocument, SellerDraft, SellerImage, SellerListingResult, SellerManagement, SellerMandate, SellerMandateInput, SellerReview, SellerStatus, SellerSubmission } from "@/types/seller-marketplace";
const root="/marketplace/seller/properties";
export const createSellerDraft=(r:AuthenticatedRequester,body:unknown={})=>r<{property:SellerDraft}>(root,"POST",body);
const normalizedDraftResponse=async(response:Promise<ApiEnvelope<{property:SellerDraft}>>)=>{const result=await response;if(result.data?.property)result.data.property=normalizeSellerDraft(result.data.property);return result};
export const getSellerDraft=(r:AuthenticatedRequester,id:string)=>normalizedDraftResponse(r<{property:SellerDraft}>(`${root}/${id}`,"GET"));
export const saveSellerDraft=(r:AuthenticatedRequester,id:string,body:unknown)=>normalizedDraftResponse(r<{property:SellerDraft}>(`${root}/${id}`,"PATCH",body));
export const deleteSellerDraft=(r:AuthenticatedRequester,id:string)=>r<{propertyId:string;deleted:true}>(`${root}/${id}`,"DELETE");
export const listSellerProperties=(r:AuthenticatedRequester,status:SellerStatus,page=1)=>r<SellerListingResult>(`${root}?status=${status}&page=${page}&limit=10`,"GET");
export const sellerManagement=(r:AuthenticatedRequester,id:string)=>r<{management:SellerManagement}>(`${root}/${id}/management`,"GET");
export const uploadSellerImages=(r:AuthenticatedRequester,id:string,body:FormData)=>r<{images:SellerImage[]}>(`${root}/${id}/images`,"POST",body);
export const deleteSellerImage=(r:AuthenticatedRequester,id:string,imageId:string)=>r<never>(`${root}/${id}/images/${imageId}`,"DELETE");
export const reorderSellerImages=(r:AuthenticatedRequester,id:string,imageIds:string[])=>r<{images:SellerImage[]}>(`${root}/${id}/images/order`,"PATCH",{imageIds});
export const setSellerCover=(r:AuthenticatedRequester,id:string,imageId:string)=>r<{images:SellerImage[]}>(`${root}/${id}/images/${imageId}/cover`,"PATCH",{});
export const uploadSellerDocument=(r:AuthenticatedRequester,id:string,body:FormData)=>r<{document:SellerDocument}>(`${root}/${id}/documents`,"POST",body);
export const deleteSellerDocument=(r:AuthenticatedRequester,id:string,documentId:string)=>r<never>(`${root}/${id}/documents/${documentId}`,"DELETE");
export const getSellerMandate=(r:AuthenticatedRequester,id:string)=>r<{mandate:SellerMandate|null}>(`${root}/${id}/mandate`,"GET");
export const saveSellerMandate=(r:AuthenticatedRequester,id:string,body:SellerMandateInput)=>r<{mandate:SellerMandate}>(`${root}/${id}/mandate`,"PUT",body);
export const getSellerReview=(r:AuthenticatedRequester,id:string)=>r<{review:SellerReview}>(`${root}/${id}/review`,"GET");
export const submitSellerProperty=(r:AuthenticatedRequester,id:string)=>r<SellerSubmission>(`${root}/${id}/submit`,"POST",{});
export const reopenSellerProperty=(r:AuthenticatedRequester,id:string)=>r<{propertyId:string;status:"DRAFT";currentStep:"REVIEW";nextAction:"EDIT_REJECTED_LISTING"}>(`${root}/${id}/reopen`,"POST",{});
