import { Feather } from "@expo/vector-icons";
import { KeyboardAwareScrollView } from "react-native-keyboard-controller";
import { Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { bedroomOptions, conditionOptions, formatNumericInput, furnishingOptions, propertyTypeOptions } from "@/marketplace/filters";
import { colors, radii, sizes, spacing } from "@/theme/tokens";
import type { MarketplaceFilters, MarketplaceSort } from "@/types/marketplace";

const toggle = (items: string[], value: string) => items.includes(value) ? items.filter(item => item !== value) : [...items, value];
const Checkbox = ({ selected, label, onPress }: { selected: boolean; label: string; onPress: () => void }) => <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: selected }} accessibilityLabel={label} onPress={onPress} style={styles.checkboxRow}><View style={[styles.checkbox, selected && styles.checkboxSelected]}>{selected ? <Feather name="check" size={15} color={colors.white}/> : null}</View><Text style={styles.checkboxLabel}>{label}</Text></Pressable>;

export function FilterSheet({ visible, value, error, onChange, onApply, onClear, onClose }: { visible: boolean; value: MarketplaceFilters; error?: string; onChange: (next: MarketplaceFilters) => void; onApply: () => void; onClear: () => void; onClose: () => void }) {
  return <Modal transparent visible={visible} animationType="slide" onRequestClose={onClose}><SafeAreaView style={styles.safe}><Pressable style={styles.backdrop} onPress={onClose}/><View accessibilityViewIsModal style={styles.sheet}>
    <KeyboardAwareScrollView keyboardShouldPersistTaps="handled" bottomOffset={18} contentContainerStyle={styles.sheetContent}>
      <View style={styles.sheetHeader}><Text accessibilityRole="header" style={styles.sheetTitle}>Filters</Text><View style={styles.headerActions}><Pressable accessibilityRole="button" onPress={onClear}><Text style={styles.clear}>Clear</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Close filters" onPress={onClose} style={styles.close}><Feather name="x" size={23} color={colors.ink}/></Pressable></View></View>
      <Text style={styles.sectionTitle}>Price Range</Text><View style={styles.priceRow}><View style={styles.money}><Text style={styles.currency}>₦</Text><TextInput accessibilityLabel="Minimum price" value={value.minPrice} onChangeText={text=>onChange({...value,minPrice:formatNumericInput(text)})} placeholder="Min. Price" keyboardType="number-pad" placeholderTextColor={colors.inputPlaceholder} selectionColor={colors.selectionColor} cursorColor={colors.selectionColor} style={styles.moneyInput}/></View><View style={styles.money}><Text style={styles.currency}>₦</Text><TextInput accessibilityLabel="Maximum price" value={value.maxPrice} onChangeText={text=>onChange({...value,maxPrice:formatNumericInput(text)})} placeholder="Max. Price" keyboardType="number-pad" placeholderTextColor={colors.inputPlaceholder} selectionColor={colors.selectionColor} cursorColor={colors.selectionColor} style={styles.moneyInput}/></View></View>
      {error ? <Text accessibilityLiveRegion="polite" style={styles.error}>{error}</Text> : null}
      <Text style={styles.sectionTitle}>Property Type</Text>{propertyTypeOptions.map(([key,label])=><Checkbox key={key} label={label} selected={value.propertyTypes.includes(key)} onPress={()=>onChange({...value,propertyTypes:toggle(value.propertyTypes,key)})}/>)}
      <Text style={styles.sectionTitle}>Bedrooms</Text><View style={styles.bedrooms}>{bedroomOptions.map(option=><Pressable key={option} accessibilityRole="radio" accessibilityLabel={`${option} bedrooms`} accessibilityState={{ selected:value.bedrooms===option }} onPress={()=>onChange({...value,bedrooms:value.bedrooms===option?"":option})} style={[styles.bedroom,value.bedrooms===option&&styles.bedroomSelected]}><Text style={[styles.bedroomText,value.bedrooms===option&&styles.bedroomTextSelected]}>{option}</Text></Pressable>)}</View>
      <Text style={styles.sectionTitle}>Condition</Text>{conditionOptions.map(([key,label])=><Checkbox key={key} label={label} selected={value.conditions.includes(key)} onPress={()=>onChange({...value,conditions:toggle(value.conditions,key)})}/>)}
      <Text style={styles.sectionTitle}>Furnishing</Text>{furnishingOptions.map(([key,label])=><Checkbox key={key} label={label} selected={value.furnishings.includes(key)} onPress={()=>onChange({...value,furnishings:toggle(value.furnishings,key)})}/>)}
      <Pressable accessibilityRole="button" onPress={onApply} style={styles.apply}><Text style={styles.applyText}>Apply Filters</Text></Pressable>
    </KeyboardAwareScrollView>
  </View></SafeAreaView></Modal>;
}

const sortOptions: Array<[MarketplaceSort,string]> = [["DEFAULT","Default"],["PRICE_HIGH_TO_LOW","Highest to Lowest Price"],["PRICE_LOW_TO_HIGH","Lowest to Highest Price"],["BEDS","Beds"],["MOST_RECENT","Most Recent"]];
export function SortSheet({ visible, value, onChange, onClose }: { visible:boolean; value:MarketplaceSort; onChange:(value:MarketplaceSort)=>void; onClose:()=>void }) { return <Modal transparent visible={visible} animationType="slide" onRequestClose={onClose}><SafeAreaView style={styles.safe}><Pressable style={styles.backdrop} onPress={onClose}/><View accessibilityViewIsModal style={styles.sortSheet}><View style={styles.sheetHeader}><Text accessibilityRole="header" style={styles.sheetTitle}>Sort by</Text><Pressable accessibilityRole="button" accessibilityLabel="Close sort options" onPress={onClose} style={styles.close}><Feather name="x" size={22} color={colors.ink}/></Pressable></View>{sortOptions.map(([key,label])=><Pressable key={key} accessibilityRole="radio" accessibilityState={{selected:value===key}} accessibilityLabel={label} onPress={()=>{onChange(key);onClose();}} style={styles.sortRow}><View style={[styles.radio,value===key&&styles.radioSelected]}>{value===key?<View style={styles.radioDot}/>:null}</View><Text style={styles.sortLabel}>{label}</Text></Pressable>)}</View></SafeAreaView></Modal>; }

const styles=StyleSheet.create({
  safe:{flex:1,justifyContent:"flex-end"},backdrop:{...StyleSheet.absoluteFill,backgroundColor:colors.overlay},sheet:{maxHeight:"90%",borderTopLeftRadius:24,borderTopRightRadius:24,overflow:"hidden",backgroundColor:colors.white},sheetContent:{padding:spacing.lg,paddingBottom:spacing.xxl},sheetHeader:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:18},sheetTitle:{fontSize:23,fontWeight:"900",color:colors.ink},headerActions:{flexDirection:"row",alignItems:"center",gap:16},clear:{fontSize:13,fontWeight:"800",color:colors.brown},close:{width:sizes.touch,height:sizes.touch,alignItems:"center",justifyContent:"center"},sectionTitle:{fontSize:16,fontWeight:"900",color:colors.ink,marginTop:18,marginBottom:11},priceRow:{flexDirection:"row",gap:10},money:{flex:1,minHeight:58,borderRadius:radii.control,flexDirection:"row",alignItems:"center",paddingHorizontal:12,backgroundColor:colors.inputBackground,borderWidth:1,borderColor:colors.inputBorder},currency:{fontSize:14,fontWeight:"700",color:colors.muted},moneyInput:{flex:1,minWidth:0,height:56,paddingLeft:7,color:colors.inputText,fontSize:14},error:{marginTop:8,fontSize:12,color:colors.danger},checkboxRow:{minHeight:42,flexDirection:"row",alignItems:"center",gap:12},checkbox:{width:22,height:22,borderWidth:1,borderColor:colors.line,borderRadius:3,alignItems:"center",justifyContent:"center",backgroundColor:colors.white},checkboxSelected:{borderColor:colors.brown,backgroundColor:colors.brown},checkboxLabel:{flex:1,fontSize:14,color:colors.muted},bedrooms:{flexDirection:"row",gap:8},bedroom:{flex:1,minWidth:48,height:52,borderWidth:1,borderColor:colors.line,borderRadius:radii.control,alignItems:"center",justifyContent:"center"},bedroomSelected:{borderColor:colors.brown,backgroundColor:colors.cream},bedroomText:{fontWeight:"800",color:colors.ink},bedroomTextSelected:{color:colors.brown},apply:{minHeight:sizes.button,borderRadius:radii.pill,alignItems:"center",justifyContent:"center",backgroundColor:colors.brown,marginTop:28},applyText:{fontSize:15,fontWeight:"800",color:colors.white},sortSheet:{borderTopLeftRadius:22,borderTopRightRadius:22,padding:spacing.lg,paddingBottom:spacing.xxl,backgroundColor:colors.white},sortRow:{minHeight:48,flexDirection:"row",alignItems:"center",gap:12},radio:{width:23,height:23,borderRadius:12,borderWidth:1,borderColor:colors.line,alignItems:"center",justifyContent:"center"},radioSelected:{borderColor:colors.brown},radioDot:{width:11,height:11,borderRadius:6,backgroundColor:colors.brown},sortLabel:{fontSize:15,color:colors.muted}
});
