import { Feather } from "@expo/vector-icons";
import { useInfiniteQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { listSavedMarketplaceProperties, unsaveMarketplaceProperty } from "@/api/marketplace";
import { AccountRequiredModal, MarketplaceEmpty, MarketplaceError, MarketplaceLoading, PropertyCard } from "@/components/marketplace/marketplace-ui";
import { useCustomerSession } from "@/store/auth-flow";
import { colors, sizes, spacing } from "@/theme/tokens";
import type { MarketplaceSavedPropertyListResult } from "@/types/marketplace";

export function SavedPropertiesScreen(){const router=useRouter();const queryClient=useQueryClient();const session=useCustomerSession();const[authOpen,setAuthOpen]=useState(!session.isAuthenticated);const query=useInfiniteQuery({queryKey:["mobile-saved-properties"],enabled:session.isAuthenticated,initialPageParam:1,queryFn:({pageParam})=>listSavedMarketplaceProperties(session.authenticatedRequest,pageParam),getNextPageParam:last=>{const pagination=last.data?.pagination;return pagination&&pagination.page<pagination.total_pages?pagination.page+1:undefined;}});const items=useMemo(()=>{const byId=new Map<string,NonNullable<MarketplaceSavedPropertyListResult["saved_properties"]>[number]>();query.data?.pages.forEach(page=>page.data?.saved_properties.forEach(item=>byId.set(item.propertyId,item)));return [...byId.values()];},[query.data?.pages]);const remove=useMutation({mutationFn:(propertyId:string)=>unsaveMarketplaceProperty(session.authenticatedRequest,propertyId),onSuccess:async()=>{await Promise.all([queryClient.invalidateQueries({queryKey:["mobile-saved-properties"]}),queryClient.invalidateQueries({queryKey:["mobile-marketplace"]})]);}});const loadMore=()=>{if(query.hasNextPage&&!query.isFetchingNextPage)void query.fetchNextPage();};if(session.isHydrating)return <SafeAreaView style={styles.safe}><MarketplaceLoading label="Loading your account"/></SafeAreaView>;return <SafeAreaView style={styles.safe} edges={["top","left","right"]}><View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Back" onPress={()=>router.back()} style={styles.back}><Feather name="chevron-left" size={24} color={colors.ink}/></Pressable><Text accessibilityRole="header" style={styles.title}>Saved properties</Text><View style={styles.back}/></View>{session.isAuthenticated?<FlatList data={items} keyExtractor={item=>item.id} contentContainerStyle={styles.content} renderItem={({item})=><PropertyCard property={{...item.property,saved:true}} view="grid" saving={remove.isPending&&remove.variables===item.propertyId} onPress={()=>router.push(`/marketplace/${item.propertyId}`)} onToggleSave={()=>{if(!remove.isPending)void remove.mutateAsync(item.propertyId);}}/>} onEndReached={loadMore} onEndReachedThreshold={.4} ListEmptyComponent={query.isLoading?<MarketplaceLoading label="Loading saved properties"/>:query.isError?<MarketplaceError onRetry={()=>void query.refetch()}/>:<MarketplaceEmpty title="No saved properties yet" copy="Tap the heart on a property to keep it here." action="Browse properties" onAction={()=>router.replace("/marketplace")}/>} ListFooterComponent={query.isFetchingNextPage?<ActivityIndicator accessibilityLabel="Loading more saved properties" color={colors.brown} style={styles.footer}/>:null}/>:null}<AccountRequiredModal visible={!session.isAuthenticated&&authOpen} returnTo="/saved" onClose={()=>{setAuthOpen(false);router.replace("/marketplace");}}/></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.white},header:{minHeight:62,paddingHorizontal:spacing.md,borderBottomWidth:1,borderBottomColor:colors.line,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{width:sizes.touch,height:sizes.touch,alignItems:"center",justifyContent:"center"},title:{fontSize:20,fontWeight:"900",color:colors.ink},content:{paddingTop:spacing.lg,paddingBottom:spacing.xxl},footer:{marginVertical:18}});
