import { adminApi } from "./api";
export type BankStatus="ON_FILE"|"MISSING"|"NOT_NEEDED";export type ReferrerFilter="ALL"|"OWED"|"PAID";export type ReferrerSort="NEWEST"|"OLDEST"|"NAME_ASC"|"NAME_DESC"|"OUTSTANDING_DESC";
export type ReferrerDirectoryPage={summary:{referrers:number;referrals:number;completed:number;outstandingMinor:number;reservedMinor:number;pendingRequests:number};counts:{all:number;owed:number;paid:number};items:{id:string;fullName:string;phone:string|null;referrals:number;completed:number;earnedMinor:number;paidMinor:number;outstandingMinor:number;reservedMinor:number;availableMinor:number;pendingRequests:number;bankStatus:BankStatus}[];page:number;pageSize:number;total:number;totalPages:number};
export type WithdrawalStatus="PENDING"|"PROCESSING"|"PAID"|"REJECTED"|"CANCELLED";
export type WithdrawalItem={id:string;amountMinor:number;status:WithdrawalStatus;requestedAt:string;processingStartedAt:string|null;paidAt:string|null;rejectedAt:string|null;rejectionReason:string|null;cancelledAt:string|null;maskedAccountNumber:string;bankName:string;paymentId:string|null};
export type WithdrawalQueuePage={items:{id:string;referrerId:string;referrerName:string;referrerEmail:string;amountMinor:number;status:WithdrawalStatus;bankName:string;maskedAccountNumber:string;requestedAt:string;updatedAt:string|null;rejectionReason:string|null;paymentId:string|null}[];page:number;pageSize:number;total:number;totalPages:number};
export type ReferrerDetail={referrer:{id:string;fullName:string;email:string;phone:string|null};summary:{referrals:number;completed:number;earnedMinor:number;paidMinor:number;outstandingMinor:number;reservedMinor:number;availableMinor:number};bank:{status:BankStatus;accountName:string|null;bankName:string|null;maskedAccountNumber:string|null};withdrawals:WithdrawalItem[];items:{commissionId:string;referralCode:string;referredName:string;referralType:"PROPERTY"|"SELLER";propertyCode:string;earnedAt:string;status:"COMPLETED";rewardMinor:number;paidMinor:number;reservedMinor:number;availableMinor:number;paymentState:"OUTSTANDING"|"PARTIALLY_PAID"|"PAID";paymentId:string|null;paidAt:string|null}[];page:number;pageSize:number;total:number;totalPages:number};
export type PaymentPreview={commissionId:string;referrerId:string;referrerName:string;referralCode:string;amountMinor:number;accountName:string;bankName:string;accountNumber:string};
export type WithdrawalPaymentPreview={withdrawalId:string;referrerId:string;referrerName:string;amountMinor:number;accountName:string;bankName:string;accountNumber:string};
export function listAdminReferrers(query:{search:string;filter:ReferrerFilter;sort:ReferrerSort;page:number},signal?:AbortSignal){const params=new URLSearchParams({...query,page:String(query.page),pageSize:"6"});return adminApi<ReferrerDirectoryPage>(`/referrers?${params}`,signal?{signal}:undefined);}
export async function getAdminReferrer(id:string,page:number,signal?:AbortSignal){const value=await adminApi<{referrer:ReferrerDetail}>(`/referrers/${encodeURIComponent(id)}?page=${page}&pageSize=10`,signal?{signal}:undefined);return value.referrer;}
export function listAdminWithdrawals(status:WithdrawalStatus|"ALL",page:number,signal?:AbortSignal){const query=new URLSearchParams({status,page:String(page),pageSize:"10"});return adminApi<WithdrawalQueuePage>(`/referrers/withdrawals?${query}`,signal?{signal}:undefined);}
export async function getPaymentPreview(id:string){const value=await adminApi<{payment:PaymentPreview}>(`/referrers/commissions/${encodeURIComponent(id)}/payment`);return value.payment;}
export async function recordPayment(id:string,requestId:string,file:File){const body=new FormData();body.set("data",JSON.stringify({requestId}));body.set("receipt",file);return adminApi<{payment:{paymentId:string}}>(`/referrers/commissions/${encodeURIComponent(id)}/payment`,{method:"POST",body});}
export async function beginWithdrawal(id:string){return adminApi<{withdrawal:{id:string}}>(`/referrers/withdrawals/${encodeURIComponent(id)}/processing`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});}
export async function rejectWithdrawal(id:string,reason:string){return adminApi<{withdrawal:{id:string}}>(`/referrers/withdrawals/${encodeURIComponent(id)}/reject`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason})});}
export async function getWithdrawalPaymentPreview(id:string){const value=await adminApi<{payment:WithdrawalPaymentPreview}>(`/referrers/withdrawals/${encodeURIComponent(id)}/payment`);return value.payment;}
export async function recordWithdrawalPayment(id:string,requestId:string,file:File){const body=new FormData();body.set("data",JSON.stringify({requestId}));body.set("receipt",file);return adminApi<{payment:{paymentId:string}}>(`/referrers/withdrawals/${encodeURIComponent(id)}/payment`,{method:"POST",body});}
export function paymentReceiptUrl(id:string){return `${(process.env.NEXT_PUBLIC_API_BASE_URL??"http://localhost:4000").replace(/\/$/,"")}/api/v1/admin/referrers/payments/${encodeURIComponent(id)}/receipt`;}
