import { Router,type NextFunction,type Request,type Response } from "express";
import { rateLimit } from "express-rate-limit";
import type { AuthConfig } from "../auth/config.js";
import { AuthError } from "../auth/errors.js";
import { normalizePhone } from "../auth/validation.js";
import type { AdminConfig } from "./config.js";
import { adminCustomerDirectoryQuerySchema,adminCustomerIdSchema } from "./customers-model.js";
import type { AdminCustomersRepository } from "./customers-repository.js";
import { AdminCustomersService } from "./customers-service.js";
import type { AdminInvitationEmail } from "./email.js";
import type { AdminIdentity } from "./identity.js";
import { acceptInvitationSchema,adminLoginSchema,invitationTokenSchema,inviteAdminSchema } from "./model.js";
import type { AdminRepository } from "./repository.js";
import { AdminInvitationService } from "./service.js";
import { AdminSessions } from "./sessions.js";

const wrap=(handler:(request:Request,response:Response)=>Promise<void>)=>(request:Request,response:Response,next:NextFunction)=>{void handler(request,response).catch(next);};
const limited=(limit:number)=>rateLimit({windowMs:15*60*1000,limit,standardHeaders:"draft-7",legacyHeaders:false,message:{success:false,error:{code:"RATE_LIMITED",message:"Too many requests. Please try again later."}}});
export function adminRouter(auth:AuthConfig,config:AdminConfig,repository:AdminRepository,customersRepository:AdminCustomersRepository,identity:AdminIdentity,email:AdminInvitationEmail){const router=Router(),sessions=new AdminSessions(auth,repository,identity),service=new AdminInvitationService(config,repository,identity,email),customers=new AdminCustomersService(customersRepository);router.use((request,response,next)=>{response.setHeader("Cache-Control","no-store");response.vary("Cookie");if(request.method!=="GET"&&(request.headers.origin!==config.appOrigin||!request.is("application/json")))return next(new AuthError(403,"UNTRUSTED_ORIGIN","This request is not permitted."));next();});router.post("/auth/login",limited(12),wrap(async(request,response)=>{const input=adminLoginSchema.parse(request.body),tokens=await identity.login(input.email,input.password),profile=await repository.profile(tokens.userId);if(!profile?.active)throw new AuthError(401,"INVALID_CREDENTIALS","Invalid credentials.");await sessions.establish(request,response,tokens);response.json({success:true,data:{admin:profile}});}));router.get("/auth/me",wrap(async(request,response)=>{response.json({success:true,data:{admin:await sessions.account(request)}});}));router.post("/auth/logout",wrap(async(request,response)=>{await sessions.logout(request,response);response.json({success:true,data:{}});}));router.get("/customers",wrap(async(request,response)=>{await sessions.account(request);const query=adminCustomerDirectoryQuerySchema.parse(request.query);response.json({success:true,data:await customers.directory(query)});}));router.get("/customers/:customerId",wrap(async(request,response)=>{await sessions.account(request);const customerId=adminCustomerIdSchema.parse(request.params.customerId);response.json({success:true,data:{customer:await customers.detail(customerId)}});}));router.post("/invitations/validate",limited(30),wrap(async(request,response)=>{const {token}=invitationTokenSchema.parse(request.body);response.json({success:true,data:{invitation:await service.preview(token)}});}));router.post("/invitations/accept",limited(10),wrap(async(request,response)=>{const input=acceptInvitationSchema.parse(request.body),admin=await service.accept(input.token,input.password);response.json({success:true,data:{admin}});}));router.post("/invitations",limited(20),wrap(async(request,response)=>{const caller=await sessions.account(request);if(caller.role!=="SUPER_ADMIN")throw new AuthError(403,"ADMIN_INVITE_FORBIDDEN","Only a Super Admin may invite administrators.");const input=inviteAdminSchema.parse(request.body),phone=normalizePhone(input.phoneNumber,"+234"),result=await service.invite(caller.userId,{...input,phone});response.status(201).json({success:true,data:{invitation:result}});}));return router;}
