import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { createRequire } from "node:module";
import { resolve } from "node:path";
import { setTimeout as delay } from "node:timers/promises";
import { chromium } from "playwright";

const origin="http://127.0.0.1:3027",require=createRequire(import.meta.url),next=require.resolve("next/dist/bin/next"),cwd=resolve(import.meta.dirname,"..");
const server=spawn(process.execPath,[next,"dev","-H","127.0.0.1","-p","3027"],{cwd,env:{...process.env,NEXT_PUBLIC_API_BASE_URL:origin},stdio:["ignore","pipe","pipe"]});let output="";server.stdout.on("data",chunk=>output+=chunk);server.stderr.on("data",chunk=>output+=chunk);
async function ready(){for(let i=0;i<60;i++){try{if((await fetch(origin)).ok)return;}catch{}await delay(500);}throw new Error(`Admin server did not start. ${output}`);}
let status="PENDING",paymentId=null;const requests=[];
const item=()=>({id:"WDR-ABC234",referrerId:"33333333-3333-4333-8333-333333333333",referrerName:"Controlled Referrer",referrerEmail:"referrer@example.test",amountMinor:250000,status,bankName:"Test Bank",maskedAccountNumber:"••••••6789",requestedAt:"2026-09-29T09:00:00Z",updatedAt:status==="PENDING"?null:"2026-09-29T10:00:00Z",rejectionReason:null,paymentId});
try{await ready();const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE}),context=await browser.newContext({serviceWorkers:"block"});await context.route(`${origin}/api/v1/admin/**`,async route=>{const url=new URL(route.request().url()),path=url.pathname.replace("/api/v1/admin","");requests.push(`${route.request().method()} ${path}${url.search}`);const reply=(data,code=200,type="application/json")=>route.fulfill({status:code,contentType:type,body:type==="application/json"?JSON.stringify({success:true,data}):"%PDF-test"});if(path==="/auth/me")return reply({admin:{userId:"admin-1",fullName:"Finance Admin",email:"admin@example.test",phone:"+2348000000000",department:"MANAGEMENT",role:"ADMIN",active:true}});if(path==="/referrers/withdrawals"&&route.request().method()==="GET"){const filter=url.searchParams.get("status")??"ALL",items=filter==="ALL"||filter===status?[item()]:[];return reply({items,page:1,pageSize:10,total:items.length,totalPages:items.length?1:0});}if(path==="/referrers/withdrawals/WDR-ABC234/processing"){status="PROCESSING";return reply({withdrawal:{id:"WDR-ABC234",status}});}if(path==="/referrers/withdrawals/WDR-ABC234/payment"&&route.request().method()==="GET")return reply({payment:{withdrawalId:"WDR-ABC234",referrerId:item().referrerId,referrerName:item().referrerName,amountMinor:item().amountMinor,accountName:"Controlled Referrer",bankName:"Test Bank",accountNumber:"0123456789"}});if(path==="/referrers/withdrawals/WDR-ABC234/payment"&&route.request().method()==="POST"){status="PAID";paymentId="PAY-WDR234";return reply({payment:{paymentId}},201);}if(path==="/referrers/payments/PAY-WDR234/receipt")return reply({},200,"application/pdf");return route.abort();});
const page=await context.newPage(),errors=[];page.on("pageerror",error=>errors.push(error.message));page.setDefaultNavigationTimeout(60000);await page.setViewportSize({width:1440,height:900});await page.goto(`${origin}/dashboard/withdrawals`);await page.getByRole("heading",{name:"Withdrawals"}).waitFor();assert.equal(await page.getByText("0123456789").count(),0);assert.equal(await page.getByText("••••••6789").count(),1);assert.equal(await page.getByRole("link",{name:"Withdrawals"}).getAttribute("href"),"/dashboard/withdrawals");await page.getByRole("button",{name:"Processing",exact:true}).click();await page.getByRole("heading",{name:"No processing withdrawals"}).waitFor();await page.getByRole("button",{name:"All",exact:true}).click();await page.getByRole("button",{name:"Begin Processing"}).click();await page.getByRole("button",{name:"Record Payment"}).waitFor();await page.getByRole("button",{name:"Record Payment"}).click();const dialog=page.getByRole("dialog");await dialog.getByText("0123456789").waitFor();await dialog.locator('input[type="file"]').setInputFiles({name:"receipt.pdf",mimeType:"application/pdf",buffer:Buffer.from("%PDF-test")});await dialog.getByRole("button",{name:"Confirm Payment"}).click();await page.getByText("WDR-ABC234 was recorded as paid.").waitFor();assert.equal(requests.some(value=>value==="POST /referrers/withdrawals/WDR-ABC234/payment"),true);for(const width of [430,390,360]){await page.setViewportSize({width,height:900});await page.goto(`${origin}/dashboard/withdrawals`);await page.getByRole("heading",{name:"Withdrawals"}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`whole-page overflow at ${width}`);}assert.deepEqual(errors,[]);await browser.close();console.log("Admin Withdrawals UI: queue, filters, processing, receipt-backed payment, privacy and responsive widths passed");}finally{server.kill();}
