import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { createRequire } from "node:module";
import { resolve } from "node:path";
import { setTimeout as delay } from "node:timers/promises";
import { chromium } from "playwright";

const origin="http://127.0.0.1:3024",require=createRequire(import.meta.url),next=require.resolve("next/dist/bin/next"),cwd=resolve(import.meta.dirname,"..");
const server=spawn(process.execPath,[next,"dev","-H","127.0.0.1","-p","3024"],{cwd,env:{...process.env,NEXT_PUBLIC_API_BASE_URL:origin,NEXT_PUBLIC_WEB_APP_URL:"http://customer.example.test"},stdio:["ignore","pipe","pipe"]});
let output="";server.stdout.on("data",chunk=>output+=chunk);server.stderr.on("data",chunk=>output+=chunk);
async function ready(){for(let attempt=0;attempt<50;attempt++){try{if((await fetch(origin)).ok)return;}catch{}await delay(500);}throw new Error(`Admin server did not start. ${output}`);}
const ids=Array.from({length:8},(_,index)=>`${String(index+1).padStart(8,"0")}-1111-4111-8111-111111111111`);
const properties=[
  ["RES-PEND01","Pending Ikoyi Home","PENDING"],["RES-PEND02","Pending Lekki Home","PENDING"],
  ["RES-LIVE01","Approved Abuja Home","LISTED"],["RES-LIVE02","Approved Lagos Home","LISTED"],
  ["RES-REJ001","Rejected Ikeja Home","REJECTED"],["RES-REJ002","Rejected Kano Home","REJECTED"],
  ["RES-OFF001","Unlisted Ibadan Home","UNLISTED"],["RES-OFF002","Unlisted Enugu Home","UNLISTED"],
].map(([code,title,status],index)=>({id:ids[index],code,title,status,propertyType:"Residential",propertySubtype:"Bungalow",city:title.split(" ")[1],state:index===2?"Federal Capital Territory (FCT)":"Lagos",createdAt:`2026-09-${String(20-index).padStart(2,"0")}T09:00:00.000Z`,updatedAt:`2026-09-${String(20-index).padStart(2,"0")}T09:00:00.000Z`,submittedAt:status==="UNLISTED"?null:`2026-09-${String(20-index).padStart(2,"0")}T09:00:00.000Z`,listedAt:status==="LISTED"?"2026-09-22T09:00:00.000Z":null,sellerId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",sellerName:"Ada Seller",thumbnailUrl:null,hasMandate:true}));
function detail(row){return{...row,version:2,description:"A controlled property description.",occupancyType:"Residential",ownershipType:"Personal",hasLien:false,bedrooms:4,bathrooms:3,toilets:4,parkingSpaces:2,units:null,landArea:450,yearBuilt:2025,facilities:["CCTV","Swimming Pool"],priceMinor:8500000000,minimumDownPaymentMinor:2125000000,location:"12 Controlled Road, Ikoyi",registeredTitleDocument:"Certificate of Occupancy",additionalInformation:null,rejectionReason:row.status==="REJECTED"?"Upload clearer photos and a readable ownership document.":null,rejectedAt:row.status==="REJECTED"?"2026-09-22T10:14:00.000Z":null,seller:{id:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",name:"Ada Seller",email:"ada@example.test",phone:"+2348011111111"},images:[{id:"10000000-0000-4000-8000-000000000001",url:"https://example.test/house.jpg",sortOrder:0,mimeType:"image/jpeg",sizeBytes:2000}],documents:[{id:"20000000-0000-4000-8000-000000000001",title:"Ownership.pdf",documentType:"Ownership",description:"Title document",sortOrder:0,mimeType:"application/pdf",sizeBytes:2400000}],mandate:{id:"30000000-0000-4000-8000-000000000001",type:"Exclusive",commissionPercent:5,signerName:"Ada Seller",mandateDate:"2026-09-20",signedAt:"2026-09-20T11:40:00.000Z",submittedAt:"2026-09-20T11:42:00.000Z",hasSignature:true,documents:[]},reviews:row.status==="REJECTED"?[{id:"40000000-0000-4000-8000-000000000001",action:"REJECTED",reason:"Upload clearer photos and a readable ownership document.",submissionRequestedAt:row.submittedAt,reviewedAt:"2026-09-22T10:14:00.000Z",reviewer:{id:"admin-1",name:"Review Admin"}}]:row.status==="LISTED"?[{id:"40000000-0000-4000-8000-000000000002",action:"APPROVED",reason:null,submissionRequestedAt:row.submittedAt,reviewedAt:"2026-09-22T10:08:00.000Z",reviewer:{id:"admin-1",name:"Review Admin"}}]:[]};}
const details=new Map(properties.map(row=>[row.code,detail(row)]));let emptyPending=false;

try{await ready();const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE});const context=await browser.newContext({serviceWorkers:"block"});const requests=[];await context.route(`${origin}/api/v1/admin/**`,async route=>{const url=new URL(route.request().url()),path=url.pathname.replace("/api/v1/admin","");requests.push(`${route.request().method()} ${path}${url.search}`);const reply=(data,status=200)=>route.fulfill({status,contentType:"application/json",body:JSON.stringify(status<400?{success:true,data}:{success:false,error:data})});if(path==="/auth/me")return reply({admin:{userId:"admin-1",fullName:"Review Admin",email:"admin@example.test",phone:"+2348000000000",department:"MANAGEMENT",role:"ADMIN",active:true}});if(path==="/properties"&&route.request().method()==="GET"){const search=(url.searchParams.get("search")??"").toLowerCase(),status=url.searchParams.get("status")??"ALL",sort=url.searchParams.get("sort")??"NEWEST",page=Number(url.searchParams.get("page")??"1");let rows=properties.filter(row=>(!search||`${row.title} ${row.code} ${row.sellerName} ${row.city} ${row.state}`.toLowerCase().includes(search))&&(status==="ALL"||row.status===status));if(emptyPending&&status==="PENDING")rows=[];rows=[...rows].sort((a,b)=>sort==="OLDEST"?a.updatedAt.localeCompare(b.updatedAt):sort==="TITLE_ASC"?a.title.localeCompare(b.title):sort==="TITLE_DESC"?b.title.localeCompare(a.title):b.updatedAt.localeCompare(a.updatedAt));const total=rows.length;return reply({counts:{all:8,unlisted:2,pending:emptyPending?0:2,approved:2,rejected:2},items:rows.slice((page-1)*6,page*6),page,pageSize:6,total,totalPages:total?Math.ceil(total/6):0});}const match=path.match(/^\/properties\/([^/]+)(?:\/(approve|reject))?$/);if(match){const code=decodeURIComponent(match[1]),action=match[2],current=details.get(code);if(!current)return reply({code:"PROPERTY_NOT_FOUND",message:"Property not found."},404);if(action){const next={...current,status:action==="approve"?"LISTED":"REJECTED",version:current.version+1,listedAt:action==="approve"?new Date().toISOString():null,rejectionReason:action==="reject"?JSON.parse(route.request().postData()).reason:null,rejectedAt:action==="reject"?new Date().toISOString():null,reviews:[{id:crypto.randomUUID(),action:action==="approve"?"APPROVED":"REJECTED",reason:action==="reject"?JSON.parse(route.request().postData()).reason:null,submissionRequestedAt:current.submittedAt,reviewedAt:new Date().toISOString(),reviewer:{id:"admin-1",name:"Review Admin"}},...current.reviews]};details.set(code,next);return reply({property:next});}return reply({property:current});}return route.abort();});
  const page=await context.newPage(),pageErrors=[];
  page.on("pageerror",error=>pageErrors.push(error.message));page.setDefaultNavigationTimeout(60000);
  await page.setViewportSize({width:1440,height:1000});await page.goto(origin);
  const navigation=page.getByRole("navigation",{name:"Admin navigation"});await navigation.waitFor();
  assert.equal(await navigation.getByRole("link",{name:"Properties",exact:true}).count(),1);
  await navigation.getByRole("link",{name:"Properties",exact:true}).click();await page.getByRole("heading",{name:"Properties"}).waitFor();
  assert.equal(await page.locator("tbody tr").count(),6);assert.equal(await page.getByText("Pending Review",{exact:true}).count()>0,true);assert.equal(await page.getByText("Approved",{exact:true}).count()>0,true);assert.equal(await page.getByText("Rejected",{exact:true}).count()>0,true);
  await page.getByRole("button",{name:"Next ›"}).click();await page.waitForURL(/page=2/);await page.getByText("Unlisted",{exact:true}).first().waitFor();
  await page.getByRole("button",{name:/Pending Review/}).click();await page.waitForURL(/status=PENDING/);await page.waitForFunction(()=>document.querySelectorAll("tbody tr").length===2);assert.equal(await page.locator("tbody tr").count(),2);
  await page.getByLabel("Search properties").fill("Lekki");await page.getByRole("button",{name:"Search",exact:true}).click();await page.waitForURL(/search=Lekki/);await page.getByText("Pending Lekki Home",{exact:true}).waitFor();assert.equal(requests.some(value=>value.includes("search=Lekki")),true);
  await page.goto(`${origin}/dashboard/properties/RES-PEND01`);await page.getByRole("heading",{name:"Pending Ikoyi Home"}).waitFor();assert.equal(await page.getByText("Ada Seller",{exact:true}).count()>0,true);assert.equal(await page.getByRole("link",{name:"View Customer"}).getAttribute("href"),"/dashboard/users/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa");await page.getByRole("button",{name:/Approve Property/}).click();await page.getByRole("dialog").waitFor();await page.keyboard.press("Escape");assert.equal(await page.getByRole("dialog").count(),0);await page.getByRole("button",{name:/Approve Property/}).click();await page.getByRole("button",{name:/Confirm Approval/}).click();await page.getByText("Live on the marketplace").waitFor();assert.equal(requests.some(value=>value==="POST /properties/RES-PEND01/approve"),true);
  await page.goto(`${origin}/dashboard/properties/RES-PEND02`);await page.getByRole("button",{name:"Reject with reason"}).click();const dialog=page.getByRole("dialog");await dialog.getByRole("button",{name:/Confirm Rejection/}).waitFor();assert.equal(await dialog.getByRole("button",{name:/Confirm Rejection/}).isDisabled(),true);await dialog.getByRole("textbox").fill("Please upload clearer property photos.");await dialog.getByRole("button",{name:/Confirm Rejection/}).click();await page.getByText("Awaiting Seller").waitFor();
  await page.goto(`${origin}/dashboard/properties/RES-REJ001`);await page.getByText("Rejection History").waitFor();assert.equal(await page.getByRole("button",{name:/Approve Property/}).count(),0);
  emptyPending=true;await page.goto(`${origin}/dashboard/properties?status=PENDING`);await page.getByRole("heading",{name:"Queue’s clear"}).waitFor();await page.getByText("No properties waiting for review.").waitFor();emptyPending=false;
  for(const width of [1440,1280,1024,768,430,390,360]){await page.setViewportSize({width,height:900});await page.goto(`${origin}/dashboard/properties`);await page.getByRole("heading",{name:"Properties"}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`whole-page overflow at ${width}`);if(width<=900){const menu=page.getByRole("button",{name:"Open navigation"});assert.equal(await menu.isVisible(),true);await menu.click();await page.getByRole("button",{name:"Close navigation"}).click();}}
  assert.deepEqual(pageErrors,[]);await browser.close();console.log("Admin Properties UI: directory, moderation, detail, empty states and responsive widths passed");
}finally{server.kill();}
