import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { createRequire } from "node:module";
import { resolve } from "node:path";
import { setTimeout as delay } from "node:timers/promises";
import { chromium } from "playwright";

const origin="http://127.0.0.1:3025",require=createRequire(import.meta.url),next=require.resolve("next/dist/bin/next"),cwd=resolve(import.meta.dirname,"..");
const server=spawn(process.execPath,[next,"dev","-H","127.0.0.1","-p","3025"],{cwd,env:{...process.env,NEXT_PUBLIC_API_BASE_URL:origin,NEXT_PUBLIC_WEB_APP_URL:"http://customer.example.test"},stdio:["ignore","pipe","pipe"]});
let output="";server.stdout.on("data",chunk=>output+=chunk);server.stderr.on("data",chunk=>output+=chunk);
async function ready(){for(let attempt=0;attempt<60;attempt++){try{if((await fetch(origin)).ok)return;}catch{}await delay(500);}throw new Error(`Admin server did not start. ${output}`);}

const leads=[
  {publicId:"ENQ-ABC234",stage:"NEW",version:1,sourceType:"REAL_ESTATE_INQUIRY",requesterName:"Ada Buyer",propertyInterest:null,receivedAt:"2026-09-28T10:00:00.000Z"},
  {publicId:"ENQ-DEF567",stage:"CONTACTED",version:2,sourceType:"PROPERTY_VIEWING",requesterName:"Bisi Viewer",propertyInterest:"Ikoyi Family Home",receivedAt:"2026-09-27T10:00:00.000Z"},
  {publicId:"ENQ-GHK789",stage:"WON",version:2,sourceType:"BUY_ASSISTANCE",requesterName:"Chidi Buyer",propertyInterest:"Residential Bungalow · Lekki, Lagos",receivedAt:"2026-09-26T10:00:00.000Z"},
  {publicId:"ENQ-JKM234",stage:"LOST",version:2,sourceType:"REAL_ESTATE_INQUIRY",requesterName:"Dayo Buyer",propertyInterest:null,receivedAt:"2026-09-25T10:00:00.000Z"},
];
function detail(row){return{...row,requester:{name:row.requesterName,email:"buyer@example.test",phone:"+2348011111111",preferredContact:null,accountLinked:false,customerId:null,accountType:null,profileType:null,kycStatus:null},message:"I would like to arrange a viewing for this property.",request:row.sourceType==="PROPERTY_VIEWING"?{preferredDate:"2026-10-02",preferredTime:"10:30:00",flexibleDates:false}:{inquiryType:"Buying a Property",sourcePage:"buy"},property:row.sourceType==="PROPERTY_VIEWING"?{code:"RES-LEAD01",title:"Ikoyi Family Home",status:"LISTED",imageUrl:null,city:"Ikoyi",state:"Lagos",location:"12 Controlled Road",priceMinor:8500000000,minimumDownPaymentMinor:2125000000,propertyType:"Residential",propertySubtype:"Bungalow",seller:{id:"seller-1",name:"Controlled Seller"}}:null,referral:null,history:[]};}
const details=new Map(leads.map(row=>[row.publicId,detail(row)]));

try{
  await ready();const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE});const context=await browser.newContext({serviceWorkers:"block"});
  let empty=false,failNext=false,stagePosts=0;const requests=[];
  await context.route(`${origin}/api/v1/admin/**`,async route=>{const request=route.request(),url=new URL(request.url()),path=url.pathname.replace("/api/v1/admin","");requests.push(`${request.method()} ${path}${url.search}`);const reply=(data,status=200)=>route.fulfill({status,contentType:"application/json",body:JSON.stringify(status<400?{success:true,data}:{success:false,error:data})});
    if(path==="/auth/me")return reply({admin:{userId:"admin-1",fullName:"Lead Admin",email:"admin@example.test",phone:"+2348000000000",department:"MANAGEMENT",role:"ADMIN",active:true}});
    if(path==="/leads"&&request.method()==="GET"){if(empty)return reply({counts:{new:0,contacted:0,won:0,lost:0},items:[],page:1,pageSize:40,total:0,allTotal:0,totalPages:0});const search=(url.searchParams.get("search")??"").toLowerCase();const rows=leads.filter(row=>!search||`${row.publicId} ${row.requesterName} ${row.propertyInterest??""}`.toLowerCase().includes(search));const count=stage=>rows.filter(row=>row.stage===stage).length;return reply({counts:{new:count("NEW"),contacted:count("CONTACTED"),won:count("WON"),lost:count("LOST")},items:rows,page:1,pageSize:40,total:rows.length,allTotal:leads.length,totalPages:rows.length?1:0});}
    const match=path.match(/^\/leads\/(ENQ-[A-Z0-9]+)(?:\/stage)?$/);if(match){const current=details.get(match[1]);if(!current)return reply({code:"LEAD_NOT_FOUND",message:"Lead not found."},404);if(request.method()==="POST"){stagePosts++;if(failNext){failNext=false;return reply({code:"LEAD_CHANGED",message:"This lead changed. Refresh and try again."},409);}const body=JSON.parse(request.postData()??"{}");const changed={...current,stage:body.stage,version:current.version+1,history:[{id:`history-${stagePosts}`,fromStage:current.stage,toStage:body.stage,changedAt:"2026-09-28T12:00:00.000Z",admin:{id:"admin-1",name:"Lead Admin"}},...current.history]};details.set(match[1],changed);const item=leads.find(row=>row.publicId===match[1]);if(item){item.stage=body.stage;item.version=changed.version;}return reply({lead:changed});}return reply({lead:current});}
    return route.abort();
  });
  const page=await context.newPage(),pageErrors=[];page.on("pageerror",error=>pageErrors.push(error.message));page.setDefaultNavigationTimeout(60000);
  await page.setViewportSize({width:1440,height:1000});await page.goto(`${origin}/dashboard/leads`);await page.getByRole("heading",{name:"Leads",exact:true}).waitFor();
  await page.getByText("4 Enquiries",{exact:true}).waitFor();for(const name of ["New","Contacted","Won","Lost"])assert.equal(await page.locator(".lead-column > header").getByText(name,{exact:true}).count(),1);assert.equal(await page.locator(".lead-card").count(),4);
  await page.getByLabel("Search leads").fill("Ikoyi");await page.getByRole("button",{name:"Search",exact:true}).click();await page.waitForURL(/search=Ikoyi/);await page.getByText("Bisi Viewer",{exact:true}).waitFor();assert.equal(await page.locator(".lead-card").count(),1);assert.equal(requests.some(value=>value.includes("search=Ikoyi")),true);
  await page.getByText("Bisi Viewer",{exact:true}).click();await page.getByRole("heading",{name:"Enquiry ENQ-DEF567"}).waitFor();await page.getByText("Contacted",{exact:true}).first().waitFor();await page.getByText("Anonymous enquiry · account not linked",{exact:true}).waitFor();await page.getByText("Not available — no linked account",{exact:true}).waitFor();await page.getByRole("link",{name:"View Property"}).waitFor();
  const won=page.getByRole("button",{name:"Won",exact:true});await won.click();await page.getByRole("dialog").waitFor();assert.equal(await page.getByText(/does not create a purchase, payment, commission/).isVisible(),true);await page.getByRole("button",{name:"Cancel",exact:true}).click();assert.equal(stagePosts,0);assert.equal(await page.getByRole("dialog").count(),0);
  await won.click();failNext=true;await page.getByRole("button",{name:"Confirm",exact:true}).click();await page.getByRole("alert").getByText("This lead changed. Refresh and try again.").waitFor();assert.equal(await page.getByRole("dialog").count(),1);await page.getByRole("button",{name:"Confirm",exact:true}).click();await page.getByText("This is a final CRM stage. No further transitions are available.").waitFor();assert.equal(stagePosts,2);assert.equal(await page.getByText("Won",{exact:true}).first().isVisible(),true);
  empty=true;await page.goto(`${origin}/dashboard/leads`);await page.getByRole("heading",{name:"No Enquiries Yet"}).waitFor();await page.getByText("Buyer enquiries will land here as they come in.",{exact:true}).waitFor();assert.equal(await page.locator(".lead-card").count(),0);empty=false;
  for(const width of [1440,1280,1024,768,430,390,360]){await page.setViewportSize({width,height:900});await page.goto(`${origin}/dashboard/leads`);await page.getByRole("heading",{name:"Leads",exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`whole-page overflow at ${width}`);if(width<=680){const local=await page.locator(".leads-board-scroll").evaluate(element=>({scroll:element.scrollWidth,client:element.clientWidth,overflow:getComputedStyle(element).overflowX}));assert.equal(local.scroll>local.client,true,`board should scroll locally at ${width}`);assert.equal(local.overflow,"auto");}}
  assert.deepEqual(pageErrors,[]);await browser.close();console.log("Admin Leads UI: board, search, detail, confirmation, transition errors, empty state and responsive widths passed");
}finally{server.kill();}
