import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { createRequire } from "node:module";
import { resolve } from "node:path";
import { setTimeout as delay } from "node:timers/promises";
import { chromium } from "playwright";

const origin="http://127.0.0.1:3021",api=origin,require=createRequire(import.meta.url),next=require.resolve("next/dist/bin/next"),cwd=resolve(import.meta.dirname,"..");
const server=spawn(process.execPath,[next,"dev","-H","127.0.0.1","-p","3021"],{cwd,env:{...process.env,NEXT_PUBLIC_API_BASE_URL:api},stdio:["ignore","pipe","pipe"]});let output="";server.stdout.on("data",chunk=>output+=chunk);server.stderr.on("data",chunk=>output+=chunk);
async function ready(){for(let attempt=0;attempt<40;attempt++){try{if((await fetch(origin)).ok)return;}catch{}await delay(500);}throw new Error(`Admin Next server did not start. ${output}`);}
try{await ready();const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE});const context=await browser.newContext({serviceWorkers:"block"});const calls=[];let fail=false,pause=false,release;await context.route(`${api}/api/v1/admin/**`,async route=>{const request=route.request(),path=new URL(request.url()).pathname.replace("/api/v1/admin","");if(path==="/auth/me")return route.fulfill({status:200,contentType:"application/json",headers:{"access-control-allow-origin":origin,"access-control-allow-credentials":"true"},body:JSON.stringify({success:true,data:{admin:{userId:"1",fullName:"Amina Yusuf",email:"amina@example.test",phone:"+2348031234567",department:"MANAGEMENT",role:"SUPER_ADMIN",active:true}}})});if(path==="/invitations"){calls.push(request.postDataJSON());if(pause)await new Promise(resolve=>release=resolve);return route.fulfill({status:fail?503:201,contentType:"application/json",headers:{"access-control-allow-origin":origin,"access-control-allow-credentials":"true"},body:JSON.stringify(fail?{success:false,error:{code:"AUTH_UNAVAILABLE",message:"Invitation delivery is temporarily unavailable."}}:{success:true,data:{invitation:{fullName:"Ada Okafor",email:"ada@example.test",expiresAt:new Date(Date.now()+172800000).toISOString()}}})});}if(path==="/invitations/validate")return route.fulfill({status:200,contentType:"application/json",headers:{"access-control-allow-origin":origin},body:JSON.stringify({success:true,data:{invitation:{fullName:"Ada Okafor",email:"ada@example.test",department:"TECH",role:"ADMIN",expiresAt:new Date(Date.now()+172800000).toISOString()}}})});if(path==="/invitations/accept")return route.fulfill({status:200,contentType:"application/json",headers:{"access-control-allow-origin":origin},body:JSON.stringify({success:true,data:{admin:{}}})});return route.abort();});const page=await context.newPage();const errors=[];page.on("pageerror",error=>errors.push(error.message));
for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:900});await page.goto(origin);await page.getByRole("button",{name:"Invite Admin"}).click();await page.getByRole("dialog").waitFor();assert.equal(await page.getByLabel("Full Name").isVisible(),true);assert.equal(await page.getByLabel("Email Address").isVisible(),true);assert.equal(await page.getByLabel("Nigerian phone number").isVisible(),true);assert.equal(await page.getByRole("radio",{name:"Tech",exact:true}).isChecked(),true);assert.equal(await page.getByRole("radio",{name:"Admin",exact:true}).isChecked(),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`horizontal overflow at ${width}`);await page.getByRole("button",{name:"Cancel"}).click();}
await page.getByRole("button",{name:"Invite Admin"}).focus();await page.getByRole("button",{name:"Invite Admin"}).click();assert.equal(await page.evaluate(()=>document.body.style.overflow),"hidden");await page.keyboard.press("Escape");assert.equal(await page.getByRole("button",{name:"Invite Admin"}).evaluate(element=>element===document.activeElement),true);await page.getByRole("button",{name:"Invite Admin"}).click();await page.getByRole("button",{name:"Close invite admin dialog"}).click();await page.getByRole("button",{name:"Invite Admin"}).click();await page.getByRole("button",{name:"Send Invitation"}).click();assert.equal(await page.getByLabel("Full Name").evaluate(input=>input.validationMessage.length>0),true);
await page.getByLabel("Full Name").fill("Ada Okafor");await page.getByLabel("Email Address").fill("ada@example.test");await page.getByLabel("Nigerian phone number").fill("08031234567");await page.getByRole("radio",{name:"Management",exact:true}).check();await page.getByRole("radio",{name:"Super Admin",exact:true}).check();pause=true;await page.getByRole("button",{name:"Send Invitation"}).click();await page.getByRole("button",{name:"Sending…"}).waitFor();assert.equal(await page.getByRole("button",{name:"Sending…"}).isDisabled(),true);assert.equal(calls.length,1);release();pause=false;await page.getByRole("heading",{name:"Invitation Sent"}).waitFor();assert.match(await page.getByRole("dialog").innerText(),/Ada Okafor.*ada@example\.test/s);assert.equal(calls[0].department,"MANAGEMENT");assert.equal(calls[0].role,"SUPER_ADMIN");await page.getByRole("button",{name:"Close invitation confirmation"}).click();
await page.getByRole("button",{name:"Invite Admin"}).click();await page.getByLabel("Full Name").fill("Ada Okafor");await page.getByLabel("Email Address").fill("ada@example.test");await page.getByLabel("Nigerian phone number").fill("08031234567");fail=true;await page.getByRole("button",{name:"Send Invitation"}).click();await page.getByText("Invitation delivery is temporarily unavailable.").waitFor();assert.equal(await page.getByRole("heading",{name:"Invitation Sent"}).count(),0);assert.equal(await page.getByLabel("Full Name").inputValue(),"Ada Okafor");
await page.goto(`${origin}/accept-invitation#token=${"a".repeat(43)}`);await page.getByText("ada@example.test").waitFor();assert.equal(page.url().includes("token="),false);await page.getByLabel("Password",{exact:true}).fill("StrongPass!");await page.getByLabel("Confirm Password").fill("StrongPass!");await page.getByRole("button",{name:"Set Password"}).click();await page.getByText("Your Admin account is ready.").waitFor();assert.deepEqual(errors,[]);await browser.close();console.log("Admin invitation UI: 17 focused behaviors passed at 1440/768/390/320");}finally{server.kill();}
