"use client";
import { useRouter } from "next/navigation";
import { useCallback,useEffect,useState } from "react";
import { toast } from "react-toastify";
import { AuthApiError } from "../../lib/auth-api";
import { fetchKyc,submitKyc,type KycDocumentType,type KycView } from "../../lib/kyc-api";
import { BrandLoader } from "../auth/brand-loader";
import { showAuthError } from "../auth/toast-provider";
import { DashboardIcon } from "./dashboard-icon";

const types:{value:KycDocumentType;label:string}[]=[{value:"PASSPORT",label:"Passport"},{value:"DRIVERS_LICENSE",label:"Driver's License"},{value:"NATIONAL_ID",label:"National ID"}],countries=["Nigeria","Ghana","United Kingdom","United States","Canada"];
function ordinal(day:number){const remainder=day%100;if(remainder>=11&&remainder<=13)return `${day}th`;switch(day%10){case 1:return `${day}st`;case 2:return `${day}nd`;case 3:return `${day}rd`;default:return `${day}th`;}}
function submittedDate(value:string){const date=new Date(value);if(Number.isNaN(date.getTime()))return "";const parts=new Intl.DateTimeFormat("en-GB",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).formatToParts(date);const part=(type:Intl.DateTimeFormatPartTypes)=>parts.find(item=>item.type===type)?.value??"";const elapsed=Math.max(0,Date.now()-date.getTime());const hours=Math.floor(elapsed/3_600_000),days=Math.floor(elapsed/86_400_000);const relative=hours<1?"less than an hour ago":hours<24?`${hours} hour${hours===1?"":"s"} ago`:`${days} day${days===1?"":"s"} ago`;return `${part("weekday")}, ${ordinal(Number(part("day")))} ${part("month")} ${part("year")} (${relative})`;}
export function KycScreen(){const router=useRouter(),[view,setView]=useState<KycView|null>(null),[failed,setFailed]=useState(false),[revision,setRevision]=useState(0),[country,setCountry]=useState(""),[documentType,setDocumentType]=useState<KycDocumentType|"">(""),[front,setFront]=useState<File>(),[back,setBack]=useState<File>(),[accepted,setAccepted]=useState(false),[pending,setPending]=useState(false);const failure=useCallback((error:unknown)=>{if(error instanceof AuthApiError&&["SESSION_EXPIRED","AUTH_REQUIRED"].includes(error.code))router.replace("/login");else showAuthError(error,"kyc-error");},[router]);useEffect(()=>{const controller=new AbortController();fetchKyc(controller.signal).then(value=>{if(!controller.signal.aborted){setView(value);setFailed(false);if(value.status==="REJECTED"){setCountry(value.country??"");setDocumentType(value.documentType??"");}}}).catch(error=>{if(!controller.signal.aborted){setFailed(true);failure(error);}});return()=>controller.abort();},[failure,revision]);
  if(!view)return <section className="kyc-page"><h1>KYC Verification</h1>{failed?<button className="button button-primary" onClick={()=>{setFailed(false);setRevision(value=>value+1);}}>Try again</button>:<BrandLoader/>}</section>;
  const locked=view.status==="PENDING_REVIEW"||view.status==="APPROVED";if(locked)return <section className="kyc-page"><h1>KYC Verification</h1><div className={`dashboard-card kyc-status ${view.status.toLowerCase()}`}><div className="kyc-status-icon" aria-hidden="true"><DashboardIcon name="verification" /></div><span>{view.status==="APPROVED"?"Approved":"Pending Review"}</span><h2>{view.status==="APPROVED"?"Your identity verification is approved":"Your documents are awaiting review"}</h2><p>{view.status==="APPROVED"?"Your approved submission cannot be replaced from this page.":<><span>Your documents have been received securely and are being reviewed by our verification team.</span>{" "}<span>We will update your status when the review is complete.</span></>}</p>{view.submittedAt&&<small>Submitted <strong>{submittedDate(view.submittedAt)}</strong></small>}</div></section>;
  const choose=(side:"front"|"back",file?:File)=>{if(file&&(!["application/pdf","image/png","image/jpeg"].includes(file.type)||!file.size||file.size>10*1024*1024)){toast.error("Choose a PDF, PNG or JPG file no larger than 10 MiB.",{toastId:"kyc-error"});return;}if(side==="front")setFront(file);else setBack(file);};
  async function submit(event:React.FormEvent){event.preventDefault();if(pending||!documentType||!front||(!accepted)||(documentType!=="PASSPORT"&&!back))return;setPending(true);try{const result=await submitKyc(country,documentType,accepted,front,documentType==="PASSPORT"?undefined:back);setView(result);toast.success("KYC submitted for review");}catch(error){failure(error);}finally{setPending(false);}}
  return <section className="kyc-page"><h1>KYC Verification</h1><form className="dashboard-card kyc-card" onSubmit={submit} aria-busy={pending}><header><h2>Upload a proof of your identity</h2><p>Provide a valid government-issued ID: Driver&apos;s License, Passport, or National ID.</p></header>{view.status==="REJECTED"&&<div className="kyc-rejected" role="status"><strong>Submission rejected</strong><span>{view.rejectionReason||"Please review your details and submit new documents."}</span></div>}<div className="kyc-selectors"><label>Your Country *<select aria-label="Country" required value={country} onChange={event=>setCountry(event.target.value)}><option value="">Select Country</option>{countries.map(value=><option key={value}>{value}</option>)}</select><small>Select the country in which your document was issued</small></label><label>Document Type *<select required value={documentType} onChange={event=>{setDocumentType(event.target.value as KycDocumentType);setBack(undefined);}}><option value="">Select an option</option>{types.map(type=><option value={type.value} key={type.value}>{type.label}</option>)}</select><small>Select your preferred document type for verification</small></label></div><div className={`kyc-uploads${documentType&&documentType!=="PASSPORT"?" two":""}`}><UploadBox side="Front" file={front} onChange={file=>choose("front",file)}/>{documentType&&documentType!=="PASSPORT"&&<UploadBox side="Back" file={back} onChange={file=>choose("back",file)}/>}</div><label className="kyc-declaration"><input type="checkbox" required checked={accepted} onChange={event=>setAccepted(event.target.checked)}/>I confirm that I uploaded a valid government-issued photo ID containing my correct details.</label><button className="button button-primary kyc-submit" disabled={pending}>{pending?"Submitting...":"Submit For Verification"}</button></form></section>;
}
function UploadBox({side,file,onChange}:{side:"Front"|"Back";file:File|undefined;onChange:(file?:File)=>void}){return <label className="kyc-upload"><span aria-hidden="true">⇧</span><strong>{side} side of your document</strong><p>Upload the {side.toLowerCase()} side of your document. Supports JPG, PNG, PDF</p><em>{file?.name??"Choose File"}</em><input aria-label={`${side} document`} type="file" required accept=".jpg,.jpeg,.png,.pdf,image/jpeg,image/png,application/pdf" onChange={event=>onChange(event.target.files?.[0])}/></label>;}
