import assert from "node:assert/strict";
import { createReadStream, existsSync, mkdirSync, statSync } from "node:fs";
import { createServer } from "node:http";
import { extname, join, normalize } from "node:path";
import { chromium } from "playwright";

const root=join(process.cwd(),".expo-web"),shots=join(root,"qa");mkdirSync(shots,{recursive:true});
const types={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json",".png":"image/png",".ttf":"font/ttf"};
const server=createServer((request,response)=>{const raw=decodeURIComponent((request.url??"/").split("?")[0]??"/");let path=normalize(join(root,raw));if(!path.startsWith(root)){response.writeHead(403).end();return;}if(existsSync(path)&&statSync(path).isDirectory())path=join(path,"index.html");if(!existsSync(path)&&existsSync(`${path}.html`))path=`${path}.html`;if(!existsSync(path))path=join(root,"index.html");response.setHeader("Content-Type",types[extname(path)]??"application/octet-stream");createReadStream(path).pipe(response);});
await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));const address=server.address();assert.ok(address&&typeof address!=="string");const origin=`http://127.0.0.1:${address.port}`;
const customer={id:"responsive-customer",first_name:"Responsive",last_name:"Tester",email:"responsive@example.test",phone_number_normalized:null,account_type:"INVESTOR",profile_type:"PERSONAL"};
const options={occupancy_type:["Residential","Commercial"],ownership_type:["Personal","Family"],property_type:["Residential","Commercial"],property_subtype:["Bungalow"],facilities:["CCTV"],document_type:["Ownership"],state:["Abia","Kwara","Lagos"]};
const overview={customer:{...customer,profile_image_url:null},summary:{total_investments:0,properties_owned:0,referral_earnings:0,new_messages:0},revenue:{monthly:[],yearly:[]},recent_messages:[],recent_property_listings:[]};
const cors={"access-control-allow-origin":"*","access-control-allow-headers":"X-Beryl-Client, Authorization, Content-Type","access-control-allow-methods":"GET, POST, OPTIONS","access-control-expose-headers":"X-Beryl-Account-Token"};
const browser=await chromium.launch({headless:true}),failures=[];
try{for(const width of [360,390,430]){const context=await browser.newContext({viewport:{width,height:900}}),page=await context.newPage(),clickVisible=label=>page.locator(`[aria-label="${label}"]:visible`).last().evaluate(element=>element.click());let optionsAuthorization="";page.on("pageerror",error=>failures.push(`${width}: ${error.message}`));await page.route("**/api/v1/**",route=>{const request=route.request(),path=new URL(request.url()).pathname;if(request.method()==="OPTIONS")return route.fulfill({status:204,headers:cors});const reply=(data,headers=cors)=>route.fulfill({status:200,headers,contentType:"application/json",body:JSON.stringify({success:true,data})});if(path==="/api/v1/public/properties")return reply({items:[],page:1,pageSize:10,total:0,totalPages:0});if(path==="/api/v1/auth/login")return reply({}, {...cors,"x-beryl-account-token":"responsive-test-token"});if(path==="/api/v1/auth/me")return reply({customer});if(path==="/api/v1/listings/options"){optionsAuthorization=request.headers().authorization??"";return reply(options);}if(path==="/api/v1/dashboard/overview")return reply(overview);return reply({});});
await page.goto(origin,{waitUntil:"networkidle"});await page.getByRole("heading",{name:/Earn Rich/}).waitFor();assert.equal(await page.locator('img[aria-label="Beryl Shelter"], img').first().evaluate(img=>img.complete&&img.naturalWidth>0),true);assert.equal(await page.getByLabel("Customer receiving a Beryl Shelter referral notification").locator("img").evaluate(img=>img.complete&&img.naturalWidth>0),true);const primary=page.getByRole("button",{name:"Browse all properties"});assert.notEqual(await primary.evaluate(el=>getComputedStyle(el).backgroundColor),"rgb(23, 18, 14)");if(width===390)await page.screenshot({path:join(shots,"home-light.png"),fullPage:true});
await clickVisible("Account tab");await page.getByRole("button",{name:"Log in",exact:true}).click();await page.getByLabel("Email or phone").fill(customer.email);await page.getByRole("textbox",{name:"Password"}).fill("responsive-test-password");await page.getByRole("button",{name:"Log in",exact:true}).click();await clickVisible("List a property tab");await page.getByText("Property Data",{exact:true}).waitFor();assert.equal(optionsAuthorization,"Bearer responsive-test-token");assert.equal(await page.getByText("Sign in to list a property").count(),0);await page.getByLabel("State selector").click();await page.getByRole("heading",{name:"Select state"}).waitFor();await page.getByText("Kwara",{exact:true}).click();await page.getByLabel("State selector").getByText("Kwara").waitFor();if(width===390)await page.screenshot({path:join(shots,"list-state-selector.png"),fullPage:true});
await clickVisible("Account tab");await page.getByText("Individual",{exact:true}).last().waitFor();assert.equal(await page.getByText("Individual Customer",{exact:true}).count(),0);if(width===390)await page.screenshot({path:join(shots,"account-light.png"),fullPage:true});await page.getByRole("button",{name:"Go to Dashboard"}).last().click();await page.getByText(/Good (morning|afternoon|evening), Responsive Tester!/).last().waitFor();await page.getByLabel("Open navigation menu").click();const drawerBrand=page.locator('[aria-label="Beryl Shelter"]:visible').last(),drawerCustomer=page.getByText(customer.email,{exact:true}).last();await drawerBrand.waitFor();await page.waitForTimeout(500);const brandBox=await drawerBrand.boundingBox(),customerBox=await drawerCustomer.boundingBox();assert.ok(brandBox&&customerBox&&brandBox.y<customerBox.y);if(width===390)await page.screenshot({path:join(shots,"drawer-light.png"),fullPage:true});await page.getByLabel("Close menu").click();
await page.goBack();await clickVisible("Account tab");await clickVisible("Dark appearance");await clickVisible("Home tab");const headline=page.getByRole("heading",{name:/Earn Rich/}).last();await headline.waitFor();assert.equal(await headline.evaluate(el=>getComputedStyle(el.parentElement.parentElement).backgroundColor),"rgb(36, 29, 22)");if(width===390)await page.screenshot({path:join(shots,"home-dark.png"),fullPage:true});await clickVisible("Account tab");await clickVisible("System appearance");await page.emulateMedia({colorScheme:"dark"});await clickVisible("Home tab");assert.equal(await headline.evaluate(el=>getComputedStyle(el.parentElement.parentElement).backgroundColor),"rgb(36, 29, 22)");assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.goto(origin);await page.goto(`${origin}/sell-assistance`);await page.getByText("Sell Assistance",{exact:true}).waitFor();assert.equal(await page.getByText("Sell Assistance",{exact:true}).count(),1);if(width===390)await page.screenshot({path:join(shots,"sell-assistance.png"),fullPage:true});await page.getByLabel("Go back").click();await page.waitForFunction(()=>location.pathname!=="/sell-assistance");await page.goto(`${origin}/buy-assistance`);await page.getByText("Buy Assistance",{exact:true}).waitFor();assert.equal(await page.getByText("Buy Assistance",{exact:true}).count(),1);await page.getByLabel("Go back").click();await page.waitForFunction(()=>location.pathname!=="/buy-assistance");await context.close();}
assert.deepEqual(failures,[]);console.log("Mobile release shell UI: branded Home, authenticated List session retention, Account wording, drawer hierarchy, Light/Dark/System and 360/390/430 passed");}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
