import assert from "node:assert/strict";
import { createReadStream, existsSync, statSync } from "node:fs";
import { createServer } from "node:http";
import { extname, join, normalize } from "node:path";
import { chromium } from "playwright";

const root=join(process.cwd(),".expo-web");
const types={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json",".png":"image/png",".ttf":"font/ttf",".ico":"image/x-icon"};
const server=createServer((request,response)=>{const raw=decodeURIComponent((request.url??"/").split("?")[0]??"/");let path=normalize(join(root,raw));if(!path.startsWith(root)){response.writeHead(403).end();return;}if(existsSync(path)&&statSync(path).isDirectory())path=join(path,"index.html");if(!existsSync(path))path=join(root,"index.html");response.setHeader("Content-Type",types[extname(path)]??"application/octet-stream");createReadStream(path).pipe(response);});
await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));const address=server.address();assert.ok(address&&typeof address!=="string");
const browser=await chromium.launch({headless:true});const failures=[];
try{for(const width of [360,390,430]){const page=await browser.newPage({viewport:{width,height:844}});page.on("pageerror",error=>failures.push(`${width}: ${error.message}`));page.on("console",message=>{if(message.type()==="error")failures.push(`${width}: ${message.text()}`);});await page.goto(`http://127.0.0.1:${address.port}`,{waitUntil:"networkidle"});for(const label of ["Home tab","Properties tab","List a property tab","Mortgage calculator tab","Account tab"])await page.getByLabel(label).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false,`horizontal overflow at ${width}`);await page.getByLabel("Account tab").click();await page.getByText("Create account",{exact:true}).waitFor();await page.getByLabel("Properties tab").click();await page.getByText("Properties",{exact:true}).first().waitFor();await page.getByLabel("List a property tab").click();await page.getByText("List a property",{exact:true}).first().waitFor();await page.getByLabel("Mortgage calculator tab").click();await page.getByText("Mortgage Calculator",{exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false,`route overflow at ${width}`);await page.close();}assert.deepEqual(failures,[]);console.log("Mobile shell: five tabs, signed-out Account, routes, and 360/390/430 widths passed without page errors or overflow");}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
