import assert from "node:assert/strict";
import { createReadStream, existsSync, statSync } from "node:fs";
import { createServer } from "node:http";
import { extname, join, normalize } from "node:path";
import { chromium } from "playwright";

const root=join(process.cwd(),".expo-web");
const types={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json",".png":"image/png",".ttf":"font/ttf",".ico":"image/x-icon"};
const server=createServer((request,response)=>{const raw=decodeURIComponent((request.url??"/").split("?")[0]??"/");let path=normalize(join(root,raw));if(!path.startsWith(root)){response.writeHead(403).end();return;}if(existsSync(path)&&statSync(path).isDirectory())path=join(path,"index.html");if(!existsSync(path)&&existsSync(`${path}.html`))path=`${path}.html`;if(!existsSync(path))path=join(root,"index.html");response.setHeader("Content-Type",types[extname(path)]??"application/octet-stream");createReadStream(path).pipe(response);});
await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));const address=server.address();assert.ok(address&&typeof address!=="string");
const listing={code:"RES-MOBILE1",title:"A deliberately long canonical property title for responsive validation",description:"A public test response used only by the automated browser harness.",propertyType:"Residential",propertySubtype:"Detached Duplexes",priceMinor:98765432100,state:"Federal Capital Territory (FCT)",city:"Central Business District",bedrooms:7,bathrooms:6,parkingSpaces:4,facilities:["CCTV","Car Park"],listedAt:"2026-09-29T00:00:00Z",images:[]};
const secondListing={...listing,code:"RES-MOBILE2",title:"A second long property title for mobile comparison",priceMinor:76543210000,city:"Maitama"};
const pageData={items:[listing],page:1,pageSize:10,total:1,totalPages:1};
const savedPageData={items:[listing,secondListing],page:1,pageSize:10,total:2,totalPages:1};
const comparedItems=[listing,secondListing].map(item=>({...item,propertyStatus:"Available",unitSizeSqft:null,yearBuilt:null,minimumDownPaymentMinor:10000000000}));
const cors={"access-control-allow-origin":"*","access-control-allow-headers":"X-Beryl-Client, Authorization, Content-Type","access-control-allow-methods":"GET, POST, OPTIONS","access-control-expose-headers":"X-Beryl-Account-Token"};
const browser=await chromium.launch({headless:true});const failures=[];
try{
  for(const width of [360,390,430]){
    const page=await browser.newPage({viewport:{width,height:900}});page.on("pageerror",error=>failures.push(`${width}: ${error.message}`));page.on("console",message=>{if(message.type()==="error"&&!message.text().includes("favicon"))failures.push(`${width}: ${message.text()}`);});page.on("requestfailed",request=>failures.push(`${width}: request failed ${request.url()} ${request.failure()?.errorText??""}`));
    await page.route("**/api/v1/public/property-searches",route=>route.request().method()==="OPTIONS"?route.fulfill({status:204,headers:cors}):route.fulfill({status:200,headers:cors,contentType:"application/json",body:JSON.stringify({success:true,data:{recorded:true}})}));
    await page.route("**/api/v1/public/properties**",route=>{if(route.request().method()==="OPTIONS")return route.fulfill({status:204,headers:cors});const detail=new URL(route.request().url()).pathname.endsWith("/RES-MOBILE1");return route.fulfill({status:200,headers:cors,contentType:"application/json",body:JSON.stringify(detail?{success:true,data:{property:{...listing,occupancyType:"Vacant",ownershipType:"Freehold",hasLien:false,minimumDownPaymentMinor:10000000000,location:"Central Business District, Abuja",landArea:null,yearBuilt:null},similar:[]}}:{success:true,data:pageData})});});
    await page.route("**/api/v1/auth/login",route=>route.request().method()==="OPTIONS"?route.fulfill({status:204,headers:cors}):route.fulfill({status:200,headers:{...cors,"x-beryl-account-token":"responsive-test-token"},contentType:"application/json",body:JSON.stringify({success:true,data:{}})}));
    await page.route("**/api/v1/auth/me",route=>route.request().method()==="OPTIONS"?route.fulfill({status:204,headers:cors}):route.fulfill({status:200,headers:cors,contentType:"application/json",body:JSON.stringify({success:true,data:{customer:{id:"responsive-customer",first_name:"Responsive",last_name:"Tester",email:"responsive@example.test",phone_number_normalized:null,account_type:"INVESTOR",profile_type:"PERSONAL"}}})}));
    await page.route("**/api/v1/saved-properties**",route=>{if(route.request().method()==="OPTIONS")return route.fulfill({status:204,headers:cors});const path=new URL(route.request().url()).pathname;const data=path.endsWith("/compare")?{items:comparedItems}:path.endsWith("/states")?{propertyCodes:comparedItems.map(item=>item.code)}:savedPageData;return route.fulfill({status:200,headers:cors,contentType:"application/json",body:JSON.stringify({success:true,data})});});
    await page.goto(`http://127.0.0.1:${address.port}`,{waitUntil:"networkidle"});
    for(const label of ["Home tab","Properties tab","List a property tab","Mortgage calculator tab","Account tab"])await page.getByLabel(label).waitFor();
    await page.getByText("Latest listings",{exact:true}).waitFor();try{await page.getByText(listing.title,{exact:true}).waitFor({timeout:10000});}catch(error){console.error(`Responsive debug at ${width}:`,await page.locator("body").innerText(),failures);throw error}assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false,`Home overflow at ${width}`);
    await page.getByLabel("Properties tab").click();await page.getByText("Properties",{exact:true}).first().waitFor();await page.getByLabel("Open property filters").click();await page.getByText("Filter properties",{exact:true}).waitFor();await page.getByLabel("Close property filters").click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false,`Properties overflow at ${width}`);
    await page.getByRole("link",{name:listing.title,exact:true}).click();await page.getByText("Payment information",{exact:true}).waitFor();await page.getByText("Photo unavailable",{exact:true}).first().waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false,`Detail overflow at ${width}`);
    await page.getByLabel("Mortgage calculator tab").click();await page.getByText("Mortgage Calculator",{exact:true}).waitFor();await page.getByLabel("Home Purchase Price").fill("50,000,000");await page.getByLabel("Down Payment").fill("10,000,000");await page.getByLabel("20 year loan term").click();await page.getByLabel("Annual Interest Rate (%)").fill("12");await page.getByText("Calculate estimate",{exact:true}).click();await page.getByText("₦440,434.45",{exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false,`Mortgage overflow at ${width}`);
    await page.getByLabel("Account tab").click();await page.getByText("Create account",{exact:true}).waitFor();await page.goto(`http://127.0.0.1:${address.port}/saved-properties`,{waitUntil:"networkidle"});await page.getByText("Sign in to view saved properties",{exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false,`Saved boundary overflow at ${width}`);
    await page.getByRole("button",{name:"Log in",exact:true}).click();await page.getByLabel("Email or phone").fill("responsive@example.test");await page.getByRole("textbox",{name:"Password"}).fill("responsive-test-password");await page.getByRole("button",{name:"Log in",exact:true}).click();await page.getByLabel(`Add ${listing.title} to comparison`).last().waitFor();await page.getByLabel(`Add ${listing.title} to comparison`).last().click();await page.getByLabel(`Add ${secondListing.title} to comparison`).last().click();await page.getByText("Review",{exact:true}).last().click();await page.getByLabel("Saved property comparison").last().waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false,`Compare overflow at ${width}`);
    await page.close();
  }
  assert.deepEqual(failures,[]);console.log("Mobile Phase 2: Home, Properties, filters, Detail, Mortgage, Saved and authenticated Compare passed at 360/390/430 without page errors or whole-page overflow");
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
