"use client";
import Link from "next/link";
import type { Route } from "next";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, FileText, Images, MapPin, RefreshCw } from "lucide-react";
import { ApiAlert } from "@/components/ui/feedback";
import { customerApi } from "@/lib/api/client";
import { formatNaira, humanizeMarketplaceValue } from "@/lib/marketplace";
import { sellerListingActionLabel, sellerListingRouteForAction } from "@/lib/seller-listings";

const listingsRoute = "/seller/listings" as Route;
export function SellerListingManagementScreen({ propertyId }: { propertyId: string }) {
  const query = useQuery({ queryKey: ["seller-marketplace-management", propertyId], queryFn: () => customerApi.sellerListingManagement(propertyId) });
  if (query.isLoading) return <main className="seller-management-page" aria-label="Loading listing status"><div className="seller-management-skeleton" /></main>;
  if (query.isError || !query.data?.data.management) return <main className="seller-management-page"><section className="seller-listing-state" role="alert"><ApiAlert>This listing is unavailable right now.</ApiAlert><button className="btn btn-secondary" type="button" onClick={() => query.refetch()}><RefreshCw size={17} />Try again</button><Link className="btn btn-secondary" href={listingsRoute}>Back to My Listings</Link></section></main>;
  const { management } = query.data.data;
  const { summary, property, documents, mandate, reviewHistory } = management;
  const date = summary.status === "LIVE" ? summary.publishedAt : summary.status === "REJECTED" ? summary.rejectedAt : summary.submittedAt;
  return <main className="seller-management-page"><Link className="property-detail-back" href={listingsRoute}><ArrowLeft size={17} aria-hidden="true" />Back to My Listings</Link><section className="seller-management-card"><div className="seller-management-heading"><div><span className={`seller-status seller-status-${summary.status.toLowerCase().replace("_", "-")}`}>{humanizeMarketplaceValue(summary.status)}</span><h1>{property.title || "Untitled property"}</h1><p>{summary.referenceId}</p></div>{property.askingPrice !== null ? <strong>{formatNaira(property.askingPrice)}</strong> : null}</div>{summary.status === "REJECTED" ? <section className="seller-management-feedback"><h2>A few changes needed</h2><p>{summary.rejectionFeedback || summary.rejectionReason || "Please review this listing before resubmitting."}</p></section> : null}{summary.status === "IN_REVIEW" ? <section className="seller-management-review"><h2>Your listing is under review</h2><p>{summary.submittedAt ? `Submitted ${new Intl.DateTimeFormat("en-NG", { day: "numeric", month: "long", year: "numeric" }).format(new Date(summary.submittedAt))}.` : "Your listing has been submitted."}</p></section> : null}{summary.status === "LIVE" ? <section className="seller-management-review"><h2>Your listing is live</h2><p>{date ? `Published ${new Intl.DateTimeFormat("en-NG", { day: "numeric", month: "long", year: "numeric" }).format(new Date(date))}.` : "This listing is published."}</p></section> : null}<div className="seller-management-grid"><section><h2>Property information</h2><dl><div><dt>Public location</dt><dd><MapPin size={15} aria-hidden="true" />{property.publicLocation || "To be added"}</dd></div><div><dt>Full address</dt><dd>{property.fullAddress || "To be added"}</dd></div><div><dt>Type</dt><dd>{property.propertyType ? humanizeMarketplaceValue(property.propertyType) : "To be added"}</dd></div></dl></section><section><h2>Photos & documents</h2><p><Images size={16} aria-hidden="true" />{property.images.length} photos</p><p><FileText size={16} aria-hidden="true" />{documents.length} supporting documents</p></section>{mandate ? <section><h2>Sales mandate</h2><p>{humanizeMarketplaceValue(mandate.mandateType)} mandate</p><p>{mandate.mandateAccepted ? "Accepted" : "Not accepted"}</p></section> : null}</div>{reviewHistory.length ? <section className="seller-management-history"><h2>Listing history</h2><ul>{reviewHistory.map((entry) => <li key={entry.id}><strong>{humanizeMarketplaceValue(entry.action)}</strong><span>{entry.reason || humanizeMarketplaceValue(entry.newStatus)}</span></li>)}</ul></section> : null}<Link className="btn btn-primary" href={sellerListingRouteForAction(summary.nextAction, summary.id)}>{sellerListingActionLabel(summary.nextAction)}</Link></section></main>;
}
