import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useMemo, useRef, useState } from "react";
import { FlatList, Image, Linking, Pressable, ScrollView, StyleSheet, Text, useWindowDimensions, View, type NativeScrollEvent, type NativeSyntheticEvent } from "react-native";
import { Button, Card, LoadingState, ScreenState, SectionHeading } from "@/components/ui";
import { PropertyCard } from "@/components/property-card";
import { AppIcon, type AppIconName } from "@/components/app-icon";
import { friendlyError, MobileApiError } from "@/lib/api-error";
import { formatNaira } from "@/lib/money";
import { canonicalPropertyUrl, isValidPropertyCode } from "@/lib/property-links";
import { propertiesApi } from "@/lib/properties-api";
import { shareCanonicalUrl } from "@/lib/share";
import type { PublicProperty, PublicPropertyDetail } from "@/lib/property-types";
import { useAuth } from "@/providers/auth-provider";
import { usePropertyState } from "@/providers/property-state-provider";
import { colors, radius, spacing, typography } from "@/theme/tokens";

export default function PropertyDetailRoute(){
  const raw=useLocalSearchParams<{propertyCode?:string;ref?:string}>();const propertyCode=typeof raw.propertyCode==="string"?raw.propertyCode:"";const referralCode=typeof raw.ref==="string"?raw.ref.trim():undefined;
  const {width}=useWindowDimensions();const galleryWidth=Math.max(280,width-32);const {status}=useAuth();const {savedCodes,refreshSaved,setSaved}=usePropertyState();
  const [property,setProperty]=useState<PublicPropertyDetail|null>(null);const [similar,setSimilar]=useState<PublicProperty[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [notFound,setNotFound]=useState(false);const [retry,setRetry]=useState(0);const [imageIndex,setImageIndex]=useState(0);const [saving,setSaving]=useState(false);const [sharing,setSharing]=useState(false);const [referring,setReferring]=useState(false);const listRef=useRef<FlatList<string>>(null);
  useEffect(()=>{let active=true;if(!isValidPropertyCode(propertyCode))return()=>{active=false};void propertiesApi.detail(propertyCode).then(result=>{if(!active)return;setProperty(result.property);setSimilar(result.similar);setImageIndex(0);}).catch(failure=>{if(!active)return;if(failure instanceof MobileApiError&&failure.kind==="not_found")setNotFound(true);else setError(friendlyError(failure));}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[propertyCode,retry]);
  useEffect(()=>{if(status==="signedIn"&&property)queueMicrotask(()=>void refreshSaved([property.code]).catch(()=>{}))},[status,property,refreshSaved]);
  const mapUrl=useMemo(()=>property?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${property.location}, ${property.city}, ${property.state}, Nigeria`)}`:"",[property]);
  async function toggleSaved(){if(!property)return;if(status!=="signedIn"){router.push({pathname:"/(auth)/login",params:{next:`/properties/${encodeURIComponent(property.code)}${referralCode?`?ref=${encodeURIComponent(referralCode)}`:""}`}});return}if(saving)return;setSaving(true);setError("");try{if(savedCodes.has(property.code)){await propertiesApi.unsave(property.code);setSaved(property.code,false)}else{await propertiesApi.save(property.code);setSaved(property.code,true)}}catch(failure){setError(friendlyError(failure))}finally{setSaving(false)}}
  async function share(){if(!property||sharing)return;setSharing(true);setError("");try{await shareCanonicalUrl(property.title,`${property.title} on Beryl Shelter`,canonicalPropertyUrl(property.code,referralCode))}catch(failure){setError(friendlyError(failure))}finally{setSharing(false)}}
  async function shareReferral(){if(!property)return;if(status!=="signedIn"){router.push({pathname:"/(auth)/login",params:{next:`/properties/${encodeURIComponent(property.code)}`}});return}if(referring)return;setReferring(true);setError("");try{const result=await propertiesApi.referral(property.code);await shareCanonicalUrl(property.title,`View ${property.title} through my Beryl Shelter referral`,result.referralUrl)}catch(failure){setError(friendlyError(failure))}finally{setReferring(false)}}
  function galleryScroll(event:NativeSyntheticEvent<NativeScrollEvent>){setImageIndex(Math.round(event.nativeEvent.contentOffset.x/galleryWidth))}
  if(!isValidPropertyCode(propertyCode))return <View style={styles.state}><ScreenState title="Property unavailable" message="This property code is invalid, unavailable, or the property is no longer publicly listed." action={<Button label="Browse listed properties" onPress={()=>router.replace("/properties")}/>} /></View>;
  if(loading)return <LoadingState label="Loading property details"/>;
  if(error&&!property)return <View style={styles.state}><ScreenState title="Property temporarily unavailable" message={error} action={<Button label="Try again" onPress={()=>{setLoading(true);setError("");setNotFound(false);setRetry(value=>value+1)}}/>}/></View>;
  if(notFound||!property)return <View style={styles.state}><ScreenState title="Property unavailable" message="This property code is invalid, unavailable, or the property is no longer publicly listed." action={<Button label="Browse listed properties" onPress={()=>router.replace("/properties")}/>} /></View>;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
    <View style={styles.actions}><Pressable accessibilityRole="button" accessibilityLabel="Share property" disabled={sharing} onPress={()=>void share()} style={styles.iconButton}><AppIcon name="share-social-outline" size={22} color={colors.brandDark}/></Pressable><Pressable accessibilityRole="button" accessibilityLabel={savedCodes.has(property.code)?`Remove ${property.title} from saved properties`:`Save ${property.title}`} accessibilityState={{selected:savedCodes.has(property.code),disabled:saving}} disabled={saving} onPress={()=>void toggleSaved()} style={styles.iconButton}><AppIcon name={savedCodes.has(property.code)?"heart":"heart-outline"} size={23} color={savedCodes.has(property.code)?colors.danger:colors.brandDark}/></Pressable></View>
    <View style={styles.gallery}>{property.images.length?<><FlatList ref={listRef} horizontal pagingEnabled data={property.images} keyExtractor={(item,index)=>`${item}-${index}`} renderItem={({item,index})=><Image source={{uri:item}} resizeMode="cover" accessibilityLabel={`${property.title} photograph ${index+1} of ${property.images.length}`} style={{width:galleryWidth,height:galleryWidth*.68}}/>} onMomentumScrollEnd={galleryScroll} showsHorizontalScrollIndicator={false}/><View style={styles.galleryCount}><Text style={styles.galleryCountText}>{imageIndex+1} / {property.images.length}</Text></View><View style={styles.dots}>{property.images.slice(0,8).map((_,index)=><Pressable key={index} accessibilityRole="button" accessibilityLabel={`Show property photograph ${index+1}`} onPress={()=>{listRef.current?.scrollToIndex({index,animated:true});setImageIndex(index)}} style={[styles.dot,index===imageIndex&&styles.dotActive]}/>)}</View></>:<View accessibilityRole="image" accessibilityLabel={`No photograph available for ${property.title}`} style={[styles.placeholder,{height:galleryWidth*.68}]}><AppIcon name="image-outline" size={42} color={colors.textMuted}/><Text style={styles.muted}>Photo unavailable</Text></View>}</View>
    <View style={styles.heading}><Text style={styles.eyebrow}>{property.propertySubtype} · {property.propertyType}</Text><Text accessibilityRole="header" style={styles.title}>{property.title}</Text><Text style={styles.price}>{formatNaira(property.priceMinor)}</Text><View style={styles.location}><AppIcon name="location-outline" size={19} color={colors.textMuted}/><Text style={styles.muted}>{property.city}, {property.state}</Text></View><View style={styles.facts}><Fact icon="bed-outline" label={`${property.bedrooms} bedrooms`}/><Fact icon="water-outline" label={`${property.bathrooms} bathrooms`}/><Fact icon="car-outline" label={`${property.parkingSpaces} parking`}/>{property.landArea!==null?<Fact icon="resize-outline" label={`${property.landArea.toLocaleString()} land area`}/>:null}</View><Text style={styles.code}>Property code: {property.code}</Text></View>
    {error?<View style={styles.errorBlock}><Text accessibilityRole="alert" style={styles.error}>{error}</Text><Button label="Retry property" variant="secondary" onPress={()=>{setLoading(true);setError("");setNotFound(false);setProperty(null);setRetry(value=>value+1)}}/></View>:null}
    <Card><SectionHeading title="Description"/><Text style={styles.body}>{property.description}</Text><DetailRow label="Occupancy type" value={property.occupancyType}/><DetailRow label="Ownership type" value={property.ownershipType}/><DetailRow label="Lien information" value={property.hasLien?"Lien recorded":"No lien recorded"}/>{property.yearBuilt!==null?<DetailRow label="Year built" value={String(property.yearBuilt)}/>:null}</Card>
    {property.facilities.length?<Card><SectionHeading title="Facilities and features"/><View style={styles.chips}>{property.facilities.map(item=><View key={item} style={styles.chip}><AppIcon name="checkmark" size={15} color={colors.success}/><Text style={styles.chipText}>{item}</Text></View>)}</View></Card>:null}
    <Card><SectionHeading title="Property location"/><Text style={styles.body}>{property.location}</Text><DetailRow label="City" value={property.city}/><DetailRow label="State" value={property.state}/><Button label="Open property in Maps" variant="secondary" onPress={()=>void Linking.openURL(mapUrl)}/><Text style={styles.caption}>This opens the property address externally. Beryl Shelter does not request your device location.</Text></Card>
    <Card><SectionHeading title="Payment information"/><DetailRow label="Property cost" value={formatNaira(property.priceMinor)}/><DetailRow label="Minimum down payment" value={formatNaira(property.minimumDownPaymentMinor)}/><Text style={styles.notice}>Information only. Property purchases are completed offline with Beryl Shelter. There is no online checkout or property payment in this app.</Text><Button label="Estimate a mortgage" onPress={()=>router.push({pathname:"/mortgage",params:{code:property.code,priceMinor:String(property.priceMinor)}})}/></Card>
    <Card><SectionHeading title="Interested in a viewing?" description="The complete viewing request form belongs to Phase 3."/><Text style={styles.body}>You can review this public property now. No viewing has been submitted from this screen.</Text><Button label="Viewing requests arrive in Phase 3" disabled onPress={()=>{}}/></Card>
    <Card><SectionHeading title="Share this property" description="Opening or sharing a link does not create commission."/><Button label="Share public property" loading={sharing} onPress={()=>void share()}/><Button label={status==="signedIn"?"Share my referral link":"Log in to create a referral link"} variant="secondary" loading={referring} onPress={()=>void shareReferral()}/><Text style={styles.caption}>The canonical referral rate is 2%. Earnings arise only after verified attribution to a completed offline sale.</Text></Card>
    <SectionHeading title="Similar properties" description="Other currently listed properties with related type and location details."/>{similar.length?<FlatList horizontal data={similar} keyExtractor={item=>item.code} renderItem={({item})=><View style={styles.similar}><PropertyCard property={item} referralCode={referralCode}/></View>} contentContainerStyle={styles.similarList} showsHorizontalScrollIndicator={false}/>:<Text style={styles.muted}>No similar listed properties are available right now.</Text>}
  </ScrollView>
}
function Fact({icon,label}:{icon:AppIconName;label:string}){return <View style={styles.fact}><AppIcon name={icon} size={17} color={colors.brandDark}/><Text style={styles.factText}>{label}</Text></View>}
function DetailRow({label,value}:{label:string;value:string}){return <View style={styles.detailRow}><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value||"—"}</Text></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,paddingBottom:spacing.xxl,gap:spacing.lg},state:{flex:1,backgroundColor:colors.background},actions:{flexDirection:"row",justifyContent:"flex-end",gap:spacing.sm},iconButton:{width:46,height:46,borderRadius:radius.pill,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,alignItems:"center",justifyContent:"center"},gallery:{borderRadius:radius.lg,overflow:"hidden",backgroundColor:colors.surfaceMuted,position:"relative"},placeholder:{alignItems:"center",justifyContent:"center",gap:spacing.sm},galleryCount:{position:"absolute",right:spacing.md,top:spacing.md,backgroundColor:colors.overlay,paddingHorizontal:spacing.sm,paddingVertical:spacing.xs,borderRadius:radius.pill},galleryCountText:{...typography.caption,color:"#fff",fontWeight:"700"},dots:{minHeight:30,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:spacing.xs,backgroundColor:colors.surface},dot:{width:7,height:7,borderRadius:radius.pill,backgroundColor:colors.border},dotActive:{width:20,backgroundColor:colors.brand},heading:{gap:spacing.sm},eyebrow:{...typography.label,color:colors.brandDark},title:{...typography.display,color:colors.text},price:{...typography.title,color:colors.brandDark},location:{flexDirection:"row",alignItems:"center",gap:spacing.xs},muted:{...typography.body,color:colors.textMuted},facts:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm},fact:{flexDirection:"row",alignItems:"center",gap:spacing.xs,paddingHorizontal:spacing.md,paddingVertical:spacing.sm,borderRadius:radius.pill,backgroundColor:colors.surface},factText:{...typography.caption,color:colors.text},code:{...typography.caption,color:colors.textMuted},errorBlock:{gap:spacing.sm},error:{...typography.caption,color:colors.danger},body:{...typography.body,color:colors.text},caption:{...typography.caption,color:colors.textMuted},detailRow:{flexDirection:"row",justifyContent:"space-between",gap:spacing.lg,paddingVertical:spacing.sm,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.border},detailLabel:{...typography.caption,color:colors.textMuted,flex:1},detailValue:{...typography.label,color:colors.text,textAlign:"right",flex:1},chips:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm},chip:{flexDirection:"row",alignItems:"center",gap:spacing.xs,paddingHorizontal:spacing.sm,paddingVertical:spacing.sm,borderRadius:radius.pill,backgroundColor:colors.surfaceMuted},chipText:{...typography.caption,color:colors.text},notice:{...typography.caption,color:colors.text,backgroundColor:"#FBF1E5",padding:spacing.md,borderRadius:radius.md},similar:{width:290},similarList:{gap:spacing.md,paddingRight:spacing.lg}});
